// Purpose: Owns localized shell navigation labels independently of domain status copy.
// Depends on: Native JavaScript/static data; no imported runtime modules.
// Used by: apps/admin/components/WorkspaceFrame.tsx, apps/admin/src/page-title.ts, apps/admin/src/route-metadata.ts, apps/admin/src/route-types.ts, tests/admin/claims-ui.spec.ts, tests/admin/customers-billing.spec.ts, tests/admin/design.spec.ts, tests/admin/entry.spec.ts, tests/admin/ledger.spec.ts, tests/admin/platform-brand-browser.mjs, tests/admin/shell-browser.mjs, tests/admin/shell-registry.test.ts, tests/admin/studio-ui.spec.ts
// Shell-only copy; business status language stays inside its domain.
const en = {
  overview: "Overview",
  live: "Live",
  orders: "Orders & shipping",
  catalog: "Products & inventory",
  messages: "Inbox",
  customers: "Customers",
  marketing: "Marketing",
  storefront: "Online store",
  finance: "Payments & reports",
  settings: "Settings",
  dashboard: "Overview",
  studio: "Live sessions",
  liveConsole: "Live console",
  liveSettings: "Live settings",
  claims: "Comment claims",
  orderList: "Orders",
  orderNew: "Create order",
  returns: "Returns",
  cvsPrint: "Print shipping label",
  products: "Products",
  product: "Edit product",
  productNew: "New product",
  collections: "Collections",
  inventory: "Inventory",
  productImport: "Import products",
  customerList: "Customers",
  customerDetail: "Customer details",
  promotions: "Discount codes",
  ads: "Ads",
  attribution: "Ad attribution",
  design: "Store design",
  financePage: "Finance",
  settingsPage: "Store settings",
  team: "Team",
  billing: "Billing",
  cardPayments: "Card payments",
  settlements: "Settlements",
  invite: "Accept invitation",
  reset: "Reset password",
  signup: "Create account",
  navigation: "Workspace navigation",
  openMenu: "Open navigation",
  closeMenu: "Close navigation",
  language: "Language",
  store: "Switch store",
  help: "Help",
  helpText:
    "Choose a workspace section. Access is limited by your store role. For payment and shipping connections, open Store settings.",
  account: "Account",
  signOut: "Sign out",
  signingOut: "Signing out…",
  signOutFailed: "Sign-out failed. Try again.",
  skip: "Skip to content",
  loading: "Loading workspace…",
  unavailable: "Workspace access could not be loaded.",
  sessionExpired: "Your session has expired. Sign in again to continue.",
  signIn: "Sign in again",
  retry: "Try again",
  forbidden: "403 · You do not have access to this page.",
  back: "Go to a page you can open",
};
export type ShellCopy = typeof en;
export type ShellLabel = keyof ShellCopy;
const zhCN: ShellCopy = {
  overview: "总览",
  live: "直播",
  orders: "订单与发货",
  catalog: "商品与库存",
  messages: "消息中心",
  customers: "顾客",
  marketing: "营销优惠",
  storefront: "网店",
  finance: "收款与报表",
  settings: "设置",
  dashboard: "总览",
  studio: "直播场次",
  liveConsole: "直播控台",
  liveSettings: "直播设置",
  claims: "留言认领",
  orderList: "订单",
  orderNew: "创建订单",
  returns: "退货",
  cvsPrint: "打印寄件标签",
  products: "商品",
  product: "编辑商品",
  productNew: "新增商品",
  collections: "分类",
  inventory: "库存",
  productImport: "导入商品",
  customerList: "顾客",
  customerDetail: "顾客详情",
  promotions: "优惠码",
  ads: "广告",
  attribution: "广告归因",
  design: "店铺装修",
  financePage: "财务",
  settingsPage: "店铺设置",
  team: "员工",
  billing: "账单",
  cardPayments: "信用卡收款",
  settlements: "结算单",
  invite: "接受邀请",
  reset: "重设密码",
  signup: "创建账号",
  navigation: "工作区导航",
  openMenu: "打开导航",
  closeMenu: "关闭导航",
  language: "语言",
  store: "切换店铺",
  help: "帮助",
  helpText:
    "选择工作区入口；可访问内容由店铺角色决定。收款和配送连接请进入店铺设置。",
  account: "账号",
  signOut: "退出登录",
  signingOut: "正在退出…",
  signOutFailed: "退出失败，请重试。",
  skip: "跳转到内容",
  loading: "正在载入工作区…",
  unavailable: "无法载入工作区权限。",
  sessionExpired: "登录已过期，请重新登录后继续。",
  signIn: "重新登录",
  retry: "重试",
  forbidden: "403 · 你没有访问此页面的权限。",
  back: "前往可用页面",
};
const zhTW: ShellCopy = {
  overview: "總覽",
  live: "直播",
  orders: "訂單與出貨",
  catalog: "商品與庫存",
  messages: "訊息中心",
  customers: "顧客",
  marketing: "行銷優惠",
  storefront: "網路商店",
  finance: "收款與報表",
  settings: "設定",
  dashboard: "總覽",
  studio: "直播場次",
  liveConsole: "直播控台",
  liveSettings: "直播設定",
  claims: "留言認領",
  orderList: "訂單",
  orderNew: "建立訂單",
  returns: "退貨",
  cvsPrint: "列印寄件標籤",
  products: "商品",
  product: "編輯商品",
  productNew: "新增商品",
  collections: "分類",
  inventory: "庫存",
  productImport: "匯入商品",
  customerList: "顧客",
  customerDetail: "顧客詳情",
  promotions: "優惠碼",
  ads: "廣告",
  attribution: "廣告歸因",
  design: "商店設計",
  financePage: "財務",
  settingsPage: "商店設定",
  team: "員工",
  billing: "帳單",
  cardPayments: "信用卡收款",
  settlements: "結算單",
  invite: "接受邀請",
  reset: "重設密碼",
  signup: "建立帳號",
  navigation: "工作區導覽",
  openMenu: "開啟導覽",
  closeMenu: "關閉導覽",
  language: "語言",
  store: "切換商店",
  help: "說明",
  helpText:
    "選擇工作區入口；可存取內容由商店角色決定。收款和配送連線請進入商店設定。",
  account: "帳號",
  signOut: "登出",
  signingOut: "正在登出…",
  signOutFailed: "登出失敗，請重試。",
  skip: "跳至內容",
  loading: "正在載入工作區…",
  unavailable: "無法載入工作區權限。",
  sessionExpired: "登入已過期，請重新登入後繼續。",
  signIn: "重新登入",
  retry: "重試",
  forbidden: "403 · 你沒有存取此頁面的權限。",
  back: "前往可用頁面",
};
export const shellCopy = { en, "zh-CN": zhCN, "zh-TW": zhTW };
