// Purpose: Buyer-facing bank-transfer checkout and proof feedback in three locales.
// Depends on: Locale and frozen bank-transfer state/error types (storefront-v2 §C).
// Used by: OrderFlow checkout and BankTransfer order panels; input names the device timezone and proof echo names the store timezone.
// Buyer-facing copy (zh-CN / zh-TW / en) for the bank-transfer payment mode (contracts/storefront-v2.md §C): the payment choice and optional
// email at checkout (components/OrderFlow.tsx) and the order page panel (components/BankTransfer.tsx).
// Rules encoded here: the order is never "paid" until the shop confirms it (CONFIRMED text names the shop as the confirmer); a REJECTED
// submission says the details were not accepted, not that the order is cancelled; EXPIRED says the items were released.
import type { Locale } from "@live-commerce/i18n";
import type { TransferErrorCode, TransferState } from "./bank-transfer-contract";

const en = {
  // checkout choice
  paymentLegend: "Payment",
  payCard: "Credit card",
  payBank: "Bank transfer",
  bankNote: (hours: number) =>
    `Pay by transferring to the shop's bank account within ${hours} hours. The shop confirms your order after it sees the transfer; nothing is charged online.`,
  createBank: "Place order (bank transfer)",
  emailLabel: "Email (optional)",
  emailHint: "Used only for updates about this order.",
  emailInvalid: "Enter a valid email address or leave the field empty.",
  // order page
  title: "Pay by bank transfer",
  stateLabel: "Transfer status",
  states: {
    AWAITING: "Waiting for your transfer",
    SUBMITTED: "Details sent — waiting for the shop to confirm",
    REJECTED: "The shop could not match your details",
    CONFIRMED: "The shop confirmed your payment",
    EXPIRED: "The transfer window ended",
    REFUNDED_OFFLINE: "The shop recorded a refund outside this site",
  } as Record<TransferState, string>,
  amountDue: "Amount to transfer",
  deadline: "Transfer before",
  timeLeft: (hours: number, minutes: number) => `${hours} h ${minutes} min left`,
  windowEnded: "The transfer window has ended.",
  bankHeading: "Shop bank account",
  bankName: "Bank",
  branch: "Branch",
  accountName: "Account name",
  accountNumber: "Account number",
  transferNote:
    "Transfer the exact amount above, then tell us below. Your items stay reserved until the deadline; the order is confirmed only after the shop checks its account.",
  // proof form
  proofHeading: "I have transferred",
  proofEdit: "Update my transfer details",
  last5: "Last 5 digits of the account you sent from",
  amountSent: "Amount you transferred",
  paidAt: "Transfer date and time",
  paidAtZone: (zone: string) => `Your device time zone: ${zone}`,
  send: "Send transfer details",
  sending: "Sending…",
  sent: "Transfer details sent. The shop will confirm after checking its account.",
  yourDetails: "Your last details",
  storeTime: "Store time (UTC+8)",
  rejectedPrefix: "The shop's note",
  rejectedHelp: "Check your transfer and send the details again before the deadline.",
  confirmed: "The shop confirmed your payment. Your order is now confirmed.",
  expired: "The transfer window ended. This order was cancelled and the items were released.",
  refunded: "The shop recorded a refund for this order outside this site.",
  invalidInput: "Enter the last 5 digits, the amount you sent and when you sent it.",
  loadFailed: "Transfer details could not be loaded. Refresh and try again.",
  sendFailed: "The details could not be sent. Check your connection and try again.",
  refresh: "Refresh status",
  errors: {
    bank_transfer_unavailable: "Bank transfer is not available for this order.",
    not_bank_transfer: "This order is not a bank-transfer order.",
    transfer_not_open: "This transfer is no longer open.",
    transfer_window_closed: "The transfer window has ended.",
    invalid_proof: "The transfer details are not valid.",
  } as Record<TransferErrorCode, string>,
};

const zhCN: typeof en = {
  paymentLegend: "付款方式",
  payCard: "信用卡",
  payBank: "银行转账",
  bankNote: (hours) => `请在 ${hours} 小时内转账到商家的银行账户。商家确认收款后订单才算成立，不会在线扣款。`,
  createBank: "提交订单（银行转账）",
  emailLabel: "电子邮箱（选填）",
  emailHint: "仅用于该订单的通知。",
  emailInvalid: "请输入有效的电子邮箱，或留空。",
  title: "银行转账付款",
  stateLabel: "转账状态",
  states: {
    AWAITING: "等待你转账",
    SUBMITTED: "已提交转账资料，等待商家确认",
    REJECTED: "商家无法核对你的转账资料",
    CONFIRMED: "商家已确认收款",
    EXPIRED: "转账期限已结束",
    REFUNDED_OFFLINE: "商家已在本站之外记录退款",
  },
  amountDue: "应转账金额",
  deadline: "转账截止时间",
  timeLeft: (hours, minutes) => `还剩 ${hours} 小时 ${minutes} 分钟`,
  windowEnded: "转账期限已结束。",
  bankHeading: "商家银行账户",
  bankName: "银行",
  branch: "分行",
  accountName: "户名",
  accountNumber: "账号",
  transferNote: "请转入上述确切金额，再在下方告知我们。截止前库存会为你保留；商家核对账户后订单才会确认。",
  proofHeading: "我已转账",
  proofEdit: "更新我的转账资料",
  last5: "转出账户的后 5 码",
  amountSent: "你转账的金额",
  paidAt: "转账日期与时间",
  paidAtZone: (zone: string) => `你设备的时区：${zone}`,
  send: "送出转账资料",
  sending: "送出中…",
  sent: "转账资料已送出。商家核对账户后会确认。",
  yourDetails: "你最近提交的资料",
  storeTime: "店铺时间（UTC+8）",
  rejectedPrefix: "商家备注",
  rejectedHelp: "请核对转账情况，并在截止前重新送出资料。",
  confirmed: "商家已确认收款，订单已确认。",
  expired: "转账期限已结束，订单已取消，库存已释放。",
  refunded: "商家已在本站之外为该订单记录退款。",
  invalidInput: "请输入后 5 码、转账金额与转账时间。",
  loadFailed: "无法载入转账资料，请刷新后重试。",
  sendFailed: "无法送出资料，请检查网络后重试。",
  refresh: "刷新状态",
  errors: {
    bank_transfer_unavailable: "该订单无法使用银行转账。",
    not_bank_transfer: "该订单不是银行转账订单。",
    transfer_not_open: "该转账已不再开放。",
    transfer_window_closed: "转账期限已结束。",
    invalid_proof: "转账资料不正确。",
  },
};

const zhTW: typeof en = {
  paymentLegend: "付款方式",
  payCard: "信用卡",
  payBank: "銀行轉帳",
  bankNote: (hours) => `請在 ${hours} 小時內轉帳到商家的銀行帳戶。商家確認收款後訂單才算成立，不會線上扣款。`,
  createBank: "送出訂單（銀行轉帳）",
  emailLabel: "電子郵件（選填）",
  emailHint: "僅用於此訂單的通知。",
  emailInvalid: "請輸入有效的電子郵件，或留空。",
  title: "銀行轉帳付款",
  stateLabel: "轉帳狀態",
  states: {
    AWAITING: "等待你轉帳",
    SUBMITTED: "已送出轉帳資料，等待商家確認",
    REJECTED: "商家無法核對你的轉帳資料",
    CONFIRMED: "商家已確認收款",
    EXPIRED: "轉帳期限已結束",
    REFUNDED_OFFLINE: "商家已在本站之外記錄退款",
  },
  amountDue: "應轉帳金額",
  deadline: "轉帳截止時間",
  timeLeft: (hours, minutes) => `還剩 ${hours} 小時 ${minutes} 分鐘`,
  windowEnded: "轉帳期限已結束。",
  bankHeading: "商家銀行帳戶",
  bankName: "銀行",
  branch: "分行",
  accountName: "戶名",
  accountNumber: "帳號",
  transferNote: "請轉入上述確切金額，再於下方告知我們。截止前庫存會為你保留；商家核對帳戶後訂單才會確認。",
  proofHeading: "我已轉帳",
  proofEdit: "更新我的轉帳資料",
  last5: "轉出帳戶的後 5 碼",
  amountSent: "你轉帳的金額",
  paidAt: "轉帳日期與時間",
  paidAtZone: (zone: string) => `你裝置的時區：${zone}`,
  send: "送出轉帳資料",
  sending: "送出中…",
  sent: "轉帳資料已送出。商家核對帳戶後會確認。",
  yourDetails: "你最近送出的資料",
  storeTime: "店鋪時間（UTC+8）",
  rejectedPrefix: "商家備註",
  rejectedHelp: "請核對轉帳情況，並在截止前重新送出資料。",
  confirmed: "商家已確認收款，訂單已確認。",
  expired: "轉帳期限已結束，訂單已取消，庫存已釋出。",
  refunded: "商家已在本站之外為此訂單記錄退款。",
  invalidInput: "請輸入後 5 碼、轉帳金額與轉帳時間。",
  loadFailed: "無法載入轉帳資料，請重新整理後再試。",
  sendFailed: "無法送出資料，請檢查網路後再試。",
  refresh: "重新整理狀態",
  errors: {
    bank_transfer_unavailable: "此訂單無法使用銀行轉帳。",
    not_bank_transfer: "此訂單不是銀行轉帳訂單。",
    transfer_not_open: "此轉帳已不再開放。",
    transfer_window_closed: "轉帳期限已結束。",
    invalid_proof: "轉帳資料不正確。",
  },
};

export const bankTransferCopy: Record<Locale, typeof en> = { en, "zh-CN": zhCN, "zh-TW": zhTW };
