import type { Locale } from "@live-commerce/i18n";
import type { CarrierCode } from "./purchase";

const en = {
  address: "Delivery address",
  recipient_name: "Recipient name",
  phone: "Phone",
  region: "Region (optional)",
  city: "City",
  postal_code: "Postal code (optional)",
  line1: "Address line 1",
  line2: "Address line 2 (optional)",
  country: "Country",
  confirm: "Confirm address",
  create: "Create unpaid order",
  createNeedsConfirm: "Confirm your delivery address above to create the order.",
  loading: "Loading delivery details…",
  explain:
    "Check your delivery address and the quoted total before creating your order.",
  confirmed:
    "Address and total confirmed. Editing any field requires confirmation again.",
  uncertain:
    "We could not tell whether your address was received. Confirm it again before continuing.",
  recoverAddress: "Bring back saved address",
  recoverWithoutQuote:
    "Check and bring back your saved address first. Then get a new total before ordering.",
  recovered:
    "A saved address was found. Check it and confirm again before ordering.",
  failed:
    "Delivery details could not be confirmed. Reload the latest quotation and try again.",
  expired:
    "This quotation has expired. Get a new total before confirming your address.",
  invalid:
    "Check the recipient, phone number and address. Remove leading or trailing spaces.",
  reload: "Reload quotation",
  review: "Review delivery address",
  order: "Your order",
  orderID: "Order number",
  refresh: "Refresh order",
  hold: "Stock hold until",
  holdNote:
    "A timer ending does not confirm cancellation. Refresh to check the order status.",
  DRAFT: "Not paid",
  AWAITING_PAYMENT: "Payment pending",
  AWAITING_TRANSFER: "Waiting for bank transfer",
  AWAITING_COLLECTION: "Waiting for cash on delivery",
  CONFIRMED: "Order confirmed",
  CANCELLED: "Order canceled",
  unavailable:
    "Payment is not open on this page yet. No payment is taken by creating an order.",
  recovery:
    "You may already have placed this order. Find that order first so you do not order twice; starting a new cart will not bring it back.",
  // manual-fulfilment-v1 §5.2: the seller's attestation only; never "in transit" or "delivered".
  shipped: "Shipped by the seller",
  carrier: "Carrier",
  tracking: "Tracking number",
  copyTracking: "Copy tracking number",
  copied: "Copied",
  copyFailed: "Copy failed — select the number and copy it manually.",
  trackLink: "Open the carrier's tracking page",
  shipNote:
    "The seller recorded this shipment. Check the carrier for parcel progress.",
};
type Copy = { [K in keyof typeof en]: string };
// Q3 carrier display names (manual-fulfilment-v1 §3.1 codes); a merchant-entered carrier_name overrides.
export const carrierNames: Record<Locale, Record<CarrierCode, string>> = {
  en: {
    seven_eleven_cvs: "7-ELEVEN",
    familymart_cvs: "FamilyMart",
    hilife_cvs: "Hi-Life",
    okmart_cvs: "OK mart",
    sf_express: "SF Express",
    black_cat: "Black Cat",
    hsinchu: "Hsinchu",
    chunghwa_post: "Chunghwa Post",
    other: "Other",
  },
  "zh-TW": {
    seven_eleven_cvs: "7-ELEVEN 交貨便",
    familymart_cvs: "全家 店到店",
    hilife_cvs: "萊爾富",
    okmart_cvs: "OK mart",
    sf_express: "順豐速運",
    black_cat: "黑貓",
    hsinchu: "新竹",
    chunghwa_post: "中華郵政",
    other: "其他",
  },
  "zh-CN": {
    seven_eleven_cvs: "7-ELEVEN 交货便",
    familymart_cvs: "全家 店到店",
    hilife_cvs: "莱尔富",
    okmart_cvs: "OK mart",
    sf_express: "顺丰速运",
    black_cat: "黑猫",
    hsinchu: "新竹",
    chunghwa_post: "中华邮政",
    other: "其他",
  },
};
export const orderCopy: Record<Locale, Copy> = {
  en,
  "zh-CN": {
    address: "收货地址",
    recipient_name: "收货人",
    phone: "手机号码",
    region: "省／地区（选填）",
    city: "城市",
    postal_code: "邮政编码（选填）",
    line1: "详细地址",
    line2: "补充地址（选填）",
    country: "国家／地区",
    confirm: "确认收货信息",
    create: "创建未付款订单",
    createNeedsConfirm: "请先确认上方收货信息，才能创建订单。",
    loading: "正在加载收货信息…",
    explain: "请核对收货地址和报价总额，再创建订单。",
    confirmed: "收货信息与总额已确认。修改任一字段后，需要重新确认。",
    uncertain: "还不确定地址是否已送出，请再确认一次，再继续。",
    recoverAddress: "带回已保存的地址",
    recoverWithoutQuote: "请先核对并带回已保存的地址，再获取新的总额后下单。",
    recovered: "已找到之前保存的地址，请核对后重新确认。",
    failed: "暂时无法确认收货信息，请重新加载最新报价后重试。",
    expired: "报价已过期，请获取新的总额后再确认收货信息。",
    invalid: "请检查收货人、手机号码和地址，并去除前后空格。",
    reload: "重新加载报价",
    review: "核对收货地址",
    order: "你的订单",
    orderID: "订单编号",
    refresh: "刷新订单",
    hold: "库存保留至",
    holdNote: "时间结束不代表订单已取消，请刷新以确认当前状态。",
    DRAFT: "尚未付款",
    AWAITING_PAYMENT: "等待支付结果",
    AWAITING_TRANSFER: "等待银行转账",
    AWAITING_COLLECTION: "等待货到付款",
    CONFIRMED: "订单已确认",
    CANCELLED: "订单已取消",
    unavailable: "此页面暂未开放支付。创建订单不会扣款。",
    recovery:
      "你可能已经下过这笔订单。请先找回该订单，避免重复下单；重新开始购物车不会找回它。",
    shipped: "商家已发货",
    carrier: "物流公司",
    tracking: "运单号",
    copyTracking: "复制运单号",
    copied: "已复制",
    copyFailed: "复制失败，请选中运单号手动复制。",
    trackLink: "打开物流公司查询页面",
    shipNote: "这是商家记录的发货信息，配送进度请以物流公司为准。",
  },
  "zh-TW": {
    address: "收件地址",
    recipient_name: "收件人",
    phone: "手機號碼",
    region: "縣市／地區（選填）",
    city: "鄉鎮市區",
    postal_code: "郵遞區號（選填）",
    line1: "詳細地址",
    line2: "補充地址（選填）",
    country: "國家／地區",
    confirm: "確認收件資訊",
    create: "建立未付款訂單",
    createNeedsConfirm: "請先確認上方收件資訊，才能建立訂單。",
    loading: "正在載入收件資訊…",
    explain: "請核對收件地址與報價總額，再建立訂單。",
    confirmed: "收件資訊與總額已確認。修改任一欄位後，需要重新確認。",
    uncertain: "還不確定地址是否已送出，請再確認一次，再繼續。",
    recoverAddress: "帶回已儲存的地址",
    recoverWithoutQuote: "請先核對並帶回已儲存的地址，再取得新的總額後下單。",
    recovered: "已找到先前儲存的地址，請核對後重新確認。",
    failed: "暫時無法確認收件資訊，請重新載入最新報價後重試。",
    expired: "報價已過期，請取得新的總額後再確認收件資訊。",
    invalid: "請檢查收件人、手機號碼與地址，並移除前後空格。",
    reload: "重新載入報價",
    review: "核對收件地址",
    order: "你的訂單",
    orderID: "訂單編號",
    refresh: "重新整理訂單",
    hold: "庫存保留至",
    holdNote: "時間結束不代表訂單已取消，請重新整理以確認目前狀態。",
    DRAFT: "尚未付款",
    AWAITING_PAYMENT: "等待付款結果",
    AWAITING_TRANSFER: "等待銀行轉帳",
    AWAITING_COLLECTION: "等待貨到付款",
    CONFIRMED: "訂單已確認",
    CANCELLED: "訂單已取消",
    unavailable: "此頁面暫未開放付款。建立訂單不會扣款。",
    recovery:
      "你可能已經下過這筆訂單。請先找回該訂單，避免重複下單；重新開始購物車不會找回它。",
    shipped: "商家已出貨",
    carrier: "物流業者",
    tracking: "貨運單號",
    copyTracking: "複製貨運單號",
    copied: "已複製",
    copyFailed: "複製失敗，請選取單號後手動複製。",
    trackLink: "開啟物流業者查詢頁面",
    shipNote: "這是商家記錄的出貨資訊，配送進度請以物流業者為準。",
  },
};
