import type { Locale } from "@live-commerce/i18n";

const en = {
  address: "Delivery address",
  recipient_name: "Recipient name",
  phone: "Phone",
  region: "Region (optional)",
  city: "City",
  postal_code: "Postal code (optional)",
  line1: "Address line 1",
  line2: "Address line 2 (optional)",
  country: "Country",
  confirm: "Confirm address",
  create: "Create unpaid order",
  loading: "Loading delivery details…",
  explain:
    "Check your delivery address and the quoted total before creating your order.",
  confirmed:
    "Address and total confirmed. Editing any field requires confirmation again.",
  uncertain:
    "The address request could not be confirmed. Confirm again to recover it before continuing.",
  recoverAddress: "Recover saved address",
  recovered:
    "A saved address was found. Check it and confirm again before ordering.",
  failed:
    "Delivery details could not be confirmed. Reload the latest quotation and try again.",
  expired:
    "This quotation has expired. Get a new total before confirming your address.",
  invalid:
    "Check the recipient, phone number and address. Remove leading or trailing spaces.",
  reload: "Reload quotation",
  review: "Review delivery address",
  order: "Your order",
  orderID: "Order number",
  refresh: "Refresh order",
  hold: "Stock hold until",
  holdNote:
    "A timer ending does not confirm cancellation. Refresh to check the order status.",
  DRAFT: "Not paid",
  AWAITING_PAYMENT: "Payment pending",
  CONFIRMED: "Order confirmed",
  CANCELLED: "Order canceled",
  unavailable:
    "Payment is not open on this page yet. No payment is taken by creating an order.",
  recovery:
    "An order may already exist. Restore access and recover the same request; a new shopping session will not recover it.",
};
type Copy = { [K in keyof typeof en]: string };
export const orderCopy: Record<Locale, Copy> = {
  en,
  "zh-CN": {
    address: "收货地址",
    recipient_name: "收货人",
    phone: "手机号码",
    region: "省／地区（选填）",
    city: "城市",
    postal_code: "邮政编码（选填）",
    line1: "详细地址",
    line2: "补充地址（选填）",
    country: "国家／地区",
    confirm: "确认收货信息",
    create: "创建未付款订单",
    loading: "正在加载收货信息…",
    explain: "请核对收货地址和报价总额，再创建订单。",
    confirmed: "收货信息与总额已确认。修改任一字段后，需要重新确认。",
    uncertain: "地址请求结果尚未确认，请再次确认以恢复该请求，再继续操作。",
    recoverAddress: "恢复已保存地址",
    recovered: "已找到之前保存的地址，请核对后重新确认。",
    failed: "暂时无法确认收货信息，请重新加载最新报价后重试。",
    expired: "报价已过期，请获取新的总额后再确认收货信息。",
    invalid: "请检查收货人、手机号码和地址，并去除前后空格。",
    reload: "重新加载报价",
    review: "核对收货地址",
    order: "你的订单",
    orderID: "订单编号",
    refresh: "刷新订单",
    hold: "库存保留至",
    holdNote: "时间结束不代表订单已取消，请刷新以确认当前状态。",
    DRAFT: "尚未付款",
    AWAITING_PAYMENT: "等待支付结果",
    CONFIRMED: "订单已确认",
    CANCELLED: "订单已取消",
    unavailable: "此页面暂未开放支付。创建订单不会扣款。",
    recovery:
      "此前可能已创建订单。请恢复访问后查询同一笔请求；新建购物会话不能恢复原订单。",
  },
  "zh-TW": {
    address: "收件地址",
    recipient_name: "收件人",
    phone: "手機號碼",
    region: "縣市／地區（選填）",
    city: "鄉鎮市區",
    postal_code: "郵遞區號（選填）",
    line1: "詳細地址",
    line2: "補充地址（選填）",
    country: "國家／地區",
    confirm: "確認收件資訊",
    create: "建立未付款訂單",
    loading: "正在載入收件資訊…",
    explain: "請核對收件地址與報價總額，再建立訂單。",
    confirmed: "收件資訊與總額已確認。修改任一欄位後，需要重新確認。",
    uncertain: "地址請求結果尚未確認，請再次確認以恢復該請求，再繼續操作。",
    recoverAddress: "恢復已儲存地址",
    recovered: "已找到先前儲存的地址，請核對後重新確認。",
    failed: "暫時無法確認收件資訊，請重新載入最新報價後重試。",
    expired: "報價已過期，請取得新的總額後再確認收件資訊。",
    invalid: "請檢查收件人、手機號碼與地址，並移除前後空格。",
    reload: "重新載入報價",
    review: "核對收件地址",
    order: "你的訂單",
    orderID: "訂單編號",
    refresh: "重新整理訂單",
    hold: "庫存保留至",
    holdNote: "時間結束不代表訂單已取消，請重新整理以確認目前狀態。",
    DRAFT: "尚未付款",
    AWAITING_PAYMENT: "等待付款結果",
    CONFIRMED: "訂單已確認",
    CANCELLED: "訂單已取消",
    unavailable: "此頁面暫未開放付款。建立訂單不會扣款。",
    recovery:
      "先前可能已建立訂單。請恢復存取後查詢同一筆請求；新的購物工作階段無法恢復原訂單。",
  },
};
