// UI chrome copy of the storefront shell in the three UI locales (zh-CN / zh-TW / en). Merchant content (titles,
// descriptions, page bodies, nav labels, announcement) is single-language and is never translated here
// (contracts/storefront-v2.md preamble). Checkout/payment/CVS wording stays in its own copy modules.
import type { Locale } from "@live-commerce/i18n";

const en = {
  skip: "Skip to content",
  menu: "Menu",
  closeMenu: "Close menu",
  mainNav: "Main navigation",
  search: "Search",
  searchPlaceholder: "Search products",
  searchSubmit: "Search",
  cart: "Cart",
  cartItems: "Cart, {n} items",
  language: "Language",
  home: "Home",
  allProducts: "All products",
  collections: "Collections",
  previewBanner: "Preview — you are viewing an unpublished draft",
  previewExit: "Exit preview",
  contact: "Contact",
  followUs: "Follow us",
  footerNav: "Shop",
  viewAll: "View all",
  shopNow: "Shop now",
  newArrivals: "New arrivals",
  products: "Products",
  productCount: "{n} products",
  sortBy: "Sort by",
  sortNewest: "Newest",
  sortPriceAsc: "Price: low to high",
  sortPriceDesc: "Price: high to low",
  sortTitle: "Name",
  priceRange: "Price",
  priceMin: "Min",
  priceMax: "Max",
  apply: "Apply",
  clear: "Clear filters",
  loadMore: "Load more",
  loading: "Loading…",
  loadFailed: "Could not load more products.",
  retry: "Retry",
  noProducts: "No products here yet",
  noProductsHint: "Check back soon, or browse everything the shop has.",
  noResults: "No products match your filters",
  noResultsHint: "Try different words or widen the price range.",
  searchTitle: "Search",
  searchEmpty: "Type a product name or SKU code.",
  resultsFor: "Results for “{q}”",
  from: "From",
  soldOut: "Sold out",
  sale: "Sale",
  inStock: "In stock",
  lowStock: "Only a few left",
  outOfStock: "Sold out",
  addToCart: "Add to cart",
  buyNow: "Buy now",
  quantity: "Quantity",
  decrease: "Decrease quantity",
  increase: "Increase quantity",
  chooseOption: "Choose {name}",
  selectionIncomplete: "Choose every option first",
  description: "Description",
  inCollections: "In collections",
  added: "Added to your cart",
  viewCart: "View cart",
  checkout: "Checkout",
  continueShopping: "Continue shopping",
  cartTitle: "Your cart",
  cartEmpty: "Your cart is empty",
  cartEmptyHint: "Find something you like and it will wait for you here.",
  subtotal: "Subtotal",
  livePrice: "Live price",
  shippingAtCheckout: "Delivery and any discount are calculated at checkout.",
  remove: "Remove",
  removeLine: "Remove {name} from the cart",
  lineUnavailable: "No longer available",
  freeShipRemaining: "Add {amount} more for free delivery",
  freeShipReached: "You qualify for free delivery",
  cartFailed: "We could not update your cart. Nothing was charged.",
  cartUncertain: "The last cart change could not be confirmed. Retry to settle it before doing anything else.",
  cartConflict: "Your cart changed in another tab. We reloaded it.",
  cartNoStorage: "Your browser is blocking storage, so the cart cannot be kept. Allow site data and try again.",
  orderLockedTitle: "You have an order in progress",
  orderLockedBody: "Finish or review it first, or start a new cart. Your order is not cancelled either way.",
  viewOrder: "View my order",
  startNewCart: "Start a new cart",
  closeCart: "Close cart",
  openCart: "Open cart",
  checkoutTitle: "Checkout",
  checkoutBack: "Back to cart",
  checkoutEmpty: "There is nothing to check out yet.",
  notFoundTitle: "We couldn't find that page",
  notFoundBody: "The link may be old, or the product is no longer for sale.",
  backHome: "Back to the shop",
  errorTitle: "This page is not loading right now",
  errorBody: "The shop is reachable, but this page could not be read. Please try again.",
  closedTitle: "This shop is not open yet",
  closedBody: "The owner has not published the storefront. Please check back later.",
  pagination: "Pages",
  breadcrumb: "Breadcrumb",
  shareDescription: "Shop {name}",
  pageNotFound: "Page not found",
  collectionsEmpty: "No collections yet",
  photo: "Photo {n} of {total}",
  noImage: "No image",
  defaultStoreName: "Store",
  railPrev: "Previous products",
  railNext: "Next products",
  save: "Save {amount}",
  priceFrom: "from {price}",
};
type Copy = { [K in keyof typeof en]: string };

const zhTW: Copy = {
  skip: "跳到主要內容",
  menu: "選單",
  closeMenu: "關閉選單",
  mainNav: "主選單",
  search: "搜尋",
  searchPlaceholder: "搜尋商品",
  searchSubmit: "搜尋",
  cart: "購物車",
  cartItems: "購物車，{n} 件商品",
  language: "語言",
  home: "首頁",
  allProducts: "全部商品",
  collections: "商品分類",
  previewBanner: "預覽中 — 你正在查看尚未發布的草稿",
  previewExit: "離開預覽",
  contact: "聯絡我們",
  followUs: "追蹤我們",
  footerNav: "逛逛商店",
  viewAll: "查看全部",
  shopNow: "立即選購",
  newArrivals: "最新上架",
  products: "商品",
  productCount: "{n} 件商品",
  sortBy: "排序",
  sortNewest: "最新上架",
  sortPriceAsc: "價格由低到高",
  sortPriceDesc: "價格由高到低",
  sortTitle: "名稱",
  priceRange: "價格",
  priceMin: "最低",
  priceMax: "最高",
  apply: "套用",
  clear: "清除篩選",
  loadMore: "載入更多",
  loading: "載入中…",
  loadFailed: "無法載入更多商品。",
  retry: "重試",
  noProducts: "這裡還沒有商品",
  noProductsHint: "稍後再來看看，或逛逛店裡的全部商品。",
  noResults: "沒有符合條件的商品",
  noResultsHint: "換個關鍵字，或放寬價格範圍試試。",
  searchTitle: "搜尋",
  searchEmpty: "輸入商品名稱或 SKU 編號。",
  resultsFor: "「{q}」的搜尋結果",
  from: "起",
  soldOut: "已售完",
  sale: "特價",
  inStock: "現貨供應",
  lowStock: "僅剩少量",
  outOfStock: "已售完",
  addToCart: "加入購物車",
  buyNow: "立即購買",
  quantity: "數量",
  decrease: "減少數量",
  increase: "增加數量",
  chooseOption: "選擇{name}",
  selectionIncomplete: "請先選好所有規格",
  description: "商品說明",
  inCollections: "所屬分類",
  added: "已加入購物車",
  viewCart: "查看購物車",
  checkout: "前往結帳",
  continueShopping: "繼續選購",
  cartTitle: "購物車",
  cartEmpty: "購物車是空的",
  cartEmptyHint: "挑選喜歡的商品，它們會在這裡等你。",
  subtotal: "小計",
  livePrice: "直播價",
  shippingAtCheckout: "運費與折扣將於結帳時計算。",
  remove: "移除",
  removeLine: "將 {name} 移出購物車",
  lineUnavailable: "商品已無法購買",
  freeShipRemaining: "再買 {amount} 即可免運",
  freeShipReached: "已達免運門檻",
  cartFailed: "購物車更新失敗，未收取任何費用。",
  cartUncertain: "上一次購物車變更尚未確認，請先重試以完成確認。",
  cartConflict: "購物車已在其他分頁變更，已為你重新載入。",
  cartNoStorage: "瀏覽器封鎖了網站資料，無法保存購物車。請允許網站資料後再試。",
  orderLockedTitle: "你有一筆進行中的訂單",
  orderLockedBody: "請先查看或完成訂單，或開始新的購物車。兩種做法都不會取消既有訂單。",
  viewOrder: "查看我的訂單",
  startNewCart: "開始新的購物車",
  closeCart: "關閉購物車",
  openCart: "開啟購物車",
  checkoutTitle: "結帳",
  checkoutBack: "返回購物車",
  checkoutEmpty: "目前沒有可結帳的商品。",
  notFoundTitle: "找不到這個頁面",
  notFoundBody: "連結可能已過期，或商品已停售。",
  backHome: "回到商店",
  errorTitle: "此頁面暫時無法載入",
  errorBody: "商店可以連線，但這個頁面讀取失敗，請再試一次。",
  closedTitle: "商店尚未開張",
  closedBody: "店主還沒有發布這個商店，請稍後再來。",
  pagination: "分頁",
  breadcrumb: "導覽路徑",
  shareDescription: "選購 {name}",
  pageNotFound: "找不到頁面",
  collectionsEmpty: "目前沒有商品分類",
  photo: "第 {n} 張，共 {total} 張",
  noImage: "無圖片",
  defaultStoreName: "商店",
  railPrev: "上一組商品",
  railNext: "下一組商品",
  save: "省 {amount}",
  priceFrom: "{price} 起",
};

const zhCN: Copy = {
  skip: "跳到主要内容",
  menu: "菜单",
  closeMenu: "关闭菜单",
  mainNav: "主菜单",
  search: "搜索",
  searchPlaceholder: "搜索商品",
  searchSubmit: "搜索",
  cart: "购物车",
  cartItems: "购物车，{n} 件商品",
  language: "语言",
  home: "首页",
  allProducts: "全部商品",
  collections: "商品分类",
  previewBanner: "预览中 — 你正在查看尚未发布的草稿",
  previewExit: "退出预览",
  contact: "联系我们",
  followUs: "关注我们",
  footerNav: "逛逛商店",
  viewAll: "查看全部",
  shopNow: "立即选购",
  newArrivals: "最新上架",
  products: "商品",
  productCount: "{n} 件商品",
  sortBy: "排序",
  sortNewest: "最新上架",
  sortPriceAsc: "价格由低到高",
  sortPriceDesc: "价格由高到低",
  sortTitle: "名称",
  priceRange: "价格",
  priceMin: "最低",
  priceMax: "最高",
  apply: "应用",
  clear: "清除筛选",
  loadMore: "加载更多",
  loading: "加载中…",
  loadFailed: "无法加载更多商品。",
  retry: "重试",
  noProducts: "这里还没有商品",
  noProductsHint: "稍后再来看看，或逛逛店里的全部商品。",
  noResults: "没有符合条件的商品",
  noResultsHint: "换个关键词，或放宽价格范围试试。",
  searchTitle: "搜索",
  searchEmpty: "输入商品名称或 SKU 编号。",
  resultsFor: "“{q}”的搜索结果",
  from: "起",
  soldOut: "已售完",
  sale: "特价",
  inStock: "现货供应",
  lowStock: "仅剩少量",
  outOfStock: "已售完",
  addToCart: "加入购物车",
  buyNow: "立即购买",
  quantity: "数量",
  decrease: "减少数量",
  increase: "增加数量",
  chooseOption: "选择{name}",
  selectionIncomplete: "请先选好所有规格",
  description: "商品说明",
  inCollections: "所属分类",
  added: "已加入购物车",
  viewCart: "查看购物车",
  checkout: "前往结账",
  continueShopping: "继续选购",
  cartTitle: "购物车",
  cartEmpty: "购物车是空的",
  cartEmptyHint: "挑选喜欢的商品，它们会在这里等你。",
  subtotal: "小计",
  livePrice: "直播价",
  shippingAtCheckout: "运费与折扣将在结账时计算。",
  remove: "移除",
  removeLine: "将 {name} 移出购物车",
  lineUnavailable: "商品已无法购买",
  freeShipRemaining: "再买 {amount} 即可免运",
  freeShipReached: "已达免运门槛",
  cartFailed: "购物车更新失败，未收取任何费用。",
  cartUncertain: "上一次购物车变更尚未确认，请先重试以完成确认。",
  cartConflict: "购物车已在其他标签页变更，已为你重新加载。",
  cartNoStorage: "浏览器屏蔽了网站数据，无法保存购物车。请允许网站数据后再试。",
  orderLockedTitle: "你有一笔进行中的订单",
  orderLockedBody: "请先查看或完成订单，或开始新的购物车。两种做法都不会取消已有订单。",
  viewOrder: "查看我的订单",
  startNewCart: "开始新的购物车",
  closeCart: "关闭购物车",
  openCart: "打开购物车",
  checkoutTitle: "结账",
  checkoutBack: "返回购物车",
  checkoutEmpty: "目前没有可结账的商品。",
  notFoundTitle: "找不到这个页面",
  notFoundBody: "链接可能已过期，或商品已停售。",
  backHome: "回到商店",
  errorTitle: "此页面暂时无法加载",
  errorBody: "商店可以连接，但这个页面读取失败，请再试一次。",
  closedTitle: "商店尚未开张",
  closedBody: "店主还没有发布这个商店，请稍后再来。",
  pagination: "分页",
  breadcrumb: "导航路径",
  shareDescription: "选购 {name}",
  pageNotFound: "找不到页面",
  collectionsEmpty: "目前没有商品分类",
  photo: "第 {n} 张，共 {total} 张",
  noImage: "无图片",
  defaultStoreName: "商店",
  railPrev: "上一组商品",
  railNext: "下一组商品",
  save: "省 {amount}",
  priceFrom: "{price} 起",
};

export const shopCopy: Record<Locale, Copy> = { en, "zh-TW": zhTW, "zh-CN": zhCN };

// "{n}" style placeholders; unknown names are left untouched so a typo is visible, not silently blank.
export function fmt(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (whole, name: string) => (name in vars ? String(vars[name]) : whole));
}
