-- S1 media-sizes B: immutable JPEG children of existing product images; no new public write capability.
-- Depends on 0082 product_images/commerce_catalog_media and buyer.resolve_published_store (0081).
CREATE TABLE catalog.product_image_sizes (
 tenant_id uuid NOT NULL,
 store_id uuid NOT NULL,
 image_id uuid NOT NULL,
 width integer NOT NULL CHECK (width IN (360,720,1080)),
 bytes bytea NOT NULL CHECK (octet_length(bytes) BETWEEN 1 AND 2097152),
 sha256 bytea NOT NULL CHECK (octet_length(sha256)=32),
 PRIMARY KEY (tenant_id,store_id,image_id,width),
 FOREIGN KEY (tenant_id,store_id,image_id) REFERENCES catalog.product_images(tenant_id,store_id,id) ON DELETE CASCADE
);
REVOKE ALL ON catalog.product_image_sizes FROM PUBLIC;
ALTER TABLE catalog.product_image_sizes ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalog.product_image_sizes FORCE ROW LEVEL SECURITY;
CREATE POLICY scope_access ON catalog.product_image_sizes TO commerce_runtime
 USING (tenant_id=nullif(current_setting('app.tenant_id',true),'')::uuid AND store_id=nullif(current_setting('app.store_id',true),'')::uuid)
 WITH CHECK (tenant_id=nullif(current_setting('app.tenant_id',true),'')::uuid AND store_id=nullif(current_setting('app.store_id',true),'')::uuid);
GRANT SELECT,INSERT,DELETE ON catalog.product_image_sizes TO commerce_runtime;
CREATE POLICY media_definer_read ON catalog.product_image_sizes FOR SELECT TO commerce_catalog_media USING (true);
GRANT SELECT ON catalog.product_image_sizes TO commerce_catalog_media;

CREATE FUNCTION catalog.buyer_media_image_size(p_origin text,p_product uuid,p_image uuid,p_width integer)
RETURNS TABLE(content_type text,bytes bytea,sha256 bytea,is_rendition boolean)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$
#variable_conflict use_column
DECLARE v_store uuid;
BEGIN
 IF p_width IS NULL OR p_width NOT IN (360,720,1080) THEN RAISE EXCEPTION 'invalid width' USING ERRCODE='PT400'; END IF;
 SELECT r.store_id INTO v_store FROM buyer.resolve_published_store(p_origin) r;
 IF NOT FOUND THEN RAISE EXCEPTION 'storefront not published' USING ERRCODE='PT404'; END IF;
 RETURN QUERY
 SELECT CASE WHEN z.image_id IS NOT NULL THEN 'image/jpeg'::text ELSE i.content_type END,
        COALESCE(z.bytes,i.bytes),COALESCE(z.sha256,i.sha256),z.image_id IS NOT NULL
 FROM catalog.product_images i
 JOIN catalog.products p ON p.tenant_id=i.tenant_id AND p.store_id=i.store_id AND p.id=i.product_id
 JOIN control.stores s ON s.tenant_id=i.tenant_id AND s.id=i.store_id
 LEFT JOIN catalog.product_image_sizes z ON z.tenant_id=i.tenant_id AND z.store_id=i.store_id AND z.image_id=i.id AND z.width=p_width
 WHERE s.id=v_store AND s.active AND i.product_id=p_product AND i.id=p_image AND p.status='active';
 IF NOT FOUND THEN RAISE EXCEPTION 'image not found' USING ERRCODE='PT404'; END IF;
END $$;
ALTER FUNCTION catalog.buyer_media_image_size(text,uuid,uuid,integer) OWNER TO commerce_catalog_media;
REVOKE ALL ON FUNCTION catalog.buyer_media_image_size(text,uuid,uuid,integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION catalog.buyer_media_image_size(text,uuid,uuid,integer) TO commerce_buyer_runtime;

COMMENT ON TABLE catalog.product_image_sizes IS 'S1 merchant-owned immutable JPEG82 product-image children. commerce_runtime scoped insert/read/delete only; cascade with original. No byte updates, no public backfill, no second storage authority.';
COMMENT ON COLUMN catalog.product_image_sizes.tenant_id IS 'internal/catalog custody from server-authenticated platform.Scope; commerce_runtime RLS only, never browser input.';
COMMENT ON COLUMN catalog.product_image_sizes.store_id IS 'internal/catalog store scope, same parent FK/RLS; commerce_catalog_media reads only through published-origin definer, not arbitrary store lookup.';
COMMENT ON COLUMN catalog.product_image_sizes.image_id IS 'internal/catalog immutable parent ID; cascade removes derived bytes on authorized original deletion. No independent media lifecycle.';
COMMENT ON COLUMN catalog.product_image_sizes.width IS 'Strict request width bucket 360/720/1080; aspect preserved, actual dimensions smaller only when source would be upscaled.';
COMMENT ON COLUMN catalog.product_image_sizes.bytes IS 'Go-generated bounded JPEG (quality82,v1); original photo bytes remain untouched. Source alpha composites over white; EXIF orientation is normalized.';
COMMENT ON COLUMN catalog.product_image_sizes.sha256 IS 'internal/catalog SHA256 of generated bytes, exposed only as response ETag; immutable, not a caller-supplied digest.';
COMMENT ON FUNCTION catalog.buyer_media_image_size(text,uuid,uuid,integer) IS 'S1 read-only published-origin definer: ACTIVE store/product and exact scoped image, with fixed width bucket. Missing sizes return original is_rendition=false and HTTP must send no-store; never generates bytes or trusts client store IDs.';
