-- PAYUNi NotifyURL receiver (w4-01b-payuni-notify). A notification is only a trigger to query:
-- it NEVER writes a money fact. The ingress verifies the callback signature in Go, then the two
-- definers below record an idempotent receipt and wake the attempt's existing payment_query_v1 job.
--
-- The frozen integration.payment_job_queue links each attempt to exactly one query job
-- (a.job_id = j.id), so a second query job cannot be inserted. The record definer therefore
-- reschedules (wakes) the existing job's scheduled_at to now instead of inserting a new one
-- (guard_payment_job_family permits scheduled_at changes; id/kind/args/unique_key/queue stay frozen).
--
-- SANDBOX/MOCK only: endpoints and receipts are pinned to environment='SANDBOX'; no LIVE keys.

CREATE ROLE commerce_payuni_ingress NOLOGIN INHERIT NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE NOREPLICATION;
COMMENT ON ROLE commerce_payuni_ingress IS 'payments webhook ingress; executes signature-fenced PAYUNi notify receipt definers only, no merchant or payment table access';
GRANT USAGE ON SCHEMA payments TO commerce_payuni_ingress;

-- ------------------------------------------------------------------------------------------------
-- review_cases: a notify amount/currency/profile mismatch precedes any provider observation, so
-- NOTIFY_MISMATCH carries no source_report_hash. Widen the reason list, relax the NOT NULL and
-- pin the two together so every other reason still requires an observation hash.
-- ------------------------------------------------------------------------------------------------
DO $$
DECLARE v_def text;
BEGIN
 SELECT pg_get_constraintdef(c.oid) INTO v_def FROM pg_constraint c
  WHERE c.conrelid='payments.review_cases'::regclass AND c.conname='review_cases_reason_check';
 IF v_def IS NULL OR v_def NOT LIKE '%REFUND_CONFLICTING%' OR v_def LIKE '%NOTIFY_MISMATCH%'
  OR v_def !~ '::text\]\)' THEN
  RAISE EXCEPTION 'review_cases_reason_check has an unexpected shape: %',v_def; END IF;
 v_def:=regexp_replace(v_def,'::text\]\)','::text, ''NOTIFY_MISMATCH''::text])');
 ALTER TABLE payments.review_cases DROP CONSTRAINT review_cases_reason_check;
 EXECUTE format('ALTER TABLE payments.review_cases ADD CONSTRAINT review_cases_reason_check %s',v_def);
END $$;

ALTER TABLE payments.review_cases ALTER COLUMN source_report_hash DROP NOT NULL;
ALTER TABLE payments.review_cases ADD CONSTRAINT review_cases_report_hash_scope
 CHECK((reason='NOTIFY_MISMATCH') = (source_report_hash IS NULL));

-- ------------------------------------------------------------------------------------------------
-- Endpoint custody: one row per (tenant,store,connection,execution_profile). The token itself is a
-- random secret generated by the registrar CLI; only its sha256 is stored. The HashKey/HashIV used
-- to verify a callback lives in integration.account_credentials (shared with query/hosted), so the
-- endpoint only needs the token hash to select the connection.
-- ------------------------------------------------------------------------------------------------
CREATE TABLE payments.payuni_notify_endpoints (
 endpoint_id uuid PRIMARY KEY,
 tenant_id uuid NOT NULL,store_id uuid NOT NULL,connection_id uuid NOT NULL,
 provider text GENERATED ALWAYS AS ('payuni'::text) STORED,
 environment text NOT NULL CHECK(environment='SANDBOX'),
 account_id text NOT NULL CHECK(account_id ~ '^[A-Za-z0-9_-]{1,64}$'),
 execution_profile text NOT NULL CHECK(execution_profile IN ('PROVIDER_MOCK','SANDBOX')),
 enabled boolean NOT NULL,
 token_hash bytea NOT NULL CHECK(octet_length(token_hash)=32),
 created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 UNIQUE(tenant_id,store_id,connection_id,execution_profile),
 UNIQUE(token_hash),
 FOREIGN KEY(tenant_id,store_id,connection_id,provider,environment,account_id)
  REFERENCES integration.merchant_accounts(tenant_id,store_id,id,provider,environment,account_id)
);

CREATE TABLE payments.payuni_notify_receipts (
 id uuid PRIMARY KEY,endpoint_id uuid NOT NULL,
 connection_id uuid NOT NULL,
 environment text NOT NULL CHECK(environment='SANDBOX'),
 account_id text NOT NULL CHECK(account_id ~ '^[A-Za-z0-9_-]{1,64}$'),
 payload_sha256 bytea NOT NULL CHECK(octet_length(payload_sha256)=32),
 merchant_trade_no text NOT NULL CHECK(merchant_trade_no ~ '^[A-Za-z0-9_-]{1,25}$'),
 provider_reference text NOT NULL CHECK(provider_reference ~ '^[A-Za-z0-9_-]{0,64}$'),
 amount_twd bigint NOT NULL CHECK(amount_twd>=1),
 status text NOT NULL CHECK(status IN ('SUCCESS','UNKNOWN','UNAPPROVED')),
 trade_status text NOT NULL CHECK(trade_status ~ '^[0-9]{1,4}$'),
 disposition text NOT NULL CHECK(disposition IN ('QUEUED','MISMATCH','UNKNOWN_TRADE')),
 reason text NOT NULL CHECK(reason IN ('notify_triggered','notify_mismatch','notify_unknown_trade')),
 attempt_id uuid,tenant_id uuid,store_id uuid,job_id bigint,
 redelivery_count integer NOT NULL DEFAULT 0 CHECK(redelivery_count BETWEEN 0 AND 100000),
 received_at timestamptz NOT NULL DEFAULT clock_timestamp(),last_redelivered_at timestamptz,
 CHECK((attempt_id IS NULL)=(tenant_id IS NULL) AND (attempt_id IS NULL)=(store_id IS NULL)),
 CHECK((disposition IN ('QUEUED','MISMATCH'))=(attempt_id IS NOT NULL)),
 CHECK((disposition='QUEUED')=(job_id IS NOT NULL)),
 UNIQUE(connection_id,payload_sha256),
 FOREIGN KEY(endpoint_id) REFERENCES payments.payuni_notify_endpoints(endpoint_id)
);

DO $$ DECLARE v_table text; v_col record; BEGIN
 FOREACH v_table IN ARRAY ARRAY['payuni_notify_endpoints','payuni_notify_receipts'] LOOP
  EXECUTE format('ALTER TABLE payments.%I ENABLE ROW LEVEL SECURITY',v_table);
  EXECUTE format('ALTER TABLE payments.%I FORCE ROW LEVEL SECURITY',v_table);
  EXECUTE format('REVOKE ALL ON payments.%I FROM PUBLIC',v_table);
  EXECUTE format('COMMENT ON TABLE payments.%I IS %L',v_table,
   'payments owner; private PAYUNi notify metadata for the ingress definers; never stores raw notify body or key');
  FOR v_col IN SELECT column_name FROM information_schema.columns
   WHERE table_schema='payments' AND table_name=v_table LOOP
   EXECUTE format('COMMENT ON COLUMN payments.%I.%I IS %L',v_table,v_col.column_name,
    'payments owner; PAYUNi notify ingress bounded metadata; no direct runtime access or PSP authority');
  END LOOP;
 END LOOP;
END $$;

-- integration_writer owns the ingress definers: read the endpoint, append receipts, wake the job.
CREATE POLICY payuni_endpoint_integration ON payments.payuni_notify_endpoints
 FOR SELECT TO commerce_integration_writer USING(true);
CREATE POLICY payuni_receipt_integration ON payments.payuni_notify_receipts TO commerce_integration_writer
 USING(true) WITH CHECK(true);
GRANT SELECT ON payments.payuni_notify_endpoints TO commerce_integration_writer;
GRANT SELECT,INSERT ON payments.payuni_notify_receipts TO commerce_integration_writer;
-- PostgreSQL requires an UPDATE column grant for SELECT ... FOR UPDATE (the dedup row lock), and the
-- redelivery bump writes exactly these two columns; guard_payuni_notify_receipt forbids every other change.
GRANT UPDATE(redelivery_count,last_redelivered_at) ON payments.payuni_notify_receipts TO commerce_integration_writer;

-- The registrar may only touch the notify token/enabled flag; identity columns are fixed by the
-- UNIQUE conflict target and the column-level grant.
GRANT SELECT,INSERT ON payments.payuni_notify_endpoints TO commerce_payment_registry_writer;
GRANT UPDATE(enabled,token_hash,updated_at) ON payments.payuni_notify_endpoints TO commerce_payment_registry_writer;
CREATE POLICY payuni_endpoint_registry ON payments.payuni_notify_endpoints TO commerce_payment_registry_writer
 USING(tenant_id=nullif(current_setting('app.tenant_id',true),'')::uuid
  AND store_id=nullif(current_setting('app.store_id',true),'')::uuid)
 WITH CHECK(tenant_id=nullif(current_setting('app.tenant_id',true),'')::uuid
  AND store_id=nullif(current_setting('app.store_id',true),'')::uuid);

-- The only review case the ingress may open is NOTIFY_MISMATCH (no observation hash exists yet).
GRANT INSERT ON payments.review_cases TO commerce_integration_writer;
CREATE POLICY payuni_notify_review ON payments.review_cases FOR INSERT TO commerce_integration_writer
 WITH CHECK(reason='NOTIFY_MISMATCH'
  AND tenant_id=nullif(current_setting('app.tenant_id',true),'')::uuid
  AND store_id=nullif(current_setting('app.store_id',true),'')::uuid);

CREATE FUNCTION payments.guard_payuni_notify_receipt() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
BEGIN
 IF (to_jsonb(NEW)-'redelivery_count'-'last_redelivered_at') IS DISTINCT FROM
  (to_jsonb(OLD)-'redelivery_count'-'last_redelivered_at')
  OR NEW.redelivery_count<OLD.redelivery_count THEN
  RAISE EXCEPTION 'PAYUNi notify receipt immutable field changed' USING ERRCODE='42501';
 END IF;
 RETURN NEW;
END $$;
ALTER FUNCTION payments.guard_payuni_notify_receipt() OWNER TO commerce_integration_writer;
REVOKE ALL ON FUNCTION payments.guard_payuni_notify_receipt() FROM PUBLIC;
CREATE TRIGGER guard_payuni_notify_receipt BEFORE UPDATE ON payments.payuni_notify_receipts
 FOR EACH ROW EXECUTE FUNCTION payments.guard_payuni_notify_receipt();
COMMENT ON FUNCTION payments.guard_payuni_notify_receipt() IS 'payments owner; integration writer allows only notify redelivery metadata to change; no receipt rewrite';

-- One enabled endpoint's scope plus the current credential envelope and (for the rotation grace
-- window) the previous one. Zero rows means unknown or disabled endpoint; the Go ingress maps that
-- to 404 without writing a receipt.
CREATE FUNCTION payments.payuni_resolve_endpoint(p_token_hash bytea)
RETURNS TABLE(tenant_id uuid,store_id uuid,connection_id uuid,environment text,
 account_id text,execution_profile text,
 cur_version bigint,cur_key_id text,cur_nonce bytea,cur_ciphertext bytea,
 prev_version bigint,prev_key_id text,prev_nonce bytea,prev_ciphertext bytea)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$
 SELECT e.tenant_id,e.store_id,e.connection_id,e.environment,e.account_id,e.execution_profile,
  cur.version,cur.key_id,cur.nonce,cur.ciphertext,
  prev.version,prev.key_id,prev.nonce,prev.ciphertext
 FROM payments.payuni_notify_endpoints e
 JOIN integration.merchant_accounts m ON m.tenant_id=e.tenant_id AND m.store_id=e.store_id
  AND m.id=e.connection_id AND m.environment=e.environment AND m.account_id=e.account_id
 JOIN integration.account_credentials cur ON cur.tenant_id=m.tenant_id AND cur.store_id=m.store_id
  AND cur.connection_id=m.id AND cur.version=m.credential_version
 LEFT JOIN integration.account_credentials prev ON prev.tenant_id=m.tenant_id AND prev.store_id=m.store_id
  AND prev.connection_id=m.id AND prev.version=m.credential_version-1
 WHERE e.token_hash=p_token_hash AND e.enabled AND m.provider='payuni'
$$;
ALTER FUNCTION payments.payuni_resolve_endpoint(bytea) OWNER TO commerce_integration_writer;
REVOKE ALL ON FUNCTION payments.payuni_resolve_endpoint(bytea) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION payments.payuni_resolve_endpoint(bytea) TO commerce_payuni_ingress;
COMMENT ON FUNCTION payments.payuni_resolve_endpoint(bytea) IS 'payments owner; ingress reads one enabled endpoint scope plus current/previous credential envelopes only; no plaintext or tenant authority from the token';

-- The whole receipt is one transaction: advisory-lock dedup on (connection, payload_sha256), map
-- MerTradeNo to the connection attempt, and either wake the existing query job (QUEUED), open a
-- NOTIFY_MISMATCH review case (MISMATCH), or record a receipt only (UNKNOWN_TRADE). No money fact.
CREATE FUNCTION payments.payuni_record_notify(p_token_hash bytea,p_payload_sha256 bytea,
 p_merchant_trade_no text,p_provider_reference text,p_amount_twd bigint,p_status text,p_trade_status text)
RETURNS TABLE(disposition text,receipt_id uuid,attempt_id uuid,tenant_id uuid,store_id uuid,job_id bigint)
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE ep payments.payuni_notify_endpoints%ROWTYPE;
 a checkout.payment_attempts%ROWTYPE;
 existing payments.payuni_notify_receipts%ROWTYPE;
 v_receipt uuid; v_disposition text; v_reason text;
 v_attempt uuid; v_tenant uuid; v_store uuid; v_job bigint;
BEGIN
 IF p_token_hash IS NULL OR octet_length(p_token_hash)<>32
  OR p_payload_sha256 IS NULL OR octet_length(p_payload_sha256)<>32
  OR p_merchant_trade_no IS NULL OR p_merchant_trade_no !~ '^[A-Za-z0-9_-]{1,25}$'
  OR p_provider_reference IS NULL OR (p_provider_reference<>'' AND p_provider_reference !~ '^[A-Za-z0-9_-]{1,64}$')
  OR p_amount_twd IS NULL OR p_amount_twd<1
  OR p_status IS NULL OR p_status NOT IN ('SUCCESS','UNKNOWN','UNAPPROVED')
  OR p_trade_status IS NULL OR p_trade_status !~ '^[0-9]{1,4}$' THEN
  RAISE EXCEPTION 'invalid PAYUNi notify record' USING ERRCODE='22023'; END IF;
 SELECT e.* INTO ep FROM payments.payuni_notify_endpoints e
  WHERE e.token_hash=p_token_hash FOR SHARE;
 IF NOT FOUND OR NOT ep.enabled THEN
  RAISE EXCEPTION 'PAYUNi notify endpoint unavailable' USING ERRCODE='40001'; END IF;
 PERFORM set_config('app.tenant_id',ep.tenant_id::text,true);
 PERFORM set_config('app.store_id',ep.store_id::text,true);
 PERFORM set_config('app.principal_id','',true);
 PERFORM pg_advisory_xact_lock(hashtextextended('payuni.notify|'
  ||ep.connection_id||'|'||encode(p_payload_sha256,'hex'),0));
 SELECT x.* INTO existing FROM payments.payuni_notify_receipts x
  WHERE x.connection_id=ep.connection_id AND x.payload_sha256=p_payload_sha256 FOR UPDATE;
 IF FOUND THEN
  UPDATE payments.payuni_notify_receipts SET redelivery_count=redelivery_count+1,
   last_redelivered_at=clock_timestamp() WHERE id=existing.id;
  RETURN QUERY SELECT 'DUPLICATE'::text,existing.id,existing.attempt_id,
   existing.tenant_id,existing.store_id,existing.job_id;
  RETURN;
 END IF;
 v_receipt:=gen_random_uuid();
 SELECT x.* INTO a FROM checkout.payment_attempts x
  WHERE x.merchant_trade_no=p_merchant_trade_no
   AND x.tenant_id=ep.tenant_id AND x.store_id=ep.store_id
   AND x.connection_id=ep.connection_id AND x.environment=ep.environment;
 IF NOT FOUND THEN
  v_disposition:='UNKNOWN_TRADE'; v_reason:='notify_unknown_trade';
 ELSIF a.currency<>'TWD' OR a.amount_minor/100<>p_amount_twd
  OR a.execution_profile<>ep.execution_profile THEN
  v_disposition:='MISMATCH'; v_reason:='notify_mismatch';
  v_attempt:=a.id; v_tenant:=a.tenant_id; v_store:=a.store_id;
 ELSE
  v_disposition:='QUEUED'; v_reason:='notify_triggered';
  v_attempt:=a.id; v_tenant:=a.tenant_id; v_store:=a.store_id; v_job:=a.job_id;
 END IF;
 INSERT INTO payments.payuni_notify_receipts(id,endpoint_id,connection_id,environment,account_id,
  payload_sha256,merchant_trade_no,provider_reference,amount_twd,status,trade_status,
  disposition,reason,attempt_id,tenant_id,store_id,job_id)
 VALUES(v_receipt,ep.endpoint_id,ep.connection_id,ep.environment,ep.account_id,
  p_payload_sha256,p_merchant_trade_no,p_provider_reference,p_amount_twd,p_status,p_trade_status,
  v_disposition,v_reason,v_attempt,v_tenant,v_store,v_job);
 IF v_disposition='MISMATCH' THEN
  INSERT INTO payments.review_cases(tenant_id,store_id,attempt_id,reason,source_report_hash)
   VALUES(v_tenant,v_store,v_attempt,'NOTIFY_MISMATCH',NULL)
   ON CONFLICT DO NOTHING;
 ELSIF v_disposition='QUEUED' THEN
  UPDATE river_payment.river_job SET scheduled_at=clock_timestamp()
   WHERE id=v_job AND kind='payment_query_v1' AND unique_key IS NULL
    AND state IN ('available','pending','scheduled','retryable')
    AND args=jsonb_build_object('operation_id',v_attempt::text,'version',1);
 END IF;
 RETURN QUERY SELECT v_disposition,v_receipt,v_attempt,v_tenant,v_store,v_job;
END $$;
ALTER FUNCTION payments.payuni_record_notify(bytea,bytea,text,text,bigint,text,text)
 OWNER TO commerce_integration_writer;
REVOKE ALL ON FUNCTION payments.payuni_record_notify(bytea,bytea,text,text,bigint,text,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION payments.payuni_record_notify(bytea,bytea,text,text,bigint,text,text)
 TO commerce_payuni_ingress;
COMMENT ON FUNCTION payments.payuni_record_notify(bytea,bytea,text,text,bigint,text,text) IS 'payments owner; signed ingress dedupes one notify, records its receipt and either wakes the existing query job or opens NOTIFY_MISMATCH; no money fact, no job insert';

-- Operator registrar creates or rotates the notify token for one SANDBOX payuni connection. The
-- plaintext token (returned by the CLI, never stored) is hashed before this call.
CREATE FUNCTION payments.set_payuni_notify_endpoint(p_tenant uuid,p_store uuid,p_principal uuid,
 p_connection uuid,p_endpoint uuid,p_profile text,p_enabled boolean,p_token_hash bytea)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE acct integration.merchant_accounts%ROWTYPE;
BEGIN
 PERFORM integration.require_stripe_registrar_scope(p_tenant,p_store,p_principal);
 IF p_connection IS NULL OR p_endpoint IS NULL OR p_profile NOT IN ('PROVIDER_MOCK','SANDBOX')
  OR p_enabled IS NULL OR p_token_hash IS NULL OR octet_length(p_token_hash)<>32 THEN
  RAISE EXCEPTION 'invalid PAYUNi notify endpoint input' USING ERRCODE='22023'; END IF;
 SELECT x.* INTO acct FROM integration.merchant_accounts x WHERE x.tenant_id=p_tenant
  AND x.store_id=p_store AND x.id=p_connection AND x.provider='payuni' FOR SHARE;
 IF NOT FOUND OR acct.environment<>'SANDBOX' THEN
  RAISE EXCEPTION 'PAYUNi endpoint account unavailable' USING ERRCODE='PT409'; END IF;
 INSERT INTO payments.payuni_notify_endpoints(endpoint_id,tenant_id,store_id,connection_id,
  environment,account_id,execution_profile,enabled,token_hash)
 VALUES(p_endpoint,p_tenant,p_store,p_connection,acct.environment,acct.account_id,p_profile,
  p_enabled,p_token_hash)
 ON CONFLICT(tenant_id,store_id,connection_id,execution_profile)
  DO UPDATE SET enabled=EXCLUDED.enabled,token_hash=EXCLUDED.token_hash,updated_at=clock_timestamp();
 INSERT INTO ops.audit_events(tenant_id,store_id,principal_id,action)
 VALUES(p_tenant,p_store,p_principal,'payuni.notify_endpoint_set');
END $$;
ALTER FUNCTION payments.set_payuni_notify_endpoint(uuid,uuid,uuid,uuid,uuid,text,boolean,bytea)
 OWNER TO commerce_payment_registry_writer;
REVOKE ALL ON FUNCTION payments.set_payuni_notify_endpoint(uuid,uuid,uuid,uuid,uuid,text,boolean,bytea) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION payments.set_payuni_notify_endpoint(uuid,uuid,uuid,uuid,uuid,text,boolean,bytea)
 TO commerce_payment_registrar;
COMMENT ON FUNCTION payments.set_payuni_notify_endpoint(uuid,uuid,uuid,uuid,uuid,text,boolean,bytea) IS 'payments owner; operator registrar creates or rotates one SANDBOX notify token by connection+profile; no key custody, rebind or LIVE ingress';
