// Purpose: LC-U2a three-locale stream/reply labels and fixed privacy-safe rule explanations.
// Depends on: frozen live-console-v1 reply rules; no provider error strings or buyer data.
// Used by: CommentStream and CommentReply.
const en = {
  title: "Live comments",
  all: "All",
  keyword: "Keywords",
  private: "Private messages",
  unreplied: "Awaiting reply",
  older: "Earlier comments",
  refresh: "Refresh",
  loading: "Loading comments…",
  empty: "No comments yet",
  unnamed: "Unnamed buyer",
  attachment: "Has attachment",
  select: "View buyer",
  selectBuyer: "Select a comment with a claim to view the buyer.",
  noBundle: "No linked claim. Buyer identity is not inferred.",
  privateReply: "Private reply",
  publicReply: "Public reply",
  text: "Reply text",
  template: "Published template",
  freeText: "Write a reply",
  send: "Send once",
  sending: "Submitting…",
  one: "Each comment permits one private reply. An automatic claim reply also uses this opportunity.",
  window:
    "A buyer's inbound message opens a 24-hour DM window. Sending this private reply does not open it.",
  publicRule: "Public replies must not contain payment links.",
  verify:
    "Delivery is uncertain. Verify in Messenger before taking any further action; this reply will not be resent automatically.",
  testOnly: "Test accounts only",
  permission: "Reply permission is required.",
  preempt:
    "An automatic reply is pending. Send this manual reply instead? The buyer's claim link may then need manual handling.",
  confirm: "Confirm manual reply",
  cancel: "Cancel",
  pendingLink:
    "The claim link needs manual handling; it has not been delivered automatically.",
  reset: "Comment stream restarted. Reloading current comments.",
  hidden: "Comments cleared while this page is hidden.",
  queued: "Queued",
  sent: "Sent",
  failed: "Failed",
  blocked: "Blocked",
  unknown: "Delivery uncertain",
  unavailable: "Comments are temporarily unavailable. Refresh to try again.",
  forbidden:
    "You cannot access these comments. Ask a store owner to review your permissions.",
  restricted: "Restricted",
  restrictedWarning:
    "This buyer is restricted. Review the restriction before sending manually.",
  reviewSend: "I have reviewed the restriction",
  capability: "This reply action is unavailable for the connected account.",
  used: "This comment's private reply has already been used.",
  auto_pending: "An automatic reply is pending. Do not send another reply.",
  auto_pending_confirm:
    "An automatic reply is pending; explicit confirmation is required to replace it.",
  expired_7d: "The private-reply window has expired.",
  ig_live_ended:
    "The Instagram live session has ended; private reply is unavailable.",
  ig_live_unsupported:
    "Public replies to Instagram live comments are not supported.",
  public_reply_forbidden_content:
    "Remove the payment link from this public reply.",
  duplicate_recent:
    "A recent duplicate reply was refused. Check the existing reply.",
  comment_facts_unavailable:
    "Comment details are not ready. Refresh before replying.",
  comment_unknown:
    "This comment could not be verified. Refresh before replying.",
  page_comment: "You cannot send a private reply to a Page's own comment.",
  reply_comment_unsupported: "Replies to nested comments are not supported.",
  invalid_text: "Check the reply text and its length.",
  invalid_request: "This request is invalid. Refresh the comments.",
  invalid_cursor:
    "The comment cursor is no longer valid. Refresh the comments.",
  no_source: "Connect a post or live source before reading comments.",
  window_closed: "The messaging window is closed.",
  rate_limited: "Requests are temporarily limited. Wait before refreshing.",
  unauthorized: "Your session expired. Sign in again.",
  not_found: "This comment or session is no longer available.",
  stream_unavailable: "The comment stream is temporarily unavailable.",
  retry_later:
    "Unable to confirm the result. Verify before taking further action.",
  invalid_json: "The request could not be read.",
  json_required: "The request format is invalid.",
  method_not_allowed: "This action is not supported.",
};
type Copy = Record<keyof typeof en, string>;
const tw: Copy = {
  ...en,
  title: "直播留言",
  all: "全部",
  keyword: "關鍵字",
  private: "私訊",
  unreplied: "待回覆",
  older: "較早的留言",
  refresh: "重新整理",
  loading: "載入留言中…",
  empty: "尚無留言",
  unnamed: "未提供姓名",
  attachment: "含附件",
  select: "查看買家",
  selectBuyer: "選擇已關聯認領的留言，查看買家資料。",
  noBundle: "尚無關聯認領，不推測買家身分。",
  privateReply: "私密回覆",
  publicReply: "公開回覆",
  text: "回覆內容",
  template: "已發佈範本",
  freeText: "自行輸入",
  send: "傳送一次",
  sending: "提交中…",
  one: "每則留言只能私密回覆一次；自動認領回覆也會使用這次機會。",
  window: "買家主動傳訊後才開啟 24 小時私訊視窗；傳送此私密回覆不會開啟視窗。",
  publicRule: "公開回覆不得包含付款連結。",
  verify: "傳送結果未確認。請先到 Messenger 核對；系統不會自動重送。",
  testOnly: "僅測試帳號",
  permission: "需要回覆訊息權限。",
  preempt:
    "自動回覆正在等待。要改為手動回覆嗎？買家的認領連結可能需要手動處理。",
  confirm: "確認手動回覆",
  cancel: "取消",
  pendingLink: "認領連結待手動處理，尚未自動送達。",
  reset: "留言串已重啟，正在重新載入。",
  hidden: "頁面隱藏時已清除留言。",
  queued: "排隊中",
  sent: "已傳送",
  failed: "傳送失敗",
  blocked: "已阻擋",
  unknown: "結果未確認",
  unavailable: "留言暫時無法載入，請重新整理。",
  forbidden: "沒有留言存取權限，請店主確認權限。",
  restricted: "已限制",
  restrictedWarning: "這位買家已受限制，手動傳送前請確認限制原因。",
  reviewSend: "已確認限制，繼續手動回覆",
  capability: "已連接帳號目前無法使用這項回覆功能。",
  used: "這則留言已使用私密回覆機會。",
  auto_pending: "自動回覆等待中，請勿重複傳送。",
  auto_pending_confirm: "自動回覆等待中，取代前需要明確確認。",
  expired_7d: "私密回覆期限已過。",
  ig_live_ended: "Instagram 直播已結束，無法私密回覆。",
  ig_live_unsupported: "不支援公開回覆 Instagram 直播留言。",
  public_reply_forbidden_content: "請移除公開回覆中的付款連結。",
  duplicate_recent: "近期已有相同回覆，請先核對。",
  comment_facts_unavailable: "留言資料尚未就緒，回覆前請重新整理。",
  comment_unknown: "無法確認這則留言，請重新整理。",
  page_comment: "無法私密回覆主頁自己的留言。",
  reply_comment_unsupported: "不支援回覆子留言。",
  invalid_text: "請檢查回覆內容及長度。",
  invalid_request: "請求無效，請重新整理留言。",
  invalid_cursor: "留言游標已失效，請重新整理。",
  no_source: "請先連接貼文或直播來源。",
  window_closed: "私訊視窗已關閉。",
  rate_limited: "請求暫時受限，請稍後重新整理。",
  unauthorized: "登入已過期，請重新登入。",
  not_found: "找不到此留言或場次。",
  stream_unavailable: "留言串暫時無法使用。",
  retry_later: "無法確認結果，請先核對再操作。",
  invalid_json: "無法讀取請求。",
  json_required: "請求格式錯誤。",
  method_not_allowed: "不支援這項操作。",
};
const cn: Copy = {
  ...tw,
  title: "直播评论",
  keyword: "关键词",
  private: "私信",
  unreplied: "待回复",
  older: "较早的评论",
  refresh: "刷新",
  loading: "正在加载评论…",
  empty: "暂无评论",
  unnamed: "未提供姓名",
  attachment: "含附件",
  select: "查看买家",
  selectBuyer: "选择已关联认领的评论，查看买家资料。",
  noBundle: "暂无关联认领，不推测买家身份。",
  privateReply: "私密回复",
  publicReply: "公开回复",
  text: "回复内容",
  template: "已发布模板",
  freeText: "自行输入",
  send: "发送一次",
  sending: "提交中…",
  one: "每条评论只能私密回复一次；自动认领回复也会使用这次机会。",
  window:
    "买家主动发消息后才开启 24 小时私信窗口；发送此私密回复不会开启窗口。",
  publicRule: "公开回复不得包含付款链接。",
  verify: "发送结果未确认。请先到 Messenger 核对；系统不会自动重发。",
  testOnly: "仅测试账号",
  permission: "需要回复消息权限。",
  preempt:
    "自动回复正在等待。要改为手动回复吗？买家的认领链接可能需要手动处理。",
  confirm: "确认手动回复",
  pendingLink: "认领链接待手动处理，尚未自动送达。",
  reset: "评论流已重启，正在重新加载。",
  hidden: "页面隐藏时已清除评论。",
  queued: "排队中",
  sent: "已发送",
  failed: "发送失败",
  blocked: "已阻止",
  unknown: "结果未确认",
  unavailable: "评论暂时无法加载，请刷新。",
  forbidden: "没有评论访问权限，请店主确认权限。",
  restricted: "已限制",
  restrictedWarning: "这位买家已受限制，手动发送前请确认限制原因。",
  reviewSend: "已确认限制，继续手动回复",
  capability: "已连接账号目前无法使用这项回复功能。",
  used: "这条评论已使用私密回复机会。",
  auto_pending: "自动回复等待中，请勿重复发送。",
  auto_pending_confirm: "自动回复等待中，替换前需要明确确认。",
  expired_7d: "私密回复期限已过。",
  ig_live_ended: "Instagram 直播已结束，无法私密回复。",
  ig_live_unsupported: "不支持公开回复 Instagram 直播评论。",
  public_reply_forbidden_content: "请移除公开回复中的付款链接。",
  duplicate_recent: "近期已有相同回复，请先核对。",
  comment_facts_unavailable: "评论资料尚未就绪，回复前请刷新。",
  comment_unknown: "无法确认这条评论，请刷新。",
  page_comment: "无法私密回复主页自己的评论。",
  reply_comment_unsupported: "不支持回复子评论。",
  invalid_text: "请检查回复内容及长度。",
  invalid_request: "请求无效，请刷新评论。",
  invalid_cursor: "评论游标已失效，请刷新。",
  no_source: "请先连接帖子或直播来源。",
  window_closed: "私信窗口已关闭。",
  rate_limited: "请求暂时受限，请稍后刷新。",
  unauthorized: "登录已过期，请重新登录。",
  not_found: "找不到此评论或场次。",
  stream_unavailable: "评论流暂时不可用。",
  retry_later: "无法确认结果，请先核对再操作。",
  invalid_json: "无法读取请求。",
  json_required: "请求格式错误。",
  method_not_allowed: "不支持这项操作。",
};
/** Select only authored copy; no upstream message is rendered. */
export const commentCopy = (locale: string): Copy =>
  locale === "zh-TW" ? tw : locale === "zh-CN" ? cn : en;
/** Map a closed server code, retaining a safe fallback for unknown future states. */
export function commentReason(locale: string, code: string): string {
  const c = commentCopy(locale);
  return Object.hasOwn(c, code) ? c[code as keyof Copy] : c.unavailable;
}
