// Purpose: LC-U1 merchant vocabulary in all supported locales, with honest unavailable and reconciliation states.
// Depends on: @live-commerce/i18n locale keys; no network services.
// Used by: LiveWorkspace, LiveConsole, SessionResults and live workspace hooks.
const en = {
  refusals: { too_many_open_windows: "Five sessions already accept comments. Close one before opening another.", billing_restricted: "Billing restrictions prevent starting this session. Check your subscription.", below_reserved: "Stock cannot fall below reserved, allocated and unavailable quantities. Refresh and enter a higher target." },
  leavePending: "A request is still pending. Leave this session? Its receipt will still require reconciliation.",
  feed: "Comment feed", stream: { live: "Receiving", throttled: "Temporarily rate-limited", reauth_required: "Reconnect the account", unavailable: "Not available", not_started: "Not started" },
  title: "Live console", sessions: "Live sessions", settings: "Session settings", choose: "Choose a session",
  settingsChoose: "Choose a session to configure its products and comment ordering.", emptySessions: "No sessions yet. Create one in Live sessions.",
  before: "Before going live", during: "Live session", after: "After the session", archived: "Archived",
  start: "Start live session", end: "End live session", copy: "Copy to next session", copyLast: "Copy previous session",
  lifecycleHint: "These controls open or close comment ordering. They do not start or stop your Facebook or Instagram broadcast.",
  confirmEnd: "End comment ordering for this session? Your platform broadcast will not be stopped.",
  refresh: "Refresh", loading: "Loading session…", unavailable: "The live console is not available. Refresh to check again; no session state has been assumed.",
  signedOut: "Your session has expired. Sign in again.", forbidden: "You do not have permission for this action.",
  conflict: "The session changed. The latest state has been loaded; review it before trying again.",
  failed: "The action was not accepted. Check the latest session state before trying again.",
  uncertain: "The result is not confirmed. Other actions are locked. Check the result or retry this same request; do not create a new request.",
  recovery: "The earlier request cannot be restored safely. Do not submit it again. Keep this session and use the original request receipt to reconcile its result.",
  secondaryUnavailable: "Some session controls are unavailable. Live statistics remain visible; refresh to check those controls again.",
  retry: "Retry the same request", updated: "Updated", taipei: "Taipei time", polling: "Refreshes every 5 seconds while visible",
  comments: "Comments", keyword: "Keyword comments", buyers: "Buyers", orders: "Orders", amount: "Order amount", paid: "Collected revenue",
  unknown: "Not available", observed: "Comments observed", graph: "Platform comment count", offers: "Session products", empty: "No products in this session yet.",
  configure: "Configure products and comment source", stock: "Sellable stock", saveStock: "Save stock", untracked: "Untracked", missingWarehouse: "Set a warehouse in Inventory before adjusting stock.",
  stockPermission: "Live-stock adjustment or inventory-management permission is required.",
  manageRequired: "Session-management permission is required.", open: "Open", closed: "Closed", recommend: "Recommend", recommended: "Recommended",
  recommendHint: "Highlights this product in the console only; no public comment is sent.", soldOut: "Sold out", lowStock: "Low stock", claimed: "Claimed quantity", paidQty: "Paid quantity",
  stockInvalid: "Enter a whole nonnegative quantity, with a change no larger than 1,000.",
  stockChanged: "Stock changed while you were editing. Your input is kept; review before saving. Current sellable stock:", confirmStock: "Confirm updated stock",
  facebook: "Facebook broadcast / post", openFacebook: "Open Facebook post", facebookLinkNotice: "Opens the linked post on Facebook. Access depends on your account and the post's visibility.",
  noFacebookLink: "No verified Facebook post link is connected. Check the comment source settings.",
  instagram: "Instagram Live cannot be embedded here. Watch in Instagram; supported comments are handled separately.",
  endReadOnly: "This session has ended; products are read-only. Copy it to prepare the next session.",
  name: "Next session name", confirmCopy: "Create next session", cancel: "Cancel", copiedConflicts: "The session was copied with product conflicts. Check its products before going live.",
  results: "Session results", paidOrders: "Paid orders", multiSession: "Includes orders shared with another session; do not sum across sessions.", sandbox: "Sandbox collected", noResults: "Session results are not available.",
  viewConsole: "Open live console", source: "Comment source and ordering settings", readOnly: "Read-only access", pending: "Sending…",
};
export type WorkspaceCopy = typeof en;
const tw: WorkspaceCopy = {
  settingsChoose: "請先選擇場次，再設定商品與留言收單。", emptySessions: "尚無場次，請先到直播場次建立。",
  refusals: { too_many_open_windows: "已有 5 場開放收單，請先關閉其中一場。", billing_restricted: "帳務限制暫時阻止開播，請核對訂閱狀態。", below_reserved: "庫存不可低於已保留、已分配與不可售數量，請重新整理並提高目標數量。" },
  leavePending: "尚有待確認請求。仍要離開場次嗎？離開後仍須核對回執。",
  feed: "留言接收", stream: { live: "接收中", throttled: "暫時限流", reauth_required: "請重新連接帳號", unavailable: "暫時無法接收", not_started: "尚未開始" },
  title: "直播控台", sessions: "直播場次", settings: "場次設定", choose: "選擇場次",
  before: "開播前準備", during: "直播中", after: "直播後", archived: "已封存",
  start: "開始直播", end: "結束直播", copy: "複製成下一場", copyLast: "複製上一場",
  lifecycleHint: "此處控制本場留言收單，不會啟動或停止 Facebook、Instagram 的實際直播。",
  confirmEnd: "結束本場留言收單？平台上的直播不會因此停止。",
  refresh: "重新整理", loading: "正在載入場次…", unavailable: "暫時無法讀取直播控台。請重新整理確認；系統未推測場次狀態。",
  signedOut: "登入已過期，請重新登入。", forbidden: "你沒有執行此操作的權限。",
  conflict: "場次已變更，已重新讀取最新資料；請確認後再操作。", failed: "操作未被接受，請核對最新場次狀態後重試。",
  uncertain: "結果尚未確認，其他操作已鎖定。請核對結果或重試同一請求，不要新增請求。",
  recovery: "無法安全還原先前請求，請勿重新提交。保留此場次，以原請求回執核對結果。",
  secondaryUnavailable: "部分場次控制暫時無法讀取；直播統計仍可查看，請重新整理以核對控制狀態。",
  retry: "重試同一請求", updated: "更新於", taipei: "台北時間", polling: "畫面顯示時每 5 秒更新",
  comments: "留言", keyword: "關鍵字留言", buyers: "買家", orders: "訂單", amount: "訂單金額", paid: "營業額（已收款）",
  unknown: "尚無資料", observed: "已觀察留言", graph: "平台留言數", offers: "本場商品", empty: "本場尚未加入商品。",
  configure: "設定商品與留言來源", stock: "可售庫存", saveStock: "儲存庫存", untracked: "不追蹤", missingWarehouse: "請先到庫存頁設定倉庫，再調整數量。",
  stockPermission: "需要直播庫存調整或庫存管理權限。",
  manageRequired: "需要直播管理權限。", open: "開放", closed: "關閉", recommend: "推薦", recommended: "推薦中",
  recommendHint: "僅在控台標示推薦商品，不發送公開留言。", soldOut: "已售罄", lowStock: "庫存偏低", claimed: "認領數量", paidQty: "已付款數量",
  stockInvalid: "請輸入非負整數，單次增減不可超過 1,000。",
  stockChanged: "編輯期間庫存已變更，已保留您的輸入；儲存前請重新確認。目前可售庫存：", confirmStock: "確認最新庫存",
  facebook: "Facebook 直播／貼文", openFacebook: "在 Facebook 查看貼文", facebookLinkNotice: "會開啟 Facebook 貼文，能否查看取決於帳號權限與貼文可見性。",
  noFacebookLink: "尚未連接可驗證的 Facebook 貼文連結，請核對留言來源設定。",
  instagram: "Instagram 直播無法嵌入此處，請在 Instagram 觀看；支援的留言另行接收。",
  endReadOnly: "本場已結束，商品僅供查看。可複製成下一場繼續準備。",
  name: "下一場名稱", confirmCopy: "建立下一場", cancel: "取消", copiedConflicts: "已複製場次，但部分商品有衝突；開播前請核對商品設定。",
  results: "場次成果", paidOrders: "已收款訂單", multiSession: "包含跨場次訂單，不可跨場次直接加總。", sandbox: "沙盒收款", noResults: "暫時無法讀取場次成果。",
  viewConsole: "開啟直播控台", source: "留言來源與收單設定", readOnly: "僅供查看", pending: "正在送出…",
};
const cn: WorkspaceCopy = {
  ...tw, title: "直播控台", sessions: "直播场次", settings: "场次设置", choose: "选择场次", before: "开播前准备", during: "直播中", after: "直播后", archived: "已归档",
  settingsChoose: "请先选择场次，再设置商品与评论收单。", emptySessions: "尚无场次，请先到直播场次创建。",
  start: "开始直播", end: "结束直播", copy: "复制成下一场", copyLast: "复制上一场", lifecycleHint: "此处控制本场评论收单，不会启动或停止 Facebook、Instagram 的实际直播。",
  feed: "评论接收", stream: { live: "接收中", throttled: "暂时限流", reauth_required: "请重新连接账号", unavailable: "暂时无法接收", not_started: "尚未开始" },
  leavePending: "仍有待确认请求。仍要离开场次吗？离开后仍须核对回执。",
  refusals: { too_many_open_windows: "已有 5 场开放收单，请先关闭其中一场。", billing_restricted: "账务限制暂时阻止开播，请核对订阅状态。", below_reserved: "库存不可低于已保留、已分配与不可售数量，请刷新并提高目标数量。" },
  confirmEnd: "结束本场评论收单？平台上的直播不会因此停止。", refresh: "刷新", loading: "正在加载场次…", unavailable: "暂时无法读取直播控台。请刷新确认；系统未推测场次状态。",
  signedOut: "登录已过期，请重新登录。", forbidden: "你没有执行此操作的权限。", conflict: "场次已变更，已重新读取最新数据；请确认后再操作。", failed: "操作未被接受，请核对最新场次状态后重试。",
  uncertain: "结果尚未确认，其他操作已锁定。请核对结果或重试同一请求，不要新增请求。", recovery: "无法安全还原先前请求，请勿重新提交。保留此场次，以原请求回执核对结果。", secondaryUnavailable: "部分场次控制暂时无法读取；直播统计仍可查看，请刷新以核对控制状态。", retry: "重试同一请求", updated: "更新于", taipei: "台北时间", polling: "画面显示时每 5 秒更新",
  comments: "评论", keyword: "关键词评论", buyers: "买家", orders: "订单", amount: "订单金额", paid: "营业额（已收款）", unknown: "暂无数据", observed: "已观察评论", graph: "平台评论数", offers: "本场商品", empty: "本场尚未加入商品。",
  configure: "设置商品与评论来源", stock: "可售库存", saveStock: "保存库存", untracked: "不追踪", missingWarehouse: "请先到库存页设置仓库，再调整数量。", stockPermission: "需要直播库存调整或库存管理权限。",
  manageRequired: "需要直播管理权限。", open: "开放", closed: "关闭", recommend: "推荐", recommended: "推荐中", recommendHint: "仅在控台标示推荐商品，不发送公开评论。", soldOut: "已售罄", lowStock: "库存偏低", claimed: "认领数量", paidQty: "已付款数量", stockInvalid: "请输入非负整数，单次增减不可超过 1,000。",
  stockChanged: "编辑期间库存已变更，已保留您的输入；保存前请重新确认。当前可售库存：", confirmStock: "确认最新库存",
  facebook: "Facebook 直播／帖子", openFacebook: "在 Facebook 查看帖子", facebookLinkNotice: "会打开 Facebook 帖子，能否查看取决于账号权限与帖子可见性。", noFacebookLink: "尚未连接可验证的 Facebook 帖子链接，请核对评论来源设置。", instagram: "Instagram 直播无法嵌入此处，请在 Instagram 观看；支持的评论另行接收。",
  endReadOnly: "本场已结束，商品仅供查看。可复制成下一场继续准备。", name: "下一场名称", confirmCopy: "创建下一场", cancel: "取消", copiedConflicts: "已复制场次，但部分商品有冲突；开播前请核对商品设置。",
  results: "场次成果", paidOrders: "已收款订单", multiSession: "包含跨场次订单，不可跨场次直接加总。", sandbox: "沙盒收款", noResults: "暂时无法读取场次成果。", viewConsole: "打开直播控台", source: "评论来源与收单设置", readOnly: "仅供查看", pending: "正在提交…",
};
export const workspaceCopy = { "zh-TW": tw, "zh-CN": cn, en };
