// Purpose: canonicalize response bodies for the browser password canary scan.
// Depends on: JSON; public error-envelope request IDs generated by admin/lib/auth.ts.
// Used by: password-auth.spec.ts and password-bff.test.ts; every sensitive body value remains scanned.
/** Prepare an actual response body for the privacy canary assertion. */
export function responseBodyForSecretScan(body: string): string {
  let value: unknown;
  try { value = JSON.parse(body); } catch { return body; }
  const canonical = JSON.stringify(value);
  // Keep raw bytes for duplicate keys, escaped values and numbers that JSON parsing can reformat.
  // Only the exact canonical envelope emitted by localError can exempt its public UUID.
  if (canonical !== body) return body + "\n" + canonical;
  if (value && typeof value === "object" && !Array.isArray(value)) {
    const envelope = value as Record<string, unknown>;
    if (typeof envelope.code === "string" && typeof envelope.message === "string"
        && typeof envelope.retryable === "boolean" && envelope.details
        && typeof envelope.details === "object" && !Array.isArray(envelope.details)
        && typeof envelope.request_id === "string"
        && /^[0-9a-f]{12}4[0-9a-f]{3}[89ab][0-9a-f]{15}$/.test(envelope.request_id)) {
      return JSON.stringify({ ...envelope, request_id: "<public-request-id>" });
    }
  }
  return canonical;
}
