// W0 route metadata only; data/authorization remain in the existing BFF and Go.
import type { RouteEntry } from "../../route-types.ts";
export const settingsRoutes = [
  {
    id: "settings",
    path: "/settings",
    group: "settings",
    labelKey: "settingsPage",
    icon: "settings",
    permission: "integration:read",
    template: "workspace",
    nav: true,
    spec: "tests/admin/meta-connect.spec.ts",
  },
  {
    id: "team",
    path: "/team",
    group: "settings",
    labelKey: "team",
    icon: "support",
    permission: "owner",
    template: "list",
    nav: true,
    spec: "tests/admin/staff-team.spec.ts",
  },
  {
    id: "billing",
    path: "/billing",
    group: "settings",
    labelKey: "billing",
    icon: "orders",
    permission: "billing:manage",
    template: "workspace",
    nav: true,
    spec: "tests/admin/customers-billing.spec.ts",
  },
  // W4-U1: platform card payments activation + settlement ledger. nav:false (never a second nav:true in a
  // group, W3-U5); entry is the in-page link from Settings step 收款 and the shell route guard still applies.
  {
    id: "card-payments",
    path: "/settings/payments/card",
    group: "settings",
    labelKey: "cardPayments",
    icon: "orders",
    permission: "integration:read",
    template: "workspace",
    nav: false,
    spec: "tests/admin/card-payments.spec.ts",
  },
  {
    id: "settlements",
    path: "/settings/settlements",
    group: "settings",
    labelKey: "settlements",
    icon: "wallet",
    permission: "billing:manage",
    template: "workspace",
    nav: false,
    spec: "tests/admin/settlements.spec.ts",
  },
] satisfies RouteEntry[];
