// D7/D9 copy only; values and availability come from the frozen attribution read, not locale or client inference.
import type { Locale } from "@live-commerce/i18n";
const en = {
  title: "Ad attribution & session review",
  back: "Back to ads",
  intro:
    "Order results and Meta attribution are different views; they can differ and are never added together.",
  from: "From",
  to: "To",
  apply: "Read report",
  invalid: "Choose a valid date range of at most 92 days.",
  loading: "Reading attribution…",
  retry: "Try again",
  unavailable: "Attribution is unavailable. Try again.",
  forbidden: "You do not have permission to read ads.",
  signedOut: "Your session ended.",
  signIn: "Sign in",
  empty: "No attribution records in this window.",
  selectDraft: "Ad draft",
  selectSession: "Live session",
  noDraft: "No draft records",
  noSession: "No session records",
  drafts: "Draft report",
  sessions: "Session review",
  ordersTitle: "Order results",
  metaTitle: "Meta reported",
  orderZone: "Order dates: Asia/Taipei",
  metaZone: "Meta account time zone",
  unknown: "Not provided",
  provisional: "Meta data may still change",
  spend: "Ad spend",
  path: "Source path",
  adClick: "Ad click",
  boosted: "From promoted post",
  boostedNote:
    "Promoted-post orders may come from paid or organic comments; ad exposure is unknown.",
  orders: "Collected orders",
  net: "Net revenue after refunds",
  pending: "Uncollected orders",
  pendingValue: "Uncollected amount",
  roas: "Order ROAS",
  purchases: "Purchases",
  purchaseValue: "Purchase value",
  audience: "Ad audience (Meta statistics)",
  day: "Meta account day",
  dimension: "Breakdown",
  bucket: "Bucket",
  reach: "Reach",
  impressions: "Impressions",
  clicks: "Clicks",
  engagements: "Engagements",
  comments: "Comments",
  ageGender: "Age & gender",
  region: "Region",
  placement: "Placement",
  device: "Device",
  hourly: "Hourly",
  noAudience: "Meta has not provided audience breakdowns.",
  buyers: "Buyer distribution (order results)",
  county: "Ship-to county / city",
  newBuyers: "New buyers",
  returning: "Returning buyers",
  average: "Average order value",
  products: "Top products",
  product: "Product",
  quantity: "Quantity",
  noBuyers: "No buyer breakdowns in this window.",
  minuteOrders: "Orders per minute",
  at: "Time (Asia/Taipei)",
  timeline: "One session timeline",
  timelineNote:
    "Hourly ad spend is aligned using absolute timestamps. No per-person join is made between Meta audiences and buyers.",
  claims: "Claims",
  checkoutLinks: "Checkout links",
  paid: "Paid / collected orders",
  funnel: "Comments → claims → checkout links → collected orders",
  viewers: "Viewers",
  liveAudience: "Viewer profile (Meta statistics)",
  audienceRefresh: "Refresh audience insights",
  audienceReading: "Queuing audience read…",
  audienceQueued:
    "Audience read queued. Read this report again later to see any updated insights.",
  audienceUnknown:
    "The read request outcome is unknown. Retry the same request.",
  audienceRetry: "Retry same read request",
  audienceForbidden:
    "Audience insights are unavailable: read_insights / pages_read_engagement permissions are missing or no longer valid.",
  audienceFailed: "Could not queue the audience read. Try again.",
  audienceStorage:
    "Could not retain this read request safely. Reload the page before trying again.",
  views: "Video views",
  peak: "Peak concurrent viewers",
  totalTime: "Total view time (ms)",
  viewTime: "View time (ms), not people",
  insufficient: "Audience too small; Meta did not provide a profile.",
  notAuthorized: "Live audience insights are not authorized.",
  ambiguous:
    "Several promotions were live; these orders were not assigned to a single ad",
  post: "Bound posts",
  draftIds: "Linked drafts",
  start: "Starts",
  end: "Ends",
  noTimeline: "No timeline observations provided.",
  noRows: "No rows provided.",
  source: "Source reference",
};
export type AttributionCopy = typeof en;
export const attributionCopy: Record<Locale, AttributionCopy> = {
  en,
  "zh-TW": {
    title: "廣告歸因與直播復盤",
    back: "返回廣告",
    intro: "訂單實績與 Meta 歸因採不同口徑，數字可能不同，兩者不相加。",
    from: "開始日期",
    to: "結束日期",
    apply: "讀取報表",
    invalid: "請選擇有效日期範圍，最多 92 天。",
    loading: "讀取歸因資料…",
    retry: "重試",
    unavailable: "暫時無法取得歸因資料，請重試。",
    forbidden: "你沒有讀取廣告的權限。",
    signedOut: "工作階段已結束。",
    signIn: "登入",
    empty: "此期間沒有歸因紀錄。",
    selectDraft: "廣告草稿",
    selectSession: "直播場次",
    noDraft: "沒有草稿紀錄",
    noSession: "沒有場次紀錄",
    drafts: "草稿報表",
    sessions: "直播復盤",
    ordersTitle: "訂單實績",
    metaTitle: "Meta 回報",
    orderZone: "訂單日期：Asia/Taipei",
    metaZone: "Meta 帳戶時區",
    unknown: "未提供",
    provisional: "Meta 數據可能仍會更新",
    spend: "廣告花費",
    path: "來源路徑",
    adClick: "廣告點擊",
    boosted: "受推廣貼文帶來",
    boostedNote: "受推廣貼文的訂單可能來自付費或自然留言，無法確認廣告曝光。",
    orders: "已收款訂單",
    net: "扣除退款後淨營收",
    pending: "待收款訂單",
    pendingValue: "待收款金額",
    roas: "訂單 ROAS",
    purchases: "購買次數",
    purchaseValue: "購買金額",
    audience: "廣告受眾（Meta 統計）",
    day: "Meta 帳戶日期",
    dimension: "分類",
    bucket: "群組",
    reach: "觸及",
    impressions: "曝光",
    clicks: "點擊",
    engagements: "互動",
    comments: "留言",
    ageGender: "年齡與性別",
    region: "地區",
    placement: "版位",
    device: "裝置",
    hourly: "每小時",
    noAudience: "Meta 尚未提供受眾分類。",
    buyers: "買家分佈（訂單實績）",
    county: "收件縣市",
    newBuyers: "新買家",
    returning: "回購買家",
    average: "平均訂單金額",
    products: "熱銷商品",
    product: "商品",
    quantity: "數量",
    noBuyers: "此期間沒有買家分類資料。",
    minuteOrders: "每分鐘訂單",
    at: "時間（Asia/Taipei）",
    timeline: "同一場次時間軸",
    timelineNote:
      "每小時廣告花費以絕對時間對齊；Meta 觀眾統計不與個別買家連結。",
    claims: "喊單",
    checkoutLinks: "結帳連結",
    paid: "已付款／收款訂單",
    funnel: "留言 → 喊單 → 結帳連結 → 已收款訂單",
    viewers: "觀眾",
    liveAudience: "觀眾輪廓（Meta 統計）",
    audienceRefresh: "刷新觀眾洞察",
    audienceReading: "正在排入觀眾讀取…",
    audienceQueued: "觀眾讀取已排入佇列，請稍後重新讀取報表查看更新。",
    audienceUnknown: "讀取請求結果未知，請重試同一請求。",
    audienceRetry: "重試同一讀取請求",
    audienceForbidden:
      "觀眾洞察不可用：缺少 read_insights／pages_read_engagement 權限，或授權已失效。",
    audienceFailed: "無法排入觀眾讀取，請重試。",
    audienceStorage: "無法安全保留此讀取請求，請重新載入頁面後再試。",
    views: "影片觀看次數",
    peak: "最高同時觀看人數",
    totalTime: "總觀看時間（毫秒）",
    viewTime: "觀看時間（毫秒），非人數",
    insufficient: "觀眾數不足，Meta 未提供輪廓",
    notAuthorized: "尚未授權直播觀眾洞察。",
    ambiguous: "多個推廣同時進行，未分配到單一廣告",
    post: "綁定貼文",
    draftIds: "關聯草稿",
    start: "開始",
    end: "結束",
    noTimeline: "尚未提供時間軸觀測。",
    noRows: "尚未提供紀錄。",
    source: "來源參照",
  },
  "zh-CN": {
    title: "广告归因与直播复盘",
    back: "返回广告",
    intro: "订单实绩与 Meta 归因采用不同口径，数字可能不同，两者不相加。",
    from: "开始日期",
    to: "结束日期",
    apply: "读取报表",
    invalid: "请选择有效日期范围，最多 92 天。",
    loading: "读取归因数据…",
    retry: "重试",
    unavailable: "暂时无法取得归因数据，请重试。",
    forbidden: "你没有读取广告的权限。",
    signedOut: "会话已结束。",
    signIn: "登录",
    empty: "此期间没有归因记录。",
    selectDraft: "广告草稿",
    selectSession: "直播场次",
    noDraft: "没有草稿记录",
    noSession: "没有场次记录",
    drafts: "草稿报表",
    sessions: "直播复盘",
    ordersTitle: "订单实绩",
    metaTitle: "Meta 回报",
    orderZone: "订单日期：Asia/Taipei",
    metaZone: "Meta 账户时区",
    unknown: "未提供",
    provisional: "Meta 数据可能仍会更新",
    spend: "广告花费",
    path: "来源路径",
    adClick: "广告点击",
    boosted: "受推广帖文带来",
    boostedNote: "受推广帖文的订单可能来自付费或自然评论，无法确认广告曝光。",
    orders: "已收款订单",
    net: "扣除退款后净营收",
    pending: "待收款订单",
    pendingValue: "待收款金额",
    roas: "订单 ROAS",
    purchases: "购买次数",
    purchaseValue: "购买金额",
    audience: "广告受众（Meta 统计）",
    day: "Meta 账户日期",
    dimension: "分类",
    bucket: "群组",
    reach: "触达",
    impressions: "曝光",
    clicks: "点击",
    engagements: "互动",
    comments: "评论",
    ageGender: "年龄与性别",
    region: "地区",
    placement: "版位",
    device: "设备",
    hourly: "每小时",
    noAudience: "Meta 尚未提供受众分类。",
    buyers: "买家分布（订单实绩）",
    county: "收件县市",
    newBuyers: "新买家",
    returning: "回购买家",
    average: "平均订单金额",
    products: "热销商品",
    product: "商品",
    quantity: "数量",
    noBuyers: "此期间没有买家分类数据。",
    minuteOrders: "每分钟订单",
    at: "时间（Asia/Taipei）",
    timeline: "同一场次时间轴",
    timelineNote:
      "每小时广告花费以绝对时间对齐；Meta 观众统计不与个人买家关联。",
    claims: "喊单",
    checkoutLinks: "结账链接",
    paid: "已付款／收款订单",
    funnel: "评论 → 喊单 → 结账链接 → 已收款订单",
    viewers: "观众",
    liveAudience: "观众轮廓（Meta 统计）",
    audienceRefresh: "刷新观众洞察",
    audienceReading: "正在排入观众读取…",
    audienceQueued: "观众读取已排入队列，请稍后重新读取报表查看更新。",
    audienceUnknown: "读取请求结果未知，请重试同一请求。",
    audienceRetry: "重试同一读取请求",
    audienceForbidden:
      "观众洞察不可用：缺少 read_insights／pages_read_engagement 权限，或授权已失效。",
    audienceFailed: "无法排入观众读取，请重试。",
    audienceStorage: "无法安全保留此读取请求，请重新加载页面后再试。",
    views: "视频观看次数",
    peak: "最高同时观看人数",
    totalTime: "总观看时间（毫秒）",
    viewTime: "观看时间（毫秒），非人数",
    insufficient: "观众数不足，Meta 未提供轮廓",
    notAuthorized: "尚未授权直播观众洞察。",
    ambiguous: "多个推广同时进行，未分配到单一广告",
    post: "绑定帖文",
    draftIds: "关联草稿",
    start: "开始",
    end: "结束",
    noTimeline: "尚未提供时间轴观测。",
    noRows: "尚未提供记录。",
    source: "来源参照",
  },
};
