// Purpose: copy for the admin Settlements page (platform card-payment settlement ledger, read-only).
// Depends on: @live-commerce/i18n Locale; Go internal/payments/settlement DTOs (W4-S2).
// Used by: Settlements.tsx, tests/admin/card-payments-copy.test.ts.
// Requires billing:manage (the page is hidden otherwise); statements are store-currency only and never
// carry Stripe ids — payout_ref is the platform's bank-transfer reference string.
import type { Locale } from "@live-commerce/i18n";

const en = {
  title: "Settlements",
  subtitle: "Platform card-payment settlement statements for this store.",
  loading: "Loading settlement statements…",
  signedOut: "Sign in to view settlements.",
  forbidden: "You do not have access to settlements.",
  notFound: "This page is not available.",
  unavailable: "Settlements are unavailable. Try again later.",
  retry: "Retry",
  empty: "No settlement statements yet.",
  emptyHint: "Statements appear after the first weekly close of platform card payments.",
  tableLabel: "Settlement statements",
  linesLabel: "Statement lines",
  scrollHint: "Scroll sideways for more columns",
  period: "Period",
  captured: "Captured",
  refunded: "Refunds (deducted)",
  disputes: "Disputes (deducted)",
  stripeFee: "Stripe fee (deducted)",
  platformFee: "Platform fee (deducted)",
  carriedIn: "Carried in (deducted)",
  netPayable: "Net payable",
  legend: "Amounts are shown as what your store receives: + is added to your payout, − is deducted. A credit (a dispute reversal, a returned fee, a failed refund) shows with +. The same applies to the amounts of the lines.",
  formula: "Net payable = Captured + Refunds + Disputes + Stripe fee + Platform fee + Carried in. Every column already carries its sign, so the columns add up to the net payable.",
  status: "Status",
  paid: "Paid",
  pending: "Pending payout",
  noPayout: "No payout due (carried forward)",
  payoutRef: "Payout reference",
  paidAt: "Paid at",
  detail: "Statement detail",
  lines: "Lines",
  back: "Back to statements",
  order: "Order",
  kind: "Kind",
  amount: "Amount",
  fee: "Stripe fee",
  date: "Date",
  kindCHARGE: "Charge",
  kindREFUND: "Refund",
  kindREFUND_FAILURE: "Refund failure",
  kindDISPUTE: "Dispute",
  kindDISPUTE_REVERSAL: "Dispute reversal",
};
export type CardPaymentsSettlementsCopy = typeof en;
export const cardPaymentsSettlementsCopy: Record<Locale, CardPaymentsSettlementsCopy> = {
  en,
  "zh-CN": {
    title: "结算单",
    subtitle: "本店平台信用卡收款的结算单。",
    loading: "正在载入结算单…",
    signedOut: "请登录后查看结算单。",
    forbidden: "你没有查看结算单的权限。",
    notFound: "此页面不可用。",
    unavailable: "结算单暂时不可用，请稍后重试。",
    retry: "重试",
    empty: "尚无结算单。",
    emptyHint: "平台信用卡收款首次每周结算关闭后，结算单会显示在这里。",
    tableLabel: "结算单列表",
    linesLabel: "结算单明细行",
    scrollHint: "横向滚动查看更多栏位",
    period: "结算周期",
    captured: "已请款",
    refunded: "退款（扣除）",
    disputes: "争议款（扣除）",
    stripeFee: "Stripe 手续费（扣除）",
    platformFee: "平台费（扣除）",
    carriedIn: "上期结转（扣除）",
    netPayable: "应拨净额",
    legend: "金额以“商店实收”计：＋表示加入应拨款，－表示扣除；争议撤销、退还的手续费、失败的退款等回补会显示为＋。明细行的金额同样如此。",
    formula: "应拨净额 = 已请款 ＋ 退款 ＋ 争议款 ＋ Stripe 手续费 ＋ 平台费 ＋ 上期结转。各栏已含正负号，直接相加即为应拨净额。",
    status: "状态",
    paid: "已拨付",
    pending: "待拨付",
    noPayout: "无需拨款（结转下期）",
    payoutRef: "拨付参考号",
    paidAt: "拨付时间",
    detail: "结算单明细",
    lines: "明细行",
    back: "返回结算单列表",
    order: "订单",
    kind: "类别",
    amount: "金额",
    fee: "Stripe 手续费",
    date: "日期",
    kindCHARGE: "收款",
    kindREFUND: "退款",
    kindREFUND_FAILURE: "退款失败",
    kindDISPUTE: "争议",
    kindDISPUTE_REVERSAL: "争议撤销",
  },
  "zh-TW": {
    title: "結算單",
    subtitle: "本店平台信用卡收款的結算單。",
    loading: "正在載入結算單…",
    signedOut: "請登入後查看結算單。",
    forbidden: "你沒有查看結算單的權限。",
    notFound: "此頁面不可用。",
    unavailable: "結算單暫時不可用，請稍後重試。",
    retry: "重試",
    empty: "尚無結算單。",
    emptyHint: "平台信用卡收款首次每週結算關閉後，結算單會顯示在這裡。",
    tableLabel: "結算單列表",
    linesLabel: "結算單明細行",
    scrollHint: "橫向捲動查看更多欄位",
    period: "結算週期",
    captured: "已請款",
    refunded: "退款（扣除）",
    disputes: "爭議款（扣除）",
    stripeFee: "Stripe 手續費（扣除）",
    platformFee: "平台費（扣除）",
    carriedIn: "上期結轉（扣除）",
    netPayable: "應撥淨額",
    legend: "金額以「商店實收」計：＋表示加入應撥款，－表示扣除；爭議撤銷、退還的手續費、失敗的退款等回補會顯示為＋。明細行的金額同樣如此。",
    formula: "應撥淨額 = 已請款 ＋ 退款 ＋ 爭議款 ＋ Stripe 手續費 ＋ 平台費 ＋ 上期結轉。各欄已含正負號，直接相加即為應撥淨額。",
    status: "狀態",
    paid: "已撥付",
    pending: "待撥付",
    noPayout: "無須撥款（結轉下期）",
    payoutRef: "撥付參考號",
    paidAt: "撥付時間",
    detail: "結算單明細",
    lines: "明細行",
    back: "返回結算單列表",
    order: "訂單",
    kind: "類別",
    amount: "金額",
    fee: "Stripe 手續費",
    date: "日期",
    kindCHARGE: "收款",
    kindREFUND: "退款",
    kindREFUND_FAILURE: "退款失敗",
    kindDISPUTE: "爭議",
    kindDISPUTE_REVERSAL: "爭議撤銷",
  },
};
