// Purpose: copy for the admin CardPayments page (platform Stripe activation) in zh-TW / zh-CN / en.
// Depends on: @live-commerce/i18n Locale; contract stripe-platform-account-v1 §5 (verbatim merchant terms).
// Used by: CardPayments.tsx, SettingsWizard.tsx (entry link), tests/admin/card-payments-copy.test.ts.
// The zh-TW terms sentence and the two ruling-fixed strings (notOpen, blockedNote) are pinned by the
// integrator ruling: never show account ids/keys/approval ids, quote the contract §5 terms verbatim.
import type { Locale } from "@live-commerce/i18n";

const en = {
  title: "Card payments",
  subtitle: "Credit card payments collected by the platform (Stripe) for this store.",
  loading: "Loading card payment state…",
  signedOut: "Sign in to manage card payments.",
  forbidden: "You do not have access to card payment settings.",
  notFound: "This page is not available.",
  unavailable: "Card payment settings are unavailable. Try again later.",
  retry: "Retry",
  stateLabel: "Card payments",
  platformLabel: "Platform",
  stateNONE: "Not set up",
  stateENABLED: "Enabled",
  stateDISABLED: "Disabled",
  stateBLOCKED: "Suspended by the platform",
  platformNONE: "Not configured",
  platformDESIGNATED: "Designated",
  platformOPEN: "Open",
  platformCLOSED: "Closed",
  platformREVOKED: "Revoked",
  notOpen: "Card payments are not open yet.",
  blockedNote: "Suspended by the platform — contact support.",
  notAllowed: "This store is not on the platform's card-payments allowlist. Contact support.",
  terms: "Funds are collected by the platform and paid out by bank transfer each settlement cycle; refunds and dispute amounts are deducted from your settlement.",
  termsLabel: "Platform collection terms",
  termsVersion: "Terms version",
  limitsTitle: "Limits",
  currencyLabel: "Currency",
  minLabel: "Minimum per order",
  maxLabel: "Maximum per order",
  enable: "Enable card payments",
  disable: "Disable card payments",
  disableConfirm: "New orders can no longer pay by card. You can enable card payments again while the platform is open.",
  saving: "Saving…",
  dialogTitle: "Enable card payments",
  dialogIntro: "The platform collects card payments on your behalf. Review the terms before enabling.",
  termsAccept: "I have read and accept the platform collection terms above.",
  suffixLabel: "Statement descriptor suffix (optional)",
  suffixHint: "Shown on the buyer's card statement after the platform name.",
  suffixRule: "2–10 characters: letters, digits, spaces, dots or dashes; must start with a letter or digit and contain a letter.",
  suffixTooLong: "Too long: at most 10 characters, and the full card statement descriptor at most 22.",
  previewLabel: "Card statement preview",
  confirm: "Enable",
  cancel: "Cancel",
  conflict: "The state changed while you worked. The page reloaded — review and try again.",
  saved: "Saved.",
  entry: "Card payments (platform Stripe)",
  errors: {
    platform_stripe_not_allowed: "This store is not on the platform's card-payments allowlist. Contact support.",
    platform_stripe_blocked: "Card payments are suspended by the platform. Contact support.",
    platform_stripe_unavailable: "Card payments are temporarily unavailable. Try again later.",
    platform_stripe_closed: "Card payments are closed by the platform.",
    terms_version_stale: "The terms changed. Review the new terms and confirm again.",
    version_changed: "The state changed while you worked. The page reloaded — review and try again.",
    stripe_store_has_own_account: "This store has its own Stripe account, so platform card payments cannot be enabled.",
    descriptor_suffix_too_long: "The descriptor suffix is too long for the card statement.",
    invalid_descriptor_suffix: "The descriptor suffix contains invalid characters.",
    currency_unsupported: "This currency is not supported for card payments.",
    no_payment_market: "No payment market is configured for this store.",
    unavailable: "The service is unavailable. Try again later.",
    retry_later: "The service is unavailable. Try again later.",
    unauthorized: "Sign in again to continue.",
    default: "The change could not be saved. Try again later.",
  } as Record<string, string>,
};
export type CardPaymentsCopy = typeof en;
export const cardPaymentsCopy: Record<Locale, CardPaymentsCopy> = {
  en,
  "zh-CN": {
    title: "信用卡收款",
    subtitle: "由平台代收的本店信用卡收款（Stripe）。",
    loading: "正在载入信用卡收款状态…",
    signedOut: "请登录后管理信用卡收款。",
    forbidden: "你没有信用卡收款设定的权限。",
    notFound: "此页面不可用。",
    unavailable: "信用卡收款设定暂时不可用，请稍后重试。",
    retry: "重试",
    stateLabel: "信用卡收款",
    platformLabel: "平台",
    stateNONE: "未设定",
    stateENABLED: "已启用",
    stateDISABLED: "已停用",
    stateBLOCKED: "已被平台暂停",
    platformNONE: "未设定",
    platformDESIGNATED: "已指定",
    platformOPEN: "已开放",
    platformCLOSED: "已关闭",
    platformREVOKED: "已撤销",
    notOpen: "信用卡收款尚未开放",
    blockedNote: "已被平台暂停，请联系客服",
    notAllowed: "此商店不在平台信用卡收款允许名单内，请联系客服。",
    terms: "款项由平台代收，按结算周期以银行转账拨付；退款与争议款会从你的结算中扣除",
    termsLabel: "平台代收条款",
    termsVersion: "条款版本",
    limitsTitle: "金额限制",
    currencyLabel: "币种",
    minLabel: "每笔最低金额",
    maxLabel: "每笔最高金额",
    enable: "启用信用卡收款",
    disable: "停用信用卡收款",
    disableConfirm: "停用后新订单将无法使用信用卡付款；平台开放期间可再次启用。",
    saving: "保存中…",
    dialogTitle: "启用信用卡收款",
    dialogIntro: "信用卡款项由平台代收。启用前请详阅条款。",
    termsAccept: "我已阅读并同意上述平台代收条款。",
    suffixLabel: "账单摘要后缀（选填）",
    suffixHint: "会显示在买家信用卡账单上平台名称之后。",
    suffixRule: "2–10 个字符：英文字母、数字、空格、点或连字符；开头为字母或数字且须含字母。",
    suffixTooLong: "过长：后缀最多 10 个字符，完整账单摘要最多 22 个字符。",
    previewLabel: "账单摘要预览",
    confirm: "启用",
    cancel: "取消",
    conflict: "状态已在其他地方变更，页面已重新载入，请确认后重试。",
    saved: "已保存。",
    entry: "信用卡收款（平台 Stripe）",
    errors: {
      platform_stripe_not_allowed: "此商店不在平台信用卡收款允许名单内，请联系客服。",
      platform_stripe_blocked: "信用卡收款已被平台暂停，请联系客服。",
      platform_stripe_unavailable: "信用卡收款暂时不可用，请稍后重试。",
      platform_stripe_closed: "平台已关闭信用卡收款。",
      terms_version_stale: "条款已更新，请阅读新条款后再次确认。",
      version_changed: "状态已在其他地方变更，页面已重新载入，请确认后重试。",
      stripe_store_has_own_account: "此商店已有自己的 Stripe 账户，无法启用平台信用卡收款。",
      descriptor_suffix_too_long: "账单摘要后缀过长。",
      invalid_descriptor_suffix: "账单摘要后缀含有无效字符。",
      currency_unsupported: "此币种不支持信用卡收款。",
      no_payment_market: "此商店尚未设定付款市场。",
      unavailable: "服务暂时不可用，请稍后重试。",
      retry_later: "服务暂时不可用，请稍后重试。",
      unauthorized: "请重新登录后继续。",
      default: "无法保存变更，请稍后重试。",
    } as Record<string, string>,
  },
  "zh-TW": {
    title: "信用卡收款",
    subtitle: "由平台代收的本店信用卡收款（Stripe）。",
    loading: "正在載入信用卡收款狀態…",
    signedOut: "請登入後管理信用卡收款。",
    forbidden: "你沒有信用卡收款設定的權限。",
    notFound: "此頁面不可用。",
    unavailable: "信用卡收款設定暫時不可用，請稍後重試。",
    retry: "重試",
    stateLabel: "信用卡收款",
    platformLabel: "平台",
    stateNONE: "未設定",
    stateENABLED: "已啟用",
    stateDISABLED: "已停用",
    stateBLOCKED: "已被平台暫停",
    platformNONE: "未設定",
    platformDESIGNATED: "已指定",
    platformOPEN: "已開放",
    platformCLOSED: "已關閉",
    platformREVOKED: "已撤銷",
    notOpen: "信用卡收款尚未開放",
    blockedNote: "已被平台暫停，請聯絡客服",
    notAllowed: "此商店不在平台信用卡收款允許名單內，請聯絡客服。",
    terms: "款項由平台代收，按結算週期以銀行轉帳撥付；退款與爭議款會從你的結算中扣除",
    termsLabel: "平台代收條款",
    termsVersion: "條款版本",
    limitsTitle: "金額限制",
    currencyLabel: "幣別",
    minLabel: "每筆最低金額",
    maxLabel: "每筆最高金額",
    enable: "啟用信用卡收款",
    disable: "停用信用卡收款",
    disableConfirm: "停用後新訂單將無法使用信用卡付款；平台開放期間可再次啟用。",
    saving: "儲存中…",
    dialogTitle: "啟用信用卡收款",
    dialogIntro: "信用卡款項由平台代收。啟用前請詳閱條款。",
    termsAccept: "我已閱讀並同意上述平台代收條款。",
    suffixLabel: "帳單摘要後綴（選填）",
    suffixHint: "會顯示在買家信用卡帳單上平台名稱之後。",
    suffixRule: "2–10 個字元：英文字母、數字、空格、點或連字號；開頭為英數且須含字母。",
    suffixTooLong: "過長：後綴最多 10 個字元，完整帳單摘要最多 22 個字元。",
    previewLabel: "帳單摘要預覽",
    confirm: "啟用",
    cancel: "取消",
    conflict: "狀態已在其他地方變更，頁面已重新載入，請確認後重試。",
    saved: "已儲存。",
    entry: "信用卡收款（平台 Stripe）",
    errors: {
      platform_stripe_not_allowed: "此商店不在平台信用卡收款允許名單內，請聯絡客服。",
      platform_stripe_blocked: "信用卡收款已被平台暫停，請聯絡客服。",
      platform_stripe_unavailable: "信用卡收款暫時不可用，請稍後重試。",
      platform_stripe_closed: "平台已關閉信用卡收款。",
      terms_version_stale: "條款已更新，請閱讀新條款後再次確認。",
      version_changed: "狀態已在其他地方變更，頁面已重新載入，請確認後重試。",
      stripe_store_has_own_account: "此商店已有自己的 Stripe 帳戶，無法啟用平台信用卡收款。",
      descriptor_suffix_too_long: "帳單摘要後綴過長。",
      invalid_descriptor_suffix: "帳單摘要後綴含有無效字元。",
      currency_unsupported: "此幣別不支援信用卡收款。",
      no_payment_market: "此商店尚未設定付款市場。",
      unavailable: "服務暫時不可用，請稍後重試。",
      retry_later: "服務暫時不可用，請稍後重試。",
      unauthorized: "請重新登入後繼續。",
      default: "無法儲存變更，請稍後重試。",
    } as Record<string, string>,
  },
};
