// Copy for the admin Products list, Product editor and Collections pages (unit catalog-core; BFF catalog-products,
// products/{id}, collections* -> Go internal/httpapi/collections.go). Owns every string those pages show in zh-CN, zh-TW
// and en, including the error map for the Go error codes. Merchant content (names, descriptions, option names) is
// single-language and never translated here (contracts/storefront-v2.md). Non-goals: no money formatting (components
// use Intl via lib/client money()), no rule (the server validates).
// Depends on: @live-commerce/i18n (Locale) only.
import type { Locale } from "@live-commerce/i18n";

const en = {
  nav: { collections: "Collections" },
  list: {
    title: "Products",
    subtitle: "Every product of this store, with price, stock and whether shoppers can see it.",
    search: "Search name, handle or SKU code",
    searchButton: "Search",
    clear: "Clear",
    status: "Status",
    all: "All",
    newProduct: "Add product",
    inventory: "Inventory ledger",
    product: "Product",
    price: "Price",
    stock: "Stock",
    variants: (n: number) => (n === 1 ? "1 variant" : `${n} variants`),
    noVariants: "No variants",
    outOfStock: "Out of stock",
    units: (n: number) => `${n} in stock`,
    empty: "No products yet. Add the first one.",
    emptySearch: "No product matches this search.",
    loading: "Loading products…",
    next: "Next page",
    previous: "First page",
    store: "Store",
    noStore: "No authorized store is available.",
    signedOut: "Sign in to view products.",
    forbidden: "This account does not have permission to view products.",
    unavailable: "Products are temporarily unavailable. Try again.",
    retry: "Try again",
    edit: "Edit",
  },
  status: { draft: "Draft", active: "Active", archived: "Archived" } as Record<string, string>,
  statusHelp: {
    draft: "Draft: only you can see it. Shoppers cannot find or buy it.",
    active: "Active: shoppers can see and buy it once the store is published.",
    archived: "Archived: hidden from shoppers; keep it for order history.",
  } as Record<string, string>,
  edit: {
    back: "All products",
    newTitle: "New product",
    create: "Create product",
    createdHint: "The product starts as a draft. Add photos and variants, then set it to Active.",
    save: "Save changes",
    saved: "Saved",
    basics: "Basic information",
    name: "Product name",
    description: "Description (plain text)",
    slug: "Page handle",
    slugHint: "Lowercase letters, digits and dashes. Leave empty to generate one from the name.",
    statusLabel: "Visibility",
    seo: "Search listing",
    seoTitle: "Page title",
    seoDescription: "Page description",
    seoHint: "Optional. Shown to search engines; leave empty to use the product name and description.",
    count: (n: number, max: number) => `${n} / ${max}`,
    options: "Options",
    optionsHint: "Up to 3 options such as Size or Color. Variants are one per combination.",
    optionName: "Option name",
    optionValues: "Values (comma separated)",
    addOption: "Add option",
    removeOption: "Remove option",
    optionsDuplicate: "Option names and values must be unique within the product.",
    optionsLimit: "At most 3 options, 50 values each, names up to 30 and values up to 40 characters.",
    saveOptions: "Save options",
    optionsLocked: "Options cannot drop a value that an active variant uses. Archive or re-key those variants first.",
    variants: "Variants",
    noVariants: "No variants yet. A product needs at least one variant with a price before it can be bought.",
    variant: "Variant",
    code: "SKU code",
    price: "Price",
    compareAt: "Compare-at price",
    compareHint: "Shown crossed out next to the price; must be higher than the price.",
    stock: "Stock",
    saveVariant: "Save variant",
    archiveVariant: "Archive variant",
    confirmArchive: "Archive this variant? Shoppers can no longer buy it.",
    newVariants: "Variants to create",
    newVariantsHint: "One for every option combination that has no variant yet. Edit code and price, then create them.",
    createVariants: "Create variants",
    defaultVariant: "Default variant",
    defaultVariantHint: "A product without options has one variant.",
    createDefault: "Create variant",
    variantLimit: "A product can have at most 100 variants.",
    adjust: "Adjust stock",
    adjustDelta: "Change (+ adds, − removes)",
    adjustReason: "Reason",
    warehouse: "Warehouse",
    apply: "Apply",
    cancel: "Cancel",
    stockAdjusted: "Stock updated",
    photos: "Photos",
    photosAfterCreate: "Create the product first, then add photos.",
    notFound: "This product is unavailable in the selected store.",
    loading: "Loading product…",
    available: (n: number) => `${n} available`,
    uncertain: "The result was not confirmed. Retrying sends the same request, so it cannot apply twice.",
    retry: "Retry",
    dismiss: "Dismiss",
    invalidPrice: "Enter a price like 12 or 12.50 for this currency.",
    invalidCompare: "The compare-at price must be higher than the price.",
    invalidCode: "SKU codes use letters, digits, dot, dash and underscore, up to 64 characters.",
    invalidDelta: "Enter a whole number other than 0.",
    invalidName: "Enter a product name (up to 120 characters).",
    invalidSlug: "Use lowercase letters, digits and single dashes, up to 80 characters.",
  },
  collections: {
    title: "Collections",
    subtitle: "Group products into pages shoppers can browse, such as New in or Sale.",
    newCollection: "New collection",
    name: "Title",
    slug: "Page handle",
    description: "Description (plain text)",
    sort: "Order products by",
    sortModes: { manual: "Manual order", newest: "Newest first", price_asc: "Price: low to high", price_desc: "Price: high to low" } as Record<string, string>,
    visibility: "Visibility",
    visible: "Visible to shoppers",
    hidden: "Hidden",
    image: "Image",
    imageHelp: "JPEG, PNG or WebP, up to 2 MB.",
    upload: "Upload image",
    replace: "Replace image",
    removeImage: "Remove image",
    imageTooLarge: "This image is over 2 MB.",
    imageType: "Choose a JPEG, PNG or WebP image.",
    members: "Products in this collection",
    membersHint: "Shoppers only see active products. Manual order is the order shown here.",
    noMembers: "No products yet.",
    findProducts: "Add products",
    findPlaceholder: "Search products to add",
    add: "Add",
    remove: "Remove",
    moveUp: "Move earlier",
    moveDown: "Move later",
    saveMembers: "Save products",
    save: "Save collection",
    create: "Create collection",
    delete: "Delete collection",
    confirmDelete: "Delete this collection? The products stay; shoppers lose the collection page. This cannot be undone.",
    confirmDeleteButton: "Delete",
    saved: "Saved",
    deleted: "Collection deleted",
    empty: "No collections yet.",
    count: (n: number) => (n === 1 ? "1 product" : `${n} products`),
    loading: "Loading collections…",
    noStore: "No authorized store is available.",
    signedOut: "Sign in to manage collections.",
    forbidden: "This account does not have permission to manage collections.",
    unavailable: "Collections are temporarily unavailable. Try again.",
    notFound: "This collection is unavailable in the selected store.",
    retry: "Try again",
    uncertain: "The result was not confirmed. Retrying sends the same request, so it cannot apply twice.",
    dismiss: "Dismiss",
    invalidTitle: "Enter a title (up to 80 characters).",
    invalidSlug: "Use lowercase letters, digits and single dashes, up to 80 characters.",
    limit: "A collection can hold up to 500 products; a store up to 200 collections.",
    inactiveBadge: (status: string): string => (status === "draft" ? "Draft" : status === "archived" ? "Archived" : ""),
  },
  errors: {
    invalid_request: "Some values are not valid. Check the fields and try again.",
    conflict: "This changed elsewhere, or the handle or code is already in use. Reload and try again.",
    forbidden: "This account does not have permission for that change.",
    not_found: "That item no longer exists.",
    unauthorized: "Your session ended. Sign in again.",
    insufficient_inventory: "That would take stock below zero.",
    too_large: "The file is over 2 MB.",
    retry_later: "The request did not complete. Try again.",
  } as Record<string, string>,
};
export type CatalogV2Copy = typeof en;

const zhCN: CatalogV2Copy = {
  nav: { collections: "商品集合" },
  list: {
    title: "商品",
    subtitle: "本店全部商品，含价格、库存和买家是否可见。",
    search: "搜索名称、网址标识或 SKU 编码",
    searchButton: "搜索",
    clear: "清除",
    status: "状态",
    all: "全部",
    newProduct: "新增商品",
    inventory: "库存台账",
    product: "商品",
    price: "价格",
    stock: "库存",
    variants: (n: number) => `${n} 个规格`,
    noVariants: "尚无规格",
    outOfStock: "已售罄",
    units: (n: number) => `库存 ${n}`,
    empty: "还没有商品。新增第一个吧。",
    emptySearch: "没有符合搜索的商品。",
    loading: "正在载入商品…",
    next: "下一页",
    previous: "回到第一页",
    store: "店铺",
    noStore: "没有可用的授权店铺。",
    signedOut: "请登录后查看商品。",
    forbidden: "此账号没有查看商品的权限。",
    unavailable: "商品暂时无法使用，请重试。",
    retry: "重试",
    edit: "编辑",
  },
  status: { draft: "草稿", active: "上架中", archived: "已封存" },
  statusHelp: {
    draft: "草稿：仅你可见，买家找不到也买不到。",
    active: "上架中：店铺发布后，买家可以看到并购买。",
    archived: "已封存：买家看不到，保留以便查看订单历史。",
  },
  edit: {
    back: "全部商品",
    newTitle: "新增商品",
    create: "创建商品",
    createdHint: "商品会先成为草稿。请加入图片和规格，再设为上架中。",
    save: "保存更改",
    saved: "已保存",
    basics: "基本信息",
    name: "商品名称",
    description: "商品描述（纯文字）",
    slug: "页面网址标识",
    slugHint: "小写字母、数字和连字符。留空会根据名称自动生成。",
    statusLabel: "可见性",
    seo: "搜索结果显示",
    seoTitle: "页面标题",
    seoDescription: "页面描述",
    seoHint: "选填。提供给搜索引擎；留空则使用商品名称和描述。",
    count: (n: number, max: number) => `${n} / ${max}`,
    options: "选项",
    optionsHint: "最多 3 个选项，例如尺寸或颜色。每种组合对应一个规格。",
    optionName: "选项名称",
    optionValues: "选项值（以逗号分隔）",
    addOption: "新增选项",
    removeOption: "移除选项",
    optionsDuplicate: "同一商品内选项名称和选项值不能重复。",
    optionsLimit: "最多 3 个选项，每个最多 50 个值；名称最多 30 字，值最多 40 字。",
    saveOptions: "保存选项",
    optionsLocked: "选项不能删除仍有上架规格在使用的值。请先封存或调整这些规格。",
    variants: "规格",
    noVariants: "尚无规格。商品至少需要一个有价格的规格才能被购买。",
    variant: "规格",
    code: "SKU 编码",
    price: "价格",
    compareAt: "划线价",
    compareHint: "显示在价格旁并加删除线，必须高于价格。",
    stock: "库存",
    saveVariant: "保存规格",
    archiveVariant: "封存规格",
    confirmArchive: "封存此规格？买家将无法再购买。",
    newVariants: "待创建的规格",
    newVariantsHint: "每个尚无规格的选项组合一行。可先修改编码和价格，再创建。",
    createVariants: "创建规格",
    defaultVariant: "默认规格",
    defaultVariantHint: "没有选项的商品只有一个规格。",
    createDefault: "创建规格",
    variantLimit: "每个商品最多 100 个规格。",
    adjust: "调整库存",
    adjustDelta: "变动量（+ 增加，− 减少）",
    adjustReason: "原因",
    warehouse: "仓库",
    apply: "确认",
    cancel: "取消",
    stockAdjusted: "库存已更新",
    photos: "图片",
    photosAfterCreate: "请先创建商品，再添加图片。",
    notFound: "此商品在所选店铺中不可用。",
    loading: "正在载入商品…",
    available: (n: number) => `可售 ${n}`,
    uncertain: "结果未能确认。重试会发送相同请求，不会重复生效。",
    retry: "重试",
    dismiss: "关闭",
    invalidPrice: "请输入此币别的价格，例如 12 或 12.50。",
    invalidCompare: "划线价必须高于价格。",
    invalidCode: "SKU 编码可用字母、数字、点、连字符和下划线，最多 64 个字符。",
    invalidDelta: "请输入不为 0 的整数。",
    invalidName: "请输入商品名称（最多 120 字）。",
    invalidSlug: "请使用小写字母、数字和单个连字符，最多 80 个字符。",
  },
  collections: {
    title: "商品集合",
    subtitle: "把商品归入买家可浏览的页面，例如「新品」或「特价」。",
    newCollection: "新增集合",
    name: "标题",
    slug: "页面网址标识",
    description: "描述（纯文字）",
    sort: "商品排序",
    sortModes: { manual: "手动排序", newest: "最新优先", price_asc: "价格从低到高", price_desc: "价格从高到低" },
    visibility: "可见性",
    visible: "买家可见",
    hidden: "隐藏",
    image: "图片",
    imageHelp: "JPEG、PNG 或 WebP，不超过 2 MB。",
    upload: "上传图片",
    replace: "更换图片",
    removeImage: "移除图片",
    imageTooLarge: "这张图片超过 2 MB。",
    imageType: "请选择 JPEG、PNG 或 WebP 图片。",
    members: "此集合中的商品",
    membersHint: "买家只会看到上架中的商品。手动排序即此处顺序。",
    noMembers: "尚无商品。",
    findProducts: "添加商品",
    findPlaceholder: "搜索要添加的商品",
    add: "添加",
    remove: "移除",
    moveUp: "前移",
    moveDown: "后移",
    saveMembers: "保存商品",
    save: "保存集合",
    create: "创建集合",
    delete: "删除集合",
    confirmDelete: "删除此集合？商品会保留，买家将失去该集合页面。此操作无法撤销。",
    confirmDeleteButton: "删除",
    saved: "已保存",
    deleted: "集合已删除",
    empty: "还没有集合。",
    count: (n: number) => `${n} 件商品`,
    loading: "正在载入集合…",
    noStore: "没有可用的授权店铺。",
    signedOut: "请登录后管理集合。",
    forbidden: "此账号没有管理集合的权限。",
    unavailable: "集合暂时无法使用，请重试。",
    notFound: "此集合在所选店铺中不可用。",
    retry: "重试",
    uncertain: "结果未能确认。重试会发送相同请求，不会重复生效。",
    dismiss: "关闭",
    invalidTitle: "请输入标题（最多 80 字）。",
    invalidSlug: "请使用小写字母、数字和单个连字符，最多 80 个字符。",
    limit: "每个集合最多 500 件商品，每家店铺最多 200 个集合。",
    inactiveBadge: (status: string) => (status === "draft" ? "草稿" : status === "archived" ? "已封存" : ""),
  },
  errors: {
    invalid_request: "部分内容无效。请检查字段后重试。",
    conflict: "内容已在别处更改，或网址标识/编码已被使用。请重新载入后再试。",
    forbidden: "此账号没有执行该更改的权限。",
    not_found: "该项目已不存在。",
    unauthorized: "登录已失效。请重新登录。",
    insufficient_inventory: "这样会使库存低于 0。",
    too_large: "文件超过 2 MB。",
    retry_later: "请求未完成，请重试。",
  },
};

const zhTW: CatalogV2Copy = {
  nav: { collections: "商品集合" },
  list: {
    title: "商品",
    subtitle: "本店全部商品，含價格、庫存與買家是否可見。",
    search: "搜尋名稱、網址識別或 SKU 編碼",
    searchButton: "搜尋",
    clear: "清除",
    status: "狀態",
    all: "全部",
    newProduct: "新增商品",
    inventory: "庫存帳",
    product: "商品",
    price: "價格",
    stock: "庫存",
    variants: (n: number) => `${n} 個規格`,
    noVariants: "尚無規格",
    outOfStock: "已售完",
    units: (n: number) => `庫存 ${n}`,
    empty: "還沒有商品。新增第一個吧。",
    emptySearch: "沒有符合搜尋的商品。",
    loading: "正在載入商品…",
    next: "下一頁",
    previous: "回到第一頁",
    store: "商店",
    noStore: "沒有可用的授權商店。",
    signedOut: "請登入後查看商品。",
    forbidden: "此帳號沒有查看商品的權限。",
    unavailable: "商品暫時無法使用，請重試。",
    retry: "重試",
    edit: "編輯",
  },
  status: { draft: "草稿", active: "上架中", archived: "已封存" },
  statusHelp: {
    draft: "草稿：只有你看得到，買家找不到也買不到。",
    active: "上架中：商店發布後，買家可以看到並購買。",
    archived: "已封存：買家看不到，保留以便查看訂單紀錄。",
  },
  edit: {
    back: "全部商品",
    newTitle: "新增商品",
    create: "建立商品",
    createdHint: "商品會先成為草稿。請加入圖片與規格，再設為上架中。",
    save: "儲存變更",
    saved: "已儲存",
    basics: "基本資料",
    name: "商品名稱",
    description: "商品描述（純文字）",
    slug: "頁面網址識別",
    slugHint: "小寫字母、數字與連字號。留空會依名稱自動產生。",
    statusLabel: "可見性",
    seo: "搜尋結果顯示",
    seoTitle: "頁面標題",
    seoDescription: "頁面描述",
    seoHint: "選填。提供給搜尋引擎；留空則使用商品名稱與描述。",
    count: (n: number, max: number) => `${n} / ${max}`,
    options: "選項",
    optionsHint: "最多 3 個選項，例如尺寸或顏色。每種組合對應一個規格。",
    optionName: "選項名稱",
    optionValues: "選項值（以逗號分隔）",
    addOption: "新增選項",
    removeOption: "移除選項",
    optionsDuplicate: "同一商品內選項名稱與選項值不可重複。",
    optionsLimit: "最多 3 個選項，每個最多 50 個值；名稱最多 30 字，值最多 40 字。",
    saveOptions: "儲存選項",
    optionsLocked: "選項不能刪除仍有上架規格使用的值。請先封存或調整這些規格。",
    variants: "規格",
    noVariants: "尚無規格。商品至少需要一個有價格的規格才能被購買。",
    variant: "規格",
    code: "SKU 編碼",
    price: "價格",
    compareAt: "劃線價",
    compareHint: "顯示在價格旁並加刪除線，必須高於價格。",
    stock: "庫存",
    saveVariant: "儲存規格",
    archiveVariant: "封存規格",
    confirmArchive: "封存此規格？買家將無法再購買。",
    newVariants: "待建立的規格",
    newVariantsHint: "每個尚無規格的選項組合一列。可先修改編碼與價格，再建立。",
    createVariants: "建立規格",
    defaultVariant: "預設規格",
    defaultVariantHint: "沒有選項的商品只有一個規格。",
    createDefault: "建立規格",
    variantLimit: "每個商品最多 100 個規格。",
    adjust: "調整庫存",
    adjustDelta: "變動量（+ 增加，− 減少）",
    adjustReason: "原因",
    warehouse: "倉庫",
    apply: "確認",
    cancel: "取消",
    stockAdjusted: "庫存已更新",
    photos: "圖片",
    photosAfterCreate: "請先建立商品，再新增圖片。",
    notFound: "此商品在所選商店中無法使用。",
    loading: "正在載入商品…",
    available: (n: number) => `可售 ${n}`,
    uncertain: "結果未能確認。重試會送出相同請求，不會重複生效。",
    retry: "重試",
    dismiss: "關閉",
    invalidPrice: "請輸入此幣別的價格，例如 12 或 12.50。",
    invalidCompare: "劃線價必須高於價格。",
    invalidCode: "SKU 編碼可用字母、數字、點、連字號與底線，最多 64 個字元。",
    invalidDelta: "請輸入不為 0 的整數。",
    invalidName: "請輸入商品名稱（最多 120 字）。",
    invalidSlug: "請使用小寫字母、數字與單一連字號，最多 80 個字元。",
  },
  collections: {
    title: "商品集合",
    subtitle: "把商品歸入買家可瀏覽的頁面，例如「新品」或「特價」。",
    newCollection: "新增集合",
    name: "標題",
    slug: "頁面網址識別",
    description: "描述（純文字）",
    sort: "商品排序",
    sortModes: { manual: "手動排序", newest: "最新優先", price_asc: "價格由低到高", price_desc: "價格由高到低" },
    visibility: "可見性",
    visible: "買家可見",
    hidden: "隱藏",
    image: "圖片",
    imageHelp: "JPEG、PNG 或 WebP，不超過 2 MB。",
    upload: "上傳圖片",
    replace: "更換圖片",
    removeImage: "移除圖片",
    imageTooLarge: "這張圖片超過 2 MB。",
    imageType: "請選擇 JPEG、PNG 或 WebP 圖片。",
    members: "此集合中的商品",
    membersHint: "買家只會看到上架中的商品。手動排序即此處順序。",
    noMembers: "尚無商品。",
    findProducts: "加入商品",
    findPlaceholder: "搜尋要加入的商品",
    add: "加入",
    remove: "移除",
    moveUp: "前移",
    moveDown: "後移",
    saveMembers: "儲存商品",
    save: "儲存集合",
    create: "建立集合",
    delete: "刪除集合",
    confirmDelete: "刪除此集合？商品會保留，買家將失去該集合頁面。此操作無法復原。",
    confirmDeleteButton: "刪除",
    saved: "已儲存",
    deleted: "集合已刪除",
    empty: "還沒有集合。",
    count: (n: number) => `${n} 件商品`,
    loading: "正在載入集合…",
    noStore: "沒有可用的授權商店。",
    signedOut: "請登入後管理集合。",
    forbidden: "此帳號沒有管理集合的權限。",
    unavailable: "集合暫時無法使用，請重試。",
    notFound: "此集合在所選商店中無法使用。",
    retry: "重試",
    uncertain: "結果未能確認。重試會送出相同請求，不會重複生效。",
    dismiss: "關閉",
    invalidTitle: "請輸入標題（最多 80 字）。",
    invalidSlug: "請使用小寫字母、數字與單一連字號，最多 80 個字元。",
    limit: "每個集合最多 500 件商品，每家商店最多 200 個集合。",
    inactiveBadge: (status: string) => (status === "draft" ? "草稿" : status === "archived" ? "已封存" : ""),
  },
  errors: {
    invalid_request: "部分內容無效。請檢查欄位後重試。",
    conflict: "內容已在別處變更，或網址識別／編碼已被使用。請重新載入後再試。",
    forbidden: "此帳號沒有執行該變更的權限。",
    not_found: "該項目已不存在。",
    unauthorized: "登入已失效。請重新登入。",
    insufficient_inventory: "這樣會使庫存低於 0。",
    too_large: "檔案超過 2 MB。",
    retry_later: "請求未完成，請重試。",
  },
};

export const catalogCopy: Record<Locale, CatalogV2Copy> = { en, "zh-CN": zhCN, "zh-TW": zhTW };
export const errorText = (c: CatalogV2Copy, code: string) => c.errors[code] ?? c.errors.retry_later;
