// Copy (zh-CN / zh-TW / en) for the admin cash-on-delivery surfaces (home-cod R5, migration 0107): the Settings card (enable switch,
// per-order cap, optional surcharge, carrier label). Rendered by components/CodSettings.tsx; the BFF routes are in lib/logistics-client.ts.
// Rules encoded here: COD is only offered on home-delivery services whose merchant setting enables it; the amount collected at the door is
// the order total plus the surcharge, collected by the carrier (黑猫 / 新竹) — never an online charge, and never confirmed here.
import type { Locale } from "@live-commerce/i18n";

const en = {
  setTitle: "Cash on delivery",
  setIntro:
    "Let buyers pay the carrier when the parcel is delivered. The order is placed with no online charge and the stock reserved; you mark the parcel shipped, then record the cash the carrier hands back.",
  setEnabled: "Offer cash on delivery at checkout",
  setMax: "Per-order amount cap (TWD)",
  setMaxHint: "Cash on delivery is offered only up to this whole-TWD order total (1–20000).",
  setSurcharge: "Surcharge (TWD)",
  setSurchargeHint: "Optional whole-TWD amount added to what the buyer pays the carrier (0–1000).",
  setCarrier: "Carrier",
  carrierBlackCat: "黑貓 (Black Cat)",
  carrierHsinchu: "新竹 (Hsinchu)",
  setNote: "Changes apply to new orders only. Orders already placed keep the amount and carrier they were shown.",
  save: "Save",
  saving: "Saving…",
  saved: "Cash on delivery settings saved.",
  retry: "Try again",
  loading: "Loading…",
  loadFailed: "Cash on delivery settings could not be loaded.",
  invalid: "Check the fields: the cap is 1 to 20000 TWD, the surcharge 0 to 1000 TWD, and a carrier must be chosen.",
  noPermission: "This account does not have permission to change these settings.",
  uncertain: "The result is not known yet. Retry sends the identical request safely, or reload.",
  retrySame: "Retry the same request",
  // order collection panel (shared pay_at_pickup / cash_on_delivery state machine, §16.4/§16.8)
  orderTitle: "Cash on delivery",
  orderState: "Collection status",
  orderStates: {
    PENDING: "Waiting for payment on delivery",
    COLLECTED: "Collected on delivery",
    RETURNED: "Not collected · returned",
    REFUNDED_OFFLINE: "Refunded outside this site",
    CANCELLED: "Cancelled · stock released",
    RESTOCKED: "Returned · stock restored",
  } as Record<string, string>,
  orderNote: "This site never holds cash-on-delivery money. Record what happened; refunds are made outside this site.",
  collected: "Mark collected on delivery",
  returned: "Mark returned unclaimed",
  refundedOffline: "Mark refunded outside this site",
  cancelOrder: "Cancel order and release stock",
  restockOrder: "Parcel is back — restore stock",
  confirmCollected: "Record that the carrier collected the cash on delivery? This cannot be undone here.",
  confirmReturned: "Record that the parcel was not collected and came back? Stock is restored separately.",
  confirmRefundedOffline: "Record that you refunded the buyer outside this site? No money moves through this site.",
  confirmCancel: "Cancel this unshipped order and release its stock? The buyer's cash-on-delivery order ends.",
  confirmRestock: "The parcel is back with you. Restore its stock now? This cannot be undone.",
  done: "Saved. The order shows the server state.",
  errors: {
    invalid_settings: "The settings are not valid.",
    version_changed: "The settings changed since you loaded them. Reload and try again.",
    idempotency_conflict: "This request key was used for a different request. Reload and try again.",
    forbidden: "This account does not have permission for this action.",
    unauthorized: "Sign in again to continue.",
    retry_later: "Temporarily unavailable. Try again.",
    default: "The request could not be completed. Reload and try again.",
  } as Record<string, string>,
};

const zhCN: typeof en = {
  setTitle: "货到付款",
  setIntro: "让买家在包裹送达时向货运公司付款。下单时不收取任何在线费用，库存会先保留；你标记出货后，再记录货运公司交回的现金。",
  setEnabled: "在结账时提供货到付款",
  setMax: "单笔金额上限（TWD）",
  setMaxHint: "订单总额为整数 TWD 且不超过此上限时才提供货到付款（1–20000）。",
  setSurcharge: "手续费（TWD）",
  setSurchargeHint: "选填的整数 TWD 金额，加到买家付给货运公司的款项中（0–1000）。",
  setCarrier: "货运业者",
  carrierBlackCat: "黑猫",
  carrierHsinchu: "新竹",
  setNote: "变更只影响新订单。已下单的订单沿用当时显示的金额与货运业者。",
  save: "保存",
  saving: "保存中…",
  saved: "货到付款设置已保存。",
  retry: "重试",
  loading: "加载中…",
  loadFailed: "无法加载货到付款设置。",
  invalid: "请检查字段：上限为 1 到 20000 TWD，手续费为 0 到 1000 TWD，且必须选择货运业者。",
  noPermission: "此账号没有修改这些设置的权限。",
  uncertain: "结果尚不确定。重试会安全地发送相同请求，或重新加载。",
  retrySame: "重试同一请求",
  orderTitle: "货到付款",
  orderState: "收款状态",
  orderStates: {
    PENDING: "等待货到付款",
    COLLECTED: "已货到收款",
    RETURNED: "未取货·已退回",
    REFUNDED_OFFLINE: "已在本站外退款",
    CANCELLED: "已取消·库存已释放",
    RESTOCKED: "已退回·库存已恢复",
  },
  orderNote: "本站不经手货到付款款项。请记录实际发生情况；退款在本站外进行。",
  collected: "标记货到收款",
  returned: "标记逾期未取退回",
  refundedOffline: "标记在本站外退款",
  cancelOrder: "取消订单并释放库存",
  restockOrder: "包裹已退回——恢复库存",
  confirmCollected: "确认记录货运公司已代收货到付款款项？此操作无法在此撤销。",
  confirmReturned: "确认记录包裹未被领取并已退回？库存需另行恢复。",
  confirmRefundedOffline: "确认记录你已在本站外向买家退款？本站不移动任何资金。",
  confirmCancel: "取消这笔未出货订单并释放库存？买家的货到付款订单就此结束。",
  confirmRestock: "包裹已退回。现在恢复其库存？此操作无法撤销。",
  done: "已保存。订单会显示服务器状态。",
  errors: {
    invalid_settings: "设置内容无效。",
    version_changed: "设置在你加载后已变更，请重新加载后重试。",
    idempotency_conflict: "此请求键已用于另一个请求，请重新加载后重试。",
    forbidden: "当前账号没有此操作的权限。",
    unauthorized: "请重新登录后继续。",
    retry_later: "暂时无法使用，请重试。",
    default: "请求未能完成，请重新加载后重试。",
  },
};

const zhTW: typeof en = {
  setTitle: "貨到付款",
  setIntro: "讓買家在包裹送達時向貨運公司付款。下單時不收取任何線上費用，庫存會先保留；你標記出貨後，再記錄貨運公司交回的現金。",
  setEnabled: "在結帳時提供貨到付款",
  setMax: "單筆金額上限（TWD）",
  setMaxHint: "訂單總額為整數 TWD 且不超過此上限時才提供貨到付款（1–20000）。",
  setSurcharge: "手續費（TWD）",
  setSurchargeHint: "選填的整數 TWD 金額，加到買家付給貨運公司的款項中（0–1000）。",
  setCarrier: "貨運業者",
  carrierBlackCat: "黑貓",
  carrierHsinchu: "新竹",
  setNote: "變更只影響新訂單。已下單的訂單沿用當時顯示的金額與貨運業者。",
  save: "儲存",
  saving: "儲存中…",
  saved: "貨到付款設定已儲存。",
  retry: "重試",
  loading: "載入中…",
  loadFailed: "無法載入貨到付款設定。",
  invalid: "請檢查欄位：上限為 1 到 20000 TWD，手續費為 0 到 1000 TWD，且必須選擇貨運業者。",
  noPermission: "此帳號沒有修改這些設定的權限。",
  uncertain: "結果尚不確定。重試會安全地送出相同請求，或重新載入。",
  retrySame: "重試同一請求",
  orderTitle: "貨到付款",
  orderState: "收款狀態",
  orderStates: {
    PENDING: "等待貨到付款",
    COLLECTED: "已貨到收款",
    RETURNED: "未取貨·已退回",
    REFUNDED_OFFLINE: "已在本站外退款",
    CANCELLED: "已取消·庫存已釋出",
    RESTOCKED: "已退回·庫存已恢復",
  },
  orderNote: "本站不經手貨到付款款項。請記錄實際發生情況；退款在本站外進行。",
  collected: "標記貨到收款",
  returned: "標記逾期未取退回",
  refundedOffline: "標記在本站外退款",
  cancelOrder: "取消訂單並釋出庫存",
  restockOrder: "包裹已退回——恢復庫存",
  confirmCollected: "確認記錄貨運公司已代收貨到付款款項？此操作無法在此撤銷。",
  confirmReturned: "確認記錄包裹未被領取並已退回？庫存需另行恢復。",
  confirmRefundedOffline: "確認記錄你已在本站外向買家退款？本站不移動任何資金。",
  confirmCancel: "取消這筆未出貨訂單並釋出庫存？買家的貨到付款訂單就此結束。",
  confirmRestock: "包裹已退回。現在恢復其庫存？此操作無法撤銷。",
  done: "已儲存。訂單會顯示伺服器狀態。",
  errors: {
    invalid_settings: "設定內容無效。",
    version_changed: "設定在你載入後已變更，請重新載入後重試。",
    idempotency_conflict: "此請求鍵已用於另一個請求，請重新載入後重試。",
    forbidden: "目前帳號沒有此操作的權限。",
    unauthorized: "請重新登入後繼續。",
    retry_later: "暫時無法使用，請重試。",
    default: "請求未能完成，請重新讀取後重試。",
  },
};

export const codCopy: Record<Locale, typeof en> = { en, "zh-CN": zhCN, "zh-TW": zhTW };
export const codError = (c: typeof en, code: string): string => c.errors[code] ?? c.errors.default;
