// Purpose: Copy for the W6-U1 tag/note UI (customers list tag badges + filter, customer detail tag editor and notes,
//   標籤管理 dialog). Owns every string those controls show, the eight colour names, the note-privacy line ruled by the
//   integrator (2026-10: notes are deleted on erasure and visible in a buyer export — verbatim in zh-TW) and the error
//   map for the frozen W6-01B Go codes. Non-goals: no date formatting (components use Intl), no consent or privacy rule.
// Depends on: @live-commerce/i18n (Locale) only.
// Used by: apps/admin/components/{Customers,CustomerDetail,CustomerTags}.tsx, tests/admin/customer-tags-bff.test.ts
import type { Locale } from "@live-commerce/i18n";

const en = {
  saving: "Saving…",
  unknown: "The result is unknown. Try this same action again before making other changes.",
  refreshRequired: "Saved, but the latest data could not be loaded. Refresh to confirm.",
  staffMember: "Staff member (name unavailable)",
  ownNotesOnly: "You can edit your own notes. Earlier notes remain read-only when the author cannot be confirmed.",
  readOnly: "You do not have permission to make changes.",
  noteDeleteConfirm: "Delete this note?",
  selectedCount: "Selected tags",
  loading: "Loading…",
  permissionUnknown: "Your permissions could not be confirmed. Changes are unavailable.",
  newTag: "New tag",
  tags: "Tags",
  manage: "Manage tags",
  manageTitle: "Tag management",
  manageHint: "Rename, recolour or delete store tags. Deleting detaches the tag from every customer.",
  filterAll: "All tags",
  filterLabel: "Filter by tag",
  createTitle: "New tag",
  nameLabel: "Name",
  nameHint: "1–20 characters, no leading or trailing spaces.",
  colorLabel: "Colour",
  create: "Create",
  save: "Save",
  cancel: "Cancel",
  close: "Close",
  rename: "Rename",
  remove: "Delete",
  removeConfirm: "Delete this tag? It will be detached from every customer.",
  usedBy: (count: number) => `${count} customer(s) tagged`,
  detached: (count: number) => `Tag deleted; detached from ${count} customer(s).`,
  created: "Tag created.",
  updated: "Tag updated.",
  editorLabel: "Customer tags",
  editorHint: "Pick up to 20 tags. If someone changes the tags before you save, refresh and try again.",
  editorEmpty: "No tags yet.",
  editorSave: "Save tags",
  editorSaved: "Tags saved.",
  notes: "Notes",
  notePrivacy: "Notes are deleted when the buyer asks for erasure, and the buyer can see them when requesting a data export.",
  noteAdd: "Add note",
  noteBodyLabel: "Note",
  noteHint: "1–1000 characters.",
  noteSave: "Save note",
  noteEdit: "Edit",
  noteDelete: "Delete",
  noteCancel: "Cancel",
  noteCreated: "Note added.",
  noteUpdated: "Note saved.",
  noteDeleted: "Note deleted.",
  noteEdited: "edited",
  noteAuthor: "Author",
  notesEmpty: "No notes yet.",
  notesMore: "Load more notes",
  conflict: "This record changed elsewhere. Reload to continue.",
  unavailable: "Tags and notes are temporarily unavailable. Try again.",
  retry: "Try again",
  refresh: "Refresh",
  colors: {
    gray: "Gray",
    red: "Red",
    orange: "Orange",
    yellow: "Yellow",
    green: "Green",
    teal: "Teal",
    blue: "Blue",
    purple: "Purple",
  },
  errors: {
    default: "The request could not be completed. Try again.",
    unauthorized: "Your session expired. Sign in again to continue.",
    forbidden: "This account does not have permission for that action.",
    not_found: "That customer or tag no longer exists in this store.",
    tag_exists: "A tag with that name already exists.",
    limit_reached: "A limit was reached (100 tags per store, 20 per customer, 200 notes per customer).",
    version_changed: "The data changed elsewhere. Refresh and try again.",
    idempotency_conflict: "This action could not be matched to the earlier request. Refresh before trying again.",
    retry_later: "The server is busy. Try again in a moment.",
    rate_limited: "Too many requests. Wait a moment and try again.",
    invalid_request: "The request was rejected as invalid. Check the input and try again.",
  },
};
/** Three-language customer tag/note copy; no side effects. */
export type CustomerTagsCopy = typeof en;

/** Localized tag/note controls and truthful backend error messages. */
export const customerTagsCopy: Record<Locale, CustomerTagsCopy> = {
  en,
  "zh-CN": {
    saving: "正在保存…",
    unknown: "结果暂时无法确认。请先重试同一操作，再做其他修改。",
    refreshRequired: "已保存，但无法读取最新资料。请刷新确认。",
    staffMember: "工作人员（姓名暂不可用）",
    ownNotesOnly: "你可以修改自己的备注。无法确认作者的旧备注暂时只读。",
    readOnly: "你没有修改权限。",
    noteDeleteConfirm: "删除这条备注？",
    selectedCount: "已选标签",
    loading: "正在读取…",
    permissionUnknown: "暂时无法确认你的权限，修改功能不可用。",
    newTag: "新增标签",
    tags: "标签",
    manage: "标签管理",
    manageTitle: "标签管理",
    manageHint: "重命名、改色或删除店铺标签。删除会把标签从所有客户上移除。",
    filterAll: "全部标签",
    filterLabel: "按标签筛选",
    createTitle: "新增标签",
    nameLabel: "名称",
    nameHint: "1–20 个字符，首尾不得留空格。",
    colorLabel: "颜色",
    create: "新增",
    save: "保存",
    cancel: "取消",
    close: "关闭",
    rename: "重命名",
    remove: "删除",
    removeConfirm: "删除该标签？它将从所有客户上移除。",
    usedBy: (count: number) => `${count} 位客户使用`,
    detached: (count: number) => `标签已删除，已从 ${count} 位客户移除。`,
    created: "标签已创建。",
    updated: "标签已更新。",
    editorLabel: "客户标签",
    editorHint: "最多选择 20 个标签。如有人在保存前修改了标签，请刷新后再试。",
    editorEmpty: "尚无标签。",
    editorSave: "保存标签",
    editorSaved: "标签已保存。",
    notes: "备注",
    notePrivacy: "备注会在买家要求删除数据时一并删除；买家申请导出数据时也能看到。",
    noteAdd: "新增备注",
    noteBodyLabel: "内容",
    noteHint: "1–1000 个字符。",
    noteSave: "保存备注",
    noteEdit: "编辑",
    noteDelete: "删除",
    noteCancel: "取消",
    noteCreated: "备注已添加。",
    noteUpdated: "备注已保存。",
    noteDeleted: "备注已删除。",
    noteEdited: "已编辑",
    noteAuthor: "作者",
    notesEmpty: "尚无备注。",
    notesMore: "加载更多备注",
    conflict: "该记录已在别处变更。请刷新后继续。",
    unavailable: "标签与备注暂时不可用，请重试。",
    retry: "重试",
    refresh: "刷新",
    colors: {
      gray: "灰色",
      red: "红色",
      orange: "橙色",
      yellow: "黄色",
      green: "绿色",
      teal: "青色",
      blue: "蓝色",
      purple: "紫色",
    },
    errors: {
      default: "操作未能完成，请重试。",
      unauthorized: "会话已过期，请重新登录后继续。",
      forbidden: "此账号没有执行该操作的权限。",
      not_found: "该客户或标签在此店铺中已不存在。",
      tag_exists: "同名标签已存在。",
      limit_reached: "已达上限（每店 100 个标签、每客户 20 个、每客户 200 条备注）。",
      version_changed: "资料已在别处变更，请刷新后重试。",
      idempotency_conflict: "此次操作与先前请求不一致，请刷新后再试。",
      retry_later: "服务器繁忙，请稍后重试。",
      rate_limited: "请求过于频繁，请稍候再试。",
      invalid_request: "请求无效被拒绝，请检查输入后重试。",
    },
  },
  "zh-TW": {
    saving: "正在儲存…",
    unknown: "結果暫時無法確認。請先重試同一操作，再做其他修改。",
    refreshRequired: "已儲存，但無法讀取最新資料。請重新整理確認。",
    staffMember: "工作人員（姓名暫不可用）",
    ownNotesOnly: "你可以修改自己的備註。無法確認作者的舊備註暫時唯讀。",
    readOnly: "你沒有修改權限。",
    noteDeleteConfirm: "刪除此備註？",
    selectedCount: "已選標籤",
    loading: "正在讀取…",
    permissionUnknown: "暫時無法確認你的權限，修改功能不可用。",
    newTag: "新增標籤",
    tags: "標籤",
    manage: "標籤管理",
    manageTitle: "標籤管理",
    manageHint: "重新命名、變更顏色或刪除店鋪標籤。刪除會把標籤從所有客戶移除。",
    filterAll: "全部標籤",
    filterLabel: "依標籤篩選",
    createTitle: "新增標籤",
    nameLabel: "名稱",
    nameHint: "1–20 個字元，首尾不得留空格。",
    colorLabel: "顏色",
    create: "新增",
    save: "儲存",
    cancel: "取消",
    close: "關閉",
    rename: "重新命名",
    remove: "刪除",
    removeConfirm: "刪除此標籤？它會從所有客戶移除。",
    usedBy: (count: number) => `${count} 位客戶使用`,
    detached: (count: number) => `標籤已刪除，已從 ${count} 位客戶移除。`,
    created: "標籤已建立。",
    updated: "標籤已更新。",
    editorLabel: "客戶標籤",
    editorHint: "最多選擇 20 個標籤。如有人在儲存前修改了標籤，請重新整理後再試。",
    editorEmpty: "尚無標籤。",
    editorSave: "儲存標籤",
    editorSaved: "標籤已儲存。",
    notes: "備註",
    notePrivacy: "備註會在買家要求刪除資料時一起刪除，買家申請匯出資料時也看得到",
    noteAdd: "新增備註",
    noteBodyLabel: "內容",
    noteHint: "1–1000 個字元。",
    noteSave: "儲存備註",
    noteEdit: "編輯",
    noteDelete: "刪除",
    noteCancel: "取消",
    noteCreated: "備註已新增。",
    noteUpdated: "備註已儲存。",
    noteDeleted: "備註已刪除。",
    noteEdited: "已編輯",
    noteAuthor: "作者",
    notesEmpty: "尚無備註。",
    notesMore: "載入更多備註",
    conflict: "此記錄已在別處變更。請重新整理後繼續。",
    unavailable: "標籤與備註暫時無法使用，請重試。",
    retry: "重試",
    refresh: "重新整理",
    colors: {
      gray: "灰色",
      red: "紅色",
      orange: "橙色",
      yellow: "黃色",
      green: "綠色",
      teal: "青色",
      blue: "藍色",
      purple: "紫色",
    },
    errors: {
      default: "操作未能完成，請重試。",
      unauthorized: "工作階段已過期，請重新登入後繼續。",
      forbidden: "此帳號沒有執行該操作的權限。",
      not_found: "該客戶或標籤在此店鋪中已不存在。",
      tag_exists: "同名標籤已存在。",
      limit_reached: "已達上限（每店 100 個標籤、每客戶 20 個、每客戶 200 則備註）。",
      version_changed: "資料已在別處變更，請重新整理後重試。",
      idempotency_conflict: "此次操作與先前請求不一致，請重新整理後再試。",
      retry_later: "伺服器忙碌中，請稍後重試。",
      rate_limited: "請求過於頻繁，請稍候再試。",
      invalid_request: "請求是無效的而被拒絕，請檢查輸入後重試。",
    },
  },
};
