// Copy for the admin Design page (components/Design*.tsx; BFF design/* -> Go internal/httpapi/design.go), locales zh-CN /
// zh-TW / en. Owns every UI string of the page and the error-code map; the merchant's own content (store name, headings,
// page text) is single-language and never goes through here. `{n}` / `{path}` / `{reason}` are filled by `fill`.
// Non-goals: no validation rule (the server decides), no formatting of dates (components use Intl).
import type { Locale } from "@live-commerce/i18n";

const en = {
  title: "Store design",
  subtitle: "Edit your storefront draft, preview it, then publish. Buyers only see published versions.",
  store: "Store",
  loading: "Loading the design…",
  signedOut: "Sign in to edit the store design.",
  forbidden: "This account does not have permission to edit the store design.",
  notFound: "The store design is unavailable for this store.",
  unavailable: "The store design is temporarily unavailable. Try again.",
  noStore: "No authorized store is available.",
  retry: "Try again",
  tabs: { profile: "Store profile", nav: "Navigation", home: "Home page", pages: "Pages", versions: "Versions" },
  draftVersion: "Draft v{n}",
  noDraft: "Not saved yet",
  liveVersion: "Live: v{n}",
  neverPublished: "Never published",
  unsaved: "Unsaved changes",
  saved: "All changes saved",
  save: "Save draft",
  saving: "Saving…",
  preview: "Preview",
  publish: "Publish",
  publishing: "Publishing…",
  publishConfirm: "Publish draft v{n}? Buyers will see it immediately.",
  needsSave: "Fix the highlighted fields before saving.",
  guard: "You have unsaved changes. Leave without saving?",
  okSaved: "Draft saved.",
  okPublished: "Published as version {n}.",
  okRolledBack: "Rolled back: published as version {n}.",
  previewOpened: "Preview opened in a new tab. The link works for 15 minutes and only for this saved draft.",
  previewNoOrigin: "Bind a storefront address first (Settings), then preview. No address is active for this store.",
  previewBlocked: "The browser blocked the new tab. Allow pop-ups and try Preview again.",
  invalidAt: "Please fix {path}: {reason}",
  issue: { required: "Required", slug: "Use lowercase letters, numbers and hyphens, unique", page: "Choose a page that exists" },
  errors: {
    unauthorized: "Your session changed. Reload and sign in again.",
    forbidden: "This account may not do that.",
    conflict: "The design changed elsewhere or is already in that state. Reload to see the latest.",
    invalid_request: "The design was refused by the server.",
    not_found: "Not found. Save the draft first.",
    retry_later: "Could not reach the server. Your edits are still here; try again.",
    default: "Could not complete the request. Try again.",
  } as Record<string, string>,
  reload: "Reload latest",
  profile: {
    name: "Store name", tagline: "Tagline", logo: "Logo", favicon: "Favicon (browser tab icon)", accent: "Accent colour", announcement: "Announcement bar",
    contact: "Contact", email: "Email", phone: "Phone", address: "Address", line: "LINE link (https://line.me/…)", facebook: "Facebook page URL", instagram: "Instagram URL",
  },
  nav: {
    header: "Header menu", footer: "Footer links", label: "Label", kind: "Links to", target: "Target", add: "Add link", remove: "Remove", up: "Move up", down: "Move down",
    kinds: { home: "Home", all_products: "All products", collection: "Collection", page: "Page", url: "Web address" } as Record<string, string>,
    collectionSlug: "Collection slug", url: "https://…", choosePage: "Choose page", empty: "No links yet.", limit: "Limit reached",
  },
  home: {
    add: "Add section", types: { hero: "Hero banner", featured_collection: "Featured collection", product_grid: "Product grid", rich_text: "Text block", image_text: "Image with text" } as Record<string, string>,
    heading: "Heading", subheading: "Subheading", ctaLabel: "Button label", ctaKind: "Button links to", ctaNone: "No button", ctaTarget: "Target",
    collectionSlug: "Collection slug", limit: "Products shown", sort: "Order", sorts: { newest: "Newest first", price_asc: "Price, low to high", price_desc: "Price, high to low" } as Record<string, string>,
    body: "Text", imageSide: "Image side", sides: { left: "Left", right: "Right" } as Record<string, string>, image: "Image", empty: "No sections yet. Buyers will see the product grid.", limit_reached: "Limit reached",
  },
  pages: {
    add: "Add page", slug: "Address (slug)", title: "Page title", body: "Page text", preview: "Preview", remove: "Remove page", empty: "No pages yet. Add one for shipping, returns or contact.",
    help: "Supported: paragraphs, **bold**, *italic*, lists starting with “- ”, and [text](https://…) links. HTML is not allowed.", problem: "Not allowed: ", limit: "Limit reached",
  },
  media: {
    noFile: "No file selected",
    choose: "Choose image", change: "Change image", upload: "Upload image", uploading: "Uploading…", remove: "Remove", none: "No images uploaded yet.", library: "Image library ({n}/60)",
    delete: "Delete image", inUse: "This image is used by the draft or the live version.", badType: "Use a JPEG, PNG or WebP image.", badSize: "The image must be 2 MB or smaller.",
    full: "The image library is full (60). Delete an unused image first.", pick: "Use this image", alt: "Store image",
  },
  versions: {
    version: "Version", kind: { publish: "Published", rollback: "Rolled back" } as Record<string, string>, source: "From v{n}", at: "Time", live: "Live", rollback: "Roll back to this",
    rollbackConfirm: "Roll back to version {n}? It will be published as a new version.", none: "Nothing published yet.", help: "Rolling back publishes a copy of an old version; history is never changed. Your draft is not touched.",
  },
};
export type DesignCopy = typeof en;

const zhCN: DesignCopy = {
  title: "店铺装修",
  subtitle: "编辑店铺草稿，预览后再发布。买家只会看到已发布的版本。",
  store: "店铺",
  loading: "正在加载装修…",
  signedOut: "请登录后编辑店铺装修。",
  forbidden: "此账号没有编辑店铺装修的权限。",
  notFound: "此店铺的装修暂不可用。",
  unavailable: "店铺装修暂时不可用，请重试。",
  noStore: "没有可用的授权店铺。",
  retry: "重试",
  tabs: { profile: "店铺资料", nav: "导航", home: "首页", pages: "信息页", versions: "版本" },
  draftVersion: "草稿 v{n}",
  noDraft: "尚未保存",
  liveVersion: "线上：v{n}",
  neverPublished: "从未发布",
  unsaved: "有未保存的修改",
  saved: "所有修改已保存",
  save: "保存草稿",
  saving: "保存中…",
  preview: "预览",
  publish: "发布",
  publishing: "发布中…",
  publishConfirm: "发布草稿 v{n}？买家将立即看到。",
  needsSave: "请先修正标出的字段再保存。",
  guard: "有未保存的修改，确定离开吗？",
  okSaved: "草稿已保存。",
  okPublished: "已发布为版本 {n}。",
  okRolledBack: "已回滚：发布为版本 {n}。",
  previewOpened: "预览已在新标签页打开。链接 15 分钟内有效，且只对当前已保存的草稿有效。",
  previewNoOrigin: "请先绑定店铺网址（设置），再预览。此店铺没有生效的网址。",
  previewBlocked: "浏览器拦截了新标签页。请允许弹出窗口后重新点击预览。",
  invalidAt: "请修正 {path}：{reason}",
  issue: { required: "必填", slug: "使用小写字母、数字和连字符，且不可重复", page: "请选择已存在的页面" },
  errors: {
    unauthorized: "登录状态已变化，请刷新并重新登录。",
    forbidden: "此账号无权执行该操作。",
    conflict: "装修已在别处被修改，或已处于该状态。请刷新查看最新内容。",
    invalid_request: "服务器拒绝了此装修内容。",
    not_found: "未找到。请先保存草稿。",
    retry_later: "无法连接服务器。你的修改仍在此处，请重试。",
    default: "无法完成请求，请重试。",
  },
  reload: "加载最新",
  profile: {
    name: "店铺名称", tagline: "一句话介绍", logo: "标志", favicon: "网站图标（浏览器标签页）", accent: "主题色", announcement: "公告栏",
    contact: "联系方式", email: "邮箱", phone: "电话", address: "地址", line: "LINE 链接（https://line.me/…）", facebook: "Facebook 粉丝专页网址", instagram: "Instagram 网址",
  },
  nav: {
    header: "页首菜单", footer: "页尾链接", label: "名称", kind: "链接到", target: "目标", add: "添加链接", remove: "删除", up: "上移", down: "下移",
    kinds: { home: "首页", all_products: "全部商品", collection: "商品系列", page: "信息页", url: "网址" },
    collectionSlug: "系列代号（slug）", url: "https://…", choosePage: "选择页面", empty: "还没有链接。", limit: "已达上限",
  },
  home: {
    add: "添加区块", types: { hero: "主视觉横幅", featured_collection: "精选系列", product_grid: "商品列表", rich_text: "文字区块", image_text: "图文区块" },
    heading: "标题", subheading: "副标题", ctaLabel: "按钮文字", ctaKind: "按钮链接到", ctaNone: "不显示按钮", ctaTarget: "目标",
    collectionSlug: "系列代号（slug）", limit: "显示商品数", sort: "排序", sorts: { newest: "最新优先", price_asc: "价格由低到高", price_desc: "价格由高到低" },
    body: "文字", imageSide: "图片位置", sides: { left: "左侧", right: "右侧" }, image: "图片", empty: "还没有区块，买家将看到商品列表。", limit_reached: "已达上限",
  },
  pages: {
    add: "添加页面", slug: "网址（slug）", title: "页面标题", body: "页面内容", preview: "预览", remove: "删除页面", empty: "还没有页面。可添加运费、退换货或联系我们。",
    help: "支持：段落、**粗体**、*斜体*、以“- ”开头的列表，以及 [文字](https://…) 链接。不支持 HTML。", problem: "不允许：", limit: "已达上限",
  },
  media: {
    noFile: "未选择文件",
    choose: "选择图片", change: "更换图片", upload: "上传图片", uploading: "上传中…", remove: "移除", none: "还没有上传图片。", library: "图片库（{n}/60）",
    delete: "删除图片", inUse: "此图片正被草稿或线上版本使用。", badType: "请使用 JPEG、PNG 或 WebP 图片。", badSize: "图片不能超过 2 MB。",
    full: "图片库已满（60 张）。请先删除未使用的图片。", pick: "使用此图片", alt: "店铺图片",
  },
  versions: {
    version: "版本", kind: { publish: "发布", rollback: "回滚" }, source: "来自 v{n}", at: "时间", live: "线上", rollback: "回滚到此版本",
    rollbackConfirm: "回滚到版本 {n}？它将作为新版本发布。", none: "尚未发布任何版本。", help: "回滚会把旧版本复制为新的发布版本，历史记录不会被修改，草稿也不会改变。",
  },
};

const zhTW: DesignCopy = {
  title: "店鋪裝修",
  subtitle: "編輯店鋪草稿，預覽後再發佈。買家只會看到已發佈的版本。",
  store: "店鋪",
  loading: "正在載入裝修…",
  signedOut: "請登入後編輯店鋪裝修。",
  forbidden: "此帳號沒有編輯店鋪裝修的權限。",
  notFound: "此店鋪的裝修暫不可用。",
  unavailable: "店鋪裝修暫時無法使用，請重試。",
  noStore: "沒有可用的授權店鋪。",
  retry: "重試",
  tabs: { profile: "店鋪資料", nav: "導覽", home: "首頁", pages: "資訊頁", versions: "版本" },
  draftVersion: "草稿 v{n}",
  noDraft: "尚未儲存",
  liveVersion: "線上：v{n}",
  neverPublished: "從未發佈",
  unsaved: "有未儲存的修改",
  saved: "所有修改已儲存",
  save: "儲存草稿",
  saving: "儲存中…",
  preview: "預覽",
  publish: "發佈",
  publishing: "發佈中…",
  publishConfirm: "發佈草稿 v{n}？買家將立即看到。",
  needsSave: "請先修正標示的欄位再儲存。",
  guard: "有未儲存的修改，確定離開嗎？",
  okSaved: "草稿已儲存。",
  okPublished: "已發佈為版本 {n}。",
  okRolledBack: "已回復：發佈為版本 {n}。",
  previewOpened: "預覽已在新分頁開啟。連結 15 分鐘內有效，且只對目前已儲存的草稿有效。",
  previewNoOrigin: "請先綁定店鋪網址（設定），再預覽。此店鋪沒有生效的網址。",
  previewBlocked: "瀏覽器封鎖了新分頁。請允許彈出視窗後重新點選預覽。",
  invalidAt: "請修正 {path}：{reason}",
  issue: { required: "必填", slug: "使用小寫字母、數字與連字號，且不可重複", page: "請選擇已存在的頁面" },
  errors: {
    unauthorized: "登入狀態已變更，請重新整理並重新登入。",
    forbidden: "此帳號無權執行該操作。",
    conflict: "裝修已在其他地方被修改，或已處於該狀態。請重新整理查看最新內容。",
    invalid_request: "伺服器拒絕了此裝修內容。",
    not_found: "找不到。請先儲存草稿。",
    retry_later: "無法連線伺服器。你的修改仍在此處，請重試。",
    default: "無法完成請求，請重試。",
  },
  reload: "載入最新",
  profile: {
    name: "店鋪名稱", tagline: "一句話介紹", logo: "標誌", favicon: "網站圖示（瀏覽器分頁）", accent: "主題色", announcement: "公告列",
    contact: "聯絡方式", email: "電子郵件", phone: "電話", address: "地址", line: "LINE 連結（https://line.me/…）", facebook: "Facebook 粉絲專頁網址", instagram: "Instagram 網址",
  },
  nav: {
    header: "頁首選單", footer: "頁尾連結", label: "名稱", kind: "連結到", target: "目標", add: "新增連結", remove: "刪除", up: "上移", down: "下移",
    kinds: { home: "首頁", all_products: "全部商品", collection: "商品分類", page: "資訊頁", url: "網址" },
    collectionSlug: "分類代號（slug）", url: "https://…", choosePage: "選擇頁面", empty: "還沒有連結。", limit: "已達上限",
  },
  home: {
    add: "新增區塊", types: { hero: "主視覺橫幅", featured_collection: "精選分類", product_grid: "商品列表", rich_text: "文字區塊", image_text: "圖文區塊" },
    heading: "標題", subheading: "副標題", ctaLabel: "按鈕文字", ctaKind: "按鈕連結到", ctaNone: "不顯示按鈕", ctaTarget: "目標",
    collectionSlug: "分類代號（slug）", limit: "顯示商品數", sort: "排序", sorts: { newest: "最新優先", price_asc: "價格由低到高", price_desc: "價格由高到低" },
    body: "文字", imageSide: "圖片位置", sides: { left: "左側", right: "右側" }, image: "圖片", empty: "還沒有區塊，買家將看到商品列表。", limit_reached: "已達上限",
  },
  pages: {
    add: "新增頁面", slug: "網址（slug）", title: "頁面標題", body: "頁面內容", preview: "預覽", remove: "刪除頁面", empty: "還沒有頁面。可新增運費、退換貨或聯絡我們。",
    help: "支援：段落、**粗體**、*斜體*、以「- 」開頭的清單，以及 [文字](https://…) 連結。不支援 HTML。", problem: "不允許：", limit: "已達上限",
  },
  media: {
    noFile: "未選擇檔案",
    choose: "選擇圖片", change: "更換圖片", upload: "上傳圖片", uploading: "上傳中…", remove: "移除", none: "還沒有上傳圖片。", library: "圖片庫（{n}/60）",
    delete: "刪除圖片", inUse: "此圖片正被草稿或線上版本使用。", badType: "請使用 JPEG、PNG 或 WebP 圖片。", badSize: "圖片不能超過 2 MB。",
    full: "圖片庫已滿（60 張）。請先刪除未使用的圖片。", pick: "使用此圖片", alt: "店鋪圖片",
  },
  versions: {
    version: "版本", kind: { publish: "發佈", rollback: "回復" }, source: "來自 v{n}", at: "時間", live: "線上", rollback: "回復到此版本",
    rollbackConfirm: "回復到版本 {n}？它將作為新版本發佈。", none: "尚未發佈任何版本。", help: "回復會把舊版本複製為新的發佈版本，歷史紀錄不會被修改，草稿也不會改變。",
  },
};

export const designCopy: Record<Locale, DesignCopy> = { en, "zh-CN": zhCN, "zh-TW": zhTW };
export const fill = (template: string, values: Record<string, string | number>) => template.replace(/\{(\w+)\}/g, (_, k: string) => String(values[k] ?? ""));
