import type { Locale } from "@live-commerce/i18n";

const en = {
  product: "Live commerce workspace",
  manage: "Workspace setup",
  account: "Merchant account",
  language: "Language",
  title: "Create your first workspace",
  signInTitle: "Sign in to your merchant workspace",
  signInBody:
    "Continue through the configured identity service. This page never asks for your provider password.",
  signIn: "Sign in with identity service",
  authFailed:
    "Sign-in did not complete. Start the identity-service flow again.",
  authExpired:
    "Your session expired. Sign in again; the previous session's draft was not carried forward.",
  providerDisabled: "Merchant sign-in is not configured",
  providerDisabledBody:
    "This environment cannot start merchant sign-in. No production data is available here.",
  serviceUnavailable: "The merchant service is temporarily unavailable",
  serviceUnavailableBody:
    "No setup request was sent. Refresh after the service is restored.",
  onboardingDisabled: "First-workspace setup is not enabled",
  onboardingDisabledBody:
    "Your signed-in session is valid, but this deployment has not enabled workspace creation.",
  currencyUnavailable: "No transaction currency policy is configured.",
  stepMerchant: "Merchant name",
  stepStore: "Store settings",
  stepWarehouse: "Warehouse",
  merchantHeading: "Name the merchant",
  merchantBody: "Use the operating name that should own this workspace.",
  merchantName: "Merchant name",
  merchantPlaceholder: "Example merchant",
  storeHeading: "Set the store name and currency",
  storeName: "Store name",
  storePlaceholder: "Example store",
  currency: "Transaction currency",
  currencyHint:
    "Changing the interface language does not change this currency.",
  completed: "Completed",
  edit: "Edit",
  warehouseHeading: "Add the initial inventory warehouse",
  warehouseName: "Initial warehouse name",
  warehousePlaceholder: "Main warehouse",
  review: "Review before creating",
  previous: "Previous",
  nextStore: "Next: store settings",
  nextWarehouse: "Next: warehouse",
  create: "Create internal workspace",
  creating: "Creating…",
  retryExact: "Retry the same request",
  checkWorkspace: "Check workspace status",
  openWorkspace: "Open workspace",
  signOut: "Sign out",
  scope:
    "This creates an internal workspace. It does not publish a store or connect payment or shipping.",
  finalHint:
    "Review every field. Only this final step sends the creation request.",
  invalid: "Complete the required field before continuing.",
  storageUnavailable:
    "Secure draft storage is unavailable. No setup request can be sent from this tab.",
  unknown:
    "The server result is unknown. Fields are locked; retry the exact saved request and key.",
  conflict:
    "A workspace may already exist or this request conflicts with an earlier setup. Check workspace status before doing anything else.",
  failed: "The workspace could not be created. Check the fields and try again.",
  success:
    "Internal workspace created. The store is not published, and payment and shipping are not connected.",
};

export type EntryCopy = typeof en;

export const entryCopy: Record<Locale, EntryCopy> = {
  en,
  "zh-CN": {
    product: "直播商家工作台",
    manage: "工作区管理",
    account: "商家账号",
    language: "语言",
    title: "创建第一个工作区",
    signInTitle: "登录商家工作区",
    signInBody: "通过已配置的身份服务继续。本页面不会要求输入身份服务密码。",
    signIn: "通过身份服务登录",
    authFailed: "登录未完成，请重新开始身份服务登录流程。",
    authExpired: "会话已过期，请重新登录；上一会话的草稿不会带入新会话。",
    providerDisabled: "尚未配置商家登录",
    providerDisabledBody: "当前环境无法开始商家登录，也不会开放生产数据。",
    serviceUnavailable: "商家服务暂时不可用",
    serviceUnavailableBody: "尚未发送开通请求，请在服务恢复后刷新。",
    onboardingDisabled: "尚未启用首个工作区开通",
    onboardingDisabledBody: "当前登录会话有效，但此部署尚未启用工作区创建。",
    currencyUnavailable: "尚未配置可用的交易币种策略。",
    stepMerchant: "商户名称",
    stepStore: "店铺设置",
    stepWarehouse: "库存仓",
    merchantHeading: "填写商户名称",
    merchantBody: "填写将持有此工作区的经营名称。",
    merchantName: "商户名称",
    merchantPlaceholder: "示例商户",
    storeHeading: "设置店铺名称与币种",
    storeName: "店铺名称",
    storePlaceholder: "示例店铺",
    currency: "交易币种",
    currencyHint: "切换界面语言不会改变交易币种。",
    completed: "已填写",
    edit: "修改",
    warehouseHeading: "设置初始库存仓",
    warehouseName: "初始库存仓名称",
    warehousePlaceholder: "主仓",
    review: "创建前核对",
    previous: "上一步",
    nextStore: "下一步：店铺设置",
    nextWarehouse: "下一步：库存仓",
    create: "创建内部工作区",
    creating: "正在创建…",
    retryExact: "重试同一请求",
    checkWorkspace: "检查工作区状态",
    openWorkspace: "进入工作区",
    signOut: "退出登录",
    scope: "创建内部工作区，不会自动发布店铺或接通支付、物流。",
    finalHint: "请核对全部资料。只有最后一步会发送创建请求。",
    invalid: "请先填写必填资料。",
    storageUnavailable: "当前标签页无法可靠保存草稿，因此不会发送开通请求。",
    unknown:
      "服务器结果未知。资料已锁定；只能使用已保存的原请求与原幂等键重试。",
    conflict:
      "工作区可能已经存在，或本次请求与既有开通记录冲突。请先检查工作区状态。",
    failed: "工作区未能创建，请检查资料后重试。",
    success: "内部工作区已创建；店铺尚未发布，支付和物流尚未接通。",
  },
  "zh-TW": {
    product: "直播商家工作台",
    manage: "工作區管理",
    account: "商家帳號",
    language: "語言",
    title: "建立第一個工作區",
    signInTitle: "登入商家工作區",
    signInBody: "透過已設定的身分服務繼續。本頁面不會要求輸入身分服務密碼。",
    signIn: "透過身分服務登入",
    authFailed: "登入未完成，請重新開始身分服務登入流程。",
    authExpired:
      "工作階段已過期，請重新登入；上一工作階段的草稿不會帶入新工作階段。",
    providerDisabled: "尚未設定商家登入",
    providerDisabledBody: "目前環境無法開始商家登入，也不會開放正式資料。",
    serviceUnavailable: "商家服務暫時無法使用",
    serviceUnavailableBody: "尚未送出開通請求，請在服務恢復後重新整理。",
    onboardingDisabled: "尚未啟用第一個工作區開通",
    onboardingDisabledBody:
      "目前登入工作階段有效，但此部署尚未啟用工作區建立。",
    currencyUnavailable: "尚未設定可用的交易幣別政策。",
    stepMerchant: "商戶名稱",
    stepStore: "商店設定",
    stepWarehouse: "庫存倉",
    merchantHeading: "填寫商戶名稱",
    merchantBody: "填寫將持有此工作區的營運名稱。",
    merchantName: "商戶名稱",
    merchantPlaceholder: "範例商戶",
    storeHeading: "設定商店名稱與幣別",
    storeName: "商店名稱",
    storePlaceholder: "範例商店",
    currency: "交易幣別",
    currencyHint: "切換介面語言不會改變交易幣別。",
    completed: "已填寫",
    edit: "修改",
    warehouseHeading: "設定初始庫存倉",
    warehouseName: "初始庫存倉名稱",
    warehousePlaceholder: "主倉",
    review: "建立前核對",
    previous: "上一步",
    nextStore: "下一步：商店設定",
    nextWarehouse: "下一步：庫存倉",
    create: "建立內部工作區",
    creating: "正在建立…",
    retryExact: "重試同一請求",
    checkWorkspace: "檢查工作區狀態",
    openWorkspace: "進入工作區",
    signOut: "登出",
    scope: "建立內部工作區，不會自動發布商店或接通付款、物流。",
    finalHint: "請核對全部資料。只有最後一步會送出建立請求。",
    invalid: "請先填寫必填資料。",
    storageUnavailable: "目前分頁無法可靠儲存草稿，因此不會送出開通請求。",
    unknown:
      "伺服器結果未知。資料已鎖定；只能使用已儲存的原請求與原冪等鍵重試。",
    conflict:
      "工作區可能已存在，或本次請求與既有開通紀錄衝突。請先檢查工作區狀態。",
    failed: "工作區未能建立，請檢查資料後重試。",
    success: "內部工作區已建立；商店尚未發布，付款和物流尚未接通。",
  },
};
