// Purpose: plain three-language migration wizard copy, no customer rows or identifiers.
// Depends on: existing Locale type only.
// Used by: ImportWizard and import wire tests.
import type { Locale } from "@live-commerce/i18n";

/** Localized wizard labels and closed-code messages; no side effects. */
export const importCopy: Record<Locale, { title: string; subtitle: string; customerKind: string; ordersKind: string; consentNotice: string; historyNotice: string; customerFirst: string; uploadLabel: string; utf8Hint: string; fileTooLarge: string; mapHeader: string; mapField: string; unmapped: string; required: string; guess: string; preview: string; commit: string; back: string; restart: string; loading: string; working: string; row: string; outcome: string; code: string; newRows: string; updateRows: string; failedRows: string; erasedRows: string; consentIgnoredRows: string; cityDroppedRows: string; empty: string; confirmLabel: string; created: string; updated: string; failed: string; replayed: string; staleNotice: string; idempotencyConflict: string; unknownCommit: string; signedOut: string; forbidden: string; notFound: string; unavailable: string; noFile: string; requiredMapping: string; failedDownload: string; downloadStarted: string; downloadUnknown: string; headersFailure: string; limits: string; fileHash: string; mappingSaved: string; storageNotice: string; onlyRowsHint: string; stages: Record<string, string>; fieldLabels: Record<string, string>; outcomes: Record<string, string>; errors: Record<string, string> }> = {
  "en": {
    "title": "Move from SHOPLINE",
    "subtitle": "Import customers first, then a read-only historical order archive.",
    "customerKind": "Customers",
    "ordersKind": "Historical orders",
    "consentNotice": "Marketing consent is not imported. All imported customers are treated as not opted in.",
    "historyNotice": "Historical orders are for viewing only and do not count toward revenue or reports.",
    "customerFirst": "Complete a customer import in this store before importing historical orders.",
    "uploadLabel": "Choose CSV file",
    "utf8Hint": "Save as CSV UTF-8. Big5 files cannot be imported.",
    "fileTooLarge": "Choose a file no larger than 2 MiB.",
    "mapHeader": "CSV column",
    "mapField": "Customer / order field",
    "unmapped": "Do not import this column",
    "required": "Required",
    "guess": "Guess column mapping",
    "preview": "Preview import",
    "commit": "Confirm import",
    "back": "Back",
    "restart": "Start again",
    "loading": "Loading…",
    "working": "Import in progress…",
    "row": "Row",
    "outcome": "Result",
    "code": "Reason",
    "newRows": "New",
    "updateRows": "Updates",
    "failedRows": "Failed",
    "erasedRows": "Previously erased",
    "consentIgnoredRows": "Consent ignored",
    "cityDroppedRows": "City discarded",
    "empty": "No rows to show.",
    "confirmLabel": "Confirm the new and updated counts below.",
    "created": "Created",
    "updated": "Updated",
    "failed": "Failed",
    "replayed": "This file was already imported. The previous result is shown; no duplicate import occurred.",
    "staleNotice": "The preview changed. Review the new counts and confirm again.",
    "idempotencyConflict": "This file was already imported using another set of column settings. To correct it, change the original file before uploading again.",
    "unknownCommit": "The result is not yet confirmed. Use the button below to retry this same import. Keep the same file and settings.",
    "signedOut": "Your session ended. Sign in again.",
    "forbidden": "You do not have import permission.",
    "notFound": "This store or import batch is unavailable.",
    "unavailable": "Import is unavailable. Try again after checking your session.",
    "noFile": "Choose a CSV file first.",
    "requiredMapping": "Map every required field before previewing.",
    "failedDownload": "Download failed row numbers",
    "downloadStarted": "Failure report download started.",
    "downloadUnknown": "The download could not be confirmed. Check your downloads before trying again.",
    "headersFailure": "The header could not be read. Check the CSV format and UTF-8 encoding.",
    "limits": "UTF-8 CSV, at most 2 MiB and 5,000 data lines. Order lines are grouped into orders.",
    "fileHash": "File check",
    "mappingSaved": "Column mapping is sent with this import.",
    "storageNotice": "The file remains in memory and is not saved in browser storage.",
    "onlyRowsHint": "Only row numbers and reasons are shown. Customer data and source IDs are not displayed.",
    "stages": {
      "select": "Select type",
      "upload": "Upload",
      "mapping": "Map columns",
      "preview": "Preview",
      "confirm": "Confirm",
      "result": "Result"
    },
    "fieldLabels": {
      "external_id": "Source customer ID",
      "name": "Customer name",
      "phone": "Phone",
      "email": "Email",
      "consent": "Consent (ignored)",
      "order_id": "Order number",
      "customer_id": "Source customer ID",
      "ordered_at": "Order date",
      "status": "Order status",
      "total": "Order total",
      "item_name": "Item name",
      "item_qty": "Quantity",
      "city": "City only"
    },
    "outcomes": {
      "created": "Created",
      "updated": "Updated",
      "failed": "Failed"
    },
    "errors": {
      "encoding_not_utf8": "Save as CSV UTF-8. Big5 files cannot be imported.",
      "too_many_rows": "UTF-8 CSV, at most 2 MiB and 5,000 data lines. Order lines are grouped into orders.",
      "required": "Map every required field before previewing.",
      "invalid_request": "Check the CSV format, number of columns and column mapping.",
      "invalid_external_id": "Use the source customer ID, not an email address or Taiwan mobile number.",
      "name_too_long": "Customer names must contain at most 80 characters.",
      "invalid_name": "Remove unsupported control characters from the customer name.",
      "invalid_phone": "Enter a Taiwan mobile number, such as 09 followed by eight digits.",
      "invalid_email": "Check that the email address is complete and correctly formatted.",
      "duplicate_external_id": "This customer ID appears more than once. Keep one row for each source customer ID.",
      "erased": "Previously erased",
      "invalid_order_id": "Use an order number, not an email address or Taiwan mobile number.",
      "invalid_date": "Enter a valid order date, such as 2026-03-05. Dates without a time zone use Taipei time.",
      "invalid_amount": "Use a non-negative whole Taiwan-dollar amount. Non-zero cents cannot be imported.",
      "invalid_status": "Keep the order status within 40 characters and exclude phone numbers or email addresses.",
      "invalid_item": "Check the item name. Phone numbers, emails or unsupported characters cannot be imported.",
      "invalid_quantity": "Item quantity must be a whole number from 1 to 9,999.",
      "inconsistent_order": "Lines of the same order must agree on customer, date, status and total.",
      "customer_not_imported": "Complete a customer import in this store before importing historical orders.",
      "order_owner_conflict": "This order number is already linked to a different customer. Check the original file.",
      "order_limit": "A customer can have at most 2,000 historical orders.",
      "nothing_to_apply": "No rows to show.",
      "idempotency_conflict": "This file was already imported using another set of column settings. To correct it, change the original file before uploading again.",
      "retry_later": "Import is unavailable. Try again after checking your session.",
      "unauthorized": "Your session ended. Sign in again.",
      "forbidden": "You do not have import permission.",
      "not_found": "This store or import batch is unavailable.",
      "city_dropped": "City discarded"
    }
  },
  "zh-TW": {
    "title": "從 SHOPLINE 搬家",
    "subtitle": "先匯入顧客，再匯入只供查看的歷史訂單。",
    "customerKind": "顧客",
    "ordersKind": "歷史訂單",
    "consentNotice": "行銷同意不會匯入，匯入的顧客一律視為未同意。",
    "historyNotice": "歷史訂單只供查看，不計入營收與報表。",
    "customerFirst": "請先在這間店鋪完成顧客匯入，再匯入歷史訂單。",
    "uploadLabel": "選擇 CSV 檔案",
    "utf8Hint": "請另存為 CSV UTF-8，無法匯入 Big5 檔案。",
    "fileTooLarge": "請選擇不超過 2 MiB 的檔案。",
    "mapHeader": "CSV 欄位",
    "mapField": "顧客／訂單欄位",
    "unmapped": "不匯入這個欄位",
    "required": "必填",
    "guess": "自動猜測欄位",
    "preview": "預覽匯入",
    "commit": "確認匯入",
    "back": "上一步",
    "restart": "重新開始",
    "loading": "正在載入…",
    "working": "正在匯入…",
    "row": "列號",
    "outcome": "結果",
    "code": "原因",
    "newRows": "新增",
    "updateRows": "更新",
    "failedRows": "失敗",
    "erasedRows": "曾要求刪除",
    "consentIgnoredRows": "已忽略行銷同意",
    "cityDroppedRows": "未儲存城市",
    "empty": "沒有可顯示的列。",
    "confirmLabel": "請確認下方新增與更新數量。",
    "created": "已新增",
    "updated": "已更新",
    "failed": "失敗",
    "replayed": "這份檔案已匯入，顯示先前結果，不會重複建立資料。",
    "staleNotice": "預覽已變更，請檢查最新數量後再次確認。",
    "idempotencyConflict": "這份檔案已按另一組欄位設定匯入；若要修正，請先修改原檔案再上傳。",
    "unknownCommit": "匯入結果尚未確認，可用下方按鈕重試同一份匯入；請勿更換檔案或設定。",
    "signedOut": "登入已結束，請重新登入。",
    "forbidden": "你沒有匯入權限。",
    "notFound": "這間店鋪或匯入批次無法使用。",
    "unavailable": "目前無法匯入，請先確認登入狀態。",
    "noFile": "請先選擇 CSV 檔案。",
    "requiredMapping": "預覽前請對應所有必填欄位。",
    "failedDownload": "下載失敗列號",
    "downloadStarted": "已開始下載失敗列報告。",
    "downloadUnknown": "下載尚未確認，再試前請先檢查下載紀錄。",
    "headersFailure": "無法讀取表頭，請檢查 CSV 格式與 UTF-8 編碼。",
    "limits": "UTF-8 CSV，最多 2 MiB、5,000 資料列；訂單品項列會合併成訂單。",
    "fileHash": "檔案核對",
    "mappingSaved": "欄位對應會隨本次匯入送出。",
    "storageNotice": "檔案只保留在記憶體，不存入瀏覽器儲存空間。",
    "onlyRowsHint": "只顯示列號與原因，不顯示顧客資料或來源編號。",
    "stages": {
      "select": "選擇類型",
      "upload": "上傳",
      "mapping": "對應欄位",
      "preview": "預覽",
      "confirm": "確認",
      "result": "結果"
    },
    "fieldLabels": {
      "external_id": "顧客來源編號",
      "name": "顧客姓名",
      "phone": "電話",
      "email": "電子郵件",
      "consent": "同意（忽略）",
      "order_id": "訂單編號",
      "customer_id": "顧客來源編號",
      "ordered_at": "訂單日期",
      "status": "訂單狀態",
      "total": "訂單金額",
      "item_name": "品項名稱",
      "item_qty": "數量",
      "city": "僅城市"
    },
    "outcomes": {
      "created": "已新增",
      "updated": "已更新",
      "failed": "失敗"
    },
    "errors": {
      "encoding_not_utf8": "請另存為 CSV UTF-8，無法匯入 Big5 檔案。",
      "too_many_rows": "UTF-8 CSV，最多 2 MiB、5,000 資料列；訂單品項列會合併成訂單。",
      "required": "預覽前請對應所有必填欄位。",
      "invalid_request": "請檢查 CSV 格式、每列欄位數與欄位對應。",
      "invalid_external_id": "請使用來源顧客編號，不可填電子郵件或台灣手機號碼。",
      "name_too_long": "顧客姓名最多 80 個字。",
      "invalid_name": "請移除顧客姓名中的控制字元。",
      "invalid_phone": "請填台灣手機號碼：09 開頭，合計 10 碼。",
      "invalid_email": "請檢查電子郵件地址是否完整、格式正確。",
      "duplicate_external_id": "同一顧客編號重複出現，請只保留一列。",
      "erased": "曾要求刪除",
      "invalid_order_id": "請使用訂單編號，不可填電子郵件或台灣手機號碼。",
      "invalid_date": "請填有效訂單日期，例如 2026-03-05；未指定時區時採台北時間。",
      "invalid_amount": "訂單金額須為非負的新台幣整數，不能含非零小數。",
      "invalid_status": "訂單狀態最多 40 個字，不可含手機號碼或電子郵件。",
      "invalid_item": "請檢查品項名稱，不可使用手機號碼、電子郵件或控制字元。",
      "invalid_quantity": "品項數量須為 1 到 9,999 的整數。",
      "inconsistent_order": "同一訂單的顧客、日期、狀態與總金額須一致。",
      "customer_not_imported": "請先在這間店鋪完成顧客匯入，再匯入歷史訂單。",
      "order_owner_conflict": "這個訂單編號已連結其他顧客，請檢查原始檔案。",
      "order_limit": "每位顧客最多保留 2,000 筆歷史訂單。",
      "nothing_to_apply": "沒有可顯示的列。",
      "idempotency_conflict": "這份檔案已按另一組欄位設定匯入；若要修正，請先修改原檔案再上傳。",
      "retry_later": "目前無法匯入，請先確認登入狀態。",
      "unauthorized": "登入已結束，請重新登入。",
      "forbidden": "你沒有匯入權限。",
      "not_found": "這間店鋪或匯入批次無法使用。",
      "city_dropped": "未儲存城市"
    }
  },
  "zh-CN": {
    "title": "从 SHOPLINE 搬家",
    "subtitle": "先导入顾客，再导入仅供查看的历史订单。",
    "customerKind": "顾客",
    "ordersKind": "历史订单",
    "consentNotice": "营销同意不会导入，导入的顾客一律视为未同意。",
    "historyNotice": "历史订单仅供查看，不计入营收与报表。",
    "customerFirst": "请先在这间店铺完成顾客导入，再导入历史订单。",
    "uploadLabel": "选择 CSV 文件",
    "utf8Hint": "请另存为 CSV UTF-8，无法导入 Big5 文件。",
    "fileTooLarge": "请选择不超过 2 MiB 的文件。",
    "mapHeader": "CSV 列",
    "mapField": "顾客／订单字段",
    "unmapped": "不导入这列",
    "required": "必填",
    "guess": "自动猜测列",
    "preview": "预览导入",
    "commit": "确认导入",
    "back": "上一步",
    "restart": "重新开始",
    "loading": "正在加载…",
    "working": "正在导入…",
    "row": "行号",
    "outcome": "结果",
    "code": "原因",
    "newRows": "新增",
    "updateRows": "更新",
    "failedRows": "失败",
    "erasedRows": "曾要求删除",
    "consentIgnoredRows": "已忽略营销同意",
    "cityDroppedRows": "未保存城市",
    "empty": "没有可显示的行。",
    "confirmLabel": "请确认下方新增与更新数量。",
    "created": "已新增",
    "updated": "已更新",
    "failed": "失败",
    "replayed": "这份文件已导入，显示先前结果，不会重复创建数据。",
    "staleNotice": "预览已变更，请检查最新数量后再次确认。",
    "idempotencyConflict": "这份文件已按另一组列设置导入；若要修正，请先修改原文件再上传。",
    "unknownCommit": "导入结果尚未确认，可用下方按钮重试同一份导入；请勿更换文件或设置。",
    "signedOut": "登录已结束，请重新登录。",
    "forbidden": "你没有导入权限。",
    "notFound": "这间店铺或导入批次无法使用。",
    "unavailable": "当前无法导入，请先确认登录状态。",
    "noFile": "请先选择 CSV 文件。",
    "requiredMapping": "预览前请对应所有必填字段。",
    "failedDownload": "下载失败行号",
    "downloadStarted": "已开始下载失败行报告。",
    "downloadUnknown": "下载尚未确认，再试前请先检查下载记录。",
    "headersFailure": "无法读取表头，请检查 CSV 格式与 UTF-8 编码。",
    "limits": "UTF-8 CSV，最多 2 MiB、5,000 数据行；订单品项行会合并成订单。",
    "fileHash": "文件核对",
    "mappingSaved": "列映射会随本次导入发送。",
    "storageNotice": "文件仅保留在内存，不存入浏览器存储空间。",
    "onlyRowsHint": "仅显示行号与原因，不显示顾客数据或来源编号。",
    "stages": {
      "select": "选择类型",
      "upload": "上传",
      "mapping": "对应列",
      "preview": "预览",
      "confirm": "确认",
      "result": "结果"
    },
    "fieldLabels": {
      "external_id": "顾客来源编号",
      "name": "顾客姓名",
      "phone": "电话",
      "email": "电子邮件",
      "consent": "同意（忽略）",
      "order_id": "订单编号",
      "customer_id": "顾客来源编号",
      "ordered_at": "订单日期",
      "status": "订单状态",
      "total": "订单金额",
      "item_name": "品项名称",
      "item_qty": "数量",
      "city": "仅城市"
    },
    "outcomes": {
      "created": "已新增",
      "updated": "已更新",
      "failed": "失败"
    },
    "errors": {
      "encoding_not_utf8": "请另存为 CSV UTF-8，无法导入 Big5 文件。",
      "too_many_rows": "UTF-8 CSV，最多 2 MiB、5,000 数据行；订单品项行会合并成订单。",
      "required": "预览前请对应所有必填字段。",
      "invalid_request": "请检查 CSV 格式、每行列数与列映射。",
      "invalid_external_id": "请使用来源顾客编号，不可填电子邮件或台湾手机号。",
      "name_too_long": "顾客姓名最多 80 个字。",
      "invalid_name": "请移除顾客姓名中的控制字符。",
      "invalid_phone": "请填台湾手机号：09 开头，共 10 位。",
      "invalid_email": "请检查电子邮件地址是否完整、格式正确。",
      "duplicate_external_id": "同一顾客编号重复出现，请仅保留一行。",
      "erased": "曾要求删除",
      "invalid_order_id": "请使用订单编号，不可填电子邮件或台湾手机号。",
      "invalid_date": "请填有效订单日期，例如 2026-03-05；未指定时区时采用台北时间。",
      "invalid_amount": "订单金额须为非负的新台币整数，不能含非零小数。",
      "invalid_status": "订单状态最多 40 个字，不可含手机号或电子邮件。",
      "invalid_item": "请检查品项名称，不可使用手机号、电子邮件或控制字符。",
      "invalid_quantity": "品项数量须为 1 到 9,999 的整数。",
      "inconsistent_order": "同一订单的顾客、日期、状态与总金额须一致。",
      "customer_not_imported": "请先在这间店铺完成顾客导入，再导入历史订单。",
      "order_owner_conflict": "这个订单编号已关联其他顾客，请检查原文件。",
      "order_limit": "每位顾客最多保留 2,000 条历史订单。",
      "nothing_to_apply": "没有可显示的行。",
      "idempotency_conflict": "这份文件已按另一组列设置导入；若要修正，请先修改原文件再上传。",
      "retry_later": "当前无法导入，请先确认登录状态。",
      "unauthorized": "登录已结束，请重新登录。",
      "forbidden": "你没有导入权限。",
      "not_found": "这间店铺或导入批次无法使用。",
      "city_dropped": "未保存城市"
    }
  }
};
