// Purpose: W3-U2 operating copy in the three supported admin locales.
// Depends on: locale identifiers and frozen reminder/private-reply policy; no inferred buyer information.
// Used by: LiveSettings and BuyerPanel restriction controls.
const tw = {
  result: "本次請求",
  already: "已提醒",
  more: "還有待處理的買家，請稍後再次執行手動提醒。",
  replied: "沒貨已回覆",
  title: "直播設定",
  manual: "手動提醒未付款",
  soldout: "沒貨回覆",
  list: "限制名單",
  rule: "只有在 24 小時內傳過訊息給粉專的買家會收到提醒；其他買家會列在待跟進清單",
  quota: "會用掉這則留言唯一一次私訊回覆",
  choose: "選擇場次",
  chooseFirst: "請先選擇場次。",
  loading: "載入中…",
  empty: "目前沒有資料。",
  refresh: "重新載入",
  retry: "以相同請求重試",
  unknown: "結果尚未確認。請使用原請求重試，確認前不會建立另一筆操作。",
  queued: "已排隊",
  followup: "待跟進",
  restricted: "已限制",
  failed: "未送出",
  sent: "已送出",
  copy: "複製連結",
  copied: "已複製連結",
  copyFailed: "無法複製，請允許剪貼簿存取後重試。",
  trigger: "提醒未付款",
  saving: "處理中…",
  save: "儲存沒貨設定",
  enabled: "啟用沒貨回覆",
  template: "新範本內容",
  preview: "草稿預覽",
  product: "示例商品",
  placeholder: "抱歉，{{product.name}} 已售完。",
  currentTemplate: "目前範本",
  templateRequired: "首次儲存請輸入商家範本；系統預設內容不會被修改。",
  draftHint:
    "填寫新內容會先發布商家範本，再儲存設定；空白則保留目前的商家範本。",
  saved: "設定已儲存。",
  conflict: "設定已由其他人更新。請重新載入，確認新版本後再儲存。",
  invalid: "請檢查內容。範本限 280 字、單行，只可使用一次 {{product.name}}。",
  unavailable: "暫時無法載入，請重新載入。",
  denied: "登入已失效或權限已變更，請重新登入。",
  hidden: "頁面隱藏時已清除私人資料。",
  missing: "此店鋪無法使用這筆資料。",
  platform: "平台",
  note: "內部備註",
  source: "來源認領組合",
  added: "加入時間",
  remove: "移除",
  removeConfirm: "確定從限制名單移除？",
  cancel: "取消",
  next: "下一頁",
  previous: "上一頁",
  block: "加入限制名單",
  blocked: "已限制",
  blockHint: "限制後不再自動傳送認領連結；先前的連結仍有效。",
  noteLong: "備註最多 200 字，且不可包含控制字元。",
  noManage: "你沒有管理直播設定的權限。",
  noReply: "你沒有傳送提醒的權限。",
  noRead: "你沒有讀取此資料的權限。",
  window_closed: "買家需先回覆私訊",
  human_takeover: "目前由人工接管",
  no_peer: "尚未建立私訊對話",
  capability: "平台傳送資格不足",
  link_unavailable: "無法提供結帳連結",
  ambiguous_actor: "此對話包含多位買家，請改選認領組合。",
  limit_reached: "限制名單已達上限。",
  no_storefront: "請先設定並啟用商店網域。",
};
const cn: typeof tw = {
  result: "本次请求",
  already: "已提醒",
  more: "还有待处理的买家，请稍后再次执行手动提醒。",
  replied: "没货已回复",
  title: "直播设置",
  manual: "手动提醒未付款",
  soldout: "没货回复",
  list: "限制名单",
  rule: "只有在 24 小时内向主页发送过消息的买家会收到提醒；其他买家会列在待跟进名单",
  quota: "会用掉这条评论唯一一次私信回复",
  choose: "选择场次",
  chooseFirst: "请先选择场次。",
  loading: "加载中…",
  empty: "目前没有数据。",
  refresh: "重新加载",
  retry: "使用相同请求重试",
  unknown: "结果尚未确认。请使用原请求重试，确认前不会创建另一笔操作。",
  queued: "已排队",
  followup: "待跟进",
  restricted: "已限制",
  failed: "未发送",
  sent: "已发送",
  copy: "复制链接",
  copied: "已复制链接",
  copyFailed: "无法复制，请允许剪贴板访问后重试。",
  trigger: "提醒未付款",
  saving: "处理中…",
  save: "保存没货设置",
  enabled: "启用没货回复",
  template: "新模板内容",
  preview: "草稿预览",
  product: "示例商品",
  placeholder: "抱歉，{{product.name}} 已售完。",
  currentTemplate: "当前模板",
  templateRequired: "首次保存请输入商家模板；系统默认内容不会被修改。",
  draftHint: "填写新内容会先发布商家模板，再保存设置；留空则保留当前商家模板。",
  saved: "设置已保存。",
  conflict: "设置已被其他人更新。请重新加载，确认新版本后再保存。",
  invalid: "请检查内容。模板限 280 字、单行，只能使用一次 {{product.name}}。",
  unavailable: "暂时无法加载，请重新加载。",
  denied: "登录已失效或权限已变更，请重新登录。",
  hidden: "页面隐藏时已清除私人数据。",
  missing: "当前店铺无法使用这条数据。",
  platform: "平台",
  note: "内部备注",
  source: "来源认领组合",
  added: "加入时间",
  remove: "移除",
  removeConfirm: "确定从限制名单移除？",
  cancel: "取消",
  next: "下一页",
  previous: "上一页",
  block: "加入限制名单",
  blocked: "已限制",
  blockHint: "限制后不再自动发送认领链接；之前的链接仍有效。",
  noteLong: "备注最多 200 字，且不能包含控制字符。",
  noManage: "你没有管理直播设置的权限。",
  noReply: "你没有发送提醒的权限。",
  noRead: "你没有读取此数据的权限。",
  window_closed: "买家需先回复私信",
  human_takeover: "当前由人工接管",
  no_peer: "尚未建立私信对话",
  capability: "平台发送资格不足",
  link_unavailable: "无法提供结账链接",
  ambiguous_actor: "该对话包含多位买家，请改选认领组合。",
  limit_reached: "限制名单已达上限。",
  no_storefront: "请先设置并启用商店域名。",
};
const en: typeof tw = {
  result: "This request",
  already: "Already reminded",
  more: "More buyers remain. Run the manual reminder again later.",
  replied: "Sold-out reply sent",
  title: "Live settings",
  manual: "Remind unpaid buyers",
  soldout: "Sold-out reply",
  list: "Restricted buyers",
  rule: "Only buyers who messaged the Page within the last 24 hours receive a reminder; other buyers appear in the follow-up list.",
  quota: "This uses the comment’s only private reply.",
  choose: "Choose a session",
  chooseFirst: "Choose a session first.",
  loading: "Loading…",
  empty: "No records yet.",
  refresh: "Reload",
  retry: "Retry the same request",
  unknown:
    "The outcome is unknown. Retry the original request; another action is blocked until its outcome is known.",
  queued: "Queued",
  followup: "Follow-up",
  restricted: "Restricted",
  failed: "Not sent",
  sent: "Sent",
  copy: "Copy link",
  copied: "Link copied",
  copyFailed: "Could not copy. Allow clipboard access and try again.",
  trigger: "Remind unpaid buyers",
  saving: "Working…",
  save: "Save sold-out settings",
  enabled: "Enable sold-out replies",
  template: "New template content",
  preview: "Draft preview",
  product: "Example product",
  placeholder: "Sorry, {{product.name}} is sold out.",
  currentTemplate: "Current template",
  templateRequired:
    "Enter a merchant template for the first save. The system default stays unchanged.",
  draftHint:
    "New content is published as a merchant template before saving. Leave blank to keep the current merchant template.",
  saved: "Settings saved.",
  conflict:
    "Someone changed these settings. Reload and review the new version before saving.",
  invalid:
    "Check the content: one line, up to 280 characters, with {{product.name}} at most once.",
  unavailable: "Unable to load right now. Reload to try again.",
  denied: "Your session or permissions changed. Sign in again.",
  hidden: "Private data was cleared while the page was hidden.",
  missing: "This record is unavailable in this store.",
  platform: "Platform",
  note: "Internal note",
  source: "Source claim bundle",
  added: "Added",
  remove: "Remove",
  removeConfirm: "Remove this buyer from the restricted list?",
  cancel: "Cancel",
  next: "Next page",
  previous: "Previous page",
  block: "Restrict buyer",
  blocked: "Restricted",
  blockHint:
    "Future claim links will not be sent automatically. Previously issued links remain valid.",
  noteLong: "Notes allow up to 200 characters and no control characters.",
  noManage: "You cannot manage live settings.",
  noReply: "You cannot send reminders.",
  noRead: "You cannot read these records.",
  window_closed: "The buyer needs to reply first",
  human_takeover: "A person has taken over",
  no_peer: "No messaging conversation yet",
  capability: "Platform sending permission unavailable",
  link_unavailable: "Checkout link unavailable",
  ambiguous_actor:
    "This conversation has multiple buyers. Select a claim bundle instead.",
  limit_reached: "The restricted list is full.",
  no_storefront: "Set up and activate a storefront domain first.",
};
/** Resolve only supported admin locales; labels never interpolate server diagnostics. */
export const liveSettingsCopy = (locale: string) =>
  locale === "en" ? en : locale === "zh-CN" ? cn : tw;
/** Map safe error codes to actionable localized copy. */
export function liveSettingsError(locale: string, code: string) {
  const c = liveSettingsCopy(locale);
  if (["conflict", "version_conflict", "idempotency_conflict"].includes(code))
    return c.conflict;
  if (["invalid_request", "invalid_json", "template_fixed"].includes(code))
    return c.invalid;
  if (["unauthorized", "forbidden"].includes(code)) return c.denied;
  if (code === "not_found") return c.missing;
  return c[code as "ambiguous_actor"] ?? c.unavailable;
}
