// Copy for the merchant tools pages (zh-CN / zh-TW / en): the dashboard (/{locale}), the product CSV import (/{locale}/products/import) and
// the manual order (/{locale}/orders/new). BFF /api/stores/{store}/tools/* -> Go internal/httpapi/merchanttools.go (contract storefront-v2 G).
// Owns every string of Dashboard.tsx, ProductImport.tsx and ManualOrder.tsx and the error map for the codes Go answers on these routes.
// Non-goals: no rule (the server decides), no date or money formatting (components use Intl), no brand names beyond the payment/chain labels
// the existing pages already use. Depends on @live-commerce/i18n (Locale) only.
import type { Locale } from "@live-commerce/i18n";

const en = {
  navDashboard: "Dashboard",
  dashboard: {
    title: "Dashboard", subtitle: "What needs you today. Days are Taipei calendar days (UTC+8).", store: "Store",
    loading: "Loading the dashboard…", retry: "Try again", noStore: "No authorized store is available.",
    signedOut: "Sign in to see the dashboard.", forbidden: "This account cannot read orders, so the dashboard is hidden.",
    notFound: "The dashboard is unavailable for this store.", unavailable: "The dashboard is temporarily unavailable. Try again.",
    ordersTitle: "Orders", today: "Today", week: "Last 7 days", ordersNote: "Placed orders: waiting for payment, waiting for a transfer or confirmed.",
    gmvTitle: "Sales by payment method", card: "Card (captured)", bank: "Bank transfer (confirmed)", pickup: "Pay at pickup (collected)",
    sandbox: "Test environment", live: "Live", noSales: "No sales in the last 7 days.",
    todosTitle: "To do", transfer: "Transfers to confirm", ship: "Orders to ship", label: "Convenience-store labels to create",
    lowStock: "Low-stock variants (5 or fewer)", refunds: "Open refunds", nothing: "Nothing waiting",
    latestTitle: "Latest orders", noOrders: "No orders yet.", allOrders: "All orders", order: "Order", created: "Created (UTC)", total: "Total", status: "Status", mode: "Payment",
    actionsTitle: "Quick actions", createOrder: "Create an order", importProducts: "Import or export products", inventory: "Inventory",
    modes: { card: "Card", pay_at_pickup: "Pay at pickup", bank_transfer: "Bank transfer" } as Record<string, string>,
    states: { DRAFT: "Draft", AWAITING_PAYMENT: "Awaiting payment", AWAITING_TRANSFER: "Awaiting transfer", CONFIRMED: "Confirmed", CANCELLED: "Cancelled" } as Record<string, string>,
  },
  importer: {
    title: "Import and export products", subtitle: "Spreadsheet in, spreadsheet out. One row per variant; nothing is ever deleted.",
    store: "Store", noStore: "No authorized store is available.", back: "Back to dashboard",
    exportTitle: "Export", exportText: "Download every product and variant with price, stock per warehouse, collections and photo count.", exportButton: "Download CSV", exporting: "Preparing the file…",
    exportFailed: "The export could not be created. Try again.", exportTooLarge: "The catalog is too large to export in one file.",
    importTitle: "Import", importText: "Choose a CSV in the same columns. You see every problem before anything is saved; one problem blocks the whole file.",
    chooseFile: "CSV file", preview: "Check the file", previewing: "Checking…", commit: "Import this file", committing: "Importing…",
    rules: [
      "Products are matched by handle, variants by SKU. New products start as drafts.",
      "Stock cells set the on-hand quantity of that warehouse; an empty cell leaves it alone.",
      "Photos are not imported. Prices are in the store currency, for example 12.50.",
      "Cells that start with = + - or @ are exported with a leading apostrophe; import removes it.",
    ],
    limits: "Up to 2 MiB and 1,500 rows. A file that would change too much at once (for example many new products with stock in several warehouses) is refused: split it.", notCsv: "Choose a .csv file.", empty: "The file is empty.", tooLarge: "The file is larger than 2 MiB.",
    summary: "Result", rows: "Rows", createdProducts: "New products", updatedProducts: "Updated products", createdSkus: "New variants", updatedSkus: "Updated variants",
    stock: "Stock changes", unchanged: "Unchanged rows", previewOK: "The file is valid. Nothing was saved yet.", committed: "Imported. The catalog now matches the file.",
    replayed: "This exact file was already imported. Nothing changed.", problems: "Problems", row: "Row", column: "Column", problem: "Problem", truncated: "Only the first 200 problems are shown.",
    fileLevel: "Whole file", fix: "Fix these rows in your spreadsheet and check the file again.", failed: "The request failed. Nothing was saved. Try again.",
    signedOut: "Sign in to import products.", forbidden: "This account cannot change products or stock.",
    codes: {
      required: "A required value is missing", too_long: "The value is too long", invalid_value: "The value is not valid", duplicate_sku: "This SKU appears twice in the file",
      conflict_product_field: "Differs from the first row of this product", slug_taken: "This handle is already used", sku_in_other_product: "This SKU belongs to another product",
      sku_archived: "This SKU is archived", option_mismatch: "Options do not match the variants already in the store", unknown_warehouse: "No warehouse has this name",
      unknown_collection: "No collection has this handle", limit: "The file is too large for one import: split it into smaller files", conflict: "Conflicts with the current catalog or stock",
    } as Record<string, string>,
  },
  manual: {
    title: "Create an order", subtitle: "For orders taken in chat, by phone or in person. Prices come from your catalog; stock is held like a normal order.",
    store: "Store", noStore: "No authorized store is available.", loading: "Loading delivery choices…", back: "Back to orders",
    signedOut: "Sign in to create orders.", forbidden: "This account cannot create orders (it needs stock-reserve permission).", unavailable: "Creating orders is not available right now.",
    notConfigured: "Creating orders from the admin is not turned on for this deployment.",
    itemsTitle: "Items", search: "Search products or SKU", searchButton: "Search", noResults: "No products found.", add: "Add", remove: "Remove", quantity: "Quantity",
    available: "Available", noLines: "Add at least one item.", variant: "Variant", price: "Price", draftProduct: "Draft",
    customerTitle: "Customer", name: "Name", phone: "Phone", email: "Email (optional, for notifications)",
    deliveryTitle: "Delivery", delivery: "Delivery method", choose: "Choose…", region: "Region", city: "City or district", postal: "Postal code", line1: "Address", line2: "Address line 2 (optional)",
    storeCode: "Store number", storeName: "Store name", storeAddress: "Store address", cvsHint: "Enter the store the customer chose.",
    mapOnly: "This service needs the store to be chosen from the map by the customer, so it is not available here.",
    paymentTitle: "Payment", bank: "Bank transfer (the customer transfers within the window)", pickup: "Pay at pickup", noCard: "Card payment is not available for orders created here.",
    submit: "Create order", submitting: "Creating…", retrySame: "The result is unknown. Send the same request again to find out.", retryButton: "Check again",
    created: "Order created", orderId: "Order", total: "Total", state: "Status", waiting: "Waiting for the bank transfer", confirmed: "Confirmed", expires: "Hold ends",
    linkTitle: "Customer link", linkText: "Paste this link to the customer in LINE or Messenger. It opens their order; keep it private.", copy: "Copy link", copied: "Copied",
    noLink: "No storefront address is published yet, so there is no link to send.", another: "Create another order", viewOrders: "View orders",
    problems: { lines: "Add items and check the quantities.", name: "Enter the customer name.", phone: "Enter a valid phone number.", email: "The email address is not valid.", delivery: "Choose a delivery method.",
      mode: "Choose a payment method this delivery supports.", address: "Enter the city and the address.", store: "Enter the store number, name and address." } as Record<string, string>,
    errors: {
      invalid_request: "Some details are not valid. Check the form.", conflict: "The catalog or stock changed. Refresh and try again.", insufficient_inventory: "Not enough stock for one of the items.",
      idempotency_conflict: "This attempt was already used with different details. Start again.", bank_transfer_unavailable: "Bank transfer is not turned on for this delivery.",
      pay_at_pickup_unavailable: "Pay at pickup is not available for this order.", pay_at_pickup_amount_exceeds: "Pay at pickup needs a whole-dollar total within the store's limit.", cvs_entry_unavailable: "This service needs the store to be chosen from the map.",
      forbidden: "This account cannot create orders.", unauthorized: "Sign in again.", not_found: "This store is unavailable.", manual_order_unavailable: "Creating orders is not available right now.",
      retry_later: "Temporarily unavailable. Try again.", default: "The order could not be created. Try again.",
    } as Record<string, string>,
    kinds: { home: "Home delivery", cvs_711: "7-ELEVEN pickup", cvs_familymart: "FamilyMart pickup", cvs_hilife: "Hi-Life pickup", cvs_okmart: "OK mart pickup" } as Record<string, string>,
  },
};
export type MerchantToolsCopy = typeof en;

const zhTW: MerchantToolsCopy = {
  navDashboard: "總覽",
  dashboard: {
    title: "總覽", subtitle: "今天需要你處理的事。日期以台北時間（UTC+8）計算。", store: "商店",
    loading: "正在載入總覽…", retry: "重試", noStore: "沒有可用的授權商店。",
    signedOut: "請先登入再查看總覽。", forbidden: "此帳號無法讀取訂單，因此看不到總覽。",
    notFound: "此商店無法顯示總覽。", unavailable: "總覽暫時無法使用，請重試。",
    ordersTitle: "訂單", today: "今天", week: "近 7 天", ordersNote: "已成立的訂單：待付款、待轉帳確認或已確認。",
    gmvTitle: "各付款方式的銷售額", card: "信用卡（已請款）", bank: "銀行轉帳（已確認）", pickup: "取貨付款（已收款）",
    sandbox: "測試環境", live: "正式", noSales: "近 7 天沒有銷售。",
    todosTitle: "待辦事項", transfer: "待確認的轉帳", ship: "待出貨訂單", label: "待建立的超商托運單",
    lowStock: "低庫存規格（5 件以下）", refunds: "處理中的退款", nothing: "沒有待辦",
    latestTitle: "最新訂單", noOrders: "還沒有訂單。", allOrders: "全部訂單", order: "訂單", created: "建立時間（UTC）", total: "金額", status: "狀態", mode: "付款方式",
    actionsTitle: "快速操作", createOrder: "建立訂單", importProducts: "匯入或匯出商品", inventory: "庫存",
    modes: { card: "信用卡", pay_at_pickup: "取貨付款", bank_transfer: "銀行轉帳" },
    states: { DRAFT: "草稿", AWAITING_PAYMENT: "待付款", AWAITING_TRANSFER: "待轉帳", CONFIRMED: "已確認", CANCELLED: "已取消" },
  },
  importer: {
    title: "匯入與匯出商品", subtitle: "試算表進、試算表出。每個規格一列；絕不會刪除任何資料。",
    store: "商店", noStore: "沒有可用的授權商店。", back: "回到總覽",
    exportTitle: "匯出", exportText: "下載所有商品與規格，含價格、各倉庫庫存、分類與圖片數量。", exportButton: "下載 CSV", exporting: "正在產生檔案…",
    exportFailed: "無法建立匯出檔，請重試。", exportTooLarge: "商品數量過多，無法匯出成單一檔案。",
    importTitle: "匯入", importText: "選擇相同欄位的 CSV。儲存之前會列出所有問題；只要有一個問題，整份檔案都不會匯入。",
    chooseFile: "CSV 檔案", preview: "檢查檔案", previewing: "檢查中…", commit: "匯入此檔案", committing: "匯入中…",
    rules: [
      "商品以 handle 對應，規格以 SKU 對應。新商品預設為草稿。",
      "庫存欄位會把該倉庫的現有數量設為此值；空白則不變。",
      "不會匯入圖片。價格使用商店幣別，例如 12.50。",
      "以 = + - 或 @ 開頭的儲存格匯出時會加上單引號，匯入時會移除。",
    ],
    limits: "最大 2 MiB、1,500 列。一次變更太多內容的檔案（例如許多含多個倉庫庫存的新商品）會被拒絕，請拆分。", notCsv: "請選擇 .csv 檔案。", empty: "檔案是空的。", tooLarge: "檔案超過 2 MiB。",
    summary: "結果", rows: "列數", createdProducts: "新增商品", updatedProducts: "更新商品", createdSkus: "新增規格", updatedSkus: "更新規格",
    stock: "庫存異動", unchanged: "未變更的列", previewOK: "檔案沒有問題，尚未儲存任何內容。", committed: "已匯入，商品目錄與檔案一致。",
    replayed: "這個檔案先前已匯入過，沒有任何變更。", problems: "問題", row: "列", column: "欄位", problem: "問題", truncated: "僅顯示前 200 個問題。",
    fileLevel: "整份檔案", fix: "請在試算表中修正這些列，然後再次檢查檔案。", failed: "請求失敗，沒有儲存任何內容，請重試。",
    signedOut: "請先登入再匯入商品。", forbidden: "此帳號無法修改商品或庫存。",
    codes: {
      required: "缺少必要的值", too_long: "內容太長", invalid_value: "值不正確", duplicate_sku: "此 SKU 在檔案中出現兩次", conflict_product_field: "與此商品第一列不一致",
      slug_taken: "此 handle 已被使用", sku_in_other_product: "此 SKU 屬於其他商品", sku_archived: "此 SKU 已封存", option_mismatch: "選項與商店中既有規格不符",
      unknown_warehouse: "找不到此名稱的倉庫", unknown_collection: "找不到此 handle 的分類", limit: "檔案太大，無法一次匯入，請拆成較小的檔案", conflict: "與目前的商品目錄或庫存衝突",
    },
  },
  manual: {
    title: "建立訂單", subtitle: "用於聊天、電話或現場接到的訂單。價格來自商品目錄；庫存與一般訂單一樣會被保留。",
    store: "商店", noStore: "沒有可用的授權商店。", loading: "正在載入配送選項…", back: "回到訂單",
    signedOut: "請先登入再建立訂單。", forbidden: "此帳號無法建立訂單（需要保留庫存的權限）。", unavailable: "目前無法建立訂單。",
    notConfigured: "此部署尚未開啟從後台建立訂單。",
    itemsTitle: "商品", search: "搜尋商品或 SKU", searchButton: "搜尋", noResults: "找不到商品。", add: "加入", remove: "移除", quantity: "數量",
    available: "可售", noLines: "請至少加入一項商品。", variant: "規格", price: "價格", draftProduct: "草稿",
    customerTitle: "顧客", name: "姓名", phone: "電話", email: "電子郵件（選填，用於通知）",
    deliveryTitle: "配送", delivery: "配送方式", choose: "請選擇…", region: "縣市", city: "鄉鎮市區", postal: "郵遞區號", line1: "地址", line2: "地址第二行（選填）",
    storeCode: "門市店號", storeName: "門市名稱", storeAddress: "門市地址", cvsHint: "請輸入顧客選擇的門市。",
    mapOnly: "此服務必須由顧客從地圖選擇門市，因此無法在此建立。",
    paymentTitle: "付款", bank: "銀行轉帳（顧客須在期限內轉帳）", pickup: "取貨付款", noCard: "在此建立的訂單無法使用信用卡付款。",
    submit: "建立訂單", submitting: "建立中…", retrySame: "結果未知。請用相同的內容再送一次來確認。", retryButton: "再次確認",
    created: "訂單已建立", orderId: "訂單", total: "金額", state: "狀態", waiting: "等待銀行轉帳", confirmed: "已確認", expires: "保留期限",
    linkTitle: "顧客連結", linkText: "把此連結用 LINE 或 Messenger 傳給顧客，即可開啟他的訂單。請勿公開。", copy: "複製連結", copied: "已複製",
    noLink: "尚未發布商店網址，因此沒有可傳送的連結。", another: "再建立一筆訂單", viewOrders: "查看訂單",
    problems: { lines: "請加入商品並檢查數量。", name: "請輸入顧客姓名。", phone: "請輸入有效的電話號碼。", email: "電子郵件格式不正確。", delivery: "請選擇配送方式。",
      mode: "請選擇此配送方式支援的付款方式。", address: "請輸入縣市與地址。", store: "請輸入門市店號、名稱與地址。" },
    errors: {
      invalid_request: "有些資料不正確，請檢查表單。", conflict: "商品目錄或庫存已變動，請重新整理後再試。", insufficient_inventory: "其中一項商品庫存不足。",
      idempotency_conflict: "這次嘗試已用不同內容送出過，請重新開始。", bank_transfer_unavailable: "此配送方式未開啟銀行轉帳。",
      pay_at_pickup_unavailable: "此訂單無法使用取貨付款。", pay_at_pickup_amount_exceeds: "取貨付款的總額須為整數元，且不得超過商店設定的上限。", cvs_entry_unavailable: "此服務必須從地圖選擇門市。",
      forbidden: "此帳號無法建立訂單。", unauthorized: "請重新登入。", not_found: "此商店無法使用。", manual_order_unavailable: "目前無法建立訂單。",
      retry_later: "暫時無法使用，請重試。", default: "無法建立訂單，請重試。",
    },
    kinds: { home: "宅配", cvs_711: "7-ELEVEN 取貨", cvs_familymart: "全家取貨", cvs_hilife: "萊爾富取貨", cvs_okmart: "OK 超商取貨" },
  },
};

const zhCN: MerchantToolsCopy = {
  navDashboard: "总览",
  dashboard: {
    title: "总览", subtitle: "今天需要你处理的事。日期按台北时间（UTC+8）计算。", store: "店铺",
    loading: "正在加载总览…", retry: "重试", noStore: "没有可用的授权店铺。",
    signedOut: "请先登录再查看总览。", forbidden: "此账号无法读取订单，因此看不到总览。",
    notFound: "此店铺无法显示总览。", unavailable: "总览暂时无法使用，请重试。",
    ordersTitle: "订单", today: "今天", week: "近 7 天", ordersNote: "已成立的订单：待付款、待转账确认或已确认。",
    gmvTitle: "各付款方式的销售额", card: "信用卡（已扣款）", bank: "银行转账（已确认）", pickup: "取货付款（已收款）",
    sandbox: "测试环境", live: "正式", noSales: "近 7 天没有销售。",
    todosTitle: "待办事项", transfer: "待确认的转账", ship: "待发货订单", label: "待创建的便利店运单",
    lowStock: "低库存规格（5 件以下）", refunds: "处理中的退款", nothing: "没有待办",
    latestTitle: "最新订单", noOrders: "还没有订单。", allOrders: "全部订单", order: "订单", created: "创建时间（UTC）", total: "金额", status: "状态", mode: "付款方式",
    actionsTitle: "快速操作", createOrder: "创建订单", importProducts: "导入或导出商品", inventory: "库存",
    modes: { card: "信用卡", pay_at_pickup: "取货付款", bank_transfer: "银行转账" },
    states: { DRAFT: "草稿", AWAITING_PAYMENT: "待付款", AWAITING_TRANSFER: "待转账", CONFIRMED: "已确认", CANCELLED: "已取消" },
  },
  importer: {
    title: "导入与导出商品", subtitle: "表格进、表格出。每个规格一行；绝不会删除任何数据。",
    store: "店铺", noStore: "没有可用的授权店铺。", back: "回到总览",
    exportTitle: "导出", exportText: "下载所有商品与规格，含价格、各仓库库存、分类与图片数量。", exportButton: "下载 CSV", exporting: "正在生成文件…",
    exportFailed: "无法生成导出文件，请重试。", exportTooLarge: "商品数量过多，无法导出为单个文件。",
    importTitle: "导入", importText: "选择相同列的 CSV。保存之前会列出所有问题；只要有一个问题，整份文件都不会导入。",
    chooseFile: "CSV 文件", preview: "检查文件", previewing: "检查中…", commit: "导入此文件", committing: "导入中…",
    rules: [
      "商品按 handle 对应，规格按 SKU 对应。新商品默认为草稿。",
      "库存列会把该仓库的现有数量设为此值；留空则不变。",
      "不会导入图片。价格使用店铺币种，例如 12.50。",
      "以 = + - 或 @ 开头的单元格导出时会加上单引号，导入时会去掉。",
    ],
    limits: "最大 2 MiB、1,500 行。一次变更太多内容的文件（例如许多含多个仓库库存的新商品）会被拒绝，请拆分。", notCsv: "请选择 .csv 文件。", empty: "文件是空的。", tooLarge: "文件超过 2 MiB。",
    summary: "结果", rows: "行数", createdProducts: "新增商品", updatedProducts: "更新商品", createdSkus: "新增规格", updatedSkus: "更新规格",
    stock: "库存变动", unchanged: "未变更的行", previewOK: "文件没有问题，尚未保存任何内容。", committed: "已导入，商品目录与文件一致。",
    replayed: "这个文件此前已导入过，没有任何变更。", problems: "问题", row: "行", column: "列", problem: "问题", truncated: "仅显示前 200 个问题。",
    fileLevel: "整份文件", fix: "请在表格中修正这些行，然后再次检查文件。", failed: "请求失败，没有保存任何内容，请重试。",
    signedOut: "请先登录再导入商品。", forbidden: "此账号无法修改商品或库存。",
    codes: {
      required: "缺少必要的值", too_long: "内容太长", invalid_value: "值不正确", duplicate_sku: "此 SKU 在文件中出现两次", conflict_product_field: "与此商品第一行不一致",
      slug_taken: "此 handle 已被使用", sku_in_other_product: "此 SKU 属于其他商品", sku_archived: "此 SKU 已归档", option_mismatch: "选项与店铺中已有规格不符",
      unknown_warehouse: "找不到此名称的仓库", unknown_collection: "找不到此 handle 的分类", limit: "文件太大，无法一次导入，请拆成较小的文件", conflict: "与当前商品目录或库存冲突",
    },
  },
  manual: {
    title: "创建订单", subtitle: "用于聊天、电话或现场接到的订单。价格来自商品目录；库存与普通订单一样会被保留。",
    store: "店铺", noStore: "没有可用的授权店铺。", loading: "正在加载配送选项…", back: "回到订单",
    signedOut: "请先登录再创建订单。", forbidden: "此账号无法创建订单（需要保留库存的权限）。", unavailable: "目前无法创建订单。",
    notConfigured: "此部署尚未开启从后台创建订单。",
    itemsTitle: "商品", search: "搜索商品或 SKU", searchButton: "搜索", noResults: "找不到商品。", add: "加入", remove: "移除", quantity: "数量",
    available: "可售", noLines: "请至少加入一项商品。", variant: "规格", price: "价格", draftProduct: "草稿",
    customerTitle: "顾客", name: "姓名", phone: "电话", email: "电子邮件（选填，用于通知）",
    deliveryTitle: "配送", delivery: "配送方式", choose: "请选择…", region: "省市", city: "城市或区", postal: "邮政编码", line1: "地址", line2: "地址第二行（选填）",
    storeCode: "门店店号", storeName: "门店名称", storeAddress: "门店地址", cvsHint: "请输入顾客选择的门店。",
    mapOnly: "此服务必须由顾客从地图选择门店，因此无法在此创建。",
    paymentTitle: "付款", bank: "银行转账（顾客须在期限内转账）", pickup: "取货付款", noCard: "在此创建的订单无法使用信用卡付款。",
    submit: "创建订单", submitting: "创建中…", retrySame: "结果未知。请用相同的内容再发一次来确认。", retryButton: "再次确认",
    created: "订单已创建", orderId: "订单", total: "金额", state: "状态", waiting: "等待银行转账", confirmed: "已确认", expires: "保留期限",
    linkTitle: "顾客链接", linkText: "把此链接用 LINE 或 Messenger 发给顾客，即可打开他的订单。请勿公开。", copy: "复制链接", copied: "已复制",
    noLink: "尚未发布店铺网址，因此没有可发送的链接。", another: "再创建一笔订单", viewOrders: "查看订单",
    problems: { lines: "请加入商品并检查数量。", name: "请输入顾客姓名。", phone: "请输入有效的电话号码。", email: "电子邮件格式不正确。", delivery: "请选择配送方式。",
      mode: "请选择此配送方式支持的付款方式。", address: "请输入城市与地址。", store: "请输入门店店号、名称与地址。" },
    errors: {
      invalid_request: "有些资料不正确，请检查表单。", conflict: "商品目录或库存已变动，请刷新后再试。", insufficient_inventory: "其中一项商品库存不足。",
      idempotency_conflict: "这次尝试已用不同内容提交过，请重新开始。", bank_transfer_unavailable: "此配送方式未开启银行转账。",
      pay_at_pickup_unavailable: "此订单无法使用取货付款。", pay_at_pickup_amount_exceeds: "取货付款的总额须为整数元，且不得超过店铺设置的上限。", cvs_entry_unavailable: "此服务必须从地图选择门店。",
      forbidden: "此账号无法创建订单。", unauthorized: "请重新登录。", not_found: "此店铺无法使用。", manual_order_unavailable: "目前无法创建订单。",
      retry_later: "暂时无法使用，请重试。", default: "无法创建订单，请重试。",
    },
    kinds: { home: "快递到家", cvs_711: "7-ELEVEN 取货", cvs_familymart: "全家取货", cvs_hilife: "莱尔富取货", cvs_okmart: "OK 便利店取货" },
  },
};

export const toolsCopy: Record<Locale, MerchantToolsCopy> = { en, "zh-TW": zhTW, "zh-CN": zhCN };
