// Copy (zh-CN / zh-TW / en) for the Settings "Facebook Page / Instagram" card (components/MetaConnect.tsx) and the Studio claims
// source picker link (components/StudioClaims.tsx). Error codes are the Go route's frozen codes (internal/metaconnect/errors.go) and
// the BFF callback's fixed `meta_error` values; unknown codes fall back to `unavailable`. Permission and Page-task names are Meta's
// own identifiers and are shown verbatim so the merchant can find them in the Facebook dialog.
import type { Locale } from "@live-commerce/i18n";

const en = {
  title: "Facebook Page / Instagram",
  intro: "Connect your own Facebook Page (and its Instagram account) so live-stream comments reach your claim board and buyers get the claim link by private reply. You sign in to Facebook yourself; we never see your password.",
  loading: "Loading…", retry: "Try again", unavailable: "This section could not be loaded. Try again.",
  notConnected: "No Page is connected yet.", connect: "Connect Facebook Page", connecting: "Opening Facebook…",
  reconnect: "Reconnect", disconnect: "Disconnect", confirmDisconnect: "Disconnect this Page? Comments stop reaching your claim board and the stored access token is destroyed right away.",
  confirm: "Confirm", cancel: "Cancel", saving: "Saving…",
  page: "Facebook Page", instagram: "Instagram account", noInstagram: "None linked", permissions: "Permissions granted",
  token: "Access", tokenActive: "Active", tokenReauth: "Expired or revoked: reconnect to keep receiving comments",
  lastEvent: "Last comment received", never: "Nothing received yet", connectedAt: "Connected", routeUntil: "Valid until",
  renewSoon: "This connection expires soon: reconnect to renew it.",
  pickTitle: "Choose the Page to connect", pickIntro: "Pick the Page this store sells through. One Page belongs to one store.",
  pickMissing: "Cannot connect yet. Connect again and tick every permission and Page access in the Facebook dialog:",
  withInstagram: "Also connect Instagram", instagramMissing: "Instagram cannot be connected yet. Connect again and allow:",
  pickSubmit: "Connect this Page", pickCancel: "Start over", noPages: "Facebook returned no Page for this account. Make sure you manage a Page and tick it in the dialog.",
  task_messaging: "Page access: Messaging", task_moderate: "Page access: Moderate comments",
  connectedNotice: "Connected. Comments on this Page now reach your claim board.", disconnectedNotice: "Disconnected.",
  uncertain: "The result is not known yet. The card was reloaded; check the status above.",
  studioNone: "No Facebook Page is connected to this store yet.", studioLink: "Connect a Page in Settings",
  errors: {
    state_mismatch: "This connection attempt does not belong to this browser or was already used. Start again.",
    state_expired: "The connection attempt expired (10 minutes). Start again.",
    state_used: "That connection attempt was already completed.",
    meta_connect_failed: "Facebook did not complete the connection. Try again; nothing was connected.",
    denied: "Facebook sign-in was cancelled. Nothing was connected.",
    invalid_request: "The return from Facebook was not valid. Start again.",
    missing_permission: "A required permission or Page access is missing. Connect again and allow everything the dialog asks for.",
    not_in_pick_list: "That Page is not in the list. Start again.",
    page_taken: "This Page is already connected to another store.",
    already_connected: "This store already has a Page connected. Disconnect it first.",
    binding_disabled: "The Page binding changed while connecting. Try again.",
    conflict: "Something changed while connecting. Try again.",
    forbidden: "This account does not have permission to connect a Page.",
    not_found: "There is nothing to disconnect.",
    unauthorized: "Your session ended. Sign in again.",
    unavailable: "The change could not be completed. Try again.",
  } as Record<string, string>,
};
export type MetaConnectCopy = typeof en;

const zhTW: MetaConnectCopy = {
  title: "Facebook 主頁 / Instagram",
  intro: "連接你自己的 Facebook 主頁（及其 Instagram 帳號），直播留言才會進入認領看板，買家也會收到私訊認領連結。登入由你自己在 Facebook 完成，我們不會看到你的密碼。",
  loading: "載入中…", retry: "重試", unavailable: "無法載入此區塊，請重試。",
  notConnected: "尚未連接任何主頁。", connect: "連接 Facebook 主頁", connecting: "正在開啟 Facebook…",
  reconnect: "重新連接", disconnect: "中斷連接", confirmDisconnect: "確定中斷這個主頁？留言將不再進入認領看板，已儲存的存取權杖會立即銷毀。",
  confirm: "確認", cancel: "取消", saving: "儲存中…",
  page: "Facebook 主頁", instagram: "Instagram 帳號", noInstagram: "未連結", permissions: "已授權的權限",
  token: "存取狀態", tokenActive: "正常", tokenReauth: "已過期或被撤銷：請重新連接才能繼續接收留言",
  lastEvent: "最近收到留言", never: "尚未收到", connectedAt: "連接時間", routeUntil: "有效至",
  renewSoon: "此連接即將到期，請重新連接以續期。",
  pickTitle: "選擇要連接的主頁", pickIntro: "選擇這間店鋪銷售所用的主頁。一個主頁只能屬於一間店鋪。",
  pickMissing: "暫時無法連接。請重新連接，並在 Facebook 對話框勾選所有權限與主頁存取：",
  withInstagram: "同時連接 Instagram", instagramMissing: "暫時無法連接 Instagram。請重新連接並允許：",
  pickSubmit: "連接此主頁", pickCancel: "重新開始", noPages: "Facebook 沒有回傳任何主頁。請確認你管理一個主頁，並在對話框中勾選它。",
  task_messaging: "主頁存取：訊息", task_moderate: "主頁存取：管理留言",
  connectedNotice: "已連接。此主頁的留言現在會進入你的認領看板。", disconnectedNotice: "已中斷連接。",
  uncertain: "結果尚不確定。已重新載入，請查看上方狀態。",
  studioNone: "這間店鋪尚未連接任何 Facebook 主頁。", studioLink: "前往設定連接主頁",
  errors: {
    state_mismatch: "此連接嘗試不屬於這個瀏覽器或已被使用，請重新開始。",
    state_expired: "連接嘗試已逾時（10 分鐘），請重新開始。",
    state_used: "該連接嘗試已經完成。",
    meta_connect_failed: "Facebook 未能完成連接，請重試；沒有任何東西被連接。",
    denied: "已取消 Facebook 登入，沒有連接任何東西。",
    invalid_request: "從 Facebook 返回的內容無效，請重新開始。",
    missing_permission: "缺少必要權限或主頁存取。請重新連接並允許對話框要求的全部項目。",
    not_in_pick_list: "清單中沒有該主頁，請重新開始。",
    page_taken: "此主頁已連接到另一間店鋪。",
    already_connected: "這間店鋪已連接了一個主頁，請先中斷連接。",
    binding_disabled: "連接過程中主頁綁定發生變更，請重試。",
    conflict: "連接過程中內容有變更，請重試。",
    forbidden: "此帳號沒有連接主頁的權限。",
    not_found: "沒有可中斷的連接。",
    unauthorized: "登入已失效，請重新登入。",
    unavailable: "無法完成變更，請重試。",
  },
};

const zhCN: MetaConnectCopy = {
  title: "Facebook 主页 / Instagram",
  intro: "连接你自己的 Facebook 主页（及其 Instagram 账号），直播留言才会进入认领看板，买家也会收到私信认领链接。登录由你自己在 Facebook 完成，我们不会看到你的密码。",
  loading: "加载中…", retry: "重试", unavailable: "无法加载此部分，请重试。",
  notConnected: "尚未连接任何主页。", connect: "连接 Facebook 主页", connecting: "正在打开 Facebook…",
  reconnect: "重新连接", disconnect: "断开连接", confirmDisconnect: "确定断开这个主页？留言将不再进入认领看板，已保存的访问令牌会立即销毁。",
  confirm: "确认", cancel: "取消", saving: "保存中…",
  page: "Facebook 主页", instagram: "Instagram 账号", noInstagram: "未关联", permissions: "已授权的权限",
  token: "访问状态", tokenActive: "正常", tokenReauth: "已过期或被撤销：请重新连接才能继续接收留言",
  lastEvent: "最近收到留言", never: "尚未收到", connectedAt: "连接时间", routeUntil: "有效至",
  renewSoon: "此连接即将到期，请重新连接以续期。",
  pickTitle: "选择要连接的主页", pickIntro: "选择这家店铺销售所用的主页。一个主页只能属于一家店铺。",
  pickMissing: "暂时无法连接。请重新连接，并在 Facebook 对话框勾选所有权限与主页访问：",
  withInstagram: "同时连接 Instagram", instagramMissing: "暂时无法连接 Instagram。请重新连接并允许：",
  pickSubmit: "连接此主页", pickCancel: "重新开始", noPages: "Facebook 没有返回任何主页。请确认你管理一个主页，并在对话框中勾选它。",
  task_messaging: "主页访问：消息", task_moderate: "主页访问：管理留言",
  connectedNotice: "已连接。此主页的留言现在会进入你的认领看板。", disconnectedNotice: "已断开连接。",
  uncertain: "结果尚不确定。已重新加载，请查看上方状态。",
  studioNone: "这家店铺尚未连接任何 Facebook 主页。", studioLink: "前往设置连接主页",
  errors: {
    state_mismatch: "此连接尝试不属于这个浏览器或已被使用，请重新开始。",
    state_expired: "连接尝试已超时（10 分钟），请重新开始。",
    state_used: "该连接尝试已经完成。",
    meta_connect_failed: "Facebook 未能完成连接，请重试；没有任何东西被连接。",
    denied: "已取消 Facebook 登录，没有连接任何东西。",
    invalid_request: "从 Facebook 返回的内容无效，请重新开始。",
    missing_permission: "缺少必要权限或主页访问。请重新连接并允许对话框要求的全部项目。",
    not_in_pick_list: "列表中没有该主页，请重新开始。",
    page_taken: "此主页已连接到另一家店铺。",
    already_connected: "这家店铺已连接了一个主页，请先断开连接。",
    binding_disabled: "连接过程中主页绑定发生变更，请重试。",
    conflict: "连接过程中内容有变更，请重试。",
    forbidden: "此账号没有连接主页的权限。",
    not_found: "没有可断开的连接。",
    unauthorized: "登录已失效，请重新登录。",
    unavailable: "无法完成变更，请重试。",
  },
};

export const metaConnectCopy: Record<Locale, MetaConnectCopy> = { en, "zh-TW": zhTW, "zh-CN": zhCN };
