// Purpose: keep operation states, refusals and actions readable in all three locales.
// Depends on: @live-commerce/i18n locale type; W6-05B machine codes.
// Used by: OperationsLedger and locale parity gates.
import type { Locale } from "@live-commerce/i18n";
const en = {
  title: "Operations ledger",
  subtitle:
    "Review failed or uncertain external operations. Actions depend on the server's current decision.",
  settings: "Store settings",
  ads: "Ad settings",
  filter: "State",
  refresh: "Refresh",
  next: "Next page",
  empty: "No operations in this view.",
  loading: "Loading operations…",
  unavailable: "Operations could not be loaded. Refresh to try again.",
  forbidden: "You do not have permission to read these operations.",
  signedOut: "Your session ended. Sign in again.",
  noStore: "No store is available.",
  detail: "Operation details",
  open: "View details",
  close: "Close",
  query: "Query",
  cancel: "Cancel operation",
  retry: "Authorize retry",
  confirm: "Confirm action",
  dismiss: "Back",
  object: "Business object",
  events: "Recent events",
  attempts: "Attempts",
  created: "Created",
  updated: "Updated",
  reason: "Reason",
  state: "State",
  action: "Action",
  provider: "Provider",
  unknown: "The result is unknown. Query before retrying.",
  confirmHint:
    "The server will check the current operation and permissions again. Cancellation only cancels a READY local operation; it does not reverse an external action.",
  saved: "Request accepted. Check the refreshed server state below.",
  uncertain:
    "The request result is uncertain. Refresh first; repeat only the same request if necessary.",
  retryRequest: "Repeat same request",
  waiting: "Query limit reached. Retry after (seconds)",
  generic: "The operation is currently unavailable. Refresh its details.",
  states: {
    attention: "Needs attention",
    FAILED: "Failed",
    FAILED_FINAL: "Failed",
    UNKNOWN: "Unknown",
    ACKNOWLEDGED: "Acknowledged",
    BLOCKED_POLICY: "Blocked by policy",
    STALE_BINDING: "Binding changed",
    READY: "Ready",
    DISPATCHING: "Dispatching",
    SUCCEEDED: "Succeeded",
    CANCELLED: "Cancelled",
  },
  reasons: {
    protective_operation:
      "This is a protective operation (such as pausing an ad) and cannot be cancelled.",
    reconcile_first: "The result is unknown. Query first.",
    query_limit: "The daily query limit was reached.",
    query_too_soon: "Wait before querying this operation again.",
    query_in_progress: "A query is already queued.",
    lease_active: "A worker currently holds this operation.",
    binding_changed:
      "The binding changed. Reconnect from the owning settings page.",
    lane_unsupported:
      "This operation's channel does not support query or retry here.",
    not_in_doubt: "This operation does not need reconciliation.",
    already_dispatched:
      "The operation may have been dispatched and cannot be cancelled.",
    operation_closed: "The operation is closed.",
    retry_not_supported: "This operation does not support retry here.",
    already_queued: "The operation is already queued.",
    already_succeeded: "The operation already succeeded.",
    operation_changed:
      "The operation changed. Refresh before taking another action.",
    forbidden: "You do not have permission to perform this action.",
    unauthorized: "Your session ended. Sign in again.",
    not_found: "This operation is no longer available in this store.",
    retry_later:
      "The service is unavailable. Refresh before repeating the request.",
  },
};
type Copy = typeof en;
const tw: Copy = {
  ...en,
  title: "失敗台賬",
  subtitle: "核對失敗或結果未知的外部操作；可執行動作以伺服器當前判定為準。",
  settings: "商店設定",
  ads: "廣告設定",
  filter: "狀態",
  refresh: "重新整理",
  next: "下一頁",
  empty: "此狀態沒有操作。",
  loading: "正在載入操作…",
  unavailable: "無法載入操作，請重新整理再試。",
  forbidden: "您沒有讀取這些操作的權限。",
  signedOut: "登入已失效，請重新登入。",
  noStore: "沒有可用商店。",
  detail: "操作詳情",
  open: "查看詳情",
  close: "關閉",
  query: "查詢",
  cancel: "取消操作",
  retry: "授權重試",
  confirm: "確認操作",
  dismiss: "返回",
  object: "業務對象",
  events: "近期事件",
  attempts: "嘗試次數",
  created: "建立時間",
  updated: "更新時間",
  reason: "原因",
  state: "狀態",
  action: "動作",
  provider: "服務平台",
  unknown: "結果未知，請先查詢。",
  confirmHint:
    "伺服器將再次核對操作狀態與權限。取消只適用於尚未執行的 READY 本地操作，不會撤回外部動作。",
  saved: "請求已受理，請核對重新整理後的伺服器狀態。",
  uncertain: "請求結果未知，請先重新整理；需要重送時只重送同一請求。",
  retryRequest: "重送同一請求",
  waiting: "已達查詢上限，請等待以下秒數",
  generic: "此操作目前不可執行，請重新整理詳情。",
  states: {
    attention: "需要關注",
    FAILED: "失敗",
    FAILED_FINAL: "失敗",
    UNKNOWN: "結果未知",
    ACKNOWLEDGED: "已受理",
    BLOCKED_POLICY: "政策阻擋",
    STALE_BINDING: "綁定已變更",
    READY: "待執行",
    DISPATCHING: "執行中",
    SUCCEEDED: "成功",
    CANCELLED: "已取消",
  },
  reasons: {
    protective_operation: "此操作是保護性操作（例如暫停廣告），不可取消。",
    reconcile_first: "結果未知，請先查詢。",
    query_limit: "已達每日查詢上限。",
    query_too_soon: "請稍候再查詢此操作。",
    query_in_progress: "查詢已在佇列中。",
    lease_active: "此操作目前由工作程序處理。",
    binding_changed: "綁定已變更，請到所屬設定重新連線。",
    lane_unsupported: "此渠道不支援在此查詢或重試。",
    not_in_doubt: "此操作不需要核對未知結果。",
    already_dispatched: "此操作可能已執行，不可取消。",
    operation_closed: "此操作已關閉。",
    retry_not_supported: "此操作不支援在此重試。",
    already_queued: "此操作已在佇列中。",
    already_succeeded: "此操作已成功。",
    operation_changed: "操作已變更，請重新整理後再操作。",
    forbidden: "您沒有執行此動作的權限。",
    unauthorized: "登入已失效，請重新登入。",
    not_found: "此商店已無法存取此操作。",
    retry_later: "服務暫時無法使用，請先重新整理再重送。",
  },
};
const cn: Copy = {
  ...en,
  title: "失败台账",
  subtitle: "核对失败或结果未知的外部操作；可执行动作以服务器当前判定为准。",
  settings: "店铺设置",
  ads: "广告设置",
  filter: "状态",
  refresh: "刷新",
  next: "下一页",
  empty: "此状态没有操作。",
  loading: "正在加载操作…",
  unavailable: "无法加载操作，请刷新后重试。",
  forbidden: "您没有读取这些操作的权限。",
  signedOut: "登录已失效，请重新登录。",
  noStore: "没有可用店铺。",
  detail: "操作详情",
  open: "查看详情",
  close: "关闭",
  query: "查询",
  cancel: "取消操作",
  retry: "授权重试",
  confirm: "确认操作",
  dismiss: "返回",
  object: "业务对象",
  events: "近期事件",
  attempts: "尝试次数",
  created: "创建时间",
  updated: "更新时间",
  reason: "原因",
  state: "状态",
  action: "动作",
  provider: "服务平台",
  unknown: "结果未知，请先查询。",
  confirmHint:
    "服务器将再次核对操作状态与权限。取消只适用于尚未执行的 READY 本地操作，不会撤回外部动作。",
  saved: "请求已受理，请核对刷新后的服务器状态。",
  uncertain: "请求结果未知，请先刷新；需要重发时只重发同一请求。",
  retryRequest: "重发同一请求",
  waiting: "已达查询上限，请等待以下秒数",
  generic: "此操作目前不可执行，请刷新详情。",
  states: {
    attention: "需要关注",
    FAILED: "失败",
    FAILED_FINAL: "失败",
    UNKNOWN: "结果未知",
    ACKNOWLEDGED: "已受理",
    BLOCKED_POLICY: "政策阻挡",
    STALE_BINDING: "绑定已变更",
    READY: "待执行",
    DISPATCHING: "执行中",
    SUCCEEDED: "成功",
    CANCELLED: "已取消",
  },
  reasons: {
    protective_operation: "此操作是保护性操作（例如暂停广告），不可取消。",
    reconcile_first: "结果未知，请先查询。",
    query_limit: "已达每日查询上限。",
    query_too_soon: "请稍候再查询此操作。",
    query_in_progress: "查询已在队列中。",
    lease_active: "此操作目前由工作程序处理。",
    binding_changed: "绑定已变更，请到所属设置重新连接。",
    lane_unsupported: "此渠道不支持在此查询或重试。",
    not_in_doubt: "此操作不需要核对未知结果。",
    already_dispatched: "此操作可能已执行，不可取消。",
    operation_closed: "此操作已关闭。",
    retry_not_supported: "此操作不支持在此重试。",
    already_queued: "此操作已在队列中。",
    already_succeeded: "此操作已成功。",
    operation_changed: "操作已变更，请刷新后再操作。",
    forbidden: "您没有执行此动作的权限。",
    unauthorized: "登录已失效，请重新登录。",
    not_found: "此店铺已无法访问此操作。",
    retry_later: "服务暂时无法使用，请先刷新再重发。",
  },
};
/** Locale-complete operation copy; machine codes remain independent of merchant wording. */
export const operationsCopy: Record<Locale, Copy> = {
  en,
  "zh-TW": tw,
  "zh-CN": cn,
};
