import type { Locale } from "@live-commerce/i18n";

const en = {
  title: "Orders",
  subtitle: "Review saved orders and their frozen checkout details.",
  store: "Store",
  filter: "Order status",
  refresh: "Refresh",
  loading: "Loading orders…",
  detailLoading: "Loading order details…",
  empty: "No orders match this status in this store.",
  signedOut: "Sign in to view orders.",
  forbidden: "This account does not have permission to read orders.",
  notFound: "This order is unavailable in the selected store.",
  unavailable: "Orders are temporarily unavailable. Try again.",
  noStore: "No authorized store is available.",
  retry: "Try again",
  previous: "Previous page",
  next: "Next page",
  pageCount: "Orders on this page",
  order: "Order",
  created: "Created (UTC)",
  total: "Total",
  commercial: "Order status",
  payment: "Payment status",
  fulfillment: "Fulfillment",
  work: "Payment work",
  test: "Test environment",
  expand: "Show order details",
  collapse: "Hide order details",
  items: "Items",
  product: "Product",
  unit: "Unit price",
  quantity: "Quantity",
  amount: "Line total",
  subtotal: "Items subtotal",
  discount: "Discount",
  shipping: "Shipping",
  shippingTax: "Shipping tax",
  tax: "Tax",
  grandTotal: "Order total",
  recipient: "Receiving details",
  name: "Recipient",
  phone: "Phone",
  method: "Delivery method",
  address: "Address",
  pickupName: "Pickup store",
  pickupCode: "Store code",
  snapshot: "Saved checkout details; store selection and merchant attestation do not confirm current carrier eligibility.",
  statuses: {
    all: "All",
    DRAFT: "Draft",
    AWAITING_PAYMENT: "Awaiting payment",
    CONFIRMED: "Confirmed",
    CANCELLED: "Cancelled",
    MANUAL_UNASSIGNED: "Not assigned",
    PAID_ALLOCATION_FAILED: "Allocation needs review",
    NOT_STARTED: "Not started",
    PENDING: "Pending",
    AUTHORIZED: "Authorized · not captured",
    CAPTURED: "Captured",
    REVIEW_REQUIRED: "Review required",
    NONE: "None",
    READY: "Ready for payment work",
    home: "Home delivery",
    cvs_711: "7-ELEVEN pickup",
    cvs_familymart: "FamilyMart pickup",
  },
};
export type OrdersCopy = typeof en;

export const ordersCopy: Record<Locale, OrdersCopy> = {
  en,
  "zh-CN": {
    title: "订单", subtitle: "查看已保存订单与结账时的固定资料。", store: "店铺", filter: "订单状态",
    refresh: "刷新", loading: "正在读取订单…", detailLoading: "正在读取订单详情…",
    empty: "该店铺在此状态下没有订单。", signedOut: "请登录后查看订单。",
    forbidden: "当前账号没有读取订单的权限。", notFound: "所选店铺中无法读取此订单。",
    unavailable: "订单暂时无法读取，请重试。", noStore: "没有获授权的店铺。", retry: "重试",
    previous: "上一页", next: "下一页", pageCount: "本页订单数", order: "订单",
    created: "创建时间（UTC）", total: "总额", commercial: "订单状态", payment: "付款状态",
    fulfillment: "履约", work: "付款待办", test: "测试环境", expand: "展开订单详情", collapse: "收起订单详情",
    items: "商品明细", product: "商品", unit: "单价", quantity: "数量", amount: "小计",
    subtotal: "商品小计", discount: "优惠", shipping: "运费", shippingTax: "运费税",
    tax: "税额", grandTotal: "订单总额", recipient: "收货资料", name: "收件人", phone: "手机",
    method: "取货方式", address: "地址", pickupName: "取货门店", pickupCode: "店号",
    snapshot: "历史结账快照；选店与商家确认不代表当前承运资格已确认。",
    statuses: {
      all: "全部", DRAFT: "草稿", AWAITING_PAYMENT: "待付款", CONFIRMED: "已确认", CANCELLED: "已取消",
      MANUAL_UNASSIGNED: "待分配", PAID_ALLOCATION_FAILED: "分配异常待核对", NOT_STARTED: "尚未开始",
      PENDING: "处理中", AUTHORIZED: "已授权·未扣款", CAPTURED: "已扣款", REVIEW_REQUIRED: "待核对",
      NONE: "无", READY: "待处理", home: "宅配", cvs_711: "7-ELEVEN 取货", cvs_familymart: "全家取货",
    },
  },
  "zh-TW": {
    title: "訂單", subtitle: "查看已儲存訂單與結帳時的固定資料。", store: "商店", filter: "訂單狀態",
    refresh: "重新整理", loading: "正在讀取訂單…", detailLoading: "正在讀取訂單詳情…",
    empty: "此商店在該狀態下沒有訂單。", signedOut: "請登入後查看訂單。",
    forbidden: "此帳號沒有讀取訂單的權限。", notFound: "所選商店中無法讀取此訂單。",
    unavailable: "訂單暫時無法讀取，請重試。", noStore: "沒有獲授權的商店。", retry: "重試",
    previous: "上一頁", next: "下一頁", pageCount: "本頁訂單數", order: "訂單",
    created: "建立時間（UTC）", total: "總額", commercial: "訂單狀態", payment: "付款狀態",
    fulfillment: "履約", work: "付款待辦", test: "測試環境", expand: "展開訂單詳情", collapse: "收起訂單詳情",
    items: "商品明細", product: "商品", unit: "單價", quantity: "數量", amount: "小計",
    subtotal: "商品小計", discount: "折扣", shipping: "運費", shippingTax: "運費稅",
    tax: "稅額", grandTotal: "訂單總額", recipient: "收貨資料", name: "收件人", phone: "手機",
    method: "取貨方式", address: "地址", pickupName: "取貨門市", pickupCode: "店號",
    snapshot: "歷史結帳快照；選店與商家確認不代表目前承運資格已確認。",
    statuses: {
      all: "全部", DRAFT: "草稿", AWAITING_PAYMENT: "待付款", CONFIRMED: "已確認", CANCELLED: "已取消",
      MANUAL_UNASSIGNED: "待分配", PAID_ALLOCATION_FAILED: "分配異常待核對", NOT_STARTED: "尚未開始",
      PENDING: "處理中", AUTHORIZED: "已授權·未扣款", CAPTURED: "已扣款", REVIEW_REQUIRED: "待核對",
      NONE: "無", READY: "待處理", home: "宅配", cvs_711: "7-ELEVEN 取貨", cvs_familymart: "全家取貨",
    },
  },
};
