// Purpose: three-locale copy for the W3-07B parcel-merge UI (banner, suggestion cards, group panel, refusal codes).
//   The owner ruling (2026-10-06) fixes the `rule` sentence: only parcels merge, never payments or amounts, and every
//   order keeps its own total and its own shipping notification. `blocked` and errors.in_parcel_group must stay the
//   same sentence as orders-copy errors.in_parcel_group (server code maps to the same text).
// Depends on: @live-commerce/i18n Locale; parcels-model.ts parcelRefusalCodes.
// Used by: apps/admin/components/ParcelGroup.tsx, MerchantOrders.tsx (badge + block hint), tests/admin/parcels-model.test.ts.
import type { Locale } from "@live-commerce/i18n";
import type { ParcelGroupState, ParcelRefusalCode } from "./parcels-model.ts";

const en = {
  // Owner ruling wording: parcels only, never money; each order is still priced and notified on its own.
  rule: "Only the parcels are merged, never payments or amounts; each order is still priced separately and gets its own shipping notification.",
  banner: (n: number) => `${n} order group${n === 1 ? "" : "s"} can ship as one parcel`,
  show: "Review",
  hide: "Hide",
  suggestionFor: "Recipient",
  suggestionOrders: (n: number) => `${n} orders`,
  merge: "Merge parcels",
  merging: "Merging…",
  groupTitle: (short: string) => `Parcel group #${short}`,
  badge: (short: string) => `Group #${short}`,
  members: "Member orders",
  states: { OPEN: "Open", SHIPPED: "Shipped", DISSOLVED: "Dissolved" } as Record<ParcelGroupState, string>,
  ship: "Fill in waybill",
  shipSubmit: "Mark the whole group shipped",
  shipSending: "Saving…",
  shipDone: "The group is shipped; every order recorded the same tracking number.",
  shipRetry: "Retry the same request",
  shipUncertain: "The result is not known yet. Retry sends the identical request safely, or reload the page and check.",
  dissolve: "Dissolve group",
  dissolveConfirm: "Confirm dissolve",
  dissolveBack: "Back",
  dissolveSending: "Dissolving…",
  dissolveDone: "Group dissolved; the orders can ship separately again.",
  close: "Close",
  // Same sentence as orders-copy errors.in_parcel_group (brief: the server code maps to this text).
  blocked: "This order is in a parcel group; fill in the waybill on the group.",
  errors: {
    cod_not_mergeable: "Cash-on-delivery orders cannot be merged: the carrier collects one amount per parcel.",
    cvs_not_mergeable: "Convenience-store pickup orders cannot be merged.",
    not_mergeable: "These orders cannot be merged in their current state.",
    already_in_group: "One of these orders is already in a parcel group. Reload the page and try again.",
    owner_mismatch: "Only orders of the same buyer can be merged.",
    destination_mismatch: "Only orders going to the same address can be merged.",
    group_not_open: "This group has already been shipped or dissolved. Reload the page and try again.",
    group_incomplete: "Not every member order is shipped yet. Reload the page and try again.",
    in_parcel_group: "This order is in a parcel group; fill in the waybill on the group.",
    version_changed: "The group changed since you loaded it. Reload the page and try again.",
    forbidden: "This account does not have permission for this action.",
    unauthorized: "Sign in again to continue.",
    not_found: "This group is unavailable in the selected store.",
    conflict: "This request conflicts with an earlier one. Reload the page and try again.",
    rate_limited: "Too many requests. Try again in a few seconds.",
    retry_later: "Temporarily unavailable. Try again.",
    default: "The request could not be completed. Reload the page and try again.",
  } as Record<ParcelRefusalCode | "version_changed" | "forbidden" | "unauthorized" | "not_found" | "conflict" | "rate_limited" | "retry_later" | "default", string>,
};
export type ParcelCopy = typeof en;

export const parcelCopy: Record<Locale, ParcelCopy> = {
  en,
  "zh-TW": {
    rule: "只合併包裹，不合併付款或金額；每張訂單仍各自計價、各自收到出貨通知。",
    banner: (n) => `${n} 組訂單可合併出貨`,
    show: "查看",
    hide: "收起",
    suggestionFor: "收件人",
    suggestionOrders: (n) => `${n} 張訂單`,
    merge: "合併出貨",
    merging: "合併中…",
    groupTitle: (short) => `合包 #${short}`,
    badge: (short) => `合包 #${short}`,
    members: "成員訂單",
    states: { OPEN: "待出貨", SHIPPED: "已出貨", DISSOLVED: "已解除" },
    ship: "填寫運單",
    shipSubmit: "整組標記已出貨",
    shipSending: "儲存中…",
    shipDone: "整組已出貨，每張訂單各自記錄同一追蹤單號。",
    shipRetry: "重試相同請求",
    shipUncertain: "結果尚未確認。重試會安全地送出相同請求，或重新整理後確認。",
    dissolve: "解除合併",
    dissolveConfirm: "確認解除",
    dissolveBack: "返回",
    dissolveSending: "解除中…",
    dissolveDone: "已解除合併，訂單可分別出貨。",
    close: "關閉",
    blocked: "此訂單在合包中，請在合包填寫運單",
    errors: {
      cod_not_mergeable: "貨到付款訂單不能合併：物流商每件包裹各自收款。",
      cvs_not_mergeable: "超商取貨訂單不能合併。",
      not_mergeable: "這些訂單目前的狀態不能合併。",
      already_in_group: "其中一張訂單已在合包中，請重新整理後重試。",
      owner_mismatch: "只有同一位買家的訂單才能合併。",
      destination_mismatch: "只有寄往同一地址的訂單才能合併。",
      group_not_open: "此合包已出貨或已解除，請重新整理後重試。",
      group_incomplete: "尚有成員訂單未出貨，請重新整理後重試。",
      in_parcel_group: "此訂單在合包中，請在合包填寫運單",
      version_changed: "合包在您讀取後已變更，請重新整理後重試。",
      forbidden: "此帳號沒有此操作的權限。",
      unauthorized: "請重新登入後繼續。",
      not_found: "所選商店中找不到此合包。",
      conflict: "此請求與先前的請求衝突，請重新整理後重試。",
      rate_limited: "請求過多，請幾秒後再試。",
      retry_later: "暫時無法使用，請重試。",
      default: "請求未能完成，請重新整理後重試。",
    },
  },
  "zh-CN": {
    rule: "只合并包裹，不合并付款或金额；每张订单仍各自计价、各自收到出货通知。",
    banner: (n) => `${n} 组订单可合并出货`,
    show: "查看",
    hide: "收起",
    suggestionFor: "收件人",
    suggestionOrders: (n) => `${n} 张订单`,
    merge: "合并出货",
    merging: "合并中…",
    groupTitle: (short) => `合包 #${short}`,
    badge: (short) => `合包 #${short}`,
    members: "成员订单",
    states: { OPEN: "待出货", SHIPPED: "已出货", DISSOLVED: "已解除" },
    ship: "填写运单",
    shipSubmit: "整组标记已出货",
    shipSending: "保存中…",
    shipDone: "整组已出货，每张订单各自记录同一追踪单号。",
    shipRetry: "重试相同请求",
    shipUncertain: "结果尚未确认。重试会安全地发送相同请求，或刷新后确认。",
    dissolve: "解除合并",
    dissolveConfirm: "确认解除",
    dissolveBack: "返回",
    dissolveSending: "解除中…",
    dissolveDone: "已解除合并，订单可分别出货。",
    close: "关闭",
    blocked: "此订单在合包中，请在合包填写运单",
    errors: {
      cod_not_mergeable: "货到付款订单不能合并：物流商每件包裹各自收款。",
      cvs_not_mergeable: "超商取货订单不能合并。",
      not_mergeable: "这些订单目前的状态不能合并。",
      already_in_group: "其中一张订单已在合包中，请刷新后重试。",
      owner_mismatch: "只有同一位买家的订单才能合并。",
      destination_mismatch: "只有寄往同一地址的订单才能合并。",
      group_not_open: "此合包已出货或已解除，请刷新后重试。",
      group_incomplete: "尚有成员订单未出货，请刷新后重试。",
      in_parcel_group: "此订单在合包中，请在合包填写运单",
      version_changed: "合包在您读取后已变更，请刷新后重试。",
      forbidden: "当前账号没有此操作的权限。",
      unauthorized: "请重新登录后继续。",
      not_found: "所选店铺中找不到此合包。",
      conflict: "此请求与先前的请求冲突，请刷新后重试。",
      rate_limited: "请求过多，请几秒后再试。",
      retry_later: "暂时无法使用，请重试。",
      default: "请求未能完成，请刷新后重试。",
    },
  },
};
