// Purpose: plain-language order selection, printing, CSV and shipment batch copy.
// Depends on: the three supported admin locales; no provider jargon in buyer-facing controls.
// Used by: PickList, CarrierExport, CvsBatch and MerchantOrders checkboxes.
const en = {
  checked: "Orders with a confirmed request",
  notCvs: "This order does not use convenience-store delivery",
  invalidOrder: "Check this order’s delivery details",
  changed: "This order changed. Refresh it before trying again",
  checkStatus: "Check label status",
  select: "Select order",
  page: "Select this page",
  selected: "Selected orders",
  clear: "Clear selection",
  limit: "Select up to 500 orders. Clear some before selecting another page.",
  pick: "Pick list",
  export: "Export",
  cvs: "Convenience-store labels",
  scope: "Orders to include",
  chosen: "Selected orders",
  session: "All orders in this live session",
  sessionHint:
    "Choose a live session in the order filters first. Up to 500 eligible orders.",
  loading: "Loading…",
  close: "Close",
  print: "Print",
  summary: "Items to pick",
  orders: "Order details",
  sku: "SKU",
  item: "Item",
  quantity: "Quantity",
  empty: "No orders are ready to pick.",
  skipped: "Orders left out",
  notPickable: "Not ready to pick or already shipped",
  notFound: "Order unavailable",
  unavailable: "Could not load this information. Please try again.",
  unauthorized: "Your access changed. Refresh the page and sign in again.",
  tooMany: "This selection exceeds the limit. Choose fewer orders.",
  template: "Carrier format",
  black_cat: "Black Cat",
  hsinchu: "Hsinchu",
  chunghwa_post: "Chunghwa Post",
  generic: "Other",
  download: "Download CSV",
  exportHint:
    "Check the columns and recipient information before uploading this file to your carrier.",
  confirm: "Create labels",
  cancel: "Cancel",
  confirmBefore: "Create",
  confirmAfter: "convenience-store labels?",
  cvsLimit:
    "Choose 1–100 convenience-store orders. Home-delivery orders are not included.",
  queued: "Requested — check the order for the label status",
  already: "A request already exists",
  failed: "Could not create this label — check the order",
  unknown:
    "We cannot confirm whether labels were created. Check the orders later. The system will not resend this request.",
  check: "View order",
  done: "Results",
  storage:
    "This browser cannot save recovery information. Enable site storage before creating labels.",
  connection: "Connect your delivery service in store settings first.",
};
type Copy = typeof en;
const tw: Copy = {
  checked: "已確認有申請紀錄的訂單",
  notCvs: "這筆訂單不是超商取貨",
  invalidOrder: "請檢查這筆訂單的配送資料",
  changed: "訂單已變更，請重新整理後再處理",
  checkStatus: "重新查看寄件單狀態",
  select: "選取訂單",
  page: "選取本頁",
  selected: "已選訂單",
  clear: "清除選取",
  limit: "最多選取 500 筆訂單，請先取消部分選取再選下一頁。",
  pick: "撿貨單",
  export: "匯出",
  cvs: "超商寄件單",
  scope: "包含哪些訂單",
  chosen: "已選訂單",
  session: "本場全部",
  sessionHint: "請先在訂單篩選選擇直播場次，最多包含 500 筆可處理訂單。",
  loading: "載入中…",
  close: "關閉",
  print: "列印",
  summary: "商品撿貨總數",
  orders: "各訂單明細",
  sku: "貨號",
  item: "商品",
  quantity: "數量",
  empty: "目前沒有可撿貨的訂單。",
  skipped: "未列入的訂單",
  notPickable: "尚未可撿貨或已寄出",
  notFound: "無法讀取這筆訂單",
  unavailable: "暫時無法讀取，請稍後再試。",
  unauthorized: "登入或權限已變更，請重新整理並登入。",
  tooMany: "超過處理上限，請減少訂單數量。",
  template: "物流商格式",
  black_cat: "黑貓",
  hsinchu: "新竹",
  chunghwa_post: "郵局",
  generic: "其他",
  download: "下載 CSV",
  exportHint: "交給物流商前，請核對檔案欄位與收件資料。",
  confirm: "建立寄件單",
  cancel: "取消",
  confirmBefore: "將建立",
  confirmAfter: "張超商寄件單，是否繼續？",
  cvsLimit: "請選取 1–100 筆超商訂單，宅配訂單不會列入。",
  queued: "已提出申請，請到訂單查看寄件單狀態",
  already: "已有申請紀錄",
  failed: "未能建立，請到訂單查看原因",
  unknown: "不確定是否建立，請稍後查看訂單，系統不會重送。",
  check: "查看訂單",
  done: "處理結果",
  storage: "瀏覽器無法保存處理紀錄，請啟用網站儲存空間後再建立。",
  connection: "請先到開店設定連接物流服務。",
};
const cn: Copy = {
  checked: "已确认有申请记录的订单",
  notCvs: "这笔订单不是便利店取货",
  invalidOrder: "请检查这笔订单的配送资料",
  changed: "订单已变更，请刷新后再处理",
  checkStatus: "重新查看寄件单状态",
  select: "选择订单",
  page: "选择本页",
  selected: "已选订单",
  clear: "清除选择",
  limit: "最多选择 500 笔订单，请先取消部分选择再选下一页。",
  pick: "拣货单",
  export: "导出",
  cvs: "便利店寄件单",
  scope: "包含哪些订单",
  chosen: "已选订单",
  session: "本场全部",
  sessionHint: "请先在订单筛选选择直播场次，最多包含 500 笔可处理订单。",
  loading: "加载中…",
  close: "关闭",
  print: "打印",
  summary: "商品拣货总数",
  orders: "各订单明细",
  sku: "货号",
  item: "商品",
  quantity: "数量",
  empty: "目前没有可拣货的订单。",
  skipped: "未列入的订单",
  notPickable: "尚不可拣货或已寄出",
  notFound: "无法读取这笔订单",
  unavailable: "暂时无法读取，请稍后再试。",
  unauthorized: "登录或权限已变更，请刷新并登录。",
  tooMany: "超过处理上限，请减少订单数量。",
  template: "物流商格式",
  black_cat: "黑猫",
  hsinchu: "新竹",
  chunghwa_post: "邮局",
  generic: "其他",
  download: "下载 CSV",
  exportHint: "交给物流商前，请核对文件字段与收件资料。",
  confirm: "建立寄件单",
  cancel: "取消",
  confirmBefore: "将建立",
  confirmAfter: "张便利店寄件单，是否继续？",
  cvsLimit: "请选择 1–100 笔便利店订单，宅配订单不会列入。",
  queued: "已提出申请，请到订单查看寄件单状态",
  already: "已有申请记录",
  failed: "未能建立，请到订单查看原因",
  unknown: "不确定是否建立，请稍后查看订单，系统不会重发。",
  check: "查看订单",
  done: "处理结果",
  storage: "浏览器无法保存处理记录，请启用网站存储空间后再建立。",
  connection: "请先到开店设置连接物流服务。",
};
export const picklistCopy = { en: en, "zh-TW": tw, "zh-CN": cn };
