// Purpose: All product-editor UI strings per locale (zh-TW, zh-CN, en).
// Depends on: @live-commerce/i18n (Locale). Pure data.
// Used by: ProductDocumentForm, ProductDocumentVariants, ProductBulkFill, ProductReadiness, ProductDocumentMedia, ProductQuickEdit.
import type { Locale } from "@live-commerce/i18n";
const en = {
  visibility: "Visibility",
  draftStatus: "Draft",
  activeStatus: "Active",
  loading: "Loading product…",
  noChanges: "No changes to save.",
  targetQty: "Resulting on-hand",
  onHand: "On hand",
  committed: "Committed",
  delta: "Add / subtract",
  inventoryLink: "Open inventory",
  warehouse_required:
    "Resulting inventory requires exactly one active warehouse. Adjust stock in Inventory for this store.",
  insufficient:
    "Resulting stock cannot be below committed units. Check the current inventory and try again.",
  media: "Product images",
  basics: "Basic information",
  pricing: "Price & inventory",
  variants: "Variants",
  collections: "Collections",
  shipping: "Shipping",
  seo: "Search engine listing",
  progress: "Readiness",
  required: "Required",
  recommended: "Recommended",
  missing: "Required items remaining",
  images: "Images",
  name: "Product name",
  price: "Price",
  stock: "Inventory",
  addImages: "Add images",
  imageHelp:
    "Up to 12 images · JPG / PNG / WebP · 2 MB each. 800 px or larger recommended.",
  cover: "Cover",
  remove: "Remove",
  left: "Move earlier",
  right: "Move later",
  photoInvalid:
    "Choose a JPG, PNG or WebP image up to 2 MB. Maximum 12 images.",
  description: "Description",
  keyword: "Live keyword",
  keywordHelp:
    "Optional · letters and numbers, unique within this store. One keyword per variant.",
  unavailableKeyword:
    "Existing keywords are not returned by the current product API.",
  compare: "Compare-at price",
  tracked: "Track quantity",
  untracked: "Do not track ∞",
  max: "Maximum per order",
  quantity: "Quantity",
  code: "SKU code",
  advanced: "Advanced",
  generated: "Generated on save if blank",
  addAxis: "Add option (color, size…)",
  axis: "Option name",
  values: "Values",
  valueHelp: "Press Enter or use commas / newlines. Up to 50 unique values.",
  color: "Color",
  size: "Size",
  style: "Style",
  volume: "Capacity",
  active: "Enabled",
  newRow: "New",
  existing: "Existing",
  archiveRows: "Existing variants to archive",
  restore: "Restore",
  matrixLimit:
    "Use up to 3 options and 100 combinations. Each option needs a name and values.",
  bulk: "Bulk fill",
  bulkField: "Field",
  bulkRows: "Apply to",
  defaultVariant: "Default variant",
  ready: "Ready",
  pending: "To do",
  all: "All",
  empty: "Only empty",
  set: "Set to",
  add: "Add",
  subtract: "Subtract",
  prefix: "Prefix + sequence",
  apply: "Apply",
  skipped: "Rows skipped",
  cancel: "Cancel",
  close: "Close",
  amount: "Value",
  searchCollections: "Find collection",
  manageCollections: "Manage collections",
  noCollections: "No collections yet",
  weight: "Weight (g)",
  length: "Length (cm)",
  width: "Width (cm)",
  height: "Height (cm)",
  shippingHelp:
    "Optional defaults for all variants. No carrier connection is implied.",
  warehouse: "Stock warehouse",
  chooseWarehouse: "Select warehouse",
  slug: "Page handle",
  seoTitle: "SEO title",
  seoDescription: "SEO description",
  saveDraft: "Save draft",
  publish: "Publish",
  save: "Save changes",
  saved: "Draft saved",
  published: "Published",
  saving: "Saving…",
  dirty: "Unsaved changes",
  leave: "Leave without saving your changes?",
  recoveryRequired:
    "A previous product creation still needs reconciliation. Do not create it again. Keep this tab and ask an administrator to confirm the command receipt before continuing; draft content was not cached.",
  imageRequired: "Add at least one image before publishing.",
  invalid_name: "Enter a name of up to 120 characters.",
  invalid_price:
    "Enter a valid price. TWD accepts whole dollars; compare-at must exceed price.",
  invalid_stock:
    "Enter a non-negative whole quantity, or a per-order maximum from 1 to 999 for untracked inventory.",
  invalid_options: "Check option names, values and the 100-variant limit.",
  invalid_code:
    "SKU codes must be unique and use letters, digits, periods, hyphens or underscores.",
  invalid_dimensions:
    "Use non-negative measurements; cm supports one decimal place.",
  keyword_taken:
    "This keyword is already used. Choose a unique keyword for each variant.",
  amount_not_whole_twd: "TWD prices must be whole dollars.",
  live_window_open:
    "This product belongs to an open live ordering window. Close the ordering window before unpublishing, archiving variants, or changing / clearing their keywords. Price changes are allowed.",
  not_found: "This product no longer exists or is not accessible.",
  editBlocked:
    "Editing is temporarily unavailable: the product API cannot yet preserve all existing keywords, collection membership and per-variant shipping fields. No changes will be sent.",
  uncertain:
    "The outcome is not confirmed. Retry the same action; do not create another product.",
  retry: "Retry same action",
  failed: "Could not save. Review your entries and try again.",
  createdContinue:
    "Product saved. Images may still need attention; retry the pending step with the same key.",
  viewBuyer: "View product",
  storeUnpublished:
    "The store may still be unpublished. Check its publication settings before sharing.",
  settings: "Store settings",
  copyKeyword: "Copy keyword",
  copied: "Copied",
  another: "Create another",
  back: "Back to products",
  select: "Select product",
  selected: "Selected",
  clear: "Clear selection",
  publishSelected: "Publish",
  unpublish: "Unpublish to draft",
  unpublishConfirm:
    "Unpublish this product? Shoppers will no longer be able to buy it.",
  deltaUnavailable:
    "The current quantity is unknown. Save an explicit target before using add/subtract.",
  archive: "Archive",
  addCollection: "Add to collection",
  copy: "Copy",
  results: "Results",
  success: "Saved",
  updated: "Updated (Taipei time)",
  editPrice: "Edit price",
  editStock: "Edit inventory",
  soldOut: "Sold out",
  lowStock: "Low stock (≤5)",
  noImage: "No image",
  noKeyword: "No keyword",
  currentPage: "Filters and sorting apply to this loaded page.",
  newest: "Updated newest",
  priceAsc: "Price: low to high",
  stockAsc: "Inventory: low to high",
  mixedTracking: "Includes untracked variants",
  listRecoveryRequired:
    "A previous catalogue command still needs reconciliation. Do not copy or submit it again. Ask an administrator to confirm its receipt before continuing; only the command identifier was retained.",
  total: "Products",
  cap: "Select up to 100 products per action.",
  membership: "Adding to a collection preserves its existing products.",
};
type Copy = typeof en;
const zhTW: Copy = {
  visibility: "顯示狀態",
  draftStatus: "草稿",
  activeStatus: "上架中",
  loading: "正在讀取商品…",
  noChanges: "沒有需要儲存的修改。",
  targetQty: "改後庫存",
  onHand: "現有庫存",
  committed: "已承諾數量",
  delta: "增加／減少",
  inventoryLink: "前往庫存",
  warehouse_required: "改後庫存需要恰好一個啟用倉庫。請前往庫存頁按倉調整。",
  insufficient: "改後庫存不能低於已承諾數量。請核對目前庫存後再試。",
  media: "商品圖片",
  basics: "基本資訊",
  pricing: "價格與庫存",
  variants: "規格",
  collections: "分類",
  shipping: "物流",
  seo: "搜尋引擎最佳化",
  progress: "完成度",
  required: "必填",
  recommended: "建議",
  missing: "尚缺必填項目",
  images: "圖片",
  name: "商品名稱",
  price: "售價",
  stock: "庫存",
  addImages: "新增圖片",
  imageHelp: "最多 12 張 · JPG／PNG／WebP · 每張 2 MB。建議 800 px 以上。",
  cover: "封面",
  remove: "移除",
  left: "向前移",
  right: "向後移",
  photoInvalid: "請選擇不超過 2 MB 的 JPG、PNG 或 WebP，最多 12 張。",
  description: "描述",
  keyword: "直播關鍵字",
  keywordHelp: "選填 · 英文及數字，每個規格一個關鍵字，店內不可重複。",
  unavailableKeyword: "目前商品 API 尚未回傳既有關鍵字。",
  compare: "原價",
  tracked: "追蹤數量",
  untracked: "不追蹤 ∞",
  max: "單次購買上限",
  quantity: "數量",
  code: "貨號",
  advanced: "進階",
  generated: "留空由系統產生",
  addAxis: "新增規格（顏色、尺寸…）",
  axis: "規格名稱",
  values: "規格值",
  valueHelp: "按 Enter 或用逗號、換行分隔，最多 50 個不重複值。",
  color: "顏色",
  size: "尺寸",
  style: "款式",
  volume: "容量",
  active: "啟用",
  newRow: "新增",
  existing: "既有",
  archiveRows: "即將封存的規格",
  restore: "還原",
  matrixLimit: "最多 3 個規格軸、100 個組合，每軸需名稱和值。",
  bulk: "批量填入",
  bulkField: "欄位",
  bulkRows: "套用範圍",
  defaultVariant: "預設規格",
  ready: "已完成",
  pending: "待填寫",
  all: "全部",
  empty: "僅空白",
  set: "設為",
  add: "增加",
  subtract: "減少",
  prefix: "前綴＋序號",
  apply: "套用",
  skipped: "已略過列數",
  cancel: "取消",
  close: "關閉",
  amount: "數值",
  searchCollections: "搜尋分類",
  manageCollections: "管理分類",
  noCollections: "尚無分類",
  weight: "重量（g）",
  length: "長（cm）",
  width: "寬（cm）",
  height: "高（cm）",
  shippingHelp: "選填，套用至所有規格。不代表已串接物流商。",
  warehouse: "庫存倉庫",
  chooseWarehouse: "選擇倉庫",
  slug: "頁面網址",
  seoTitle: "SEO 標題",
  seoDescription: "SEO 描述",
  saveDraft: "儲存草稿",
  publish: "上架",
  save: "儲存修改",
  saved: "草稿已儲存",
  published: "已上架",
  saving: "儲存中…",
  dirty: "尚未儲存的修改",
  leave: "要離開並捨棄未儲存的修改嗎？",
  recoveryRequired:
    "先前的商品新增仍待核對，請勿重複新增。請保留此分頁，請管理員核對命令回執後再繼續；系統未快取草稿內容。",
  imageRequired: "上架前請至少新增一張圖片。",
  invalid_name: "請輸入不超過 120 字的名稱。",
  invalid_price: "請輸入有效售價；台幣只收整數，原價須高於售價。",
  invalid_stock: "請輸入非負整數庫存；不追蹤庫存時，單次上限須為 1–999。",
  invalid_options: "請檢查規格名稱、值與 100 個組合上限。",
  invalid_code: "貨號不可重複，僅限英文、數字、點、連字號與底線。",
  invalid_dimensions: "尺寸須為非負數，公分最多一位小數。",
  keyword_taken: "關鍵字已被使用，請為每個規格選擇店內唯一的關鍵字。",
  amount_not_whole_twd: "台幣售價必須是整數元。",
  live_window_open:
    "商品仍在開放收單的直播場次中。請先關閉收單窗口，再下架、封存規格或修改／清空關鍵字；改價仍可進行。",
  not_found: "商品已不存在，或你沒有存取權限。",
  editBlocked:
    "暫時無法編輯：商品 API 尚無法完整保留既有關鍵字、分類和各規格物流欄位，不會送出任何修改。",
  uncertain: "結果尚未確認，請重試同一動作，不要另建商品。",
  retry: "重試同一動作",
  failed: "無法儲存，請檢查輸入後重試。",
  createdContinue:
    "商品已儲存，圖片步驟可能尚未完成；請以原請求重試待處理步驟。",
  viewBuyer: "查看商品",
  storeUnpublished: "商店可能尚未發布，分享前請確認發布設定。",
  settings: "商店設定",
  copyKeyword: "複製關鍵字",
  copied: "已複製",
  another: "再新增商品",
  back: "返回商品列表",
  select: "選取商品",
  selected: "已選取",
  clear: "取消選取",
  publishSelected: "上架",
  unpublish: "下架轉草稿",
  unpublishConfirm: "確定下架此商品？買家將無法再購買此商品。",
  deltaUnavailable: "目前數量未知，請先儲存明確的改後庫存，再使用加減調整。",
  archive: "封存",
  addCollection: "加入分類",
  copy: "複製",
  results: "處理結果",
  success: "已儲存",
  updated: "更新時間（台北時間）",
  editPrice: "修改價格",
  editStock: "修改庫存",
  soldOut: "已售罄",
  lowStock: "低庫存（≤5）",
  noImage: "無圖片",
  noKeyword: "無關鍵字",
  currentPage: "篩選與排序適用於本頁已載入商品。",
  newest: "最近更新",
  priceAsc: "價格由低到高",
  stockAsc: "庫存由低到高",
  mixedTracking: "含不追蹤數量的規格",
  listRecoveryRequired:
    "先前的商品命令仍待核對，請勿重複複製或提交。請管理員核對回執後再繼續；系統只保留命令編號。",
  total: "商品數",
  cap: "每次最多選取 100 個商品。",
  membership: "加入分類時會保留該分類原有商品。",
};
const zhCN: Copy = {
  visibility: "显示状态",
  draftStatus: "草稿",
  activeStatus: "上架中",
  loading: "正在读取商品…",
  noChanges: "没有需要保存的修改。",
  targetQty: "改后库存",
  onHand: "现有库存",
  committed: "已承诺数量",
  delta: "增加／减少",
  inventoryLink: "前往库存",
  warehouse_required: "改后库存需要恰好一个启用仓库。请前往库存页按仓调整。",
  insufficient: "改后库存不能低于已承诺数量。请核对目前库存后再试。",
  media: "商品图片",
  basics: "基本信息",
  pricing: "价格与库存",
  variants: "规格",
  collections: "分类",
  shipping: "物流",
  seo: "搜索引擎优化",
  progress: "完成度",
  required: "必填",
  recommended: "建议",
  missing: "还缺必填项目",
  images: "图片",
  name: "商品名称",
  price: "售价",
  stock: "库存",
  addImages: "添加图片",
  imageHelp: "最多 12 张 · JPG／PNG／WebP · 每张 2 MB。建议 800 px 以上。",
  cover: "封面",
  remove: "移除",
  left: "向前移",
  right: "向后移",
  photoInvalid: "请选择不超过 2 MB 的 JPG、PNG 或 WebP，最多 12 张。",
  description: "描述",
  keyword: "直播关键字",
  keywordHelp: "选填 · 英文及数字，每个规格一个关键字，店内不可重复。",
  unavailableKeyword: "目前商品 API 尚未返回已有关键字。",
  compare: "原价",
  tracked: "追踪数量",
  untracked: "不追踪 ∞",
  max: "单次购买上限",
  quantity: "数量",
  code: "货号",
  advanced: "高级",
  generated: "留空由系统生成",
  addAxis: "添加规格（颜色、尺寸…）",
  axis: "规格名称",
  values: "规格值",
  valueHelp: "按 Enter 或用逗号、换行分隔，最多 50 个不重复值。",
  color: "颜色",
  size: "尺寸",
  style: "款式",
  volume: "容量",
  active: "启用",
  newRow: "新增",
  existing: "已有",
  archiveRows: "即将封存的规格",
  restore: "恢复",
  matrixLimit: "最多 3 个规格轴、100 个组合，每轴需名称和值。",
  bulk: "批量填充",
  bulkField: "字段",
  bulkRows: "应用范围",
  defaultVariant: "默认规格",
  ready: "已完成",
  pending: "待填写",
  all: "全部",
  empty: "仅空白",
  set: "设为",
  add: "增加",
  subtract: "减少",
  prefix: "前缀＋序号",
  apply: "套用",
  skipped: "已跳过行数",
  cancel: "取消",
  close: "关闭",
  amount: "数值",
  searchCollections: "搜索分类",
  manageCollections: "管理分类",
  noCollections: "暂无分类",
  weight: "重量（g）",
  length: "长（cm）",
  width: "宽（cm）",
  height: "高（cm）",
  shippingHelp: "选填，应用于所有规格。不代表已接入物流商。",
  warehouse: "库存仓库",
  chooseWarehouse: "选择仓库",
  slug: "页面网址",
  seoTitle: "SEO 标题",
  seoDescription: "SEO 描述",
  saveDraft: "保存草稿",
  publish: "上架",
  save: "保存修改",
  saved: "草稿已保存",
  published: "已上架",
  saving: "保存中…",
  dirty: "未保存的修改",
  leave: "要离开并放弃未保存的修改吗？",
  recoveryRequired:
    "先前的商品新增仍待核对，请勿重复新增。请保留此标签页，请管理员核对命令回执后再继续；系统未缓存草稿内容。",
  imageRequired: "上架前请至少添加一张图片。",
  invalid_name: "请输入不超过 120 字的名称。",
  invalid_price: "请输入有效售价；台币只收整数，原价须高于售价。",
  invalid_stock: "请输入非负整数库存；不追踪库存时，单次上限须为 1–999。",
  invalid_options: "请检查规格名称、值与 100 个组合上限。",
  invalid_code: "货号不可重复，仅限英文、数字、点、连字符与下划线。",
  invalid_dimensions: "尺寸须为非负数，厘米最多一位小数。",
  keyword_taken: "关键字已被使用，请为每个规格选择店内唯一的关键字。",
  amount_not_whole_twd: "台币售价必须是整数元。",
  live_window_open:
    "商品仍在开放收单的直播场次中。请先关闭收单窗口，再下架、封存规格或修改／清空关键字；改价仍可进行。",
  not_found: "商品已不存在，或你没有访问权限。",
  editBlocked:
    "暂时无法编辑：商品 API 尚无法完整保留已有关键字、分类和各规格物流字段，不会发送任何修改。",
  uncertain: "结果尚未确认，请重试同一动作，不要另建商品。",
  retry: "重试同一动作",
  failed: "无法保存，请检查输入后重试。",
  createdContinue:
    "商品已保存，图片步骤可能尚未完成；请以原请求重试待处理步骤。",
  viewBuyer: "查看商品",
  storeUnpublished: "商店可能尚未发布，分享前请确认发布设置。",
  settings: "商店设置",
  copyKeyword: "复制关键字",
  copied: "已复制",
  another: "再新增商品",
  back: "返回商品列表",
  select: "选择商品",
  selected: "已选择",
  clear: "取消选择",
  publishSelected: "上架",
  unpublish: "下架转草稿",
  unpublishConfirm: "确定下架此商品？买家将无法再购买此商品。",
  deltaUnavailable: "当前数量未知，请先保存明确的改后库存，再使用加减调整。",
  archive: "封存",
  addCollection: "加入分类",
  copy: "复制",
  results: "处理结果",
  success: "已保存",
  updated: "更新时间（台北时间）",
  editPrice: "修改价格",
  editStock: "修改库存",
  soldOut: "已售罄",
  lowStock: "低库存（≤5）",
  noImage: "无图片",
  noKeyword: "无关键字",
  currentPage: "筛选与排序适用于本页已加载商品。",
  newest: "最近更新",
  priceAsc: "价格从低到高",
  stockAsc: "库存从低到高",
  mixedTracking: "含不追踪数量的规格",
  listRecoveryRequired:
    "先前的商品命令仍待核对，请勿重复复制或提交。请管理员核对回执后再继续；系统只保留命令编号。",
  total: "商品数",
  cap: "每次最多选择 100 个商品。",
  membership: "加入分类时会保留该分类原有商品。",
};
export const productEditorCopy: Record<Locale, Copy> = {
  en,
  "zh-TW": zhTW,
  "zh-CN": zhCN,
};
export type ProductEditorCopy = Copy;
