// Purpose: PM-U plain copy for three media sections; Japanese copy is ready for the unified locale unit.
// Depends on: current admin locales; no backend locale expansion.
// Used by: draft/server media editors and local refusal rendering.
const en = {
  title: "Product images",
  activeMainMissing:
    "This published product needs a main image. Add one, or unpublish it to save as a draft.",
  main: "Main images",
  mainHelp:
    "Up to 4 images. The first is the cover. Square photos 800px or larger are recommended.",
  detail: "Detail images",
  detailHelp: "Up to 20 images. Tall images may be up to 6 times their width.",
  sku: "Variant images",
  skuHelp:
    "One image for each value of the image option. Without one, buyers see the cover.",
  axis: "Image option",
  defaultAxis: "Use the first option",
  noAxis: "Add and save product options to use variant images.",
  useCover: "Use cover image",
  unused: "Images not used by the current image option",
  add: "Add images",
  addOption: "Add image",
  remove: "Delete image",
  earlier: "Move earlier",
  later: "Move later",
  toMain: "Move to main images",
  toDetail: "Move to detail images",
  cover: "Cover",
  loading: "Loading images…",
  processing: "Preparing photo…",
  saving: "Saving images…",
  retry: "Retry the same request",
  refresh: "Refresh images",
  ack: "I checked the image list",
  lost: "An earlier image request may have completed. Check the list before continuing.",
  unknown:
    "We could not confirm the result. Refresh the list or retry the same request. Do not upload it again.",
  done: "Images saved",
  axisChanged: "The image option changed. Check the images before continuing.",
  storageFailed:
    "This browser cannot keep upload recovery information. Allow site storage and try again.",
  failed: "Could not save the images. Refresh the list and try again.",
  unauthorized: "Your access changed. Refresh the page and sign in again.",
  mainFull: "Main images are limited to 4. Delete or move one first.",
  detailFull: "Detail images are limited to 20. Delete or move one first.",
  optionFull:
    "This option already has an image. Delete it before uploading another.",
  optionCap: "There are too many variant images. Delete unused images first.",
  type: "Choose a JPEG, PNG or WebP photo.",
  decode: "Could not read this photo. Choose another file.",
  size: "The photo is still larger than 2 MB after resizing. Choose a smaller image.",
  ratio: "Detail image height must be no more than 6 times its width.",
  changedAxis:
    "Delete unsaved variant images before changing the image option.",
  staleOption:
    "Product options changed. Remove images for values that are no longer used.",
  deleteConfirm: "Delete this image?",
  axisSaved: "Image option saved",
};
type Copy = typeof en;
const tw: Copy = {
  title: "商品圖片",
  activeMainMissing:
    "已上架商品需要至少 1 張主圖。請新增主圖，或先下架為草稿。",
  main: "主圖",
  mainHelp: "最多4張，第一張為封面。建議使用800px以上的正方形照片。",
  detail: "詳情圖",
  detailHelp: "最多20張，可上傳長圖，高度最多為寬度的6倍。",
  sku: "規格圖",
  skuHelp: "每個圖片規格值各一張；沒有規格圖時，買家會看到封面。",
  axis: "圖片規格",
  defaultAxis: "使用第一個規格",
  noAxis: "請先新增並儲存商品規格，才能上傳規格圖。",
  useCover: "使用封面",
  unused: "目前圖片規格未使用的圖片",
  add: "新增圖片",
  addOption: "新增規格圖",
  remove: "刪除圖片",
  earlier: "往前移",
  later: "往後移",
  toMain: "移到主圖",
  toDetail: "移到詳情圖",
  cover: "封面",
  loading: "載入圖片中…",
  processing: "處理照片中…",
  saving: "儲存圖片中…",
  retry: "重試同一筆操作",
  refresh: "重新讀取圖片",
  ack: "已確認圖片清單",
  lost: "上次圖片操作可能已完成，請查看清單後再繼續。",
  unknown: "不確定是否已完成，請重新讀取清單或重試同一筆操作，勿重複上傳。",
  done: "圖片已儲存",
  axisChanged: "圖片選項已變更。請檢查圖片後再繼續。",
  storageFailed: "瀏覽器無法保留上傳恢復資訊。請允許網站儲存後再試。",
  failed: "圖片未能儲存，請重新讀取清單後再試。",
  unauthorized: "登入或權限已變更，請重新整理並登入。",
  mainFull: "主圖最多4張，請先刪除一張或移到詳情圖。",
  detailFull: "詳情圖最多20張，請先刪除一張或移到主圖。",
  optionFull: "這個規格值已有圖片，請先刪除再上傳。",
  optionCap: "規格圖已達上限，請先刪除未使用的圖片。",
  type: "請選擇JPEG、PNG或WebP照片。",
  decode: "無法讀取這張照片，請換一個檔案。",
  size: "縮小後仍超過2MB，請選擇較小的照片。",
  ratio: "詳情長圖的高度最多為寬度的6倍。",
  changedAxis: "切換圖片規格前，請先移除尚未儲存的規格圖。",
  staleOption: "商品規格已變更，請移除不再使用的規格圖。",
  deleteConfirm: "確定刪除這張圖片？",
  axisSaved: "圖片規格已儲存",
};
const ja: Copy = {
  title: "商品画像",
  activeMainMissing:
    "公開中の商品にはメイン画像が必要です。画像を追加するか、非公開にして下書きに戻してください。",
  main: "メイン画像",
  mainHelp:
    "4枚まで。最初の画像がカバーです。800px以上の正方形写真をおすすめします。",
  detail: "詳細画像",
  detailHelp: "20枚まで。縦長画像の高さは幅の6倍までです。",
  sku: "バリエーション画像",
  skuHelp:
    "画像を使うオプションの各値につき1枚。未設定の場合はカバーを表示します。",
  axis: "画像を使うオプション",
  defaultAxis: "最初のオプションを使う",
  noAxis: "商品オプションを追加して保存すると画像を設定できます。",
  useCover: "カバーを使用",
  unused: "現在のオプションで使われていない画像",
  add: "画像を追加",
  addOption: "画像を追加",
  remove: "画像を削除",
  earlier: "前へ移動",
  later: "後へ移動",
  toMain: "メイン画像へ移動",
  toDetail: "詳細画像へ移動",
  cover: "カバー",
  loading: "画像を読み込み中…",
  processing: "写真を処理中…",
  saving: "画像を保存中…",
  retry: "同じ操作を再試行",
  refresh: "画像を再読み込み",
  ack: "画像一覧を確認しました",
  lost: "前回の操作が完了している可能性があります。画像一覧を確認してから続けてください。",
  unknown:
    "完了したか確認できません。一覧を再読み込みするか、同じ操作を再試行してください。再アップロードはしないでください。",
  done: "画像を保存しました",
  axisChanged:
    "画像の選択項目が変更されました。画像を確認してから続けてください。",
  storageFailed:
    "このブラウザではアップロードの復元情報を保存できません。サイトの保存を許可してから再試行してください。",
  failed: "画像を保存できませんでした。一覧を再読み込みしてお試しください。",
  unauthorized:
    "ログインまたは権限が変わりました。再読み込みしてログインしてください。",
  mainFull: "メイン画像は4枚までです。削除するか詳細画像へ移動してください。",
  detailFull:
    "詳細画像は20枚までです。削除するかメイン画像へ移動してください。",
  optionFull:
    "この値には画像があります。削除してからアップロードしてください。",
  optionCap:
    "バリエーション画像が上限に達しました。未使用の画像を削除してください。",
  type: "JPEG、PNG、WebPの写真を選んでください。",
  decode: "この写真を読み込めません。別のファイルを選んでください。",
  size: "縮小後も2MBを超えています。小さな写真を選んでください。",
  ratio: "詳細画像の高さは幅の6倍までです。",
  changedAxis:
    "画像オプションを変える前に、未保存のバリエーション画像を削除してください。",
  staleOption:
    "商品オプションが変わりました。使われなくなった値の画像を削除してください。",
  deleteConfirm: "この画像を削除しますか？",
  axisSaved: "画像オプションを保存しました",
};
const cn: Copy = {
  ...tw,
  title: "商品图片",
  activeMainMissing:
    "已上架商品需要至少 1 张主图。请新增主图，或先下架为草稿。",
  main: "主图",
  mainHelp: "最多4张，第一张为封面。建议使用800px以上的正方形照片。",
  detail: "详情图",
  detailHelp: "最多20张，可上传长图，高度最多为宽度的6倍。",
  sku: "规格图",
  skuHelp: "每个图片规格值各一张；没有规格图时，买家会看到封面。",
  axis: "图片规格",
  defaultAxis: "使用第一个规格",
  noAxis: "请先新增并保存商品规格，才能上传规格图。",
  useCover: "使用封面",
  unused: "当前图片规格未使用的图片",
  add: "新增图片",
  addOption: "新增规格图",
  remove: "删除图片",
  earlier: "向前移",
  later: "向后移",
  toMain: "移到主图",
  toDetail: "移到详情图",
  cover: "封面",
  loading: "加载图片中…",
  processing: "处理照片中…",
  saving: "保存图片中…",
  retry: "重试同一笔操作",
  refresh: "重新读取图片",
  ack: "已确认图片清单",
  lost: "上次图片操作可能已完成，请查看清单后再继续。",
  unknown: "不确定是否已完成，请重新读取清单或重试同一笔操作，勿重复上传。",
  done: "图片已保存",
  axisChanged: "图片选项已变更。请检查图片后再继续。",
  storageFailed: "浏览器无法保留上传恢复信息。请允许网站存储后再试。",
  failed: "图片未能保存，请重新读取清单后再试。",
  unauthorized: "登录或权限已变更，请刷新并登录。",
  mainFull: "主图最多4张，请先删除一张或移到详情图。",
  detailFull: "详情图最多20张，请先删除一张或移到主图。",
  optionFull: "这个规格值已有图片，请先删除再上传。",
  optionCap: "规格图已达上限，请先删除未使用的图片。",
  type: "请选择JPEG、PNG或WebP照片。",
  decode: "无法读取这张照片，请换一个文件。",
  size: "缩小后仍超过2MB，请选择较小的照片。",
  ratio: "详情长图的高度最多为宽度的6倍。",
  changedAxis: "切换图片规格前，请先移除尚未保存的规格图。",
  staleOption: "商品规格已变更，请移除不再使用的规格图。",
  deleteConfirm: "确定删除这张图片？",
  axisSaved: "图片规格已保存",
};
export const productMediaCopy = { en, "zh-TW": tw, "zh-CN": cn, ja };
export type ProductMediaCopy = Copy;
