// Copy for the admin discount-codes page (/{locale}/promotions); locales zh-CN / zh-TW / en (contracts/storefront-v2.md §F). Owns every
// string of components/Promotions.tsx and the error map for the codes of Go internal/httpapi/promotions.go (promo_exists, invalid_promotion,
// version_changed, idempotency_conflict) plus the shared authority codes.
// Non-goals: no rule (the server decides validity, windows and limits), no money formatting (the component uses lib/client money()).
// Depends on: @live-commerce/i18n (Locale) only.
import type { Locale } from "@live-commerce/i18n";

const en = {
  nav: "Discount codes",
  title: "Discount codes",
  subtitle: "Codes buyers type in the cart or at checkout. A code takes money off the goods, never off shipping, and one order uses one code.",
  store: "Store",
  loading: "Loading discount codes…",
  signedOut: "Sign in to manage discount codes.",
  forbidden: "You do not have permission to manage discount codes in this store.",
  notFound: "Discount codes are unavailable for this store.",
  unavailable: "Discount codes are temporarily unavailable. Try again.",
  noStore: "No authorized store is available.",
  retry: "Try again",
  listTitle: "Codes",
  empty: "No discount codes yet.",
  colCode: "Code",
  colDiscount: "Discount",
  colMinimum: "Minimum order",
  colWindow: "Valid (Taipei time)",
  colUsage: "Used",
  colPerBuyer: "Per buyer",
  colStatus: "Status",
  colActions: "Actions",
  statusActive: "Active",
  statusPaused: "Paused",
  noMinimum: "None",
  noLimit: "No limit",
  always: "Always",
  from: "from",
  until: "until",
  pause: "Pause",
  resume: "Resume",
  edit: "Edit",
  percentOff: "% off",
  createTitle: "New discount code",
  editTitle: "Edit discount code",
  code: "Code",
  codeHint: "3 to 24 letters, digits or hyphens. Buyers can type it in any case. It cannot be changed later.",
  kind: "Type",
  kindPercent: "Percent off",
  kindFixed: "Amount off",
  valuePercent: "Percent off (1 to 90)",
  valueFixed: "Amount off",
  minSubtotal: "Minimum order amount",
  minSubtotalHint: "Compared with the goods total before the discount. Leave empty for no minimum.",
  startsAt: "Starts (Taipei time)",
  endsAt: "Ends (Taipei time)",
  windowHint: "Leave empty for no start or end.",
  totalLimit: "Total uses",
  perBuyerLimit: "Uses per buyer",
  limitHint: "Leave empty for no limit. Cancelled and expired orders free their use. A buyer is recognised by phone number, email or device, so this limit is a deterrent, not a guarantee.",
  statusLabel: "Status",
  create: "Create code",
  save: "Save changes",
  cancel: "Cancel",
  invalid: "Check the form: the code, the amount or percent, the dates and the limits.",
  invalidWhole: "NT$ amounts are whole dollars, for example 500. Remove the decimals.",
  created: "Discount code created.",
  saved: "Changes saved.",
  toggled: "Status updated.",
  uncertain: "The result is unconfirmed. Press the same button again to retry safely.",
  errors: {
    promo_exists: "A discount code with this text already exists.",
    invalid_promotion: "The discount code settings are not valid.",
    version_changed: "This code changed since it was loaded. The list was refreshed; try again.",
    idempotency_conflict: "This request key was already used for a different request. Reload and try again.",
    forbidden: "You do not have permission to change discount codes.",
    unauthorized: "Your session ended. Sign in again.",
    retry_later: "Temporarily unavailable. Try again.",
    default: "The change could not be saved. Try again.",
  } as Record<string, string>,
};

const zhCN: typeof en = {
  nav: "优惠码",
  title: "优惠码",
  subtitle: "买家在购物车或结账时输入的代码。优惠码只减商品金额，不减运费，一张订单只能用一个。",
  store: "店铺",
  loading: "正在载入优惠码…",
  signedOut: "请登录后管理优惠码。",
  forbidden: "您没有管理本店优惠码的权限。",
  notFound: "本店暂时无法使用优惠码。",
  unavailable: "优惠码暂时不可用，请重试。",
  noStore: "没有可用的授权店铺。",
  retry: "重试",
  listTitle: "代码",
  empty: "还没有优惠码。",
  colCode: "代码",
  colDiscount: "优惠",
  colMinimum: "最低消费",
  colWindow: "有效期（台北时间）",
  colUsage: "已使用",
  colPerBuyer: "每位买家",
  colStatus: "状态",
  colActions: "操作",
  statusActive: "启用中",
  statusPaused: "已暂停",
  noMinimum: "无",
  noLimit: "不限",
  always: "长期有效",
  from: "自",
  until: "至",
  pause: "暂停",
  resume: "恢复",
  edit: "编辑",
  percentOff: "% 折扣",
  createTitle: "新增优惠码",
  editTitle: "编辑优惠码",
  code: "代码",
  codeHint: "3 到 24 个字母、数字或连字符。买家输入时不分大小写。创建后不能修改。",
  kind: "类型",
  kindPercent: "百分比折扣",
  kindFixed: "固定金额折扣",
  valuePercent: "折扣百分比（1 到 90）",
  valueFixed: "折扣金额",
  minSubtotal: "最低订单金额",
  minSubtotalHint: "与折扣前的商品总额比较。留空表示不设最低金额。",
  startsAt: "开始时间（台北时间）",
  endsAt: "结束时间（台北时间）",
  windowHint: "留空表示不设开始或结束时间。",
  totalLimit: "总使用次数",
  perBuyerLimit: "每位买家使用次数",
  limitHint: "留空表示不限。已取消和已过期的订单会释放其使用次数。买家以手机号、邮箱或设备识别，因此此限制是威慑而非保证。",
  statusLabel: "状态",
  create: "创建优惠码",
  save: "保存更改",
  cancel: "取消",
  invalid: "请检查表单：代码、金额或百分比、日期和次数限制。",
  invalidWhole: "新台币金额为整数元，例如 500，请去掉小数。",
  created: "优惠码已创建。",
  saved: "更改已保存。",
  toggled: "状态已更新。",
  uncertain: "结果尚未确认。请再次点击同一按钮，可安全重试。",
  errors: {
    promo_exists: "已存在相同的优惠码。",
    invalid_promotion: "优惠码设置无效。",
    version_changed: "此优惠码在载入后已被更改，列表已刷新，请重试。",
    idempotency_conflict: "此请求标识已用于另一个请求，请重新载入后再试。",
    forbidden: "您没有修改优惠码的权限。",
    unauthorized: "登录已失效，请重新登录。",
    retry_later: "暂时无法使用，请重试。",
    default: "无法保存更改，请重试。",
  },
};

const zhTW: typeof en = {
  nav: "優惠碼",
  title: "優惠碼",
  subtitle: "買家在購物車或結帳時輸入的代碼。優惠碼只減商品金額，不減運費，一張訂單只能用一個。",
  store: "店鋪",
  loading: "正在載入優惠碼…",
  signedOut: "請登入後管理優惠碼。",
  forbidden: "您沒有管理本店優惠碼的權限。",
  notFound: "本店暫時無法使用優惠碼。",
  unavailable: "優惠碼暫時無法使用，請重試。",
  noStore: "沒有可用的授權店鋪。",
  retry: "重試",
  listTitle: "代碼",
  empty: "還沒有優惠碼。",
  colCode: "代碼",
  colDiscount: "優惠",
  colMinimum: "最低消費",
  colWindow: "有效期（台北時間）",
  colUsage: "已使用",
  colPerBuyer: "每位買家",
  colStatus: "狀態",
  colActions: "操作",
  statusActive: "啟用中",
  statusPaused: "已暫停",
  noMinimum: "無",
  noLimit: "不限",
  always: "長期有效",
  from: "自",
  until: "至",
  pause: "暫停",
  resume: "恢復",
  edit: "編輯",
  percentOff: "% 折扣",
  createTitle: "新增優惠碼",
  editTitle: "編輯優惠碼",
  code: "代碼",
  codeHint: "3 到 24 個字母、數字或連字號。買家輸入時不分大小寫。建立後不能修改。",
  kind: "類型",
  kindPercent: "百分比折扣",
  kindFixed: "固定金額折扣",
  valuePercent: "折扣百分比（1 到 90）",
  valueFixed: "折扣金額",
  minSubtotal: "最低訂單金額",
  minSubtotalHint: "與折扣前的商品總額比較。留空表示不設最低金額。",
  startsAt: "開始時間（台北時間）",
  endsAt: "結束時間（台北時間）",
  windowHint: "留空表示不設開始或結束時間。",
  totalLimit: "總使用次數",
  perBuyerLimit: "每位買家使用次數",
  limitHint: "留空表示不限。已取消和已過期的訂單會釋放其使用次數。買家以手機號碼、電子郵件或裝置辨識，因此此限制是嚇阻而非保證。",
  statusLabel: "狀態",
  create: "建立優惠碼",
  save: "儲存變更",
  cancel: "取消",
  invalid: "請檢查表單：代碼、金額或百分比、日期和次數限制。",
  invalidWhole: "新台幣金額為整數元，例如 500，請去掉小數。",
  created: "優惠碼已建立。",
  saved: "變更已儲存。",
  toggled: "狀態已更新。",
  uncertain: "結果尚未確認。請再次點擊同一按鈕，可安全重試。",
  errors: {
    promo_exists: "已存在相同的優惠碼。",
    invalid_promotion: "優惠碼設定無效。",
    version_changed: "此優惠碼在載入後已被更改，列表已重新整理，請重試。",
    idempotency_conflict: "此請求識別碼已用於另一個請求，請重新載入後再試。",
    forbidden: "您沒有修改優惠碼的權限。",
    unauthorized: "登入已失效，請重新登入。",
    retry_later: "暫時無法使用，請重試。",
    default: "無法儲存變更，請重試。",
  },
};

export type PromotionsCopy = typeof en;
export const promotionsCopy: Record<Locale, PromotionsCopy> = { en, "zh-CN": zhCN, "zh-TW": zhTW };
