// Purpose: plain three-language report copy, including actual money/cohort and unavailable-label limitations.
// Depends on: locale type from the existing i18n package (type only).
// Used by: Reports.tsx, report subcomponents and focused copy tests.
import type { Locale } from "@live-commerce/i18n";

const en = {
  title: "Sales reports", subtitle: "Compare products, sales channels and live purchase steps for one store.",
  tabs: { products: "Products", channels: "Channels", funnel: "Live purchase funnel", "manual-orders": "Manual orders" },
  channels: { facebook_live: "Facebook Live", instagram_live: "Instagram Live", storefront: "Storefront", manual: "Manual entry" } as Record<string, string>,
  moneyBasis: "Collected = successful online payments; cash on delivery / transfers shown separately",
  moneyDetails: "Refunds are deducted from online payments. Offline collections include cash on delivery, pickup and confirmed bank transfers. Currencies and test/live amounts stay separate.",
  rangeBasis: "Dates use Taipei time (UTC+8). Payments follow their receipt date; order counts follow creation date and the deployment payment mode.",
  from: "From", to: "To", show: "Show report", store: "Store", noStore: "No store available", rangeInvalid: "Choose valid dates, in order, covering at most 92 days.",
  csv: "Download CSV", csvHint: "Each download requires export permission and records an export audit.", csvForbidden: "You do not have permission to export this report.",
  csvUnknown: "The export result is unknown. Check your downloads before starting another export. We did not retry.", csvDone: "CSV download started.",
  csvUnavailable: "Export is unavailable. Try again after refreshing the report.", exportUnknownPermission: "Export permission could not be confirmed. Refresh the report.",
  loading: "Loading report…", empty: "No data in this date range.", signedOut: "Your session ended. Sign in again to view reports.",
  forbidden: "You do not have permission to read this report.", notFound: "This store or report is unavailable.", unavailable: "Report unavailable. Refresh to try again.",
  retry: "Refresh report", exporting: "Preparing CSV…", test: "Test payments", live: "Live payments", currency: "Currency", environment: "Payment mode",
  product: "Product / SKU", units: "Online paid units", captured: "Online collected", refunded: "Online refunds", net: "Online net", offlineUnits: "Offline units", offline: "Offline collected",
  orders: "Orders", cancelled: "Cancelled", creator: "Created by", session: "Live session", unknownCreator: "Creator unavailable", noSession: "No linked live session", unknownSession: "Session title unavailable",
  staffFallback: "A creator name is shown only when your team access allows it. Unavailable names are marked below.",
  manualBasis: "Includes every manual order, including orders linked to Facebook or Instagram. These may appear in the live channel totals as well.",
  truncated: "Only the first 1,000 product rows are returned, ordered by online net. CSV uses the same limit.",
  channelChart: "Order counts by channel and currency", funnelChart: "Four nested live purchase steps", claimed: "Accepted claims", linkSent: "System link sent", ordered: "Order created", paid: "Payment received",
  conversion: "Conversion from previous step", totalConversion: "Claims to payment", noRatio: "No starting count", unlinked: "Orders without a system link",
  funnelBasis: "Unique accepted claims in this date range. Later steps can occur afterwards. System links count successful private replies; separately sent messages are excluded. Offline collections count as paid.",
  sortHint: "Sort amounts within each currency and payment mode; groups are kept separate.",
  tabsLabel: "Report type", previous: "Previous tab", next: "Next tab", wholeStore: "Whole store", hidden: "Report hidden until this tab is active.",
};

/** Localized copy; no data access or side effects. */
export const reportsCopy: Record<Locale, typeof en> = {
  en,
  "zh-TW": {
    title: "銷售報表", subtitle: "查看單一店鋪的商品、成交渠道與直播購買步驟。",
    tabs: { products: "商品", channels: "渠道", funnel: "直播成交漏斗", "manual-orders": "手工單" },
    channels: { facebook_live: "Facebook 直播", instagram_live: "Instagram 直播", storefront: "獨立站", manual: "手工建立" },
    moneyBasis: "實收 = 線上付款成功；貨到付款/轉帳另列",
    moneyDetails: "線上淨額已扣除退款。線下收款包含貨到付款、到店付款與已確認轉帳；不同幣別及測試／正式款項分開顯示。",
    rangeBasis: "日期採台北時間（UTC+8）。款項按收到日期計算；訂單數按建立日期與目前部署的付款模式計算。",
    from: "起日", to: "迄日", show: "查看報表", store: "店鋪", noStore: "沒有可用店鋪", rangeInvalid: "請選擇有效日期，起日不晚於迄日，合計最多 92 天。",
    csv: "匯出 CSV", csvHint: "每次下載需要匯出權限，並留下匯出紀錄。", csvForbidden: "你沒有匯出這份報表的權限。",
    csvUnknown: "匯出結果尚未確認。再次匯出前請先檢查下載紀錄；系統沒有自動重試。", csvDone: "已開始下載 CSV。",
    csvUnavailable: "目前無法匯出，請重新整理報表後再試。", exportUnknownPermission: "尚未確認匯出權限，請重新整理報表。",
    loading: "正在載入報表…", empty: "這段期間沒有資料。", signedOut: "登入已結束，請重新登入查看報表。",
    forbidden: "你沒有查看這份報表的權限。", notFound: "這間店鋪或報表目前無法使用。", unavailable: "目前無法載入報表，請重新整理再試。",
    retry: "重新整理報表", exporting: "正在準備 CSV…", test: "測試款項", live: "正式款項", currency: "幣別", environment: "付款模式",
    product: "商品／SKU", units: "線上已付件數", captured: "線上實收", refunded: "線上退款", net: "線上淨額", offlineUnits: "線下件數", offline: "線下實收",
    orders: "訂單數", cancelled: "已取消", creator: "建立人員", session: "直播場次", unknownCreator: "建立人員名稱無法取得", noSession: "未連結直播", unknownSession: "直播名稱無法取得",
    staffFallback: "僅在團隊權限允許時顯示人員名稱，無法取得的名稱會標示在表格中。",
    manualBasis: "包含所有手工單，也包含連結 Facebook 或 Instagram 的訂單；這些訂單亦可能出現在直播渠道中。",
    truncated: "商品最多顯示按線上淨額排列的前 1,000 筆，CSV 亦使用相同上限。",
    channelChart: "各渠道及幣別的訂單數", funnelChart: "四個逐步縮小的直播購買階段", claimed: "接受喊單", linkSent: "系統已發連結", ordered: "已建立訂單", paid: "已收到付款",
    conversion: "前一步轉化率", totalConversion: "喊單到付款", noRatio: "沒有起始數量", unlinked: "未經系統發連結的訂單",
    funnelBasis: "計算這段期間接受的唯一喊單，後續步驟可以發生於期間之後。系統連結只計成功的留言私回，另行私訊不計入；線下收款亦算已付。",
    sortHint: "金額在同幣別及付款模式內排序，各組保持分開。",
    tabsLabel: "報表種類", previous: "上一個分頁", next: "下一個分頁", wholeStore: "全店", hidden: "回到這個分頁後再顯示報表。",
  },
  "zh-CN": {
    title: "销售报表", subtitle: "查看单一店铺的商品、成交渠道与直播购买步骤。",
    tabs: { products: "商品", channels: "渠道", funnel: "直播成交漏斗", "manual-orders": "手工单" },
    channels: { facebook_live: "Facebook 直播", instagram_live: "Instagram 直播", storefront: "独立站", manual: "手工创建" },
    moneyBasis: "实收 = 线上付款成功；货到付款/转账另列",
    moneyDetails: "线上净额已扣除退款。线下收款包含货到付款、到店付款与已确认转账；不同币种及测试／正式款项分开显示。",
    rangeBasis: "日期采用台北时间（UTC+8）。款项按收到日期计算；订单数按创建日期与当前部署的付款模式计算。",
    from: "开始日期", to: "结束日期", show: "查看报表", store: "店铺", noStore: "没有可用店铺", rangeInvalid: "请选择有效日期，开始不晚于结束，合计最多 92 天。",
    csv: "导出 CSV", csvHint: "每次下载需要导出权限，并留下导出记录。", csvForbidden: "你没有导出这份报表的权限。",
    csvUnknown: "导出结果尚未确认。再次导出前请先检查下载记录；系统没有自动重试。", csvDone: "已开始下载 CSV。",
    csvUnavailable: "当前无法导出，请刷新报表后再试。", exportUnknownPermission: "尚未确认导出权限，请刷新报表。",
    loading: "正在加载报表…", empty: "这段期间没有数据。", signedOut: "登录已结束，请重新登录查看报表。",
    forbidden: "你没有查看这份报表的权限。", notFound: "这间店铺或报表当前无法使用。", unavailable: "当前无法加载报表，请刷新再试。",
    retry: "刷新报表", exporting: "正在准备 CSV…", test: "测试款项", live: "正式款项", currency: "币种", environment: "付款模式",
    product: "商品／SKU", units: "线上已付件数", captured: "线上实收", refunded: "线上退款", net: "线上净额", offlineUnits: "线下件数", offline: "线下实收",
    orders: "订单数", cancelled: "已取消", creator: "创建人员", session: "直播场次", unknownCreator: "创建人员名称无法取得", noSession: "未关联直播", unknownSession: "直播名称无法取得",
    staffFallback: "仅在团队权限允许时显示人员名称，无法取得的名称会标注在表格中。",
    manualBasis: "包含所有手工单，也包含关联 Facebook 或 Instagram 的订单；这些订单亦可能出现在直播渠道中。",
    truncated: "商品最多显示按线上净额排列的前 1,000 条，CSV 亦使用相同上限。",
    channelChart: "各渠道及币种的订单数", funnelChart: "四个逐步缩小的直播购买阶段", claimed: "接受喊单", linkSent: "系统已发链接", ordered: "已创建订单", paid: "已收到付款",
    conversion: "前一步转化率", totalConversion: "喊单到付款", noRatio: "没有起始数量", unlinked: "未经系统发链接的订单",
    funnelBasis: "计算这段期间接受的唯一喊单，后续步骤可以发生于期间之后。系统链接只计成功的评论私回，另行私信不计入；线下收款亦算已付。",
    sortHint: "金额在同币种及付款模式内排序，各组保持分开。",
    tabsLabel: "报表类型", previous: "上一个分页", next: "下一个分页", wholeStore: "全店", hidden: "回到这个分页后再显示报表。",
  },
};
