// Purpose: Copy (zh-TW / zh-CN / en) for the merchant returns (RMA) surfaces and the merchant order cancel
//   (contracts/returns-v1.md; unit W3-U5). Traditional Chinese is the primary merchant locale.
// Depends on: @live-commerce/i18n (Locale type only), ./returns-model.ts (rmaStates, returnReasons).
// Used by: apps/admin/components/OrderReturns.tsx, apps/admin/components/OrderDetailPanel.tsx (cancel button),
//   apps/admin/components/ReturnsList.tsx, apps/admin/components/OrderListFilters.tsx (page link).
// Invariants: returns-v1 §3 — the cancel refusal codes are merchant-actionable sentences; `refund_first` never
//   auto-refunds, it points at the existing refund section (Integrator 裁决, unit brief w3-u5).
import type { Locale } from "@live-commerce/i18n";
import type { ReturnReason, RmaState } from "./returns-model";

const zhTW = {
  sectionTitle: "退貨",
  listLink: "退貨與取消",
  pageTitle: "退貨管理",
  pageIntro: "已出貨訂單的退貨單（RMA）。點進訂單可登記退貨、收貨、驗貨與關閉。",
  stateFilter: "狀態",
  allStates: "全部狀態",
  states: {
    REGISTERED: "已登記",
    RECEIVED: "已收貨",
    INSPECTED: "已驗貨",
    CLOSED: "已關閉",
    CANCELLED: "已撤銷",
  } as Record<RmaState, string>,
  colOrder: "訂單",
  colCreated: "登記時間",
  colUpdated: "更新時間",
  colLines: "內容",
  colReason: "原因",
  colState: "狀態",
  viewOrder: "查看訂單",
  empty: "目前沒有退貨單。",
  emptyFiltered: "此狀態目前沒有退貨單。",
  loading: "載入中…",
  unavailable: "退貨資料暫時無法讀取。",
  retry: "重試",
  signedOut: "請重新登入後繼續。",
  forbidden: "此帳號沒有查看退貨的權限。",
  notFound: "找不到此商店或資料。",
  noStore: "沒有可用的商店。",
  none: "此訂單尚無退貨紀錄。",
  lineSummary: (registered: number, received: number | null) =>
    received === null ? `登記 ${registered} 件` : `登記 ${registered} 件・實收 ${received} 件`,
  // 登記退貨
  register: "登記退貨",
  registerTitle: "登記退貨",
  registerIntro: "選擇要退回的商品與數量。登記後請在收到包裹時回填實收數量。",
  registerReason: "退貨原因",
  reasons: {
    buyer_request: "買家要求",
    wrong_item: "商品寄錯",
    damaged: "商品受損",
    defective: "商品瑕疵",
    other: "其他",
  } as Record<ReturnReason, string>,
  note: "備註（選填）",
  notePlaceholder: "給倉庫的說明，最多 60 字",
  qtyToReturn: "退回數量",
  shippedQty: (qty: number) => `已出貨 ${qty} 件`,
  registerInvalid: "請至少選擇一件商品，且數量不得超過已出貨數量。",
  registerSubmit: "送出登記",
  registerDone: "退貨已登記。",
  // 收貨
  receive: "確認收貨",
  receiveTitle: "確認收到退貨",
  receiveIntro: "回填每個商品實際收到的數量（0 到登記數量）。",
  qtyReceived: "實收數量",
  registeredQty: (qty: number) => `登記 ${qty} 件`,
  receiveInvalid: "每行的實收數量需介於 0 與登記數量之間，且至少收到一件。",
  receiveSubmit: "確認收貨",
  receiveDone: "已記錄實收數量。",
  // 驗貨（處置）
  inspect: "驗貨與處置",
  inspectTitle: "驗貨與處置",
  inspectIntro: "決定每個實收商品的去向：可再售的數量會在關閉退貨單後回到可售庫存，不可售則報廢。",
  qtyRestock: "可再售",
  qtyScrap: "不可售（報廢）",
  receivedQty: (qty: number) => `實收 ${qty} 件`,
  inspectInvalid: "每行的「可再售 + 不可售」必須等於實收數量。",
  inspectSubmit: "送出驗貨結果",
  inspectDone: "驗貨結果已記錄。",
  // 關閉
  close: "關閉退貨單",
  closeTitle: "關閉退貨單",
  closeConfirm: (units: number) =>
    `關閉後，可再售的 ${units} 件會回到可售庫存，且無法再修改此退貨單。確定關閉？`,
  closeSubmit: "確定關閉",
  closeDone: "退貨單已關閉，庫存已更新。",
  refundHint: "如需退款，請使用本訂單的「退款」功能。",
  refundLink: "前往退款",
  // 撤銷登記
  cancelRma: "撤銷登記",
  cancelRmaTitle: "撤銷退貨登記",
  cancelRmaConfirm: "撤銷後此退貨單即失效，登記的數量會釋放。確定撤銷？",
  cancelRmaSubmit: "確定撤銷",
  cancelRmaDone: "退貨登記已撤銷。",
  refundLinked: "已連結退款",
  // 取消訂單
  cancelOrder: "取消訂單",
  cancelTitle: "取消訂單",
  cancelIntro: "取消後訂單即結束，會釋放已保留的庫存。此操作無法復原。",
  cancelReason: "取消原因",
  cancelReasonPlaceholder: "例如：買家要求取消（最多 60 字）",
  cancelSubmit: "確定取消訂單",
  cancelDone: "訂單已取消。",
  cancelInvalid: "請填寫取消原因。",
  // 退款失敗待處理
  gapsTitle: "退款失敗待處理",
  scrollHint: "左右捲動以查看完整表格",
  gapsIntro: "這些訂單已取消，但取消前進行中的退款後來失敗，買家的款項仍扣留中。請到訂單的「退款」重新退款，完成後會從此列表消失。",
  gapsEmpty: "目前沒有待處理的退款。",
  colCaptured: "已收金額",
  colRefunded: "已退款",
  colGap: "待退缺口",
  colCancelledAt: "取消時間",
  gapReason: "取消後退款失敗",
  goRefund: "前往訂單退款",
  sending: "送出中…",
  retrySame: "重試相同請求",
  uncertain: "結果尚不確定。重試會安全地送出相同請求，或重新整理查看最新狀態。",
  back: "返回",
  cancel: "取消",
  close2: "關閉視窗",
  errors: {
    not_shipped: "訂單尚未出貨，無法登記退貨。",
    not_returnable: "此訂單目前不可退貨（款項或取貨狀態尚未完成）。",
    version_changed: "退貨單已被其他人更新，請重新整理後再試。",
    invalid_state: "此退貨單的狀態已改變，請重新整理。",
    has_returns: "此訂單有進行中的退貨，請先完成或撤銷退貨單。",
    already_cancelled: "訂單已取消。",
    state_changed: "訂單狀態已改變，請重新整理後再試。",
    payment_in_flight: "此訂單有付款正在進行中，請等候付款完成或失效後再取消。",
    refund_first: "請先完成全額退款，再取消訂單。",
    already_shipped: "訂單已出貨，無法取消；如需收回商品請改用「登記退貨」。",
    cvs_attempt_in_flight: "超商寄件正在建立中，請稍後再試。",
    payment_review_open: "此訂單有進行中的付款審查，請先完成審查。",
    conflict: "此請求鍵已被用於另一個請求，請重新整理後再試。",
    unknown_line: "退貨內容與訂單商品不符，請重新整理後再試。",
    ambiguous_line: "此商品位於多個倉庫，系統無法判定退貨倉別，請聯絡客服。",
    exceeds_shipped: "退貨數量超過已出貨數量（含其他退貨單已登記的數量）。",
    exceeds_registered: "數量超過登記數量。",
    invalid_quantities: "數量不正確，請確認後再試。",
    quantities_mismatch: "每行的「可再售 + 不可售」必須等於實收數量。",
    lines_incomplete: "請為退貨單的每一行填寫數量。",
    nothing_received: "實收數量至少需有一件。",
    refund_mismatch: "連結的退款不屬於此訂單。",
    not_cancellable: "此訂單的付款方式或狀態無法線上取消（銀行轉帳訂單請等候逾期或走線下退款）。",
    invalid_request: "請求內容不正確，請重新整理後再試。",
    forbidden: "此帳號沒有此操作的權限。",
    unauthorized: "請重新登入後繼續。",
    retry_later: "系統暫時忙碌，請稍後再試。",
    unavailable: "服務暫時無法使用，請稍後再試。",
    default: "操作未完成，請重新整理後再試。",
  } as Record<string, string>,
};

const zhCN: typeof zhTW = {
  sectionTitle: "退货",
  listLink: "退货与取消",
  pageTitle: "退货管理",
  pageIntro: "已发货订单的退货单（RMA）。点进订单可登记退货、收货、验货与关闭。",
  stateFilter: "状态",
  allStates: "全部状态",
  states: {
    REGISTERED: "已登记",
    RECEIVED: "已收货",
    INSPECTED: "已验货",
    CLOSED: "已关闭",
    CANCELLED: "已撤销",
  },
  colOrder: "订单",
  colCreated: "登记时间",
  colUpdated: "更新时间",
  colLines: "内容",
  colReason: "原因",
  colState: "状态",
  viewOrder: "查看订单",
  empty: "目前没有退货单。",
  emptyFiltered: "此状态目前没有退货单。",
  loading: "加载中…",
  unavailable: "退货数据暂时无法读取。",
  retry: "重试",
  signedOut: "请重新登录后继续。",
  forbidden: "此账号没有查看退货的权限。",
  notFound: "找不到此商店或数据。",
  noStore: "没有可用的商店。",
  none: "此订单尚无退货记录。",
  lineSummary: (registered, received) =>
    received === null ? `登记 ${registered} 件` : `登记 ${registered} 件・实收 ${received} 件`,
  register: "登记退货",
  registerTitle: "登记退货",
  registerIntro: "选择要退回的商品与数量。登记后请在收到包裹时回填实收数量。",
  registerReason: "退货原因",
  reasons: {
    buyer_request: "买家要求",
    wrong_item: "商品寄错",
    damaged: "商品受损",
    defective: "商品瑕疵",
    other: "其他",
  },
  note: "备注（选填）",
  notePlaceholder: "给仓库的说明，最多 60 字",
  qtyToReturn: "退回数量",
  shippedQty: (qty) => `已发货 ${qty} 件`,
  registerInvalid: "请至少选择一件商品，且数量不得超过已发货数量。",
  registerSubmit: "提交登记",
  registerDone: "退货已登记。",
  receive: "确认收货",
  receiveTitle: "确认收到退货",
  receiveIntro: "回填每个商品实际收到的数量（0 到登记数量）。",
  qtyReceived: "实收数量",
  registeredQty: (qty) => `登记 ${qty} 件`,
  receiveInvalid: "每行的实收数量需介于 0 与登记数量之间，且至少收到一件。",
  receiveSubmit: "确认收货",
  receiveDone: "已记录实收数量。",
  inspect: "验货与处置",
  inspectTitle: "验货与处置",
  inspectIntro: "决定每个实收商品的去向：可再售的数量会在关闭退货单后回到可售库存，不可售则报废。",
  qtyRestock: "可再售",
  qtyScrap: "不可售（报废）",
  receivedQty: (qty) => `实收 ${qty} 件`,
  inspectInvalid: "每行的「可再售 + 不可售」必须等于实收数量。",
  inspectSubmit: "提交验货结果",
  inspectDone: "验货结果已记录。",
  close: "关闭退货单",
  closeTitle: "关闭退货单",
  closeConfirm: (units) => `关闭后，可再售的 ${units} 件会回到可售库存，且无法再修改此退货单。确定关闭？`,
  closeSubmit: "确定关闭",
  closeDone: "退货单已关闭，库存已更新。",
  refundHint: "如需退款，请使用本订单的「退款」功能。",
  refundLink: "前往退款",
  cancelRma: "撤销登记",
  cancelRmaTitle: "撤销退货登记",
  cancelRmaConfirm: "撤销后此退货单即失效，登记的数量会释放。确定撤销？",
  cancelRmaSubmit: "确定撤销",
  cancelRmaDone: "退货登记已撤销。",
  refundLinked: "已关联退款",
  cancelOrder: "取消订单",
  cancelTitle: "取消订单",
  cancelIntro: "取消后订单即结束，会释放已保留的库存。此操作无法复原。",
  cancelReason: "取消原因",
  cancelReasonPlaceholder: "例如：买家要求取消（最多 60 字）",
  cancelSubmit: "确定取消订单",
  cancelDone: "订单已取消。",
  cancelInvalid: "请填写取消原因。",
  gapsTitle: "退款失败待处理",
  scrollHint: "左右滚动以查看完整表格",
  gapsIntro: "这些订单已取消，但取消前进行中的退款后来失败，买家的款项仍扣留中。请到订单的「退款」重新退款，完成后会从此列表消失。",
  gapsEmpty: "目前没有待处理的退款。",
  colCaptured: "已收金额",
  colRefunded: "已退款",
  colGap: "待退缺口",
  colCancelledAt: "取消时间",
  gapReason: "取消后退款失败",
  goRefund: "前往订单退款",
  sending: "提交中…",
  retrySame: "重试相同请求",
  uncertain: "结果尚不确定。重试会安全地提交相同请求，或刷新查看最新状态。",
  back: "返回",
  cancel: "取消",
  close2: "关闭窗口",
  errors: {
    not_shipped: "订单尚未发货，无法登记退货。",
    not_returnable: "此订单目前不可退货（款项或取货状态尚未完成）。",
    version_changed: "退货单已被其他人更新，请刷新后再试。",
    invalid_state: "此退货单的状态已改变，请刷新。",
    has_returns: "此订单有进行中的退货，请先完成或撤销退货单。",
    already_cancelled: "订单已取消。",
    state_changed: "订单状态已改变，请刷新后再试。",
    payment_in_flight: "此订单有付款正在进行中，请等候付款完成或失效后再取消。",
    refund_first: "请先完成全额退款，再取消订单。",
    already_shipped: "订单已发货，无法取消；如需收回商品请改用「登记退货」。",
    cvs_attempt_in_flight: "超商寄件正在创建中，请稍后再试。",
    payment_review_open: "此订单有进行中的付款审查，请先完成审查。",
    conflict: "此请求键已被用于另一个请求，请刷新后再试。",
    unknown_line: "退货内容与订单商品不符，请刷新后再试。",
    ambiguous_line: "此商品位于多个仓库，系统无法判定退货仓别，请联系客服。",
    exceeds_shipped: "退货数量超过已发货数量（含其他退货单已登记的数量）。",
    exceeds_registered: "数量超过登记数量。",
    invalid_quantities: "数量不正确，请确认后再试。",
    quantities_mismatch: "每行的「可再售 + 不可售」必须等于实收数量。",
    lines_incomplete: "请为退货单的每一行填写数量。",
    nothing_received: "实收数量至少需有一件。",
    refund_mismatch: "关联的退款不属于此订单。",
    not_cancellable: "此订单的付款方式或状态无法在线取消（银行转账订单请等候逾期或走线下退款）。",
    invalid_request: "请求内容不正确，请刷新后再试。",
    forbidden: "此账号没有此操作的权限。",
    unauthorized: "请重新登录后继续。",
    retry_later: "系统暂时忙碌，请稍后再试。",
    unavailable: "服务暂时无法使用，请稍后再试。",
    default: "操作未完成，请刷新后再试。",
  },
};

const en: typeof zhTW = {
  sectionTitle: "Returns",
  listLink: "Returns & cancellations",
  pageTitle: "Returns",
  pageIntro: "Return merchandise authorizations (RMA) for shipped orders. Open an order to register, receive, inspect and close a return.",
  stateFilter: "State",
  allStates: "All states",
  states: {
    REGISTERED: "Registered",
    RECEIVED: "Received",
    INSPECTED: "Inspected",
    CLOSED: "Closed",
    CANCELLED: "Cancelled",
  },
  colOrder: "Order",
  colCreated: "Registered",
  colUpdated: "Updated",
  colLines: "Contents",
  colReason: "Reason",
  colState: "State",
  viewOrder: "Open order",
  empty: "No returns yet.",
  emptyFiltered: "No returns in this state.",
  loading: "Loading…",
  unavailable: "Returns could not be loaded.",
  retry: "Try again",
  signedOut: "Sign in again to continue.",
  forbidden: "This account does not have permission to view returns.",
  notFound: "Store or data not found.",
  noStore: "No store available.",
  none: "No returns registered for this order.",
  lineSummary: (registered, received) =>
    received === null ? `${registered} registered` : `${registered} registered · ${received} received`,
  register: "Register a return",
  registerTitle: "Register a return",
  registerIntro: "Choose the items and quantities the buyer sends back. Record the actually received quantities when the parcel arrives.",
  registerReason: "Return reason",
  reasons: {
    buyer_request: "Buyer request",
    wrong_item: "Wrong item shipped",
    damaged: "Damaged",
    defective: "Defective",
    other: "Other",
  },
  note: "Note (optional)",
  notePlaceholder: "Note for the warehouse, up to 60 characters",
  qtyToReturn: "Quantity to return",
  shippedQty: (qty) => `${qty} shipped`,
  registerInvalid: "Choose at least one item; quantities cannot exceed the shipped quantity.",
  registerSubmit: "Register return",
  registerDone: "Return registered.",
  receive: "Confirm receipt",
  receiveTitle: "Confirm the returned parcel",
  receiveIntro: "Enter how many units of each item actually arrived (0 up to the registered quantity).",
  qtyReceived: "Quantity received",
  registeredQty: (qty) => `${qty} registered`,
  receiveInvalid: "Each line must be between 0 and the registered quantity, and at least one unit must arrive.",
  receiveSubmit: "Confirm receipt",
  receiveDone: "Received quantities recorded.",
  inspect: "Inspect & disposition",
  inspectTitle: "Inspect & disposition",
  inspectIntro: "Decide the disposition of each received unit: sellable units return to sellable stock when the RMA closes; unsellable units are scrapped.",
  qtyRestock: "Sellable",
  qtyScrap: "Unsellable (scrap)",
  receivedQty: (qty) => `${qty} received`,
  inspectInvalid: "Per line, sellable + unsellable must equal the received quantity.",
  inspectSubmit: "Submit inspection",
  inspectDone: "Inspection recorded.",
  close: "Close RMA",
  closeTitle: "Close the RMA",
  closeConfirm: (units) =>
    `Closing returns ${units} sellable unit(s) to sellable stock and the RMA can no longer be changed. Close it?`,
  closeSubmit: "Close RMA",
  closeDone: "RMA closed; stock updated.",
  refundHint: "To refund the buyer, use this order's “Refund” section.",
  refundLink: "Go to refunds",
  cancelRma: "Withdraw registration",
  cancelRmaTitle: "Withdraw the return registration",
  cancelRmaConfirm: "The RMA becomes void and its registered quantities are released. Withdraw it?",
  cancelRmaSubmit: "Withdraw",
  cancelRmaDone: "Return registration withdrawn.",
  refundLinked: "Refund linked",
  cancelOrder: "Cancel order",
  cancelTitle: "Cancel order",
  cancelIntro: "Cancelling ends the order and releases the reserved stock. This cannot be undone.",
  cancelReason: "Cancellation reason",
  cancelReasonPlaceholder: "E.g. buyer asked to cancel (up to 60 characters)",
  cancelSubmit: "Cancel this order",
  cancelDone: "Order cancelled.",
  cancelInvalid: "Please enter a cancellation reason.",
  gapsTitle: "Failed refunds to redo",
  scrollHint: "Scroll horizontally to view the full table",
  gapsIntro: "These orders were cancelled while a refund was still in flight, and that refund later failed — the buyer's money is still held. Refund again from the order's “Refund” section; the row disappears once the captured amount is covered.",
  gapsEmpty: "No pending failed refunds.",
  colCaptured: "Captured",
  colRefunded: "Refunded",
  colGap: "Outstanding",
  colCancelledAt: "Cancelled at",
  gapReason: "Refund failed after cancel",
  goRefund: "Open order refund",
  sending: "Sending…",
  retrySame: "Retry the same request",
  uncertain: "The result is not known yet. Retrying sends the identical request safely, or reload to see the latest state.",
  back: "Back",
  cancel: "Cancel",
  close2: "Close dialog",
  errors: {
    not_shipped: "The order has not shipped yet; a return cannot be registered.",
    not_returnable: "This order is not returnable right now (payment or pickup is not complete).",
    version_changed: "The RMA was updated by someone else. Reload and try again.",
    invalid_state: "The RMA's state has changed. Reload to see it.",
    has_returns: "This order has a live return; finish or withdraw it first.",
    already_cancelled: "The order is already cancelled.",
    state_changed: "The order state has changed. Reload and try again.",
    payment_in_flight: "A payment is in flight for this order. Wait for it to finish or lapse before cancelling.",
    refund_first: "Refund the captured amount in full first, then cancel the order.",
    already_shipped: "The order has shipped and cannot be cancelled; use “Register a return” to take the goods back.",
    cvs_attempt_in_flight: "A CVS shipment is being created. Try again shortly.",
    payment_review_open: "A payment review is open on this order. Resolve it first.",
    conflict: "This request key was used for a different request. Reload and try again.",
    unknown_line: "The return does not match the order's items. Reload and try again.",
    ambiguous_line: "This item is stocked in more than one warehouse; the system cannot pick one. Contact support.",
    exceeds_shipped: "The return quantity exceeds the shipped quantity (including quantities on other RMAs).",
    exceeds_registered: "The quantity exceeds the registered quantity.",
    invalid_quantities: "The quantities are not valid. Check and try again.",
    quantities_mismatch: "Per line, sellable + unsellable must equal the received quantity.",
    lines_incomplete: "Enter a quantity for every line of the RMA.",
    nothing_received: "At least one unit must be received.",
    refund_mismatch: "The linked refund does not belong to this order.",
    not_cancellable: "This order's payment method or state cannot be cancelled online (a bank-transfer order ends by expiry or the offline refund path).",
    invalid_request: "The request was not valid. Reload and try again.",
    forbidden: "This account does not have permission for this action.",
    unauthorized: "Sign in again to continue.",
    retry_later: "Temporarily busy. Try again shortly.",
    unavailable: "Temporarily unavailable. Try again shortly.",
    default: "The action could not be completed. Reload and try again.",
  },
};

export type ReturnsCopy = typeof zhTW;
export const returnsCopy: Record<Locale, ReturnsCopy> = { en, "zh-CN": zhCN, "zh-TW": zhTW };
/** Maps a Go refusal code to merchant copy (returns-v1 §7 closed set); unknown codes fall back to `default`. */
export const returnsError = (c: ReturnsCopy, code: string): string => c.errors[code] ?? c.errors.default;
