import type { Locale } from "@live-commerce/i18n";

const en = {
  title: "Delivery & payment settings",
  subtitle: "Set up your own account and merchant-arranged delivery.",
  steps: [
    "Choose platform",
    "Connect account",
    "Configure methods",
    "Check status",
  ],
  platformTitle: "Choose what to configure",
  payuni: "PAYUNi payment",
  manual: "Merchant-arranged delivery",
  payuniHint:
    "Use your own PAYUNi merchant account. Configuration alone does not permit live collection.",
  manualHint:
    "You arrange shipment outside this platform. No carrier booking, label, tracking or delivery guarantee is created.",
  next: "Continue",
  back: "Previous",
  saveContinue: "Save account and continue",
  save: "Save",
  refresh: "Refresh status",
  accountTitle: "Your PAYUNi account",
  accountHint: "Choose a saved account or enter new merchant credentials.",
  accountChoice: "Account",
  newAccount: "Create a new account",
  rotate: "Rotate credentials for this account",
  environment: "Environment",
  sandbox: "Sandbox",
  live: "Live",
  merchantID: "Merchant ID (MerID)",
  hashKey: "HashKey",
  hashIV: "HashIV",
  secretHint: "Enter credentials each time; they are never shown again.",
  accountSaved:
    "Account configuration saved. Provider qualification is still unverified.",
  accountUnverified:
    "Saved credentials are CONFIGURED_UNVERIFIED; no payment or provider validation occurred.",
  marketTitle: "Market",
  market: "Selected market",
  createMarket: "Create market",
  marketCode: "Market code",
  marketName: "Market name",
  currency: "Store currency",
  marketInactive:
    "This market is inactive. Service changes require an active market.",
  country: "Country",
  methodTitle: "PAYUNi payment methods",
  method: "Payment method",
  enabled: "Enabled",
  visible: "Visible to buyers",
  disabledReason:
    "Payment activation is gated. You can save a disabled configuration draft; buyer visibility is separate from availability.",
  nameHans: "Simplified Chinese name",
  nameHant: "Traditional Chinese name",
  nameEN: "English name",
  sort: "Sort order",
  minAmount: "Minimum amount (minor units)",
  maxAmount: "Maximum amount (minor units)",
  saveMethod: "Save disabled payment draft",
  methodSaved: "Payment draft saved. It remains disabled.",
  deliveryTitle: "Merchant-arranged delivery",
  service: "Delivery service",
  createService: "New service",
  serviceCode: "Stable service code",
  deliveryKind: "Delivery kind",
  home: "Home delivery",
  cvs711: "7-ELEVEN pickup",
  cvsFamily: "FamilyMart pickup",
  shipping: "Flat shipping (minor units)",
  taxMode: "Tax mode",
  taxNone: "No tax",
  taxInclusive: "Included",
  taxExclusive: "Added",
  taxBasis: "Tax basis",
  goods: "Goods",
  goodsShipping: "Goods and shipping",
  taxRate: "Tax rate (basis points)",
  ttl: "Quote lifetime (seconds)",
  policyEnabled: "Enable pricing policy",
  serviceEnabled: "Enable delivery service",
  ref: "Configuration reference / reason",
  refHint:
    "Required for every policy version. Enter a new nonsecret reference; previous text is not returned.",
  savePolicy: "Save pricing policy",
  saveService: "Save delivery service",
  policySaved: "Pricing policy saved. Save the service separately.",
  serviceSaved: "Delivery service saved.",
  prereq:
    "An active market and explicitly enabled policy are required before saving a service.",
  sequential:
    "Policy and service are two separate saves. If service saving fails, the policy remains saved.",
  statusTitle: "Current setup status",
  platform: "Platform",
  account: "Account",
  payment: "Payment method",
  qualification: "Provider qualification",
  runtime: "Runtime availability",
  notChecked: "Not checked",
  notConfigured: "Not configured",
  notApproved: "Not verified",
  unknown:
    "Result unknown. Keep this command and retry with the same key; credentials require re-entry.",
  retry: "Retry pending command",
  pending: "Saving…",
  requestID: "Request ID",
  conflict: "Configuration changed. Reload before saving a corrected version.",
  forbidden: "Your account cannot change this setting.",
  invalid: "Check the required values and their allowed ranges.",
  failed: "Request failed. Check access or connection, then reload.",
  storage:
    "Reliable browser storage or cross-tab lock is unavailable. Mutations are blocked.",
  session: "Your session changed. Reload and sign in again before saving.",
  noStore: "No authorized store is available.",
  recoverWorkspace: "Return to sign-in or workspace setup",
  loading: "Loading saved configuration…",
  loadMore: "Load more",
  inspect: "Inspect runtime availability",
  noMethods: "No payment methods configured.",
  notAvailable: "Unavailable",
  saved: "Saved configuration",
  providerGate: "No provider admission evidence is available here.",
};
export type SettingsCopy = typeof en;
export const settingsCopy: Record<Locale, SettingsCopy> = {
  en,
  "zh-CN": {
    title: "物流与收款设置",
    subtitle: "配置您自己的收款账户与商家自行安排配送。",
    steps: ["选择平台", "连接账户", "配置方式", "检查状态"],
    platformTitle: "选择要配置的服务",
    payuni: "PAYUNi 收款",
    manual: "商家自行安排配送",
    payuniHint: "使用您自己的 PAYUNi 商户账户。保存配置不代表可以正式收款。",
    manualHint:
      "配送由商家在平台外安排；不会自动建单、购买面单、查询轨迹或保证送达。",
    next: "继续",
    back: "上一步",
    saveContinue: "保存账户并继续",
    save: "保存",
    refresh: "刷新状态",
    accountTitle: "您的 PAYUNi 账户",
    accountHint: "选择已保存账户，或输入新的商户凭据。",
    accountChoice: "账户",
    newAccount: "创建新账户",
    rotate: "轮换此账户凭据",
    environment: "环境",
    sandbox: "沙盒测试",
    live: "正式环境",
    merchantID: "商户代号（MerID）",
    hashKey: "HashKey",
    hashIV: "HashIV",
    secretHint: "每次需重新输入密钥；保存后无法再次查看。",
    accountSaved: "账户配置已保存；供应商资格仍未验证。",
    accountUnverified:
      "仅保存 CONFIGURED_UNVERIFIED 配置；未验证供应商或发起收款。",
    marketTitle: "市场",
    market: "所选市场",
    createMarket: "创建市场",
    marketCode: "市场代码",
    marketName: "市场名称",
    currency: "店铺币种",
    marketInactive: "该市场未激活。保存配送服务需要已激活市场。",
    country: "国家/地区",
    methodTitle: "PAYUNi 收款方式",
    method: "收款方式",
    enabled: "已启用",
    visible: "向买家展示",
    disabledReason:
      "正式启用仍受门禁限制。可保存禁用草稿；买家展示不等于运行时可用。",
    nameHans: "简体中文名称",
    nameHant: "繁体中文名称",
    nameEN: "英文名称",
    sort: "排序",
    minAmount: "最低金额（最小货币单位）",
    maxAmount: "最高金额（最小货币单位）",
    saveMethod: "保存禁用收款草稿",
    methodSaved: "收款草稿已保存，仍处于禁用状态。",
    deliveryTitle: "商家自行安排配送",
    service: "配送服务",
    createService: "新建服务",
    serviceCode: "固定服务代码",
    deliveryKind: "配送类型",
    home: "宅配",
    cvs711: "7-ELEVEN 取货",
    cvsFamily: "全家取货",
    shipping: "固定运费（最小货币单位）",
    taxMode: "税费模式",
    taxNone: "不计税",
    taxInclusive: "含税",
    taxExclusive: "另计税",
    taxBasis: "税费基数",
    goods: "商品",
    goodsShipping: "商品与运费",
    taxRate: "税率（基点）",
    ttl: "报价有效期（秒）",
    policyEnabled: "启用价格政策",
    serviceEnabled: "启用配送服务",
    ref: "配置依据／原因",
    refHint: "每个政策版本必填新的非密钥依据；旧内容不会返回。",
    savePolicy: "保存价格政策",
    saveService: "保存配送服务",
    policySaved: "价格政策已保存；配送服务需要单独保存。",
    serviceSaved: "配送服务已保存。",
    prereq: "保存服务前，市场须已激活且政策须明确启用。",
    sequential: "政策和服务分两次保存。服务失败时，已保存的政策会保留。",
    statusTitle: "当前设置状态",
    platform: "平台",
    account: "账户",
    payment: "收款方式",
    qualification: "供应商资格",
    runtime: "运行时可用性",
    notChecked: "未检查",
    notConfigured: "未配置",
    notApproved: "未验证",
    unknown: "结果未知。保留原请求标识重试；凭据需重新输入。",
    retry: "重试待确认指令",
    pending: "保存中…",
    requestID: "请求 ID",
    conflict: "配置已变化。请重新读取，修正后再用新指令保存。",
    forbidden: "当前账户无权修改。",
    invalid: "请检查必填值及允许范围。",
    failed: "请求失败，请检查权限或连接后重新读取。",
    storage: "浏览器存储或跨标签页锁不可用，写入已阻止。",
    session: "会话已变化。请重新加载并登录后再保存。",
    noStore: "没有可访问的店铺。",
    recoverWorkspace: "返回登录或工作区设置",
    loading: "正在读取已保存配置…",
    loadMore: "读取更多",
    inspect: "检查运行时可用性",
    noMethods: "尚未配置收款方式。",
    notAvailable: "不可用",
    saved: "已保存配置",
    providerGate: "这里没有供应商准入证据。",
  },
  "zh-TW": {
    title: "物流與收款設定",
    subtitle: "設定您自己的收款帳戶與商家自行安排配送。",
    steps: ["選擇平台", "連接帳戶", "設定方式", "檢查狀態"],
    platformTitle: "選擇要設定的服務",
    payuni: "PAYUNi 收款",
    manual: "商家自行安排配送",
    payuniHint: "使用您自己的 PAYUNi 商戶帳戶。儲存設定不代表可以正式收款。",
    manualHint:
      "配送由商家在平台外安排；不會自動建單、購買面單、查詢軌跡或保證送達。",
    next: "繼續",
    back: "上一步",
    saveContinue: "儲存帳戶並繼續",
    save: "儲存",
    refresh: "重新整理狀態",
    accountTitle: "您的 PAYUNi 帳戶",
    accountHint: "選擇已儲存帳戶，或輸入新的商戶憑證。",
    accountChoice: "帳戶",
    newAccount: "建立新帳戶",
    rotate: "輪換此帳戶憑證",
    environment: "環境",
    sandbox: "沙盒測試",
    live: "正式環境",
    merchantID: "商戶代號（MerID）",
    hashKey: "HashKey",
    hashIV: "HashIV",
    secretHint: "每次須重新輸入密鑰；儲存後無法再次查看。",
    accountSaved: "帳戶設定已儲存；供應商資格仍未驗證。",
    accountUnverified:
      "僅儲存 CONFIGURED_UNVERIFIED 設定；未驗證供應商或發起收款。",
    marketTitle: "市場",
    market: "所選市場",
    createMarket: "建立市場",
    marketCode: "市場代碼",
    marketName: "市場名稱",
    currency: "店鋪幣別",
    marketInactive: "該市場未啟用。儲存配送服務需要已啟用市場。",
    country: "國家／地區",
    methodTitle: "PAYUNi 收款方式",
    method: "收款方式",
    enabled: "已啟用",
    visible: "向買家顯示",
    disabledReason:
      "正式啟用仍受門檻限制。可儲存停用草稿；向買家顯示不等於執行時可用。",
    nameHans: "簡體中文名稱",
    nameHant: "繁體中文名稱",
    nameEN: "英文名稱",
    sort: "排序",
    minAmount: "最低金額（最小貨幣單位）",
    maxAmount: "最高金額（最小貨幣單位）",
    saveMethod: "儲存停用收款草稿",
    methodSaved: "收款草稿已儲存，仍處於停用狀態。",
    deliveryTitle: "商家自行安排配送",
    service: "配送服務",
    createService: "新增服務",
    serviceCode: "固定服務代碼",
    deliveryKind: "配送類型",
    home: "宅配",
    cvs711: "7-ELEVEN 取貨",
    cvsFamily: "全家取貨",
    shipping: "固定運費（最小貨幣單位）",
    taxMode: "稅費模式",
    taxNone: "不計稅",
    taxInclusive: "含稅",
    taxExclusive: "另計稅",
    taxBasis: "稅費基數",
    goods: "商品",
    goodsShipping: "商品與運費",
    taxRate: "稅率（基點）",
    ttl: "報價有效期（秒）",
    policyEnabled: "啟用價格政策",
    serviceEnabled: "啟用配送服務",
    ref: "設定依據／原因",
    refHint: "每個政策版本必填新的非密鑰依據；舊內容不會返回。",
    savePolicy: "儲存價格政策",
    saveService: "儲存配送服務",
    policySaved: "價格政策已儲存；配送服務需要另外儲存。",
    serviceSaved: "配送服務已儲存。",
    prereq: "儲存服務前，市場須已啟用且政策須明確啟用。",
    sequential: "政策和服務分兩次儲存。服務失敗時，已儲存的政策會保留。",
    statusTitle: "目前設定狀態",
    platform: "平台",
    account: "帳戶",
    payment: "收款方式",
    qualification: "供應商資格",
    runtime: "執行時可用性",
    notChecked: "未檢查",
    notConfigured: "未設定",
    notApproved: "未驗證",
    unknown: "結果未知。保留原請求識別碼重試；憑證須重新輸入。",
    retry: "重試待確認指令",
    pending: "儲存中…",
    requestID: "請求 ID",
    conflict: "設定已變更。請重新讀取，修正後再用新指令儲存。",
    forbidden: "目前帳戶無權修改。",
    invalid: "請檢查必填值及允許範圍。",
    failed: "請求失敗，請檢查權限或連線後重新讀取。",
    storage: "瀏覽器儲存或跨分頁鎖不可用，寫入已阻止。",
    session: "工作階段已變更。請重新載入並登入後再儲存。",
    noStore: "沒有可存取的店鋪。",
    recoverWorkspace: "返回登入或工作區設定",
    loading: "正在讀取已儲存設定…",
    loadMore: "讀取更多",
    inspect: "檢查執行時可用性",
    noMethods: "尚未設定收款方式。",
    notAvailable: "不可用",
    saved: "已儲存設定",
    providerGate: "這裡沒有供應商准入證據。",
  },
};

const reasonText: Record<Locale, Record<string, string>> = {
  en: {
    METHOD_VERSION_CHANGED: "Method changed; reload",
    METHOD_DISABLED: "Method disabled",
    METHOD_HIDDEN: "Hidden from buyers",
    MARKET_INACTIVE: "Market inactive",
    ENVIRONMENT_MISMATCH: "Environment does not match",
    CURRENCY_MISMATCH: "Currency does not match",
    AMOUNT_OUT_OF_RANGE: "Amount outside configured range",
    CONNECTION_MISSING: "Account connection missing",
    BINDING_VERSION_CHANGED: "Account binding changed",
    BINDING_DISABLED: "Account binding disabled",
    CREDENTIALS_UNVERIFIED: "Credentials unverified",
    ADAPTER_UNAVAILABLE: "Payment adapter unavailable",
  },
  "zh-CN": {
    METHOD_VERSION_CHANGED: "方式版本已变化，请重新读取",
    METHOD_DISABLED: "方式未启用",
    METHOD_HIDDEN: "未向买家展示",
    MARKET_INACTIVE: "市场未激活",
    ENVIRONMENT_MISMATCH: "环境不匹配",
    CURRENCY_MISMATCH: "币种不匹配",
    AMOUNT_OUT_OF_RANGE: "金额超出配置范围",
    CONNECTION_MISSING: "缺少账户连接",
    BINDING_VERSION_CHANGED: "账户绑定版本已变化",
    BINDING_DISABLED: "账户绑定未启用",
    CREDENTIALS_UNVERIFIED: "凭据未验证",
    ADAPTER_UNAVAILABLE: "收款适配器不可用",
  },
  "zh-TW": {
    METHOD_VERSION_CHANGED: "方式版本已變更，請重新讀取",
    METHOD_DISABLED: "方式未啟用",
    METHOD_HIDDEN: "未向買家顯示",
    MARKET_INACTIVE: "市場未啟用",
    ENVIRONMENT_MISMATCH: "環境不符",
    CURRENCY_MISMATCH: "幣別不符",
    AMOUNT_OUT_OF_RANGE: "金額超出設定範圍",
    CONNECTION_MISSING: "缺少帳戶連接",
    BINDING_VERSION_CHANGED: "帳戶綁定版本已變更",
    BINDING_DISABLED: "帳戶綁定未啟用",
    CREDENTIALS_UNVERIFIED: "憑證未驗證",
    ADAPTER_UNAVAILABLE: "收款介接不可用",
  },
};
export function availabilityReason(locale: Locale, code: string) {
  return reasonText[locale][code] ?? code;
}
