// Copy (zh-CN / zh-TW / en) for the Settings "Storefront publishing" card (components/StorefrontSettings.tsx).
// Contract: published-storefront-resolver-v1 "Writer (R3)". Error codes are the Go route's stable codes
// (httpapi classify): conflict (stale version), forbidden, unauthorized, unavailable/retry_later; unknown codes fall back
// to `unavailable`. Domain binding is the platform's act and is only described here, never offered as a control.
import type { Locale } from "@live-commerce/i18n";

const en = {
  title: "Storefront publishing",
  intro:
    "Publishing is your decision: it lets buyers open your store. Buyers can only reach it once the platform has also bound your store's domain.",
  loading: "Loading…",
  retry: "Try again",
  unavailable: "This section could not be loaded. Try again.",
  noPermission: "This account does not have permission to change publishing.",
  state: "Status",
  published: "Published",
  unpublished: "Not published",
  domain: "Domain",
  validUntil: "Certificate valid until",
  awaitingDomain: "Awaiting platform domain. The platform operator binds your store's domain after checking ownership and the certificate.",
  domainExpired: "Certificate window ended. The platform operator must renew it before buyers can reach the store.",
  publishedNoDomain: "Published, but buyers cannot open the store until a domain is live.",
  readyToPublish: "A domain is live. Publish when you are ready for buyers.",
  live: "Live: buyers can open your store.",
  publish: "Publish storefront",
  unpublish: "Unpublish storefront",
  confirmPublish: "Publish your storefront? Buyers can open it as soon as a domain is live.",
  confirmUnpublish: "Unpublish your storefront? Buyers lose access to the store, claim links and cart links right away.",
  confirm: "Confirm",
  cancel: "Cancel",
  saving: "Saving…",
  savedPublished: "Published.",
  savedUnpublished: "Unpublished.",
  uncertain: "The result is not known yet. The card was reloaded; check the status above.",
  errors: {
    conflict: "This changed after you loaded it. The card was reloaded; check the status and try again.",
    unauthorized: "Your session ended. Sign in again.",
    forbidden: "This account does not have permission to change publishing.",
    unavailable: "The change could not be saved. Try again.",
  } as Record<string, string>,
};
export type StorefrontCopy = typeof en;

export const storefrontCopy: Record<Locale, StorefrontCopy> = {
  en,
  "zh-CN": {
    title: "网店发布",
    intro: "是否发布由你决定：发布后买家才能打开你的网店。只有平台同时绑定了你的店铺域名，买家才真正访问得到。",
    loading: "加载中…",
    retry: "重试",
    unavailable: "无法加载此部分，请重试。",
    noPermission: "此账号没有更改发布状态的权限。",
    state: "状态",
    published: "已发布",
    unpublished: "未发布",
    domain: "域名",
    validUntil: "证书有效期至",
    awaitingDomain: "等待平台绑定域名。平台运维在核实域名所有权和证书后为你的店铺绑定域名。",
    domainExpired: "证书有效期已过，需要平台运维续期，买家才能访问网店。",
    publishedNoDomain: "已发布，但在域名生效之前买家无法打开网店。",
    readyToPublish: "域名已生效。准备好迎接买家时再发布。",
    live: "已上线：买家可以打开你的网店。",
    publish: "发布网店",
    unpublish: "取消发布",
    confirmPublish: "确认发布网店？域名生效后买家即可打开。",
    confirmUnpublish: "确认取消发布？买家将立刻无法访问网店、认领链接和购物车链接。",
    confirm: "确认",
    cancel: "取消",
    saving: "保存中…",
    savedPublished: "已发布。",
    savedUnpublished: "已取消发布。",
    uncertain: "结果尚不确定。已重新加载，请查看上方状态。",
    errors: {
      conflict: "内容在你加载之后已变更，已重新加载，请核对状态后重试。",
      unauthorized: "登录已失效，请重新登录。",
      forbidden: "此账号没有更改发布状态的权限。",
      unavailable: "无法保存更改，请重试。",
    },
  },
  "zh-TW": {
    title: "網店發佈",
    intro: "是否發佈由你決定：發佈後買家才能打開你的網店。只有平台同時綁定了你的店鋪網域，買家才真正連得到。",
    loading: "載入中…",
    retry: "重試",
    unavailable: "無法載入此部分，請重試。",
    noPermission: "此帳號沒有變更發佈狀態的權限。",
    state: "狀態",
    published: "已發佈",
    unpublished: "未發佈",
    domain: "網域",
    validUntil: "憑證有效期至",
    awaitingDomain: "等待平台綁定網域。平台維運在核實網域所有權與憑證後，為你的店鋪綁定網域。",
    domainExpired: "憑證有效期已過，需要平台維運續期，買家才能連到網店。",
    publishedNoDomain: "已發佈，但在網域生效之前買家無法打開網店。",
    readyToPublish: "網域已生效。準備好迎接買家時再發佈。",
    live: "已上線：買家可以打開你的網店。",
    publish: "發佈網店",
    unpublish: "取消發佈",
    confirmPublish: "確認發佈網店？網域生效後買家即可打開。",
    confirmUnpublish: "確認取消發佈？買家將立刻無法使用網店、認領連結與購物車連結。",
    confirm: "確認",
    cancel: "取消",
    saving: "儲存中…",
    savedPublished: "已發佈。",
    savedUnpublished: "已取消發佈。",
    uncertain: "結果尚不確定。已重新載入，請查看上方狀態。",
    errors: {
      conflict: "內容在你載入之後已變更，已重新載入，請核對狀態後重試。",
      unauthorized: "登入已失效，請重新登入。",
      forbidden: "此帳號沒有變更發佈狀態的權限。",
      unavailable: "無法儲存變更，請重試。",
    },
  },
};
