// Copy (zh-CN / zh-TW / en) for the Settings "Storefront publishing" card (components/StorefrontSettings.tsx).
// Contract: published-storefront-resolver-v1 "Writer (R3)" and the R5 merchant self-service domain routes
// (store-domains, Decision 3). Publication error codes are the Go route's stable codes (httpapi classify):
// conflict (stale version), forbidden, unauthorized, unavailable/retry_later; unknown codes fall back to `unavailable`.
// Domain-write errors (domains.errors) are the domain route's codes: invalid_request (bad/reserved hostname),
// conflict (domain active/suspended/detached/owned elsewhere), unavailable, unauthorized, forbidden.
import type { Locale } from "@live-commerce/i18n";

const en = {
  title: "Storefront publishing",
  intro:
    "Publishing is your decision: it lets buyers open your store. Buyers can only reach it once the platform has also bound your store's domain.",
  loading: "Loading…",
  retry: "Try again",
  unavailable: "This section could not be loaded. Try again.",
  noPermission: "This account does not have permission to change publishing.",
  state: "Status",
  published: "Published",
  unpublished: "Not published",
  domain: "Domain",
  validUntil: "Certificate valid until",
  awaitingDomain: "Awaiting platform domain. The platform operator binds your store's domain after checking ownership and the certificate.",
  domainExpired: "Certificate window ended. The platform operator must renew it before buyers can reach the store.",
  publishedNoDomain: "Published, but buyers cannot open the store until a domain is live.",
  readyToPublish: "A domain is live. Publish when you are ready for buyers.",
  live: "Live: buyers can open your store.",
  publish: "Publish storefront",
  unpublish: "Unpublish storefront",
  confirmPublish: "Publish your storefront? Buyers can open it as soon as a domain is live.",
  confirmUnpublish: "Unpublish your storefront? Buyers lose access to the store, claim links and cart links right away.",
  confirm: "Confirm",
  cancel: "Cancel",
  saving: "Saving…",
  savedPublished: "Published.",
  savedUnpublished: "Unpublished.",
  uncertain: "The result is not known yet. The card was reloaded; check the status above.",
  domains: {
    title: "Store address",
    intro:
      "Buyers reach your store at your platform address automatically. You can also use your own domain name.",
    platform: "Platform address",
    merchant: "Your own domain",
    add: "Add your own domain",
    hostnameLabel: "Domain name",
    hostnamePlaceholder: "www.example.com",
    request: "Request verification",
    requesting: "Requesting…",
    primary: "Primary",
    serving: "Serving buyers",
    suspend: "Suspend",
    detach: "Detach",
    confirmSuspend: "Suspend this domain? Buyers will no longer be able to open this address. To use it again, request verification with fresh DNS records.",
    confirmDetach: "Detach this domain? It will stop serving your store. Connecting it again requires fresh DNS verification.",
    copy: "Copy DNS instructions",
    copied: "DNS instructions copied.",
    copyFailed: "Could not copy. Select and copy the records below manually.",
    unconfirmed: "The last domain operation is unconfirmed. Retry that same operation to retrieve its result safely. Other domain changes stay paused until it is confirmed.",
    legacyUnconfirmed: "An earlier operation is unconfirmed and its original request is unavailable. Refresh the status and contact the platform to reconcile it. Do not submit it again.",
    retry: "Retry the same operation",
    copyRecord: "Copy record",
    storageUnavailable: "Safe operation tracking is unavailable. Domain changes are disabled; you can still read the current status.",
    refresh: "Refresh status",
    verifying:
      "We check your DNS records automatically, retrying for up to 72 hours. Once the records are in place, no further action is needed.",
    dnsTitle: "DNS records to add",
    dnsIntro: "Add these records at your DNS provider, then leave them in place while we verify.",
    dnsTxtName: "TXT record name",
    dnsTxtValue: "TXT record value",
    dnsCname: "CNAME record",
    dnsApex: "A / AAAA records (root domain)",
    dnsApexNote: "The server has not provided an IP address for the root domain. Ask the platform for the exact A/AAAA value before adding it. Do not enter a hostname as an A record value.",
    states: {
      REQUESTED: "Awaiting DNS setup",
      OWNERSHIP_PENDING: "Verifying",
      TLS_PENDING: "Issuing certificate",
      ACTIVE: "Active",
      SUSPENDED: "Suspended",
      DETACHED: "Detached",
    },
    errors: {
      invalid_request: "That domain name is not valid, or is reserved by the platform.",
      conflict: "That domain cannot be changed right now. Reload and check its state.",
      unavailable: "The domain service is temporarily unavailable. Try again.",
      unauthorized: "Your session ended. Sign in again.",
      forbidden: "This account does not have permission to manage domains.",
    } as Record<string, string>,
  },
  errors: {
    conflict: "This changed after you loaded it. The card was reloaded; check the status and try again.",
    unauthorized: "Your session ended. Sign in again.",
    forbidden: "This account does not have permission to change publishing.",
    unavailable: "The change could not be saved. Try again.",
  } as Record<string, string>,
};
export type StorefrontCopy = typeof en;

export const storefrontCopy: Record<Locale, StorefrontCopy> = {
  en,
  "zh-CN": {
    title: "网店发布",
    intro: "是否发布由你决定：发布后买家才能打开你的网店。只有平台同时绑定了你的店铺域名，买家才真正访问得到。",
    loading: "加载中…",
    retry: "重试",
    unavailable: "无法加载此部分，请重试。",
    noPermission: "此账号没有更改发布状态的权限。",
    state: "状态",
    published: "已发布",
    unpublished: "未发布",
    domain: "域名",
    validUntil: "证书有效期至",
    awaitingDomain: "等待平台绑定域名。平台运维在核实域名所有权和证书后为你的店铺绑定域名。",
    domainExpired: "证书有效期已过，需要平台运维续期，买家才能访问网店。",
    publishedNoDomain: "已发布，但在域名生效之前买家无法打开网店。",
    readyToPublish: "域名已生效。准备好迎接买家时再发布。",
    live: "已上线：买家可以打开你的网店。",
    publish: "发布网店",
    unpublish: "取消发布",
    confirmPublish: "确认发布网店？域名生效后买家即可打开。",
    confirmUnpublish: "确认取消发布？买家将立刻无法访问网店、认领链接和购物车链接。",
    confirm: "确认",
    cancel: "取消",
    saving: "保存中…",
    savedPublished: "已发布。",
    savedUnpublished: "已取消发布。",
    uncertain: "结果尚不确定。已重新加载，请查看上方状态。",
    domains: {
      title: "店铺网址",
      intro: "买家可自动通过平台网址访问你的网店；你也可以使用自己的域名。",
      platform: "平台网址",
      merchant: "自有域名",
      add: "添加自有域名",
      hostnameLabel: "域名",
      hostnamePlaceholder: "www.example.com",
      request: "请求校验",
      requesting: "正在请求…",
      primary: "主域名",
      serving: "正在服务买家",
      suspend: "暂停",
      detach: "解绑",
      confirmSuspend: "暂停此域名？买家将无法打开此网址。再次使用时，需要重新申请并完成 DNS 验证。",
      confirmDetach: "解绑此域名？它将停止展示你的店铺。再次绑定需要重新完成 DNS 验证。",
      copy: "复制 DNS 设置说明",
      copied: "DNS 设置说明已复制。",
      copyFailed: "未能复制，请手动选中并复制下方记录。",
      unconfirmed: "上次域名操作结果尚未确认。可重试同一操作，安全取回结果。确认前，其他域名变更仍暂停。",
      legacyUnconfirmed: "较早的操作结果尚未确认，且原始请求已不可用。请刷新状态并联系平台核对，请勿重新提交。",
      retry: "重试同一操作",
      copyRecord: "复制此记录",
      storageUnavailable: "无法安全保存操作记录，域名变更已禁用，仍可查看当前状态。",
      refresh: "刷新状态",
      verifying: "我们会自动校验你的 DNS 记录，最多重试 72 小时。记录就位后无需再做任何操作。",
      dnsTitle: "需要添加的 DNS 记录",
      dnsIntro: "请在你的 DNS 服务商处添加以下记录，并在校验期间保持它们。",
      dnsTxtName: "TXT 记录名称",
      dnsTxtValue: "TXT 记录值",
      dnsCname: "CNAME 记录",
      dnsApex: "A / AAAA 记录（根域名）",
      dnsApexNote: "服务器尚未提供根域名所需的 IP 地址。请向平台索取准确的 A/AAAA 记录值后再设置，不要把主机名填入 A 记录值。",
      states: {
        REQUESTED: "等待 DNS 设置",
        OWNERSHIP_PENDING: "验证中",
        TLS_PENDING: "签发证书中",
        ACTIVE: "已启用",
        SUSPENDED: "已暂停",
        DETACHED: "已解绑",
      },
      errors: {
        invalid_request: "该域名无效，或被平台保留。",
        conflict: "该域名当前无法变更。请刷新后查看其状态。",
        unavailable: "域名服务暂时不可用，请重试。",
        unauthorized: "登录已失效，请重新登录。",
        forbidden: "此账号没有管理域名的权限。",
      },
    },
    errors: {
      conflict: "内容在你加载之后已变更，已重新加载，请核对状态后重试。",
      unauthorized: "登录已失效，请重新登录。",
      forbidden: "此账号没有更改发布状态的权限。",
      unavailable: "无法保存更改，请重试。",
    },
  },
  "zh-TW": {
    title: "網店發佈",
    intro: "是否發佈由你決定：發佈後買家才能打開你的網店。只有平台同時綁定了你的店鋪網域，買家才真正連得到。",
    loading: "載入中…",
    retry: "重試",
    unavailable: "無法載入此部分，請重試。",
    noPermission: "此帳號沒有變更發佈狀態的權限。",
    state: "狀態",
    published: "已發佈",
    unpublished: "未發佈",
    domain: "網域",
    validUntil: "憑證有效期至",
    awaitingDomain: "等待平台綁定網域。平台維運在核實網域所有權與憑證後，為你的店鋪綁定網域。",
    domainExpired: "憑證有效期已過，需要平台維運續期，買家才能連到網店。",
    publishedNoDomain: "已發佈，但在網域生效之前買家無法打開網店。",
    readyToPublish: "網域已生效。準備好迎接買家時再發佈。",
    live: "已上線：買家可以打開你的網店。",
    publish: "發佈網店",
    unpublish: "取消發佈",
    confirmPublish: "確認發佈網店？網域生效後買家即可打開。",
    confirmUnpublish: "確認取消發佈？買家將立刻無法使用網店、認領連結與購物車連結。",
    confirm: "確認",
    cancel: "取消",
    saving: "儲存中…",
    savedPublished: "已發佈。",
    savedUnpublished: "已取消發佈。",
    uncertain: "結果尚不確定。已重新載入，請查看上方狀態。",
    domains: {
      title: "商店網址",
      intro: "買家可自動透過平台網址開啟你的商店；你也可以使用自己的網域名稱。",
      platform: "平台網址",
      merchant: "自有網域",
      add: "新增自有網域",
      hostnameLabel: "網域名稱",
      hostnamePlaceholder: "www.example.com",
      request: "請求驗證",
      requesting: "正在請求…",
      primary: "主網域",
      serving: "正在服務買家",
      suspend: "暫停",
      detach: "解除綁定",
      confirmSuspend: "暫停此網域？買家將無法開啟此網址。再次使用時，需要重新申請並完成 DNS 驗證。",
      confirmDetach: "解除綁定此網域？它將停止顯示你的商店。再次綁定需要重新完成 DNS 驗證。",
      copy: "複製 DNS 設定說明",
      copied: "DNS 設定說明已複製。",
      copyFailed: "無法複製，請手動選取並複製下方記錄。",
      unconfirmed: "上次網域操作結果尚未確認。可重試同一操作，安全取回結果。確認前，其他網域變更仍暫停。",
      legacyUnconfirmed: "較早的操作結果尚未確認，且原始請求已無法取得。請重新整理狀態並聯絡平台核對，請勿重新送出。",
      retry: "重試同一操作",
      copyRecord: "複製此記錄",
      storageUnavailable: "無法安全儲存操作記錄，網域變更已停用，仍可查看目前狀態。",
      refresh: "重新整理狀態",
      verifying: "我們會自動驗證你的 DNS 記錄，最多重試 72 小時。記錄就位後無需再採取任何動作。",
      dnsTitle: "需要新增的 DNS 記錄",
      dnsIntro: "請在你的 DNS 服務商新增以下記錄，並在驗證期間保持它們。",
      dnsTxtName: "TXT 記錄名稱",
      dnsTxtValue: "TXT 記錄值",
      dnsCname: "CNAME 記錄",
      dnsApex: "A / AAAA 記錄（根網域）",
      dnsApexNote: "伺服器尚未提供根網域所需的 IP 位址。請向平台取得準確的 A/AAAA 記錄值後再設定，不要把主機名稱填入 A 記錄值。",
      states: {
        REQUESTED: "等待 DNS 設定",
        OWNERSHIP_PENDING: "驗證中",
        TLS_PENDING: "憑證簽發中",
        ACTIVE: "已啟用",
        SUSPENDED: "已暫停",
        DETACHED: "已解除綁定",
      },
      errors: {
        invalid_request: "該網域名稱無效，或被平台保留。",
        conflict: "該網域目前無法變更。請重新整理後查看其狀態。",
        unavailable: "網域服務暫時無法使用，請重試。",
        unauthorized: "登入已失效，請重新登入。",
        forbidden: "此帳號沒有管理網域的權限。",
      },
    },
    errors: {
      conflict: "內容在你載入之後已變更，已重新載入，請核對狀態後重試。",
      unauthorized: "登入已失效，請重新登入。",
      forbidden: "此帳號沒有變更發佈狀態的權限。",
      unavailable: "無法儲存變更，請重試。",
    },
  },
};
