// Purpose: Owns localized team membership and invitation labels.
// Depends on: @live-commerce/i18n
// Used by: apps/admin/components/Team.tsx, apps/admin/components/TeamInvite.tsx, tests/admin/team-model.test.ts
// Copy for the admin Team page (/{locale}/team) and the invitation page (/{locale}/invite/{token}); locales zh-CN / zh-TW / en
// (BFF POST /api/team/* -> Go /v1/identity/staff/*, contract storefront-v2 §D). Owns every string of Team.tsx and TeamInvite.tsx,
// the five role labels and what each role can do, and the error map for the staff codes of internal/identityhttp/staff.go.
// Non-goals: no permission rule (the server decides who is an owner), no date formatting (components use Intl).
// Depends on: @live-commerce/i18n (Locale) only. Role labels must stay equal to internal/identity/staffmail.go (the invitation mail).
import type { Locale } from "@live-commerce/i18n";

const en = {
  nav: "Team",
  title: "Team",
  subtitle: "Invite people to work in this store and choose what each of them can do.",
  store: "Store",
  loading: "Loading team…",
  working: "A team change is being saved. Wait for it to finish.",
  signedOut: "Sign in to manage the team.",
  notOwner: "Only a store owner can manage the team. Ask an owner to change roles or invite people.",
  notFound: "The team is unavailable for this store.",
  unavailable: "The team is temporarily unavailable. Try again.",
  noStore: "No authorized store is available.",
  retry: "Try again",
  membersTitle: "Members",
  you: "You",
  colEmail: "Email",
  colRole: "Role",
  colJoined: "Joined",
  colStatus: "Status",
  colActions: "Actions",
  scrollHint: "Scroll horizontally to see every column and action.",
  noEmail: "Sign-in without email",
  changeRole: "Change role",
  removeMember: "Remove",
  removeConfirm: "Remove this person from the store? They lose access on their next request.",
  removeConfirmSelf: "Remove yourself from the store? You will lose access immediately.",
  removeYes: "Yes, remove",
  cancel: "Cancel",
  invitesTitle: "Pending invitations",
  invitesNone: "No pending invitations.",
  expires: "Expires",
  expired: "Expired",
  resend: "Send again",
  revokeInvite: "Withdraw",
  mailState: {
    PENDING: "Sending…",
    SENT: "Email sent",
    FAILED: "Email could not be sent. Send it again.",
    UNKNOWN: "Email delivery is unconfirmed. Send it again if it does not arrive.",
  } as Record<string, string>,
  inviteTitle: "Invite someone",
  inviteHint: "They get an email with a link that works once for 72 hours. They sign in or sign up with this email address and accept.",
  inviteEmail: "Email address",
  inviteRole: "Role",
  inviteSend: "Send invitation",
  inviteSending: "Sending…",
  inviteSent: "Invitation sent.",
  inviteMailFailed: "The invitation was created but the email could not be sent. Use “Send again”.",
  inviteMailUnknown: "The invitation was created; email delivery is unconfirmed. Use “Send again” if it does not arrive.",
  roleNames: { owner: "Owner", admin: "Admin", live_operator: "Live operator", fulfilment: "Fulfilment", viewer: "Viewer" } as Record<string, string>,
  roleHelp: {
    owner: "Everything, including the team and billing.",
    admin: "Everything except the team and billing.",
    live_operator: "Runs live sessions; can view products, orders and stock.",
    fulfilment: "Handles orders, shipping, exports and stock.",
    viewer: "Can view everything, changes nothing.",
  } as Record<string, string>,
  saved: "Saved.",
  errors: {
    forbidden: "Only a store owner can do this.",
    last_owner: "A store must keep at least one owner. Make someone else an owner first.",
    already_member: "This person is already a member of this store.",
    too_many_invitations: "Too many invitations right now. Try again later.",
    invalid_email: "Enter a valid email address.",
    invalid_request: "That request was not valid.",
    not_found: "That item no longer exists. Reload the page.",
    unauthorized: "Your session ended. Sign in again.",
    default: "The service did not answer. Try again.",
  } as Record<string, string>,
  // Invitation page
  inviteIntro: "You have been invited to join a store team.",
  inviteNeedLogin: "Sign in or create an account with the email address that received the invitation, then open the link from the email again.",
  signIn: "Sign in",
  signUp: "Create an account",
  inviteAccept: "Accept invitation",
  inviteAccepting: "Accepting…",
  inviteSameEmail: "You must be signed in with the email address that was invited.",
  inviteDone: "You joined the team.",
  inviteOpen: "Open the workspace",
  inviteErrors: {
    invite_invalid: "This invitation is not valid. It may have expired, been used, withdrawn, or sent to another email address. Ask the store owner for a new one.",
    already_member: "You are already a member of this store.",
    unauthorized: "Your session ended. Sign in again, then reopen the link from the email.",
    default: "The service did not answer. Try again.",
  } as Record<string, string>,
};
export type TeamCopy = typeof en;

const zhCN: TeamCopy = {
  nav: "团队",
  title: "团队",
  subtitle: "邀请成员加入这个店铺，并决定每个人能做什么。",
  store: "店铺",
  loading: "正在加载团队…",
  working: "正在保存团队更改，请等待完成。",
  signedOut: "请登录后管理团队。",
  notOwner: "只有店铺所有者可以管理团队。请联系所有者调整角色或邀请成员。",
  notFound: "此店铺的团队暂时不可用。",
  unavailable: "团队暂时不可用，请重试。",
  noStore: "没有可用的已授权店铺。",
  retry: "重试",
  membersTitle: "成员",
  you: "您",
  colEmail: "邮箱",
  colRole: "角色",
  colJoined: "加入时间",
  colStatus: "状态",
  colActions: "操作",
  scrollHint: "横向滚动以查看全部列和操作。",
  noEmail: "无邮箱登录",
  changeRole: "更改角色",
  removeMember: "移除",
  removeConfirm: "确定将此成员移出店铺？对方下一次请求起即失去访问权限。",
  removeConfirmSelf: "确定将自己移出店铺？您将立即失去访问权限。",
  removeYes: "确定移除",
  cancel: "取消",
  invitesTitle: "待处理的邀请",
  invitesNone: "没有待处理的邀请。",
  expires: "到期时间",
  expired: "已过期",
  resend: "重新发送",
  revokeInvite: "撤回",
  mailState: {
    PENDING: "正在发送…",
    SENT: "邮件已发送",
    FAILED: "邮件未能发送，请重新发送。",
    UNKNOWN: "邮件送达情况未确认，如未收到请重新发送。",
  },
  inviteTitle: "邀请成员",
  inviteHint: "对方会收到一封带链接的邮件，链接 72 小时内有效且仅能使用一次。对方需用此邮箱登录或注册后接受邀请。",
  inviteEmail: "邮箱地址",
  inviteRole: "角色",
  inviteSend: "发送邀请",
  inviteSending: "发送中…",
  inviteSent: "邀请已发送。",
  inviteMailFailed: "邀请已创建，但邮件未能发送。请使用“重新发送”。",
  inviteMailUnknown: "邀请已创建，邮件送达情况未确认。如未收到请使用“重新发送”。",
  roleNames: { owner: "所有者", admin: "管理员", live_operator: "直播运营", fulfilment: "履约", viewer: "只读成员" },
  roleHelp: {
    owner: "全部权限，包括团队与账单。",
    admin: "除团队与账单外的全部权限。",
    live_operator: "负责直播场次；可查看商品、订单与库存。",
    fulfilment: "处理订单、发货、导出与库存。",
    viewer: "可查看全部内容，不能做任何修改。",
  },
  saved: "已保存。",
  errors: {
    forbidden: "只有店铺所有者可以执行此操作。",
    last_owner: "店铺必须至少保留一位所有者。请先让其他人成为所有者。",
    already_member: "此人已经是该店铺的成员。",
    too_many_invitations: "当前邀请过多，请稍后再试。",
    invalid_email: "请输入有效的邮箱地址。",
    invalid_request: "请求无效。",
    not_found: "该项目已不存在，请刷新页面。",
    unauthorized: "登录已失效，请重新登录。",
    default: "服务没有响应，请重试。",
  },
  inviteIntro: "您被邀请加入一个店铺团队。",
  inviteNeedLogin: "请使用收到邀请的邮箱地址登录或注册，然后重新打开邮件里的链接。",
  signIn: "登录",
  signUp: "注册账号",
  inviteAccept: "接受邀请",
  inviteAccepting: "正在接受…",
  inviteSameEmail: "您必须用被邀请的邮箱地址登录。",
  inviteDone: "您已加入团队。",
  inviteOpen: "进入工作台",
  inviteErrors: {
    invite_invalid: "此邀请无效：可能已过期、已使用、已被撤回，或发给了另一个邮箱地址。请向店铺所有者索取新的邀请。",
    already_member: "您已经是该店铺的成员。",
    unauthorized: "登录已失效。请重新登录，然后重新打开邮件里的链接。",
    default: "服务没有响应，请重试。",
  },
};

const zhTW: TeamCopy = {
  nav: "團隊",
  title: "團隊",
  subtitle: "邀請成員加入這個店鋪，並決定每個人能做什麼。",
  scrollHint: "橫向捲動以查看全部欄位和操作。",
  store: "店鋪",
  loading: "正在載入團隊…",
  working: "正在儲存團隊變更，請等待完成。",
  signedOut: "請登入後管理團隊。",
  notOwner: "只有店鋪擁有者可以管理團隊。請聯絡擁有者調整角色或邀請成員。",
  notFound: "此店鋪的團隊暫時無法使用。",
  unavailable: "團隊暫時無法使用，請重試。",
  noStore: "沒有可用的已授權店鋪。",
  retry: "重試",
  membersTitle: "成員",
  you: "您",
  colEmail: "電子郵件",
  colRole: "角色",
  colJoined: "加入時間",
  colStatus: "狀態",
  colActions: "操作",
  noEmail: "無電子郵件登入",
  changeRole: "變更角色",
  removeMember: "移除",
  removeConfirm: "確定將此成員移出店鋪？對方從下一次請求起即失去存取權限。",
  removeConfirmSelf: "確定將自己移出店鋪？您將立即失去存取權限。",
  removeYes: "確定移除",
  cancel: "取消",
  invitesTitle: "待處理的邀請",
  invitesNone: "沒有待處理的邀請。",
  expires: "到期時間",
  expired: "已過期",
  resend: "重新寄送",
  revokeInvite: "撤回",
  mailState: {
    PENDING: "寄送中…",
    SENT: "郵件已寄出",
    FAILED: "郵件未能寄出，請重新寄送。",
    UNKNOWN: "郵件送達情況未確認，如未收到請重新寄送。",
  },
  inviteTitle: "邀請成員",
  inviteHint: "對方會收到一封附連結的郵件，連結 72 小時內有效且僅能使用一次。對方需用此電子郵件登入或註冊後接受邀請。",
  inviteEmail: "電子郵件地址",
  inviteRole: "角色",
  inviteSend: "寄送邀請",
  inviteSending: "寄送中…",
  inviteSent: "邀請已寄出。",
  inviteMailFailed: "邀請已建立，但郵件未能寄出。請使用「重新寄送」。",
  inviteMailUnknown: "邀請已建立，郵件送達情況未確認。如未收到請使用「重新寄送」。",
  roleNames: { owner: "擁有者", admin: "管理員", live_operator: "直播營運", fulfilment: "履約", viewer: "唯讀成員" },
  roleHelp: {
    owner: "全部權限，包括團隊與帳單。",
    admin: "除團隊與帳單外的全部權限。",
    live_operator: "負責直播場次；可檢視商品、訂單與庫存。",
    fulfilment: "處理訂單、出貨、匯出與庫存。",
    viewer: "可檢視全部內容，無法做任何修改。",
  },
  saved: "已儲存。",
  errors: {
    forbidden: "只有店鋪擁有者可以執行此操作。",
    last_owner: "店鋪必須至少保留一位擁有者。請先讓其他人成為擁有者。",
    already_member: "此人已經是該店鋪的成員。",
    too_many_invitations: "目前邀請過多，請稍後再試。",
    invalid_email: "請輸入有效的電子郵件地址。",
    invalid_request: "請求無效。",
    not_found: "該項目已不存在，請重新整理頁面。",
    unauthorized: "登入已失效，請重新登入。",
    default: "服務沒有回應，請重試。",
  },
  inviteIntro: "您被邀請加入一個店鋪團隊。",
  inviteNeedLogin: "請使用收到邀請的電子郵件地址登入或註冊，然後重新開啟郵件裡的連結。",
  signIn: "登入",
  signUp: "註冊帳號",
  inviteAccept: "接受邀請",
  inviteAccepting: "正在接受…",
  inviteSameEmail: "您必須用被邀請的電子郵件地址登入。",
  inviteDone: "您已加入團隊。",
  inviteOpen: "進入工作台",
  inviteErrors: {
    invite_invalid: "此邀請無效：可能已過期、已使用、已被撤回，或寄給了另一個電子郵件地址。請向店鋪擁有者索取新的邀請。",
    already_member: "您已經是該店鋪的成員。",
    unauthorized: "登入已失效。請重新登入，然後重新開啟郵件裡的連結。",
    default: "服務沒有回應，請重試。",
  },
};

export const teamCopy: Record<Locale, TeamCopy> = { en, "zh-CN": zhCN, "zh-TW": zhTW };
