// Copy (zh-CN / zh-TW / en) for the admin bank-transfer surfaces (contracts/storefront-v2.md §C): the Settings card (bank details and
// transfer window) and the order section (buyer's transfer details, Confirm / Reject with reason / offline refund).
// Rendered by components/{BankTransferSettings,OrderBankTransfer}.tsx; the BFF routes are listed in lib/logistics-client.ts.
// Rules encoded here: Confirm says the merchant checked their OWN bank account (the platform never sees the money); Reject rejects the
// buyer's submission, not the order (the buyer can send again until the deadline; expiry is the only cancel); the offline refund records
// that the merchant returned the money outside the platform.
import type { Locale } from "@live-commerce/i18n";
import type { TransferState } from "./transfer-model";

const en = {
  // settings card
  setTitle: "Bank transfer",
  setIntro:
    "Let buyers pay by transferring to your bank account. The order is placed with the stock reserved; you confirm it after you see the money in your own account. Nothing is confirmed automatically.",
  setEnabled: "Offer bank transfer at checkout",
  setAllowCvs: "Also offer it for convenience-store pickup",
  setBank: "Bank",
  setBranch: "Branch (optional)",
  setAccountName: "Account name",
  setAccountNumber: "Account number",
  setAccountHint: "Digits, spaces and hyphens only.",
  setWindow: "Transfer window (hours, 6–168)",
  setWindowHint: "Stock stays reserved this long. If no transfer is confirmed in time the order is cancelled and the stock released.",
  setNote: "Changes apply to new orders only. Orders already placed keep the bank details they were given.",
  save: "Save",
  saving: "Saving…",
  saved: "Bank transfer settings saved.",
  retry: "Try again",
  loading: "Loading…",
  loadFailed: "Bank transfer settings could not be loaded.",
  invalid: "Check the fields: the bank, account name and number are required to switch it on; the window is 6 to 168 hours.",
  noPermission: "This account does not have permission to change these settings.",
  uncertain: "The result is not known yet. Retry sends the identical request safely, or reload.",
  retrySame: "Retry the same request",
  // order section
  secTitle: "Bank transfer",
  loadingOrder: "Loading transfer details…",
  secLoadFailed: "The transfer details could not be loaded.",
  state: "Transfer status",
  states: {
    AWAITING: "Waiting for the buyer's transfer",
    SUBMITTED: "Buyer says they transferred",
    REJECTED: "Submission rejected — waiting for the buyer",
    CONFIRMED: "Transfer confirmed",
    EXPIRED: "Window ended — order cancelled",
    REFUNDED_OFFLINE: "Refunded outside the platform",
  } as Record<TransferState, string>,
  amount: "Amount due",
  deadline: "Transfer deadline",
  bankHeading: "Account the buyer was given",
  proofHeading: "What the buyer reported",
  noProof: "The buyer has not sent transfer details yet. You can still confirm if you see the money.",
  last5: "Last 5 digits",
  amountSent: "Amount reported",
  paidAt: "Reported time",
  submittedAt: "Sent at",
  attempts: "Times sent",
  rejectReason: "Your rejection reason",
  confirmedAt: "Confirmed at",
  refundedAt: "Refund recorded at",
  mismatch: "The reported amount differs from the amount due.",
  confirm: "Confirm transfer",
  reject: "Reject details",
  refund: "Record offline refund",
  // dialogs
  confirmTitle: "Confirm this transfer?",
  confirmText: (amount: string) =>
    `Only confirm after you checked your own bank account and saw ${amount} arrive. The order becomes confirmed, the reserved stock is committed and the order can be shipped. This is recorded in the audit log.`,
  confirmNoProofWarning:
    "The buyer has not sent any transfer details. Confirm only if you can match the money in your own account to this order (for example proof the buyer sent you by LINE). This is recorded in the audit log as confirmed without buyer proof.",
  rejectTitle: "Reject the buyer's details?",
  rejectText: "The buyer is told your reason and can send the details again until the deadline. The order is not cancelled and the stock stays reserved.",
  rejectReasonLabel: "Reason shown to the buyer (1–200 characters)",
  refundTitle: "Record an offline refund?",
  refundText:
    "Use this after you returned the money to the buyer outside this platform. No money moves here. The order can no longer be shipped and leaves the confirmed-transfer total.",
  refundRestockLabel: "Also return the reserved stock to inventory",
  refundRestockHint: "Only possible while the order has not been shipped. If it was handed over, leave this off and restock through the shipping flow.",
  refundRestockShipped: "This order was already shipped, so its stock cannot be restocked here.",
  submitConfirm: "Confirm",
  submitReject: "Reject",
  submitRefund: "Record refund",
  cancel: "Cancel",
  close: "Close",
  working: "Working…",
  done: "Done.",
  errors: {
    already_confirmed: "This transfer was already confirmed.",
    already_refunded: "This transfer was already refunded.",
    transfer_not_open: "This transfer is no longer open (the window ended or it was already decided).",
    transfer_window_closed: "The transfer window has ended; the order is being cancelled and its stock released.",
    transfer_not_submitted: "The buyer has not sent details to reject.",
    transfer_not_confirmed: "Only a confirmed transfer can be refunded.",
    already_shipped: "This order was already shipped, so the stock cannot be restocked here. Record the refund without restocking.",
    restock_unavailable: "The reserved stock of this order cannot be released. Record the refund without restocking.",
    not_bank_transfer: "This is not a bank-transfer order.",
    invalid_reason: "Enter a reason of 1 to 200 characters.",
    idempotency_conflict: "This request key was used for a different request. Reload and try again.",
    invalid_settings: "The settings are not valid.",
    version_changed: "The settings changed since you loaded them. Reload and try again.",
    forbidden: "This account does not have permission for this action.",
    unauthorized: "Sign in again to continue.",
    retry_later: "Temporarily unavailable. Try again.",
    default: "The request could not be completed. Reload the order and try again.",
  } as Record<string, string>,
};

const zhCN: typeof en = {
  setTitle: "银行转账",
  setIntro: "让买家转账到你的银行账户付款。下单时库存会先保留；你在自己的账户看到款项后再确认订单。系统不会自动确认。",
  setEnabled: "在结账时提供银行转账",
  setAllowCvs: "超商取货也提供银行转账",
  setBank: "银行",
  setBranch: "分行（选填）",
  setAccountName: "户名",
  setAccountNumber: "账号",
  setAccountHint: "仅限数字、空格和连字符。",
  setWindow: "转账期限（小时，6–168）",
  setWindowHint: "库存会保留这么久。若期限内没有确认转账，订单会取消并释放库存。",
  setNote: "变更只影响新订单。已下单的订单沿用当时提供的银行资料。",
  save: "保存",
  saving: "保存中…",
  saved: "银行转账设置已保存。",
  retry: "重试",
  loading: "加载中…",
  loadFailed: "无法加载银行转账设置。",
  invalid: "请检查字段：开启需填写银行、户名和账号；期限为 6 到 168 小时。",
  noPermission: "此账号没有修改这些设置的权限。",
  uncertain: "结果尚不确定。重试会安全地发送相同请求，或重新加载。",
  retrySame: "重试同一请求",
  secTitle: "银行转账",
  loadingOrder: "正在加载转账资料…",
  secLoadFailed: "无法加载转账资料。",
  state: "转账状态",
  states: {
    AWAITING: "等待买家转账",
    SUBMITTED: "买家表示已转账",
    REJECTED: "已驳回买家资料，等待买家",
    CONFIRMED: "转账已确认",
    EXPIRED: "期限已结束，订单已取消",
    REFUNDED_OFFLINE: "已在平台外退款",
  },
  amount: "应收金额",
  deadline: "转账截止时间",
  bankHeading: "提供给买家的账户",
  proofHeading: "买家回报的资料",
  noProof: "买家尚未送出转账资料。若你已看到款项，仍可确认。",
  last5: "后 5 码",
  amountSent: "回报金额",
  paidAt: "回报时间",
  submittedAt: "送出时间",
  attempts: "送出次数",
  rejectReason: "你的驳回原因",
  confirmedAt: "确认时间",
  refundedAt: "退款记录时间",
  mismatch: "回报金额与应收金额不同。",
  confirm: "确认转账",
  reject: "驳回资料",
  refund: "记录线下退款",
  confirmTitle: "确认这笔转账？",
  confirmText: (amount) => `请先在你自己的银行账户确认已收到 ${amount} 再确认。订单将变为已确认、保留的库存会正式扣留，订单可以出货。此操作会记入审计日志。`,
  confirmNoProofWarning:
    "买家尚未送出任何转账资料。仅在你能把自己账户里的款项对应到这笔订单时才确认（例如买家通过 LINE 传给你的凭证）。审计日志会记为「无买家凭证确认」。",
  rejectTitle: "驳回买家的资料？",
  rejectText: "买家会看到你的原因，并可在截止前重新送出资料。订单不会取消，库存仍保留。",
  rejectReasonLabel: "显示给买家的原因（1–200 字）",
  refundTitle: "记录线下退款？",
  refundText: "在你已于本平台之外把款项退还买家后使用。这里不会移动任何资金。订单将不能再出货，并从已确认转账合计中移除。",
  refundRestockLabel: "同时把保留的库存退回库存",
  refundRestockHint: "仅限订单尚未出货时。若已交出包裹，请不要勾选，改走出货流程恢复库存。",
  refundRestockShipped: "此订单已出货，无法在这里恢复库存。",
  submitConfirm: "确认",
  submitReject: "驳回",
  submitRefund: "记录退款",
  cancel: "取消",
  close: "关闭",
  working: "处理中…",
  done: "完成。",
  errors: {
    already_confirmed: "这笔转账已确认。",
    already_refunded: "这笔转账已退款。",
    transfer_not_open: "这笔转账已不再开放（期限已过或已处理）。",
    transfer_window_closed: "转账期限已结束，订单将取消并释放库存。",
    transfer_not_submitted: "买家尚未送出资料，无法驳回。",
    transfer_not_confirmed: "只有已确认的转账才能退款。",
    already_shipped: "此订单已出货，无法在这里恢复库存。请不勾选恢复库存再记录退款。",
    restock_unavailable: "无法释放此订单保留的库存。请不勾选恢复库存再记录退款。",
    not_bank_transfer: "这不是银行转账订单。",
    invalid_reason: "请输入 1 到 200 字的原因。",
    idempotency_conflict: "此请求键已用于另一个请求，请重新加载后重试。",
    invalid_settings: "设置内容无效。",
    version_changed: "设置在你加载后已变更，请重新加载后重试。",
    forbidden: "当前账号没有此操作的权限。",
    unauthorized: "请重新登录后继续。",
    retry_later: "暂时无法使用，请重试。",
    default: "请求未能完成，请重新读取订单后重试。",
  },
};

const zhTW: typeof en = {
  setTitle: "銀行轉帳",
  setIntro: "讓買家轉帳到你的銀行帳戶付款。下單時庫存會先保留；你在自己的帳戶看到款項後再確認訂單。系統不會自動確認。",
  setEnabled: "在結帳時提供銀行轉帳",
  setAllowCvs: "超商取貨也提供銀行轉帳",
  setBank: "銀行",
  setBranch: "分行（選填）",
  setAccountName: "戶名",
  setAccountNumber: "帳號",
  setAccountHint: "僅限數字、空格與連字號。",
  setWindow: "轉帳期限（小時，6–168）",
  setWindowHint: "庫存會保留這麼久。若期限內沒有確認轉帳，訂單會取消並釋出庫存。",
  setNote: "變更只影響新訂單。已下單的訂單沿用當時提供的銀行資料。",
  save: "儲存",
  saving: "儲存中…",
  saved: "銀行轉帳設定已儲存。",
  retry: "重試",
  loading: "載入中…",
  loadFailed: "無法載入銀行轉帳設定。",
  invalid: "請檢查欄位：開啟需填寫銀行、戶名與帳號；期限為 6 到 168 小時。",
  noPermission: "此帳號沒有修改這些設定的權限。",
  uncertain: "結果尚不確定。重試會安全地送出相同請求，或重新載入。",
  retrySame: "重試同一請求",
  secTitle: "銀行轉帳",
  loadingOrder: "正在載入轉帳資料…",
  secLoadFailed: "無法載入轉帳資料。",
  state: "轉帳狀態",
  states: {
    AWAITING: "等待買家轉帳",
    SUBMITTED: "買家表示已轉帳",
    REJECTED: "已駁回買家資料，等待買家",
    CONFIRMED: "轉帳已確認",
    EXPIRED: "期限已結束，訂單已取消",
    REFUNDED_OFFLINE: "已在平台外退款",
  },
  amount: "應收金額",
  deadline: "轉帳截止時間",
  bankHeading: "提供給買家的帳戶",
  proofHeading: "買家回報的資料",
  noProof: "買家尚未送出轉帳資料。若你已看到款項，仍可確認。",
  last5: "後 5 碼",
  amountSent: "回報金額",
  paidAt: "回報時間",
  submittedAt: "送出時間",
  attempts: "送出次數",
  rejectReason: "你的駁回原因",
  confirmedAt: "確認時間",
  refundedAt: "退款記錄時間",
  mismatch: "回報金額與應收金額不同。",
  confirm: "確認轉帳",
  reject: "駁回資料",
  refund: "記錄線下退款",
  confirmTitle: "確認這筆轉帳？",
  confirmText: (amount) => `請先在你自己的銀行帳戶確認已收到 ${amount} 再確認。訂單將變為已確認、保留的庫存會正式扣留，訂單可以出貨。此操作會記入稽核日誌。`,
  confirmNoProofWarning:
    "買家尚未送出任何轉帳資料。僅在你能把自己帳戶裡的款項對應到這筆訂單時才確認（例如買家透過 LINE 傳給你的憑證）。稽核日誌會記為「無買家憑證確認」。",
  rejectTitle: "駁回買家的資料？",
  rejectText: "買家會看到你的原因，並可在截止前重新送出資料。訂單不會取消，庫存仍保留。",
  rejectReasonLabel: "顯示給買家的原因（1–200 字）",
  refundTitle: "記錄線下退款？",
  refundText: "在你已於本平台之外把款項退還買家後使用。這裡不會移動任何資金。訂單將不能再出貨，並從已確認轉帳合計中移除。",
  refundRestockLabel: "同時把保留的庫存退回庫存",
  refundRestockHint: "僅限訂單尚未出貨時。若已交出包裹，請不要勾選，改走出貨流程恢復庫存。",
  refundRestockShipped: "此訂單已出貨，無法在這裡恢復庫存。",
  submitConfirm: "確認",
  submitReject: "駁回",
  submitRefund: "記錄退款",
  cancel: "取消",
  close: "關閉",
  working: "處理中…",
  done: "完成。",
  errors: {
    already_confirmed: "這筆轉帳已確認。",
    already_refunded: "這筆轉帳已退款。",
    transfer_not_open: "這筆轉帳已不再開放（期限已過或已處理）。",
    transfer_window_closed: "轉帳期限已結束，訂單將取消並釋出庫存。",
    transfer_not_submitted: "買家尚未送出資料，無法駁回。",
    transfer_not_confirmed: "只有已確認的轉帳才能退款。",
    already_shipped: "此訂單已出貨，無法在這裡恢復庫存。請不勾選恢復庫存再記錄退款。",
    restock_unavailable: "無法釋出此訂單保留的庫存。請不勾選恢復庫存再記錄退款。",
    not_bank_transfer: "這不是銀行轉帳訂單。",
    invalid_reason: "請輸入 1 到 200 字的原因。",
    idempotency_conflict: "此請求鍵已用於另一個請求，請重新載入後重試。",
    invalid_settings: "設定內容無效。",
    version_changed: "設定在你載入後已變更，請重新載入後重試。",
    forbidden: "目前帳號沒有此操作的權限。",
    unauthorized: "請重新登入後繼續。",
    retry_later: "暫時無法使用，請重試。",
    default: "請求未能完成，請重新讀取訂單後重試。",
  },
};

export const transferCopy: Record<Locale, typeof en> = { en, "zh-CN": zhCN, "zh-TW": zhTW };
export const transferError = (c: typeof en, code: string): string => c.errors[code] ?? c.errors.default;
