// W0 route metadata only; data/authorization remain in the existing BFF and Go.
import type { RouteEntry } from "../../route-types.ts";
export const catalogRoutes = [
  {
    id: "products",
    path: "/products",
    group: "catalog",
    labelKey: "products",
    icon: "product",
    permission: "catalog:read",
    template: "list",
    nav: true,
    spec: "tests/admin/catalog-core.spec.ts",
  },
  {
    id: "product",
    path: "/products/[product]",
    group: "catalog",
    labelKey: "product",
    icon: "product",
    permission: "catalog:read",
    template: "form",
    nav: false,
    spec: "tests/admin/catalog-core.spec.ts",
  },
  {
    id: "collections",
    path: "/collections",
    group: "catalog",
    labelKey: "collections",
    icon: "product",
    permission: "catalog:read",
    template: "list",
    nav: true,
    spec: "tests/admin/catalog-core.spec.ts",
  },
  {
    id: "inventory",
    path: "/inventory",
    group: "catalog",
    labelKey: "inventory",
    icon: "inventory",
    permission: "inventory:read",
    template: "list",
    nav: true,
    spec: "tests/admin/ledger.spec.ts",
  },
  {
    id: "product-import",
    path: "/products/import",
    group: "catalog",
    labelKey: "productImport",
    icon: "product",
    permission: "catalog:read",
    template: "form",
    nav: false,
    spec: "tests/admin/shell-browser.mjs",
  },
] satisfies RouteEntry[];
