#!/usr/bin/env bash
# File: scripts/dev/gen-deps.sh
# Purpose: regenerate docs/architecture/DEPENDENCIES.md — a machine-made map of who depends on what (Go package imports
#   inside the repo, third-party Go modules per package, env vars read, SQL schema-qualified functions called, admin/storefront
#   BFF routes and the Go endpoints they proxy). Zero model tokens: run it instead of asking an agent "what calls what".
# Depends on: go (go list -json), git grep, python3 (stdlib only).
# Used by: integrator after each merge; docs/delivery/AGENT-PREAMBLE.md §4 (agents read the map instead of exploring).
# Usage: bash scripts/dev/gen-deps.sh   (writes docs/architecture/DEPENDENCIES.md; deterministic output, diff-friendly)
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"
mkdir -p docs/architecture
go list -json ./... 2>/dev/null | python3 -c '
import json,sys,re,subprocess,collections
dec=json.JSONDecoder(); s=sys.stdin.read(); i=0; pk=[]
while i<len(s):
    while i<len(s) and s[i].isspace(): i+=1
    if i>=len(s): break
    o,i=dec.raw_decode(s,i); pk.append(o)
mod=pk[0]["ImportPath"].split("/")[0] if pk else ""
def grep(pat,path):
    try: return subprocess.run(["git","grep","-hoE",pat,"--",path],capture_output=True,text=True).stdout.split()
    except Exception: return []
out=["# DEPENDENCIES (generated by scripts/dev/gen-deps.sh — do not edit by hand)","",
     "Per Go package: internal imports, third-party modules, env vars read, SQL functions called. Regenerate after every merge.",""]
for p in sorted(pk,key=lambda x:x["ImportPath"]):
    ip=p["ImportPath"]; d=p.get("Dir","").split("/"+ip.split("/",1)[-1])[0] if "/" in ip else ""
    rel=ip.split("/",1)[1] if "/" in ip else ip
    imps=p.get("Imports",[])
    internal=sorted(x.split("/",1)[1] for x in imps if x.startswith(mod+"/"))
    third=sorted({ "/".join(x.split("/")[:3]) for x in imps if "." in x.split("/")[0] and not x.startswith(mod+"/")})
    env=sorted(set(re.findall(r"Getenv\(\"([A-Z0-9_]+)\"",subprocess.run(["bash","-c",f"cat {rel}/*.go 2>/dev/null | grep -v _test || true"],capture_output=True,text=True).stdout)))
    sql=sorted(set(re.findall(r"\b((?:catalog|claims|orders|payments|fulfillment|inventory|integration|live|identity|billing|customers|ads|promotions|storefront|notify|retention|checkout|merchant|platform)\.[a-z_]+)\(",subprocess.run(["bash","-c",f"cat {rel}/*.go 2>/dev/null"],capture_output=True,text=True).stdout)))
    out.append(f"## {rel}")
    if internal: out.append("- imports: "+", ".join(internal))
    if third: out.append("- third-party: "+", ".join(third))
    if env: out.append("- env: "+", ".join(env))
    if sql: out.append("- SQL calls: "+", ".join(sql))
    out.append("")
open("docs/architecture/DEPENDENCIES.md","w").write("\n".join(out)+"\n")
print("wrote docs/architecture/DEPENDENCIES.md", len(pk), "packages")
'
