#!/usr/bin/env node
// Purpose: balanced CI shards of the tests/foundation suite. Packs every top-level Go test into G groups by measured duration (scripts/dev/shard-timing.json), writes the
//   explicit groups to scripts/dev/shard-plan.json, prints the anchored -run / -skip regex of a group for gates.yml, and --check proves each top-level test
//   runs in exactly one group (a new test can never fall outside every shard).
// Depends on: tests/foundation/*_test.go (test names, parsed from source: files carrying a `browser` build tag run only in their --browser-* modes and are excluded),
//   scripts/dev/shard-timing.json (seconds per test, refreshed with --ingest from `go test -v` shard logs), scripts/dev/shard-plan.json (generated). Node >= 20, no deps.
// Used by: .github/workflows/gates.yml (via scripts/dev/ci-plan.mjs and `shard-plan.mjs run|skip <id>`), scripts/dev/check-gates.sh (--check), tests/ci/shard-plan.test.mjs.
// Invariants: exactly one group is the catch-all (runs with -skip <every other group's tests>), so a test that is in no list (just added, renamed) still runs, in the catch-all;
//   a test listed in two groups, or selected by none, fails --check. Usage: shard-plan.mjs --check | --write | --ingest <go-test-v.log>... | run <id> | skip <id> | ids
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

export const GROUPS = 10; // ~475 s of tests per group from the 2026-10-07 run (79 min of tests in total); the unit shard (~6.5 min) is separate
export const UNPLANNED_LIMIT = 60; // more unplanned tests than this and the catch-all group has drifted: regenerate (--write) instead of letting it grow silently
export const DEFAULT_SECONDS = 5; // a test with no timing yet (new) is assumed PG-heavy
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const TIMING = path.join(root, "scripts/dev/shard-timing.json"), PLAN = path.join(root, "scripts/dev/shard-plan.json");

/** Top-level `func TestXxx(t *testing.T)` names of the files `go test ./tests/foundation` compiles without tags (what a foundation shard can run). */
export function topLevelTests(dir = path.join(root, "tests/foundation")) {
  const names = [];
  for (const f of readdirSync(dir).filter((n) => n.endsWith("_test.go")).sort()) {
    const src = readFileSync(path.join(dir, f), "utf8");
    const head = src.slice(0, src.search(/^package\s/m));
    if (/^\/\/go:build\b.*(?<![!\w])browser\b/m.test(head)) continue; // the 44 `//go:build browser` files; the exact tag set is asserted in tests/ci/shard-plan.test.mjs
    for (const m of src.matchAll(/^func (Test(?:[^a-z(\s][A-Za-z0-9_]*)?)\(\s*[A-Za-z_][A-Za-z0-9_]*\s+\*testing\.T\s*\)/gm)) names.push(m[1]);
  }
  if (new Set(names).size !== names.length) throw new Error("duplicate top-level test names in tests/foundation");
  return names.sort();
}

/** Longest-processing-time packing into `groups` groups; the group with the most tests becomes the catch-all (shortest skip list). Deterministic. */
export function pack(names, seconds, groups = GROUPS) {
  const items = names.map((n) => ({ n, s: Math.max(seconds[n] ?? DEFAULT_SECONDS, 0.05) })).sort((a, b) => b.s - a.s || (a.n < b.n ? -1 : 1));
  const bins = Array.from({ length: groups }, () => ({ est: 0, tests: [] }));
  for (const it of items) { const b = bins.reduce((m, x) => (x.est < m.est ? x : m)); b.est += it.s; b.tests.push(it.n); }
  const catchAll = bins.reduce((m, x, i) => (x.tests.length > bins[m].tests.length ? i : m), 0);
  return {
    version: 1,
    note: "GENERATED by `node scripts/dev/shard-plan.mjs --write` from scripts/dev/shard-timing.json; do not edit by hand. The catch_all group runs everything not listed in another group.",
    groups: bins.map((b, i) => ({ id: `g${String(i + 1).padStart(2, "0")}`, est_seconds: Math.round(b.est), catch_all: i === catchAll, tests: b.tests.sort() })),
  };
}

/** Anchored explicit -run list of a group ("" for the catch-all, which uses -skip instead). */
export const runRegex = (g) => (g.catch_all ? "" : `^(${g.tests.join("|")})$`);
/** -skip list of the catch-all: every test of every other group ("" for the other groups). */
export const skipRegex = (plan, g) => (g.catch_all ? `^(${plan.groups.filter((x) => x !== g).flatMap((x) => x.tests).sort().join("|")})$` : "");

/** Ids of the groups whose go test invocation (-run AND NOT -skip, Go's own semantics) selects this top-level test name. */
export function selectedBy(plan, name) {
  return plan.groups.filter((g) => {
    const run = runRegex(g), skip = skipRegex(plan, g);
    return (!run || new RegExp(run).test(name)) && !(skip && new RegExp(skip).test(name));
  }).map((g) => g.id);
}

/** Findings of the coverage proof: [] = every name in exactly one group. `info` is advisory (drift). */
export function check(plan, names) {
  const problems = [], info = [];
  const ids = plan.groups.map((g) => g.id);
  if (new Set(ids).size !== ids.length) problems.push("duplicate group ids");
  if (plan.groups.filter((g) => g.catch_all).length !== 1) problems.push("exactly one group must be catch_all");
  const listed = new Map();
  for (const g of plan.groups) for (const t of g.tests) { if (listed.has(t)) problems.push(`${t} is listed in both ${listed.get(t)} and ${g.id}`); listed.set(t, g.id); }
  for (const n of names) {
    const by = selectedBy(plan, n);
    if (by.length !== 1) problems.push(`${n} is selected by ${by.length} shard(s) [${by.join(",")}], want exactly 1`);
  }
  const unplanned = names.filter((n) => !listed.has(n)), stale = [...listed.keys()].filter((t) => !names.includes(t));
  if (unplanned.length) info.push(`${unplanned.length} test(s) are in no list and run in the catch-all ${plan.groups.find((g) => g.catch_all)?.id}: ${unplanned.slice(0, 5).join(", ")}${unplanned.length > 5 ? ", ..." : ""}`);
  if (stale.length) info.push(`${stale.length} planned name(s) no longer exist (renamed/deleted): ${stale.slice(0, 5).join(", ")}${stale.length > 5 ? ", ..." : ""}`);
  if (unplanned.length > UNPLANNED_LIMIT) problems.push(`${unplanned.length} unplanned tests (> ${UNPLANNED_LIMIT}): the catch-all shard has drifted; run \`node scripts/dev/shard-plan.mjs --write\` and commit scripts/dev/shard-plan.json`);
  return { problems, info };
}

/** Top-level `--- PASS|FAIL|SKIP: TestX (N.NNs)` lines of `go test -v` output -> seconds per test (subtests are indented and ignored). */
export function parseDurations(text) {
  const out = {};
  for (const m of text.matchAll(/^--- (?:PASS|FAIL|SKIP): (Test\S*) \(([0-9.]+)s\)$/gm)) out[m[1]] = Math.max(out[m[1]] ?? 0, Number(m[2]));
  return out;
}

const readJSON = (f) => JSON.parse(readFileSync(f, "utf8"));
export function main(argv) {
  const [cmd, ...rest] = argv;
  if (cmd === "--ingest") {
    const seconds = {};
    for (const f of rest) Object.assign(seconds, parseDurations(readFileSync(f, "utf8")));
    const kept = Object.fromEntries(Object.entries(seconds).map(([k, s]) => [k, Math.round(s * 10) / 10]).sort((a, b) => (a[0] < b[0] ? -1 : 1)));
    const note = "Seconds per top-level tests/foundation test from `go test -v` shard logs (0 = under 0.05 s; a test missing here is new and weighs DEFAULT_SECONDS). Refresh: gh run download <push run> -D <dir>; node scripts/dev/shard-plan.mjs --ingest <dir>/*/ci-gates/shard_g*.log; node scripts/dev/shard-plan.mjs --write";
    const body = Object.entries(kept).map(([k, s]) => `  ${JSON.stringify(k)}: ${s}`).join(",\n");
    writeFileSync(TIMING, `{\n "_note": ${JSON.stringify(note)},\n "seconds": {\n${body}\n }\n}\n`); // one test per line: reviewable diffs
    console.log(`shard-plan: ${Object.keys(kept).length} timings written`);
    return 0;
  }
  if (cmd === "--write") {
    const plan = pack(topLevelTests(), readJSON(TIMING).seconds);
    const found = check(plan, topLevelTests());
    if (found.problems.length) { console.error(found.problems.join("\n")); return 1; }
    writeFileSync(PLAN, JSON.stringify(plan, null, 1) + "\n");
    console.log(`shard-plan: ${plan.groups.length} groups, est ${plan.groups.map((g) => g.est_seconds).join("/")} s, catch-all ${plan.groups.find((g) => g.catch_all).id}`);
    return 0;
  }
  const plan = readJSON(PLAN);
  if (cmd === "--check") {
    const names = topLevelTests(), { problems, info } = check(plan, names);
    for (const i of info) console.log(`shard-plan: note: ${i}`);
    if (problems.length) { console.error(problems.map((p) => `shard-plan: ${p}`).join("\n")); return 1; }
    console.log(`shard-plan: ok (${names.length} top-level tests, each in exactly one of ${plan.groups.length} groups)`);
    return 0;
  }
  if (cmd === "ids") { console.log(plan.groups.map((g) => g.id).join("\n")); return 0; }
  if (cmd === "run" || cmd === "skip") {
    const g = plan.groups.find((x) => x.id === rest[0]);
    if (!g) { console.error(`shard-plan: unknown group ${rest[0]}`); return 2; }
    process.stdout.write(cmd === "run" ? runRegex(g) : skipRegex(plan, g));
    return 0;
  }
  console.error("usage: shard-plan.mjs --check | --write | --ingest <go-test-v.log>... | run <id> | skip <id> | ids");
  return 2;
}
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) process.exit(main(process.argv.slice(2)));
